### ISSUE TITLE
APT version of steam is not drawing window

### ISSUE THREAD

**Issue by jmendez1223** [ValveSoftware/steam-for-linux#10112]
#### Your system information

* Steam client version (build number or date): 1:1.0.0.78
* Distribution (e.g. Ubuntu): Ubuntu 23.04 (using gnome and x11)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* [bootstrap_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/12804053/bootstrap_log.txt)
* GPU: Nvidia 1060 Mobile (6gb vram)
#### Please describe your issue in as much detail as possible: I had steam installed with snap, but any single game wanted to launch, then i uninstalled the snap version, and installed it with apt, it installed no problem, but it doesnt want to show any windows at all, yet when i try to run it thru the terminal, it throws this:

steam.sh[18974]: Running Steam on ubuntu 23.04 64-bit
steam.sh[18974]: STEAM_RUNTIME is enabled automatically
setup.sh[19093]: Steam runtime environment up-to-date!
steam.sh[18974]: Steam client's requirements are satisfied

Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. uninstall snap steam
2. install apt steam
3. double click the steam icon to run it,

**Comment by kisak-valve** [comment]
Hello @jmendez1223, this reads like #9752. Can you check what video driver gets used with the 32 bit OpenGL render path on your system? I'd usually suggest a 32 bit build of `glxinfo`, but unfortunately, Ubuntu doesn't provide a 32 bit builds of this on 23.04. Maybe try unpacking http://launchpadlibrarian.net/358252438/mesa-utils_8.4.0-1_i386.deb from https://launchpad.net/ubuntu/bionic/i386/mesa-utils/8.4.0-1 with an archive utility and using the utility without installing it to the system.

When you tried to run Steam from a terminal, did you check if Steam was completely closed first because `steam` checks to see if there's already a running instance and does a hand off of the parameters passed to it in that case instead of starting a second instance of Steam.

**Comment by jmendez1223** [comment]
hi, and sorry for the late response, yes, when i launched steam throught the terminal, i am sure it was completely closed, in fact, i had uninstalled it prior to installing it again and running it,
now, in regard to the driver, after installing the dependency you mentioned, and launching it from terminal, it worked just fine, and the games that previously refused to worked, just, worked perfectly. thank you so much :3

**Comment by kisak-valve** [comment]
I didn't mention any dependency, but glad to hear it started working for you.

Closing as a system config issue.
