### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by amitavmohanty01** [ValveSoftware/steam-for-linux#10210]
#### Your system information

* Steam client version (build number or date): 1698777785
* Distribution (e.g. Ubuntu): Arch linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Intel
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13325726/steam-logs.tar.gz)

#### Please describe your issue in as much detail as possible:
Steam crashed

```
           PID: 1323 (steam)
           UID: 1000 (dknight)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Tue 2023-11-07 02:50:39 GMT (4 days ago)
  Command Line: /home/dknight/.local/share/Steam/ubuntu12_32/steam
    Executable: /home/dknight/.local/share/Steam/ubuntu12_32/steam
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-steam-abccc501cc464d22a3a6a8af64c299b0.scope
          Unit: user@1000.service
     User Unit: app-steam-abccc501cc464d22a3a6a8af64c299b0.scope
         Slice: user-1000.slice
     Owner UID: 1000 (dknight)
       Boot ID: f9b92b7dd2db408b8dafaf954bf7c091
    Machine ID: f52d0eeb525f4cd584fe54d97e927133
      Hostname: clown.man.machine
       Storage: /var/lib/systemd/coredump/core.steam.1000.f9b92b7dd2db408b8dafaf954bf7c091.1323.1699325439000000.zst (missing)
       Message: Process 1323 (steam) of user 1000 dumped core.
                
                Module [dso] without build-id.
                Module [dso] without build-id.
                Module [dso] without build-id.
                Stack trace of thread 1323:
                #0  0x0000000059f0b9c8 n/a (n/a + 0x0)
                ELF object binary architecture: Intel 80386
```

**Comment by helmchenlord** [comment]
same here on Gentoo, after I couldn't start steam because of a segfault I did a steam --reset. But doesn't change the result.
It's the third time I had this issue which was always resolved after using the reset function. Not this time.
steam
steam.sh[39202]: Running Steam on gentoo 1.0.0.78-r1 64-bit
steam.sh[39202]: STEAM_RUNTIME is enabled by the user
setup.sh[39271]: Steam runtime environment up-to-date!
steam.sh[39202]: Steam client's requirements are satisfied
[2023-11-26 12:09:43] Startup - updater built Nov 16 2023 18:22:28
[2023-11-26 12:09:43] Startup - Steam Client launched with: '~.local/share/Steam/ubuntu12_32/steam'
11/26 12:09:43 Init: Installing breakpad exception handler for appid(steam)/version(1700160213)/tid(39323)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2023-11-26 12:09:44] Loading cached metrics from disk (~.local/share/Steam/package/steam_client_metrics.bin)
[2023-11-26 12:09:44] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2023-11-26 12:09:44] Using the following download hosts for Public, Realm steamglobal
[2023-11-26 12:09:44] 1. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-11-26 12:09:44] Checking for update on startup
[2023-11-26 12:09:44] Checking for available updates...
[2023-11-26 12:09:44] Downloading manifest: https://cdn.steamstatic.com/client/steam_client_ubuntu12
[2023-11-26 12:09:44] Manifest download: send request
[2023-11-26 12:09:44] Manifest download: waiting for download to finish
[2023-11-26 12:09:44] Manifest download: finished
[2023-11-26 12:09:44] Download skipped: /client/steam_client_ubuntu12 version 1700160213, installed version 1700160213, existing pending version 0
[2023-11-26 12:09:44] Nothing to do
[2023-11-26 12:09:44] Verifying installation...
[2023-11-26 12:09:44] Performing checksum verification of executable files
[2023-11-26 12:09:44] Verification complete

Steam logging initialized: directory: ~.local/share/Steam/logs

~.themes/Pax-GTK/gtk-2.0/main.rc:733: error: unexpected identifier 'direction', expected character '}'
~.themes/Pax-GTK/gtk-2.0/apps.rc:7: Invalid symbolic color 'dark_sidebar_bg'
~.themes/Pax-GTK/gtk-2.0/apps.rc:7: error: invalid identifier 'dark_sidebar_bg', expected valid identifier
~.themes/Pax-GTK/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
~.themes/Pax-GTK/gtk-2.0/apps/chrome.rc:9: Invalid symbolic color 'wm_color'
~.themes/Pax-GTK/gtk-2.0/apps/chrome.rc:9: error: invalid identifier 'wm_color', expected valid identifier
~.themes/Pax-GTK/gtk-2.0/apps/thunar.rc:7: Invalid symbolic color 'sidebar_bg'
~.themes/Pax-GTK/gtk-2.0/apps/thunar.rc:7: error: invalid identifier 'sidebar_bg', expected valid identifier
~.themes/Pax-GTK/gtk-2.0/apps/xfce.rc:4: Invalid symbolic color 'panel_bg_color'
~.themes/Pax-GTK/gtk-2.0/apps/xfce.rc:4: error: invalid identifier 'panel_bg_color', expected valid identifier
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf0c326a0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf0c30fc0
steamwebhelper.sh[39340]: Runtime for steamwebhelper: defaulting to ~.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[39340]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
~.local/share/Steam/steam.sh: Zeile 798: 39323 Speicherzugriffsfehler  (Speicherabzug geschrieben) "$STEAMROOT/$STEAMEXEPATH" "$@"

[ DEBUGGER=gdb steam ](https://gist.github.com/helmchenlord/ffb5e9ebc70801ffe64dc68f103f5c95#file-gistfile1-txt)

[System_Info](https://gist.github.com/helmchenlord/9e690e4227b310d193d06c335e4740b1#file-system_info-log)

**Comment by WebFreak001** [comment]
I had this issue and it was related to pulseaudio/pipewire (having done a system update 8 days ago)

```
Thread 49 "threaded-ml" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xcceffb40 (LWP 138301)]
0xd808e677 in ?? () from /home/webfreak/.local/share/Steam/ubuntu12_32/libaudio.so
(gdb) bt
#0  0xd808e677 in ?? () from /home/webfreak/.local/share/Steam/ubuntu12_32/libaudio.so
#1  0xe61036d9 in ?? () from /usr/lib32/libpulse.so.0
#2  0xe59aa618 in ?? () from /usr/lib32/pulseaudio/libpulsecommon-16.1.so
#3  0xe59ab87f in pa_pdispatch_run () from /usr/lib32/pulseaudio/libpulsecommon-16.1.so
#4  0xe60f1493 in ?? () from /usr/lib32/libpulse.so.0
#5  0xe59b098a in ?? () from /usr/lib32/pulseaudio/libpulsecommon-16.1.so
#6  0xe59b181d in ?? () from /usr/lib32/pulseaudio/libpulsecommon-16.1.so
#7  0xe6105384 in pa_mainloop_dispatch () from /usr/lib32/libpulse.so.0
#8  0xe6105b33 in pa_mainloop_iterate () from /usr/lib32/libpulse.so.0
#9  0xe6105bed in pa_mainloop_run () from /usr/lib32/libpulse.so.0
#10 0xe6116eb9 in ?? () from /usr/lib32/libpulse.so.0
#11 0xe59c4c84 in ?? () from /usr/lib32/pulseaudio/libpulsecommon-16.1.so
#12 0xf7a8c73c in ?? () from /usr/lib32/libc.so.6
#13 0xf7b2b46c in ?? () from /usr/lib32/libc.so.6
```

upgrading the system packages again today fixed the issue though. Now after the latest package updates steam works fine on arch again.

**Comment by Melechtna** [comment]
It's not just Arch, it's now an issue in Fedora as well

**Comment by Melechtna** [comment]
> on Arch the issue has been resolved a while ago

Looks like it just got resolved in Fedora now too.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
