### ISSUE TITLE
Compile Vulkan shaders on the GPU

### ISSUE THREAD

**Issue by EntityinArray** [ValveSoftware/steam-for-linux#10230]
#### Your system information

* Steam client version (build number or date): 1700160213
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/13403675/steam-logs.tar.gz)
* GPU: Nvidia RTX 3060

#### Please describe your issue in as much detail as possible:
Currently Steam uses CPU for compiling Vulkan shaders

#### Steps for reproducing this issue:

1. Start any game
2. Vulkan shaders begin to compile on the CPU
3. You computer turns into a nuclear turbine, glaciers melt, ozone layer gets destroyed, next mass-extinction gets triggered

**Comment by kisak-valve** [comment]
Hello @EntityinArray, the actual shader compilation is handled by your video driver, not Steam itself. This would be an implementation detail of the video driver and not Steam.

That written, if this was implemented, it's highly likely that it would be massively slower than how things are currently handled due to the nature of GPUs.

**Comment by mtricolici** [comment]
![shaders-on-cpu](https://github.com/ValveSoftware/steam-for-linux/assets/717384/cf00d825-af22-49cf-a677-c340f864260a)

so it's not possible to compile these shaders on GPU ?:(
