### ISSUE TITLE
Discussion. Active support for Wayland.

### ISSUE THREAD

**Issue by alexeysvrv** [ValveSoftware/steam-for-linux#10267]
Good afternoon. There have already been a lot of requests for the inclusion of native Wayland support, but so far there has not been one place for discussion and communication with developers and development managers.
Summarizing all the requests on this topic, I want to ask the following key questions...
1. Is Valve generally working on supporting Wayland (native support) for the Steam client and in particular Dota 2 and Cs2?
2. Are its developers involved in the formation and development of Wayland protocols?
3. More and more distributions are switching to native Wayland support. How does Valve assess this trend?
4. Wine is actively promoting native Wayland support right now. Since Proton is based on new versions of Wine, this is a huge step forward to support games directly on this display server (not via XWayland) 
4. I would like more developer feedback on this issue. @ValveSoftware

**Comment by kisak-valve** [comment]
Hello @alexeysvrv, centralizing the discussion of multiple projects is non-productive and will lead to an echo chamber of frustrated users.

This issue is already being tracked in various issue reports like #4924 / https://github.com/ValveSoftware/csgo-osx-linux/issues/3359 / https://github.com/ValveSoftware/Dota-2/issues/999.

Closing as a duplicate.

**Comment by perpetuumcontinuum** [comment]
agree steam on pure wayland
