### ISSUE TITLE
libGL error: failed to load driver iris; failed to load driver swrast

### ISSUE THREAD

**Issue by marek-lach** [ValveSoftware/steam-for-linux#10298]
#### Your system information

* Steam client version (build number or date): 
* Distribution: Arch Linux
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]
* GPU: Nvidia
* Logs: attached as .zip 
[logs.zip](https://github.com/ValveSoftware/steam-for-linux/files/13687762/logs.zip)

#### Please describe your issue in as much detail as possible:
Steam client crashes immediately after launch, with

libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: iris
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: iris
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

**Comment by kisak-valve** [comment]
Hello @marek-lach, can you check if any 32 bit OpenGL application like `glxinfo32` from `lib32-mesa-utils` works?

**Comment by marek-lach** [comment]
> Hello @marek-lach, can you check if any 32 bit OpenGL application like `glxinfo32` from `lib32-mesa-utils` works?

Launching `glxinfo32` only returns:

$ glxinfo32
name of display: :1
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: iris
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: iris
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  54
  Current serial number in output stream:  55

**Comment by kisak-valve** [comment]
Thanks, that tells us that you have a general system config issue. If you're using the proprietary NVIDIA driver, double check that the `lib32-nvidia-utils` package is installed (or the appropriate equivalent package if you're using a different driver series from the AUR).

**Comment by marek-lach** [comment]
> Thanks, that tells us that you have a general system config issue. If you're using the proprietary NVIDIA driver, double check that the `lib32-nvidia-utils` package is installed (or the appropriate equivalent package if you're using a different driver series from the AUR).

Thank you for the pointers.

**Comment by vadcx** [comment]
*I suggest to close as invalid (not OP)*. Thanks for the `glxinfo32` hint. It was user issue - a **mismatched mesa vs lib32-mesa package issue.**

AMD/Radeon GPU. I hope this helps @marek-lach 

**More info:** since Manjaro stopped compiling their mesa packages with hardware video acceleration, I pulled the corresponding mesa package from AUR (with codecs enabled). Issues waiting to happen? Yes. The mesa-git is now on v24, whereas previously installed (for Steam) lib32-mesa are still v1.23.1.

**Solution:** make sure all your mesa packages are for the same version to avoid incompatibilities etc. I installed the [amdonly*](https://aur.archlinux.org/packages?O=0&SeB=nd&K=mesa&outdated=&SB=m&SO=d&PP=50&submit=Go) packages, but _I had to do it manually_ because for some reason git wouldn't clone the mesa repository.

**I don't recommend going this route!!!**

- Clone the AUR package data [64-bit](https://aur.archlinux.org/packages/amdonly-gaming-mesa) / repeat for [lib32](https://aur.archlinux.org/packages/lib32-amdonly-gaming-mesa) (I installed amd-only versions)
- Automatic install failed due to failing git clone, manually downloaded a mesa version I wanted (latest): https://gitlab.freedesktop.org/mesa/mesa
   - Unpack to either `src/` or `./` of the package metadata folder (whereever other files like   'LICENSE'  'llvm32.native' `gamescope.patch` are)
- run `makepkg` to build packages
- It has built a few packages and saved as archives
- Determine which ones you want to install (make sure to update all current system-wide packages), `pacman -U pkgname-pkgver.pkg.tar.zst` - [makepkg wiki](https://wiki.archlinux.org/title/Makepkg)
- repeat for lib32

Don't forget the vulkan packages if you need them.

**Comment by marek-lach** [comment]
> _I suggest to close as invalid (not OP)_. Thanks for the `glxinfo32` hint. It was user issue - a **mismatched mesa vs lib32-mesa package issue.**
> 
> AMD/Radeon GPU. I hope this helps @marek-lach
> 
> **More info:** since Manjaro stopped compiling their mesa packages with hardware video acceleration, I pulled the corresponding mesa package from AUR (with codecs enabled). Issues waiting to happen? Yes. The mesa-git is now on v24, whereas previously installed (for Steam) lib32-mesa are still v1.23.1.
> 
> **Solution:** make sure all your mesa packages are for the same version to avoid incompatibilities etc. I installed the [amdonly*](https://aur.archlinux.org/packages?O=0&SeB=nd&K=mesa&outdated=&SB=m&SO=d&PP=50&submit=Go) packages, but _I had to do it manually_ because for some reason git wouldn't clone the mesa repository.
> 
> **I don't recommend going this route!!!**
> 
>     * Clone the AUR package data [64-bit](https://aur.archlinux.org/packages/amdonly-gaming-mesa) / repeat for [lib32](https://aur.archlinux.org/packages/lib32-amdonly-gaming-mesa) (I installed amd-only versions)
> 
>     * Automatic install failed due to failing git clone, manually downloaded a mesa version I wanted (latest): https://gitlab.freedesktop.org/mesa/mesa
>       
>       * Unpack to either `src/` or `./` of the package metadata folder (whereever other files like   'LICENSE'  'llvm32.native' `gamescope.patch` are)
> 
>     * run `makepkg` to build packages
> 
>     * It has built a few packages and saved as archives
> 
>     * Determine which ones you want to install (make sure to update all current system-wide packages), `pacman -U pkgname-pkgver.pkg.tar.zst` - [makepkg wiki](https://wiki.archlinux.org/title/Makepkg)
> 
>     * repeat for lib32
> 
> 
> Don't forget the vulkan packages if you need them.

I have an NVIDIA GPU, but matching `mesa` and `lib32-mesa`, as well as `lib32-vulkan-mesa-layers` helped, though I had to enable _multilib-testing_ in Arch Linux for the moment.

Much thanks.
