### ISSUE TITLE
Steam Input - incorrect button prompts on OLED after January 11th update

### ISSUE THREAD

**Issue by Darten-Corewood** [ValveSoftware/steam-for-linux#10378]
#### Your system information

* Steam client version: 1704936806
* SteamOS version: 3.5.7
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > Yes

#### Please describe your issue in as much detail as possible:
After the latest update, some games which support Steam Input (like **Prey**) and Steam Controller prompts have blank squares instead of button prompts. I've also seen reports of this in **Marvel's Spider Man Remastered**, but don't have it, so I've been only able to reproduce it in **Prey**.

#### Steps for reproducing this issue:

1. Enable Steam Input for the game.
2. Launch game with either default or custom/community layout.

**Comment by kisak-valve** [comment]
Hello @Darten-Corewood, this reads like an issue with the Steam Input sub-component of the Steam client instead of an issue with SteamOS as a platform, so I've transferred this issue report to the steam-for-linux issue tracker.

**Comment by Vergasm** [comment]
**Your system information**

-Steam client version: 1704936806
-SteamOS version: 3.5.7
-Opted into Steam client beta?: No
-Opted into SteamOS beta?: No
-Have you checked for updates in Settings > Yes

**Please describe your issue in as much detail as possible:**

After the latest update, some games have blank squares instead of button prompts. I've noticed it in Spiderman Remastered, Ratchet & Clank and No Man's Sky among others.

**Steps for reproducing this issue:**

-Enable Steam Input for the game.
-Launch game

**Comment by ffielding** [comment]
**Your system information**

-Steam client version: 1704936806
-SteamOS version: 3.5.7
-Opted into Steam client beta?: No
-Opted into SteamOS beta?: No
-Have you checked for updates in Settings > Yes

**Please describe your issue in as much detail as possible:**

After the latest update, Spiderman remastered shows '?'s instead of actual button prompts. I understand this issue is related to games using Steam Input API. I am not able to disable this setting as I am using the Steam Controller and therefore it must be enabled as per the settings.

**Steps for reproducing this issue:**

-Launch game

**Comment by waspennator** [comment]
Apparently a hotfix just got pushed out, try updating and check if its fixed.

"Note: This client was re-released on January 12th to fix a regression with controller glyphs for Steam Deck OLED"

**Comment by Darten-Corewood** [comment]
Yup, fixed it!
