### ISSUE TITLE
Error: "You must update your version of the Steam client to watch this video."

### ISSUE THREAD

**Issue by mishaguyas** [ValveSoftware/steam-for-linux#10449]
#### Your system information

* Steam client version (build number or date): 
Steam Version:  1705108172
Steam Client Build Date:  Fri, Jan 12 17:52 UTC -07:00
Steam Web Build Date:  Fri, Jan 12 10:02 UTC -07:00
Steam API Version:  SteamClient021
* Distribution: Ubuntu & Mint 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14119212/steam-logs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:

I keep getting the error: 
"You must update your version of the Steam client to watch this video."
but the STEAM Client is up to date, and I've verified this repeatedly. 
This is happening with several videos, but not all of them. 

The FAQ link in the screenshot gives me no solutions to this.
I did also install the extra software ...steam 360 and WideVine by Google.. but no difference.

As I noted previously, this happens on a lot of the videos in my library,
both free
(The Freeman Chronicles, Phobia Series, Beholder the short film, etc)
and purchased
(Dead Space: Aftermath, Dead Space: Downfall),
while other videos in my library
(Gillespie, Future Farmer, Kung Fury, etc)
play just fine, so I know the problem is not my browser (Firefox) which is also up-to-date.

The ones that won't play all give me the screenshot message.

I know the Dead Space films are no longer available for purchase, 
but that shouldn't stop me from being able to watch them, 
especially since I paid for them, and the other films/series 
that won't play, all still have store pages up.

I've seen other users post that they couldn't watch some of the same things 
I couldn't, and got the same error, but no one in the community has found a solution.

I get the same error on the same videos in both Ubuntu 22.4 LTS and Mint 21.3 Cinnamon.  

#### Steps for reproducing this issue:

1. go to video page
2. click "play video"
3. browser window opens with (or without) error depending on the video
![steam error](https://github.com/ValveSoftware/steam-for-linux/assets/103957849/8409ae92-0557-498e-a0c5-62c30e07abd7)

**Comment by kisak-valve** [comment]
Hello @mishaguyas, this issue is already being tracked at #6780. Closing as a duplicate.

**Comment by zatricky** [comment]
@kisak-valve is this really a duplicate of #6780?

From what I'm able to ascertain, the behaviour in this issue is that Steam opens a web browser which then does not have support to view videos on the Steam website:
- a bug in Steam client that it is launching the web browser instead of just playing the video
- a bug in the web browser (Firefox/Chrome/etc) that it is unable to view the video

#6780 seems to be about the Steam client itself only:
- a bug in Steam client that it is unable to view videos or broadcasts

In my case I am seeing the former behaviour. I am able to view broadcasts fine in the Steam client - but when opening videos, Steam launches Firefox. Firefox then shows this nonsensical "You must update your version of the Steam client to watch this video." error.

The example right now is this (free) video I am unable to watch: https://store.steampowered.com/app/1059340/Kingdom_Come_Deliverance__Festival_Suite/

I've not had any issues using the Community Broadcasts inside the Steam client ; Everything there works 100%

**Comment by zatricky** [comment]
I tried opening it in Google Chrome now and the result is comical:

- I'm logged in to the Steam web site in both Firefox and in Chrome
- In Chrome I am viewing https://store.steampowered.com/app/1059340/Kingdom_Come_Deliverance__Festival_Suite/
- I click [ Watch ] ; It gives me a prompt asking if I have the Steam client installed
- I click [ Yes, Steam is installed ], it launches steam://run/1059340, which causes the Steam client window to show activity (but otherwise does nothing) - but then Firefox launches with the actual video URI (https://store.steampowered.com/video/watch/1059340/), which then fails with the error.
- I copy the URI to Chrome, where it works.
- Thinking on it further, I copy the URI to a Steam chat with my brother, click the resulting link, and it works *in the Steam client*.

Therefore, to my mind, this is a different bug

**Comment by TrenchcoatCraig** [comment]
I concur with zatricky, this does appear to be a separate issue from #6780. Community broadcasts and videos from the Steam library are loaded differently and have different playback requirements, and the discussed workarounds there don't apply here because of those differences. This issue should be reopened as its own thing, or the reasons kisak believes they're the same should be expanded upon.
