### ISSUE TITLE
Shader cache should always be downloaded last.

### ISSUE THREAD

**Issue by PenguinDOOM** [ValveSoftware/steam-for-linux#10473]
#### Your system information

* Steam client version (build number or date): 1705108172
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14204014/steam-logs.tar.gz)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
This becomes a problem for games with very large shader caches.
Shader caches should be downloaded last, as they can be generated locally and are less important than updating game content or addons.
If I download the game over several days, I will have to wait each time because the shader cache is downloaded before the game.

#### Steps for reproducing this issue:

1. Just start downloading game or updates
2. 
3.

**Comment by kisak-valve** [comment]
Hello @PenguinDOOM, the shader pre-cache files are hardware independent and need some time to be run through your video driver to warm the video driver's on-disk shader cache. It's downloaded before game content so that the Steam client has the opportunity to do that process while potentially larger game content is being downloaded. Your issue is with subsequent pre-cache updates being larger than expected and that issue is being tracked at #10285.
