### ISSUE TITLE
Activate product window has some context menu bugs

### ISSUE THREAD

**Issue by iodream** [ValveSoftware/steam-for-linux#10488]
#### Your system information

* Steam client version (build number or date): 1707518866
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes 
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14230288/steam-logs.tar.gz)
* GPU: Nvidia/Intel/AMD intel hd 3000
* Desktop environment: kde Plasma 5.27 X11

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

The context menu for the code entering field is broken with broken theming and layout. It does not match Steam's overall theme like the other context menus after the ui update.

Also, if you right click on the text immediately above explaining the procedure you can also get an unthemed white context menu with "Forward" and "Print". Print calls up a Chromium print window which is a bit weird and i'm not sure if intentional.

![Screenshot_20240210_212202](https://github.com/ValveSoftware/steam-for-linux/assets/42720874/a936b251-547d-46e3-a66b-f4099a2c14d6)

#### Steps for reproducing this issue:

1. open activate product window 
2. type in some text
3. right click on input field

**Comment by iodream** [comment]
Another place where this happens is the games install menu

![image](https://github.com/ValveSoftware/steam-for-linux/assets/42720874/6815978d-2a8d-41eb-a089-5c9c06687855)

**Comment by iodream** [comment]
Latest Steam beta 1711147596 has fixed all of these

**Comment by kisak-valve** [comment]
Closing per the last comment and the [2024-05-07](https://store.steampowered.com/news/app/593110/view/4182231197207095612) Steam client update.

**Comment by RokeJulianLockhart** [comment]
@kisak-valve, these remain:

1. #### Empty Context Menu Entrants

   <p></p><img width="1279" height="689" alt="Image" src="https://github.com/user-attachments/assets/4344264b-7b21-4361-bd3a-69a30891d875" /><p></p>

1. #### Presence Of “Print” Context Menu Entrant

   However, I am less confident that *this* remains a problem, because it now works. [^3]

   [^3]: [`issues/10529#issuecomment-3402443815`](https://github.com/ValveSoftware/steam-for-linux/issues/10529#issuecomment-3402443815)

   - <p></p><img width="1279" height="689" alt="Image" src="https://github.com/user-attachments/assets/2a15bc7a-a2e0-4203-a9a7-d1890ef6ca28" /><p></p>

   - > <p></p><img width="1279" height="689" alt="Image" src="https://github.com/user-attachments/assets/bde265d9-578d-48a1-b8ee-a212e0bf2da4" /><p></p>

     [^1]

     [^1]: [`issues/10529#issuecomment-3401525859`](https://github.com/ValveSoftware/steam-for-linux/issues/10529#issuecomment-3401525859)

[`issues/11784#issuecomment-3401400393`](https://github.com/ValveSoftware/steam-for-linux/issues/11784#issuecomment-3401400393) provides environment information.

**Comment by iodream** [comment]
I can no longer reproduce any of the above mentioned issues with Steam Version 1785799196

**Comment by beedell-roke** [comment]
@iodream, I remain able to, in a later version (V 1787097529). It requires <kbd>Shift</kbd> + a click:

<p></p><img width="635" height="774" alt="Image" src="https://github.com/user-attachments/assets/30d7dcbd-5d9d-4f57-bcfc-ea175d7989fd" /><p></p>

This is reproducible that it previously was.

#### My Environment

<blockquote>

~~~YAML
Steam Beta Branch: Steam Beta Update
Steam Version: 1787097529
Steam Client Build Date: Wed, Aug 19, 2026 00:29 UTC -08:00
Steam Web Build Date: Tue, Aug 18, 2026 23:32 UTC -08:00
Steam API Version: SteamClient023
~~~

</blockquote>

**Comment by iodream** [comment]
hm you're right. Just reproduced with Shift + right click too on the Stable client and in all the test cases 

```
Steam Beta Branch:  Stable Client
Steam Version:  1785799196
Steam Client Build Date:  Mon, Aug 3, 2026 22:41 UTC -08:00
Steam Web Build Date:  Tue, Aug 4, 2026 02:15 UTC -08:00
Steam API Version:  SteamClient023
```
