### ISSUE TITLE
Ao tentar baixar o software da Steam ele dá a seguinte menssagem: You are missing the following 32-bit libraries, and Steam may not run: libGL.so.1 libdrm.so.2

### ISSUE THREAD

**Issue by SuellenMiranda** [ValveSoftware/steam-for-linux#10510]
![image](https://github.com/ValveSoftware/steam-for-linux/assets/62394959/4ae224cf-0dec-4e7e-83a8-3092c87b2afb)

![image](https://github.com/ValveSoftware/steam-for-linux/assets/62394959/eac82e16-e772-49cb-9949-3b943917b5c9)

#### Sobre o sistema

* Nome do SO: Debian GNU/Linux 11 (bullseye) 64 bits 3.38.5
* Processador/Gráficos: AMD Ryzen 7 5700u Renoir

#### Problema
Estava instalando o steam_latest.deb e ao "terminar" ele aparentemente da certo, ele mostra que algumas dependências precisam ser instalados e termina, tento rodas a steam e da as imagens acima após apertar enter quando pede.

#### Já tentei

1. sudo apt install libgl1-mesa-dri:i386 libgl1:i386
2. sudo apt-get upgrade steam -f
3. sudo dpkg -i libGL.so.1 e ... libdrm.so.2 {dá erro de de expressão.

O que eu posso fazer para solucionar e eu conseguir terminar de baixar Steam no meu Linux Debian?

**Comment by kisak-valve** [comment]
Hello @SuellenMiranda, Steam needs the host system to provide 32 bit and 64 bit OpenGL drivers. You're indirectly showing that you have a distro packaging issue of some kind.

Can you share the output of `apt policy libgl1 libgl1:i386 libdrm2 libdrm2:i386`?

**Comment by SuellenMiranda** [comment]
Hi @kisak-valve the first command:

![image](https://github.com/ValveSoftware/steam-for-linux/assets/62394959/5195781e-008b-403c-b0ee-b911e1f5a81c)

the second command:

![image](https://github.com/ValveSoftware/steam-for-linux/assets/62394959/3cba82f0-3771-4361-b23f-67583a534148)

sorry, my computer is in Portuguese I hope you can translate :')

**Comment by kisak-valve** [comment]
Thanks, that points fairly directly to an issue with libc6. Let's look at what `apt policy libc6 libc6:i386` tells us followed by `sudo apt install libc6 libc6:i386`. Debian's multiarch implementation requires that all arch variants of a package have exactly the same version, and it also does not like to downgrade packages to resolve dependency conflicts.

**Comment by SuellenMiranda** [comment]
Ok, sorry for taking so long, I ended up busy, here are the commands in order (the first and the second in a row):

`apt policy libc6 libc6:i386`
![image](https://github.com/ValveSoftware/steam-for-linux/assets/62394959/cf837fdc-2e43-497a-8f5c-4e0256ee8519)

`sudo apt install libc6 libc6:i386`
![image](https://github.com/ValveSoftware/steam-for-linux/assets/62394959/729c0210-c915-499f-92f0-348ec8e3aaa2)

Well, I understand little but basically I always say that there is a broken part and that there were (hold) broken packages. I've already cleaned files and stuff like that and besides not cleaning it, it didn't help or worsen the reinstallations I tried.

**Comment by kisak-valve** [comment]
Looking at https://packages.debian.org/bullseye/libc6, the 2.31-13+deb11u8 package should be available for all arch variants (amd64 and i386). For some reason the locally cached version from the bullseye/main package repository is back on 2.31-13+deb11u5. I'd guess that was just caused by unfortunate timing with updates being published and do an update cycle with gui update tools or `sudo apt update` and `sudo apt upgrade`, then try again.

If that doesn't work, then you should look at explicitly asking apt to install the exact and matched version from the bullseye-security/main repository, which would be something like `sudo apt install libc6=2.31-13+deb11u7 libc6:i386=2.31-13+deb11u7`.

**Comment by SuellenMiranda** [comment]
Well, sorry for the delay in responding, but with the return of my classes at college I'm having to divide my attention between solving this problem with Steam and classes.

I saw the link and I understand the problem it could be, some friends who tried to help me also had the same problem but we couldn't actually solve it. I've already done these first 2 commands a lot, but I did them again just to clear my conscience, right?

Here the first 2 commands:

![image](https://github.com/ValveSoftware/steam-for-linux/assets/62394959/3fd2277d-b93e-43f3-9fc6-67648f987179)
![image](https://github.com/ValveSoftware/steam-for-linux/assets/62394959/13ee71a5-da89-4087-8e5b-517a4971c9a2)
![image](https://github.com/ValveSoftware/steam-for-linux/assets/62394959/7e0de876-3297-4d03-bd14-722535d5f105)

I tested to see if it finally worked and it gave me the same problem again as if the installation was either not done or it was not working (which already happened with one of my windows, when I was using Python as a server). Here's what happened when you tried to open Steam and press enter to continue:

![image](https://github.com/ValveSoftware/steam-for-linux/assets/62394959/e81cdf85-9fb2-4b66-95d0-cce1cbc514fe)

As it didn't work I tried the last command and finally the same thing, I ran the command apparently it worked and gave the same error when running Steam.

![image](https://github.com/ValveSoftware/steam-for-linux/assets/62394959/54c4efb9-c619-407e-9acd-aa75e7b63aa4)
![image](https://github.com/ValveSoftware/steam-for-linux/assets/62394959/7c04b414-5459-40cf-addc-73c96fcb667a)

It's good to remember that the app is ''theoretically'' downloaded. However, when running it to finish the installation and download some games (there are at most 2 or 3 that I wanted to use) it shows that it cannot run the two 32-bit libraries.

**Comment by kisak-valve** [comment]
Has the output of `sudo apt install libgl1-mesa-dri libgl1-mesa-dri:i386` changed?

**Comment by SuellenMiranda** [comment]
still remains at "impossible to fix problems, you kept (hold) broken packages.

![image](https://github.com/ValveSoftware/steam-for-linux/assets/62394959/390a41e2-1c3a-4e19-b9fd-30d7f3b38227)

**Comment by kisak-valve** [comment]
You'll need to repeat the same process of looking at what packages are available that are in conflict, and see if the locally installed package is newer than or doesn't match what's available in Debian's repositories. The next step would be to check out the 32 bit and 64 bit packages for libbsd0 and libtinfo6, which you can see in your screenshot. (Something like `apt policy libbsd0 libbsd0:i386 libtinfo6 libtinfo6:i386`)

Alternatively, since a general update didn't clear the issue, I would suspect that a regional mirror of Debian's software repository is not getting proper updates of i386 packages and check if that can be manually configure to a known good repository mirror, but that's probably better handled with your distro's community and with someone who doesn't require a translator.

**Comment by SuellenMiranda** [comment]
Well, I've already tried redoing everything from 0 about 2 times and it always gives the same error.
I bought this laptop and it already comes with this distro, normally I use Ubuntu, and since when I bought it it has pending updates that it simply won't install. Could the problem be with this update not installing and preventing some things from working?

**Comment by leobragatti** [comment]
@SuellenMiranda Try to install Steam using `snap`. I'm using Ubuntu and it worked like a charm

**Comment by SuellenMiranda** [comment]
I thank everyone who tried to help but I'm not using Linux at the moment. Thanks for the help.
