### ISSUE TITLE
Steam Input remains in desktop mode instead of switching to gamepad mode when running some apps.

### ISSUE THREAD

**Issue by ClaudeLib** [ValveSoftware/steam-for-linux#10551]
#### Your system information

* Steam client version (build number or date): 1708985249
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14441780/steam-logs.tar.gz)

* GPU: AMD

#### Please describe your issue in as much detail as possible:
When running certain apps, notably flatpaks but not only them, my Steam Controller keeps emulating keyboard and mouse instead of the virtual gamepad. This was not an issue before the yesterday's update. The affected apps are:
<details> 
  <summary>PCSX2, installed from https://flathub.org/apps/net.pcsx2.PCSX2 </summary>
https://i.imgur.com/I3GHF0c.png
https://i.imgur.com/0Z5F3EU.png
https://i.imgur.com/PXXb8vo.png
</details>
<details> 
  <summary>Ryujinx, installed from https://flathub.org/apps/org.ryujinx.Ryujinx </summary>
https://i.imgur.com/M1dgepO.png https://i.imgur.com/Vblrlqt.png
https://i.imgur.com/aNfZGup.png
https://i.imgur.com/SOsHRSz.png
</details>
<details> 
  <summary>Ryujinx, installed from https://aur.archlinux.org/packages/ryujinx-bin </summary>
https://i.imgur.com/TIMUvNC.png
https://i.imgur.com/zpYFsFE.png
https://i.imgur.com/OJS0ZpC.png
</details>
Toggling "Use Desktop Configuration in Launcher" doesn't do anything.

Some other apps, like https://aur.archlinux.org/packages/pcsx2-latest-bin, or Xenia emulator running via Proton are not affected.
I've also encountered this exact same issue on my LCDeck, it also started happening just yesterday, however running apps from the game mode, rather than desktop mode, seems to help avoid the issue. I can attach logs a bit later if needed.

#### Steps for reproducing this issue:

1. Add third party apps as Non-Steam games to the library
2. Launch them via Steam

**Comment by ClaudeLib** [comment]
The issue still persists on my Deck, after installing the update that dropped an hour ago.

* Steam client version (build number or date): 1709168962
* Distribution (e.g. Ubuntu): SteamOS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14442461/steam-logs.tar.gz)
* GPU: AMD

It also affects both Steam Controller (gordon) and Steam Deck builtin controls (neptune).

As a test, I added Ark (the KDE Archiving tool) to Steam and when I launch it, Steam Input seems to switch to gamepad mode just fine, as in, the right touchpad (or right stick) doesn't move the mouse around.
https://i.imgur.com/XtYuJ0I.png

However, when launching PPSSPP (https://flathub.org/apps/org.ppsspp.PPSSPP), it still emulates the desktop controls.
https://i.imgur.com/8iMAN7E.png

**Comment by prodbyloti** [comment]
happening to me too. mainly an issue for me rn bc it breaks Moonlight, the button combo to close it doesnt work. started after the newest update.

**Comment by prodbyloti** [comment]
still not fixed after the newest update

**Comment by Lazorne** [comment]
I can confirm this is happening on both the Steam Flatpak version and Native in Fedora as well when running any none Steam Apps via Steam.

I have also tried to disable both Steam Input on the Game and on Desktop and vice versa.  

Even sometimes I get a weird behavior when both profiles are used in the same time and sends dual inputs, but even then if I turn of the Desktop Profile it stops the game profile from working.

I have tried even to load a game profile as a Desktop profile, without any success. 

https://github.com/XargonWan/RetroDECK/tree/cooker-0.8.0b/emu-configs/defaults/retrodeck/controller_configs

**Comment by prodbyloti** [comment]
i have a feeling that Valve wont do anything since its affecting such a small amount of people. really wish there was an official way to roll back farther.

**Comment by Porkch0p** [comment]
I'm seeing this regression with an LCD Steam Deck running RetroArch (flatpak) installed via Emudeck. 

On Desktop, controls that were previously a gamepad layout (both internal controls and a wired gamepad) are now acting as the desktop profile after the client update of Feb 27.

The regression may not be limited to Desktop mode. In Game Mode, I'm finding the app will load with the correct mappings, but changing the brightness level via chord (Three Dot + Joystick Up) is enough to break the controls in the same way, silently changing application inputs to desktop profile.

After some testing, the behavior appears different in Game Mode if the Steam button has been pressed. With an overlay active, the gamepad profile of the running application does not appear to be lost.

**Comment by ClaudeLib** [comment]
It also happens on LMDE, based on Debian.

#### Your system information

* Steam client version (build number or date): 1709168962
* Distribution (e.g. Ubuntu): Linux Mint Debian Edition
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14489210/steam-logs.tar.gz)
* GPU: AMD

yuzu installed from Flathub (https://flathub.org/apps/org.yuzu_emu.yuzu) does have this issue.
![Screenshot from 2024-03-05 06-48-00](https://github.com/ValveSoftware/steam-for-linux/assets/5920490/2565f7a3-2393-4ed5-93aa-6b426a6b0f78)

yuzu installed from Debian (https://debian.pkgs.org/12/debian-main-amd64/yuzu_0-1335+ds-1+deb12u1_amd64.deb.html) does not, Steam Input switches to gamepad emulation just fine and I'm able to configure the controls in the app's settings.
![Screenshot from 2024-03-05 06-47-35](https://github.com/ValveSoftware/steam-for-linux/assets/5920490/4e1bd54a-cd89-44f8-9d14-cff6f402ccf3)

As a test I tried adding Text Editor and Archive Manager as non-Steam games and they also seem to have this issue, despite not being flatpaks.
![Screenshot from 2024-03-05 06-45-45](https://github.com/ValveSoftware/steam-for-linux/assets/5920490/e09772ec-8b15-46ad-93d2-3146a54c07ec)
![Screenshot from 2024-03-05 06-45-55](https://github.com/ValveSoftware/steam-for-linux/assets/5920490/b3d433d3-130f-45e8-a88c-fb6eb2942d0b)

**Comment by ClaudeLib** [comment]
The issue is still there as of build 1709846872.

**Comment by ClaudeLib** [comment]
Build 1710458266, the issue is still present.

**Comment by Aepoh** [comment]
Can confirm the issue is still present and still irritating.

**Comment by creativecoder** [comment]
I'm also experiencing this with non-Steam flatpak games launched through Steam. It seems similar to (and possibly a regression of) https://github.com/ValveSoftware/steam-for-linux/issues/8599.

For me

- Flatpak games launched through Steam don't receive any controller input at all, unless Steam input is disabled for that game.
- Once Steam input is disabled, the desktop configuration for the controller is used for that game, if the controller has a desktop profile.

* Steam client version (build number or date): 1709846872
* Distribution (e.g. Ubuntu): Pop!_OS 22.04 LTS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* GPU: AMD

**Comment by creativecoder** [comment]
Possible duplicate: https://github.com/ValveSoftware/steam-for-linux/issues/10430

**Comment by Managor** [comment]
I came here to report the same issue that using chords through the QAM button causes non-steam game binding to be overridden with the desktop config until you press the QAM button. Using chords through the STEAM button does not have this effect
Here's a demonstrative video: https://youtu.be/_7q7VCEgV24
I reported this previously on the Steam Forums. https://steamcommunity.com/app/1675200/discussions/1/3642874410681493222/

**Comment by creativecoder** [comment]
I did a little more testing on Steam Deck and my Linux desktop launching non-Steam games from Steam that run as flatpak apps (in my case, game launched from Steam but run through Heroic launcher flatpak). In all cases, Steam input was enabled with a custom controller configuration for the non-Steam game.

**Steam Deck**

Desktop mode
- Controller uses the Desktop configuration instead of the game specific configuration for the (built-in) controller

Game mode
- The correct controller configuration is used (but I didn't test activating the overlays)

**Linux Desktop**
(tested both a Steam Controller and a PS5 controller, wired and bluetooth)

Desktop mode
- Controller uses the Desktop configuration instead of the game specific configuration

Big Picture mode
- Controller does not work at all

**Comment by ShayBox** [comment]
I can't believe I spent all day trying every combination of RetroArch from pacman/steam, every input/controller driver, and steam running/not just to find out it's a bug.

If you want a workaround you can manually swap the desktop profile to gamepad, or you can use action sets to swap profiles with buttons on the controller. steam://controllerconfig/413080/909196706

**Comment by ShayBox** [comment]
Yeah manually switching is inconvenient, but it'll let you use your steam controller at all so it does partially work around the issue of a completely unusable controller, but I recommend action sets, it's very convenient to switch between desktop and game pad with a button, whether in desktop or a game.

**Comment by Managor** [comment]
The default deskto config, at least for the Deck, contains a gamepad action set that you switch to by holding Start.

**Comment by ClaudeLib** [comment]
> The default deskto config, at least for the Deck, contains a gamepad action set that you switch to by holding Start.
Woah, nice. Thanks, gonna be using that for the time being. Sadly it doesn't seem to work for Steam Controller, though.

**Comment by Managor** [comment]
SC doesn't probably have it by default. You need to create it yourself.

**Comment by ClaudeLib** [comment]
After the update 3.5.19 the issue is still there. I guess that's because the client is still 1710458266.

**Comment by JamesBCrazy** [comment]
Confirming. Issue still exists on 3.5.19 (20240422.1) on both Stable and Preview.

This is a major issue as it renders a number of games (particularly those that rely on multiple windows and/or the system mouse cursor) virtually unplayable on Steam Deck.

**Comment by bjoern-tantau** [comment]
Happens with gamescope as well, which is especially annoying.

`"/usr/bin/gamescope" -W 1280 -H 800 -r 60 -e -f --expose-wayland -- ./CGeniusExe`

When I run CGeniusExe (or any other game) without gamescope I can control it just fine.

**Comment by ClaudeLib** [comment]
After long awaited Steam Client update 1714854927, despite numerous Steam Input fixes and improvements, this particular issue seems to still be there.

**Comment by ClaudeLib** [comment]
Steam Client 1715635533, the issue is still there.

**Comment by ClaudeLib** [comment]
Steam Client 1715891371, the issue still persists.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
Can confirm I cannot play a non-steam game (that lives in Bottles from flathub) that previously (quite a while ago) worked fine. It seems that the entire steam overlay doesn't work, and without it there won't be any steam input either. 
It's not a problem with a Steam Deck, as controls work fine in Game Mode. However, there is no such workaround on my desktop PC, so I can't play such games with a controller anymore.

**Comment by ClaudeLib** [comment]
> It's not a problem with a Steam Deck, as controls work fine in Game Mode. However, there is no such workaround on my desktop PC, so I can't play such games with a controller anymore.
You can run flatpaks from Big Picture for now, should work.

**Comment by Merrit** [comment]
> > It's not a problem with a Steam Deck, as controls work fine in Game Mode. However, there is no such workaround on my desktop PC, so I can't play such games with a controller anymore.
> 
> You can run flatpaks from Big Picture for now, should work.

Unfortunately doesn't work for me when launched from Big Picture either, even though the controller works fine in the Big Picture interface. Games see no controller at all, unless I disable Steam Input (which means no remapping or anything available).

**Comment by creativecoder** [comment]
For non-Steam flatpak games on desktop PCs, the only other workaround I've found is to change the Desktop layout for the controller to the one I want to use in the game, then launch the game in Desktop mode.

Note that this does not work for me in Big Picture mode. Like @Merrit , I get no controller input in Big Picture mode for games running through Bottles or Heroic Games Launcher.

**Comment by creativecoder** [comment]
> The regression may not be limited to Desktop mode. In Game Mode, I'm finding the app will load with the correct mappings, but changing the brightness level via chord (Three Dot + Joystick Up) is enough to break the controls in the same way, silently changing application inputs to desktop profile.

I've also experienced this multiple times, the custom controller profile becoming disabled in Game mode on the Steam Deck after using the right fly out menu or using the `...` button + left stick to adjust brightness. It also happened once after a scheduled activation of night mode. In my case it was for a non-Steam game running through Heroic. I'm not sure if it happens for Steam games or not.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
> > It's not a problem with a Steam Deck, as controls work fine in Game Mode. However, there is no such workaround on my desktop PC, so I can't play such games with a controller anymore.
> 
> You can run flatpaks from Big Picture for now, should work.

Does not work for me.

**Comment by Merrit** [comment]
I haven't tried Flatpak games myself, but for me no configuration of any kind can get Steam input working in non-steam games from sources like Lutris or Heroic.

Actual Steam games seem to get the overlay and Steam input just fine, even without Big Picture Mode.

**Comment by ClaudeLib** [comment]
Steam version 1716242052, the issue is still present.
Also, yeah, I stand corrected, running the games via BP doesn't help.

**Comment by ClaudeLib** [comment]
Steam Client version 1716584667, the issue still persists.

**Comment by ClaudeLib** [comment]
Felt like trying the Preview Channel, SteamOS 3.6.3 build 20240516.100, Steam Client version 1716951179 (not sure if the Stable Channel got this update), the issue is still there.

**Comment by Fatalution** [comment]
Stumbled on this issue as I tried to use the 3rd party added app with native Steam Input API support - to no avail, simply can't get the app to detect it's running on a Steam Deck. So I'm stuck between either playing with "Gamepad" - or no input whatsoever, even when Steam Input is enabled and the bindings config is manually pasted into config folder.

I guess, this issue is the answer to my problems

**Comment by ClaudeLib** [comment]
Steam Client version 1717294964, the issue is *still* there.

**Comment by ClaudeLib** [comment]
Steam Client version 1718305227, the issue is still there.

**Comment by ClaudeLib** [comment]
I'm genuinely sorry for bringing this up every now and they, I really don't want to be annoying, I just want this issue to be resolved, but as of 1718521059, it's still there.

**Comment by Aepoh** [comment]
> I'm genuinely sorry for bringing this up every now and then, I really don't want to be annoying, I just want this issue to be resolved, but as of 1718521059, it's still there.

Don't be sorry. You paid for your Steam Deck didn't you? You have every right as a customer to have a bug free system.

**Comment by ClaudeLib** [comment]
Steam Client version 1719010598, the issue is still there. I'm moving back to stable.

**Comment by sairuk** [comment]
Ran into similar recently on manjaro and deb12 with later steam builds both stable and beta channels, I am using 4xDS4 controllers as the default inputs on this machine, however users were free to BYOD a device due to SI, my experience seems close enough to behaviours reported in this issue.

As a carry over/workaround from old SBP limitations I do have my desktop configuration set to default to gamepad (first action set) with k/m as a secondary action set, so i can just disable SI and get a gamepad in desktop mode, but its interactions with new SBP needs more review.

Enabling steam input (SI) on a flatpak based application creates the x360 virt js device as expected however in flatpak applications it is (now) not detected although the flatpak may say a device is connected it does not detect the steam virtual device. It does detect the initial js host device however the host js device inputs are nuked by steam. On non-flatpak based applications SI is fine. Supporting this, if i launch pegasus (non-flatpak) with SI enabled controls work until I launch a flatpak based application from pegasus then input on the launched application is also dead.

This all used to work fine and all my non-steam applications were configured to use SI for the flexibility of BYOD. I do not know what build this started on as broken controls in applications was only reported to me yesterday, my users report this "has been happening for a while". Having a look into it last night it is only flatpak applications (ryu, ppsspp, simple64, gzdoom, etc) experiencing the issue. I am willing to ack this may be related to linux or flatpak changes, not explicitly steam.

reviewing some of the flatpak perms
- had `device=all` perms.
- No [global] overrides in regards to devices are present on the system. 
- one filesystems override to add some additional ro pathing access for game storage
- adding a global override for the new `device=input` also had no affect.

if i disable steam input and configure the inputs separately within the flatpak directly the controls are fine but rely on whatever limitations the applications have for configuration and BYOD becomes infinitely more painful. I'd prefer to use SI as baseline input for all non-steam stuff where possible.

**Comment by Wibbbs** [comment]
Just wanted to give this a bump as this issues still seems to persist.

Added bolt launcher (Runescape) as a non steam game.
Custom controls work perfectly in game mode.
Launch in desktop mode, custom controls are not used and desktop configuration is used.

If anyone has found any workaround for this please let us know. Doesn't look like it will be fixed anytime soon.

**Comment by ClaudeLib** [comment]
Yeah, the issue is still there, actually. As a matter of fact, I've tried all three branches (Stable, Beta, Preview) earlier this week on my Deck and the issue still plagued the experience.

**Comment by ClaudeLib** [comment]
Steam Client version 1726088054, the issue is still present.

**Comment by ClaudeLib** [comment]
Steam Client version 1726256783, the issue is still there.
I don't want to sound annoying or impatient, but this has been broken for more than half a year and it's quite literally game breaking. Though I admit some might call the cases when it happens very specific.

**Comment by Managor** [comment]
Well you do sound annoying and impatient.

**Comment by Aepoh** [comment]
Oh no how dare someone expect a device they paid half a thousand dollars for to work properly and not commonly regress and stay regressed on bugs like this. How dare they!

**Comment by ClaudeLib** [comment]
No need to stoop to that. I do report every now and then that the issue still exists, which can possibly get annoying after a while.

**Comment by Managor** [comment]
I personally do my bug reporting with the fire and forget mentality. There are some reports from me that date back to 2018 and it can get annoying when you constantly encounter it but seeing how many side projects there are in maintaining and improving more immediate things, I don't bother to complain.

**Comment by Aepoh** [comment]
I think bugs related to Steam Input should be higher priority than a lot of other bugs and new feature implementations. Steam Input is how the user interfaces with the device, if it isn't working properly then everything else doesn't matter because the user can't interface with the system in the way they need to.

**Comment by Managor** [comment]
I do agree. It's not even a personal grievance. They *should* focus on that so that there are less people who try PC gaming and leave with the opinion that PC is buggy.
I have like 70 Steam Input bug reports open that I'm involved with and I wish one dev went through them because some of them are just simple UI bugs.

**Comment by ClaudeLib** [comment]
Felt like trying out Beta once more and as of version 1728093750, this issue seems to finally be fixed.

**Comment by ClaudeLib** [comment]
That up there was on my LCDeck, now I tried that on my main rig running ChimeraOS, jumping back and forth between Stable 1726683985 and Beta 1728093750, and indeed, on Beta the issue is gone, and after going back to Stable it reappears. I'll also try to test this on my laptop running Manjaro.

**Comment by Wibbbs** [comment]
@ClaudeLib Thanks for the update. I am going to have to switch my steam deck over to beta this evening and try this out.

**Comment by ClaudeLib** [comment]
No problem, glad to be of help. However, it seems that it needs some more work. I tested this on my laptop with Manjaro and the issue still persists on both Stable (for some reason 1726604483 and says it's up to date) and Beta 1728093750. This is weird.

**Comment by Managor** [comment]
Slowly getting there.

**Comment by ClaudeLib** [comment]
Okay, let me sum it up. I tested PCSX2, PPSSPP and yuzu, all installed via Flatpak, on two systems, running ChimeraOS and Manjaro Linux with Steam Client installed natively. On Stable branch (1726683985 on ChimeraOS, 1726604483 on Manjaro) Steam Input consistently does NOT switch to ingame layout/gamepad emulation for any of the three apps on both systems. On Beta branch (1728093750 on both) Steam Input DOES switch for PCSX2 and PPSSPP, but not for yuzu (which is strange because I remember playing yuzu on my Deck earlier today and I was in desktop mode).

**Comment by ClaudeLib** [comment]
Back at my Deck, tested Citra, yuzu, Ryujinx, PCSX2, PPSSPP, Flycast, Dolphin, Kodi, all Flatpaks. Steam Input seems to correctly switch to ingame layout/gamepad emulation in all cases. SteamOS Beta 3.6.17 Build 20241003.100, Steam Client Build 1728093750.

**Comment by Lazorne** [comment]
Good testing Cloudelib. I will test RetroDECK later on multiple systems and report back here by editing the comment :)

Edit Update:

**Comment by ClaudeLib** [comment]
Can somebody else please check yuzu specifically? It's still physically hosted on Flathub and can be installed from the console with
>sudo flatpak install org.yuzu_emu.yuzu

I'm really confused why Steam Input refuses to switch to ingame layout for it on my main rig, but does so on my Deck.

**Comment by aewhite** [comment]
> I'm really confused why Steam Input refuses to switch to ingame layout for it on my main rig, but does so on my Deck.

FWIW, my Deck still has the issue with the latest beta.

**Comment by aewhite** [comment]
I'm curious if there is any reasonable workarounds for the Steam Deck in particular that I've missed. So far, my only ideas are:

1. Install a non-flatpak version of the game
2. Create a dedicated actionset/layer in the desktop profile and switch to that ingame

Is there any file that can be modified to override Steam to use the game profile? Is there any setting to completely disable the desktop profile for a game? Are there any special "wapper" processes that might be able to resolve the issue? Or maybe a special hidden steam button combo that can do some soft of manual switch in game?

**Comment by ClaudeLib** [comment]
I've just tested this on my LCDeck running latest Stable. In Desktop mode, all of my flatpaks, including yuzu, correctly switched Steam Input to gamepad mode, without any workarounds. I will test my regular Linux laptop when I get home later today.

**Comment by casasfernando** [comment]
Running Steam client version **1731433018** from yesterday (Nov 12 18:10 UTC) on Steam Deck OLED here.

Steam Input Gamepad layouts stopped working for all my games in Heroic (flatpak), when launched through Steam, regardless of using gaming or desktop mode.
This was working fine as long as I remember in gaming mode and was certainly working last Sunday (Nov 10).

Oddly enough if I change the Steam Input layout to "Keyboard (WASD) with Mouse" it works so the problem seems to be specific to Gamepad emulation.
Launching the games directly from Heroic (flatpak) in desktop mode with Gamepad layouts also works.

Not sure what's going on but I hope the fix this ASAP.

**Comment by kisak-valve** [comment]
Closing as fixed.

**Comment by DanielOS96** [comment]
Still getting this issue. It stops me using Spotify and games together. It doesn't switch from gamepad settings to M&K settings.

**Comment by danaYatsuta** [comment]
I'm also getting this issue on PCSX2 AppImage added to Steam as non-steam game. Am I doing something wrong? Are there any workarounds?

**Comment by Jawzper** [comment]
I'm still having this issue for many games, especially launching via Heroic or emulators. 

I would really like to see this fixed for the new Steam Controller, since it requires SteamInput to function.

**Comment by JetBl4ck9** [comment]
I just unboxed my Steam Controller and loaded up Doom Dark Ages and found this thread specifically because I'm having this exact issue. Game thinks I'm gaming both on my controller and mouse/keyboard at the same time. There no longer seems to be a way to disable the Desktop Layout in Steam anymore, which likely would solve this issue.

**Comment by Warionator** [comment]
Issue definitely not fixed, non-steam games always use Desktop config

**Comment by tajo48** [comment]
Arc Riders uses a pad and desktop at the same time and switches between them multiple times a second.

**Comment by piercegwang** [comment]
I'm also having this issue. Hasn't been fixed for a while and it breaks a lot on the Desktop mode side. Let me know if there's anything I can test or try to help debug the issue!

Also going to ping @kisak-valve just to see if this can be reopened (or if another issue needs to be made)

**Comment by Jawzper** [comment]
This has still not been reopened, perhaps a new issue should be made?

**Comment by Xzaver** [comment]
I can confirm, I have the same Problem with Flatpaks aswell.

**Comment by catsgomoo** [comment]
Issue has been happening for me as well. This issue seems to happen in games that open multiple windows. If a game boot up one window the game uses the game controls, however if it has a launcher or boots up multiple windows and closes one the game almost always uses the desktop layout instead. This happens in big picture mode and in desktop mode.

**Comment by WitherredAway** [comment]
This was happening to me with FC25 and FC26. What fixed it for me is turning on EA's Ingame Overlay (thru the EA app). It also fixed steam input not working, steam overlay not working, steam desktop controller layout not disabling, steam recordings not working, etc.

**Comment by alicelilium** [comment]
I was having a similar issue with maybe a different root cause to the Steam one, KDE updated and enabled "Allow using as pointer and keyboard" under Game Controller when it was previously disabled, and it caused similar issues for me. Not the same issue but I came across this thread while searching for mine and thought someone else might do the same.

**Comment by Thornskade** [comment]
Not fixed. Doesn't work with Flatpak as multiple people suggest, probably because the overlay isn't working either.

It's reasons like that why Steam Input should allow a standalone global daemon for fallback where you can manually switch to a game config if there's no other way to get Steam to hook into it.

**Comment by anishgoyal1108** [comment]
Hi guys! I found a solution that works for me in [this other issue](https://github.com/ValveSoftware/steam-for-linux/issues/13314#issuecomment-4754666627). If someone could test it out and let me know, that would be great! Hopefully this issue gets resolved natively within Steam in the future. But in the meantime, my fix should hopefully work for those using a Steam Controller on Flatpak (should technically work on non-Flatpak too).

**Comment by Kiaos** [comment]
I just got my steam controller and can confirm the issue with steam reconizing windowed mode games on kde desktop as desktop controller. IT doesnt swtich to the game controller. when I use big picutre to go to controller it wont even let me remap in the normal controller settings in big picure. 

Game scope works fine I had to install it on cachyos and it works just fine. But Sometimes it doesnt detect not steam linux native stuff as a game. I loaded duck station and it read it as a desktop controler . I had to hold select to switch it back. But recently I did it in subnautica 2 and then turned off big picutre and i was stuck in the steam desktop overlay and no input worked yet while i was spaming buttons I sometimes was moving the volume slider.


No clue why this issue is closed its still a issue in latest build of steam. I was running kde plasma on cachyos. 

End result on kde desktop a lot of games dont revert to controller. IT uses desktop controller by default. KDE Desktop and steam controllers are really buggy. 

Gamescope is a much better experience. I suspect this is a kde steam issue. Not sure how to fix it on my end.

**Comment by Thornskade** [comment]
For me the fix has been to use X11. That's not a great solution if you want HDR, though using Valve's Game Mode is another option. It's also annoying to switch desktop environments for individual games.

This post explains in much more detail what's happening and proposes some fixes:
https://github.com/ValveSoftware/steam-for-linux/issues/13314#issuecomment-5214475410

Either way, the conclusion is that Steam Input is kind of busted under Wayland desktops.
