### ISSUE TITLE
Game crashes when trying to display it on an external screen in Big Picture mode

### ISSUE THREAD

**Issue by mcoulont** [ValveSoftware/steam-for-linux#10640]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): 
* Opted into Steam client beta?: [Yes/No]
* Have you checked for system updates?: [Yes/No]
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia/Intel/AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

1. I run a game. I'm in Big picture mode
2. I press the "Windows" button 
3. I drag-and-drop the game onto my big screen

I expected that the game runs on my big screen.
Instead, the game suddenly stops (app crash?)

**Comment by kisak-valve** [comment]
Hello @mcoulont, there's not enough information here to even start pondering your issue since you've omitted any actionable details.

If you're testing a Linux native game (or a Windows native game on Windows), that should be mentioned to the game's developers. Alternatively, if you're testing a Windows based game being run with Proton on Linux, then that should be mentioned on the game's compatibility report on the Proton issue tracker.

Closing as not a Steam client issue.
