### ISSUE TITLE
Steam lost all drives with ALL games and I can't recover it.

### ISSUE THREAD

**Issue by kaarelen** [ValveSoftware/steam-for-linux#10652]
#### Your system information

* Steam client version (build number or date): Steam Version:  1709846872Steam Client Build Date:  Wed, Mar 6 9:28 PM UTC -08:00
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/14711637/steam-logs.tar.gz)

* GPU: Nvidia 1070

#### Please describe your issue in as much detail as possible:
First issue:

I have played a game (Pathologic 2 via proton experimental). Game crashed. Reboot. ALL games are gone, because steam lost all steam drives except main one (which was close to empty). 

Second: 
I have tried to readd drive but I can't, because folder uses custom path, but "custom path button" just do nothing.

#### Steps for reproducing this issue:

1. play game
2. game crashes
3. steam failes to kill the game
4. reboot
5. all games are gone

**Comment by kisak-valve** [comment]
Hello @kaarelen, the first half of your issue is being already being tracked at #8552.

For the second half, Steam tried to call xdg-desktop-portal to give you a user-configurable folder chooser dialog window. If this fails, then a fallback folder chooser is shown and that has an issue being tracked at #10415.

Closing in favor of the older issue reports.

**Comment by kaarelen** [comment]
thanks, @kisak-valve
