### ISSUE TITLE
Gunman Chronicles doesn't load.

### ISSUE THREAD

**Issue by Sarkie** [ValveSoftware/steam-for-linux#1070]
I know it is Third Party but it works with Half Life Windows.

I can get it loading with 

```
LD_LIBRARY_PATH=. ./hl_linux -game rewolf
```

But it'll fail to load a level

```
Host_Error: Couldn't get DLL API from om.hp2!
```

**Comment by rea987** [comment]
@Sarkie You mentioned that the game works perfectly. I have copied the game folder into Steam folder. Applied Steam Fix from the following URL. Copied hl.so file to dlls folder of the mod. Edited liblist.gam with the mentioned line. The game launches as a HL mod on Steam without a problem; the game starts without an issue. However, characters and some of the sounds are unable to be loaded. Because of that it is not possible proceed. Have you experienced such problem?

Thanks, regards.

http://www.nextdimension.org/gunmantosteam/
