### ISSUE TITLE
Shift + Left Click does not work on both actual keyboard + mouse  and game mode

### ISSUE THREAD

**Issue by Jakeulous** [ValveSoftware/steam-for-linux#10902]
#### System Information
Command: cat /etc/os-release
NAME="SteamOS"
PRETTY_NAME="SteamOS"
VERSION_CODENAME=holo
ID=steamos
ID_LIKE=arch
ANSI_COLOR="1;35"
VERSION_ID=3.6.3
BUILD_ID=20240516.100
STEAMOS_DEFAULT_UPDATE_BRANCH=stable

* Steam client version: 1715891371 - Fri, May 17 4:11 AM UTC -08:00
* SteamOS version: 3.6.3 Build 20240516.100
* Opted into Steam client beta?: Yes/Preview
* Opted into SteamOS beta?: Yes/Preview
* Have you checked for updates in Settings > System?: Yes

Doing Shift + Left Mouse Click actions does not register when launching a game in game mode/steam inputs
issues are present to both on custom controls binding and actual keyboard and mouse connection[bluetooth/wired]

1. open a game
2.  binded game inputs to shift + L Click using custom controller layout or connect keyboard + mouse
3. game does nothing register the input at all

**Comment by jakenildo** [comment]
Hello @kisak-valve [here](https://imgur.com/a/ly6JSuR)'s a screenshot for my custom steam input configuration.

as for the game i was testing on, I was playing on Minecraft using said Steam Input settings, and whenever I do commands for crafting multiple batches of items, normally Shift + L. Click would allow to quickly craft all allocated items,

this issue is also quite noticeable when doing drag and drop actions using L. Click/ R. Click bindings, it doesn't occur on windows side of things, and on SteamOS' stable and Beta branches this functionality works without a problem.

as for ctrl + click, it just works without a problem
