### ISSUE TITLE
Steam doesn't recognize my back-up directory

### ISSUE THREAD

**Issue by Areyzaga** [ValveSoftware/steam-for-linux#11005]
#### Your system information

* Steam client version (build number or date): 1.0.0.79 from Flathub via Discover
* Distribution (e.g. Ubuntu):  Fedora KDE 40
* Opted into Steam client beta?: [Yes/No] NO
* Have you checked for system updates?: [Yes/No] YES
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia/Intel/AMD: AMD

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
NOTE: I couldn't find the logs.
So i had ubuntu installed before i installed Fedora and got some couple of games there, so in order to avoid waiting for my games to redownload i made some back-ups, after my fresh installation of Fedora and all of the common procedure i tried to reinstall my games with the back-ups i previously created, but once i selected the directory in which the files are steam "doesn't mount" the directory, it's just stay still like waiting for me to select the directory (as shown in the SS atached) i contacted steam support but they sent me here. Thank you in advance.

![imagen](https://github.com/ValveSoftware/steam-for-linux/assets/51249797/52e430f1-02f9-4ba4-8575-7a725ccb8012)

#### Steps for reproducing this issue:

1. Open steam
2. Try normal procedure to install from back-up
3. Try to select the directory to the back-up
4. Steam stays still not recognizing the back-up

**Comment by kisak-valve** [comment]
Hello @Areyzaga, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

This should be calling xdg-desktop-portal to open a user-configured folder chooser dialog. The question to ponder here is why xdg-desktop-portal isn't behaving as expected.

Since you're running Steam inside a Flatpak container, you also might need to manually give the Steam flatpak access to the folder on the host system.

**Comment by Areyzaga** [comment]
Hi, thx you so much to answer, i reinstalled the client via 3rd party repo, and i that got my issue resolved.
