### ISSUE TITLE
[Steamdeck] Shader pre-caching updates on every wake/boot

### ISSUE THREAD

**Issue by maxdp66** [ValveSoftware/steam-for-linux#11051]
* Steam client version (build number or date): 1719259903
* Distribution (e.g. Ubuntu):  SteamOS (20240422.1)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: https://drive.google.com/file/d/1EcBU94p-oNhE3BtB4VKiB9JFno-5Jflq/view?usp=sharing
* GPU: AMD Custom APU 0932

#### Please describe your issue in as much detail as possible:
Several games have Shader Pre-Caching updates on Steam Deck startup/wake. While some of them aren't that problematic, Warframe (in this example) is. The Shader Pre-Caching update for Warframe is approx. 1.3GB to 1.9GB. While this isn't an issue for me personally as of now, it might be for when I'm on the go and connected to my limited mobile data plan, or, for users with limited harddrive space and/or network speeds. Plus, depending on network speed, this slows down users from playing the game asap.

As far as I can tell, this issue has been prominent for a couple of years now.

#### Steps for reproducing this issue:

1. Download, install and play Warframe for a bit
2.  Sleep/turn off the steam deck
3. Wake/turn on the steam deck
4. Shader Pre-Caching update

While this wasn't the case immediately after downloading the game the issue happened recently (after about 3 days of having the game installed).

Hopefully the logs provided can help Steamdeck and Linux gamers alike!

**Comment by kisak-valve** [comment]
Hello @maxdp66, you've described that the precompiled shader cache bucket is changing often. Skimming shader_log.txt for AppID 230410, this is the case and Steam is behaving within expectations. Warframe has several million shaders in the pre-cache data set and the data set is changing over time.

This issue is already being tracked at #8076 (frequency), and #10285 (download size). Closing in favor of the older issue reports.
