### ISSUE TITLE
Steam client segmentation fault

### ISSUE THREAD

**Issue by Chiffario** [ValveSoftware/steam-for-linux#11406]
#### Your system information

* Steam client version (build number or date): 1.0.0.81-2
* Distribution (e.g. Ubuntu): Endeavour
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/17562198/steam-logs.tar.gz)
* GPU: Nvidia GTX 1660S

#### Please describe your issue in as much detail as possible:
Running Steam causes a segmentation fault

Logs for running `steam`:
https://gist.github.com/Chiffario/8047090602bc17923edef453f11884f8

Logs for running `DEBUGGER=gdb steam`
https://gist.github.com/Chiffario/d293d915a93e442eb950b22663fe6dd0

**Comment by kisak-valve** [comment]
Hello @Chiffario, `pressure-vessel-wrap[153421]: E: Could not create copy "./lib/x86_64-linux-gnu/libgcc_s.so.1" from "/home/chiffa/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/sniper_platform_0.20240618.92328/files/./lib/x86_64-linux-gnu/libgcc_s.so.1" into "/home/chiffa/.local/share/Steam/ubuntu12_64/steam-runtime-sniper/var/tmp-9UWUW2/usr": fstatat(./lib/x86_64-linux-gnu/libgcc_s.so.1): No such file or directory` is the line to focus on in your terminal spew.

I would check if that libgcc_s.so.1 is healthy, then move/remove `/home/chiffa/.local/share/Steam/ubuntu12_64/steam-runtime-sniper` so that the folder is regenerated on the next Steam start and see if that changes anything.

**Comment by Chiffario** [comment]
Not sure how to check the health of `libgcc_s.so.1`, but doing `rm -rf .local/share/Steam/` into running `steam` still causes a segfault

tail of the log:
https://gist.github.com/Chiffario/89e3e6c9166671112cb2d4be5bb9d3ae

upon removing just `.local/share/Steam/ubuntu12_64/steam-runtime/sniper` and running steam with gdb, the segfault still remains and still points to libaudio.so

doing that and `pacman -Rs steam` doesn't affect things either

**Comment by Chiffario** [comment]
Update: Flatpak doesn't work either
launch log: https://gist.github.com/Chiffario/220f4a2f403fb214c4411a2997861194
logs from `.var/app/com.valvesoftware.Steam/.local/share/Steam/logs`: 
[flatpak-logs.tar.gz](https://github.com/user-attachments/files/17566912/flatpak-logs.tar.gz)

**Comment by Chiffario** [comment]
Deleting `.steam` and trying to forcefully downgrade Steam via `steam -forcesteamupdate -forcepackagedownload -overridepackageurl https://web.archive.org/web/20240210115543if_/http://media.steampowered.com/client -exitsteam` and running `steam` normally afterwards removed the libgcc error message, but the segfault remains and the client doesn't launch

**Comment by Chiffario** [comment]
Update: After some extra checking, it seems to only segfault on LTS kernel version (6.6.58-1) and not on latest Stable (6.11.5-arch1-1 in my case)

**Comment by Chiffario** [comment]
Update: upon further investigation, it seems to be a duplicate of #9289, so pls close the issue if that's necessary

**Comment by kisak-valve** [comment]
Closing in favor of the older issue report.
