### ISSUE TITLE
Steam Input configuration not functional in some games with DS5

### ISSUE THREAD

**Issue by nullwyrm** [ValveSoftware/steam-for-linux#11428]
#### Your system information

* Steam client version (build number or date): 1730853027
* Distribution (e.g. Ubuntu): Ubuntu 22.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: Includes personal information, which would be too much effort to filter out at this time. If specific logs are relevant, I can provide those.
* GPU: Intel

#### Please describe your issue in as much detail as possible:
As of the latest steam client update, my DualSense5 controller has started behaving oddly in Hollow Knight when running the native version. This issue has not been occurring when using proton.
Specifically, the square and triangle buttons are swapped with regards to their usual behaviour, and the the start and select buttons are completely nonfunctional, with those functions instead being applied when half-pressing the right or left triggers, respectively.
Furthermore, attempting to rectify this using Steam Input's remapping features didn't work, as any edits made did not reflect in game, with the exception of adding an always-on layer to change the LED colour.

#### Steps for reproducing this issue:

1. Start Hollow Knight (or likely other games that run natively, but I can't easily test this right now)
2. Note that the controls are incorrect
3. Close the game, and edit the Steam Input map
4. Restart the game
5. Note that the controls are unchanged

**Comment by kisak-valve** [comment]
Hello @nullwyrm, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/8217. In particular, https://github.com/ValveSoftware/steam-for-linux/issues/8217#issuecomment-1179724343.

In the recent Steam client update cycle, it's expected that Linux native games started to be run inside the Steam Linux Runtime container environment, but we already know that this game bundles and older version of SDL2 that has a hard time with your controller.

Closing in favor of the older issue report.
