### ISSUE TITLE
Offer and allow to select Steam Linux Runtime 3.0 (sniper) on the compatibility tool dropdown list

### ISSUE THREAD

**Issue by tgurr** [ValveSoftware/steam-for-linux#11607]
#### Your system information

* Steam client version (build number or date): 1734743608
* Distribution (e.g. Ubuntu):  Exherbo Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: -
* GPU: AMD

#### Please describe your issue in as much detail as possible:
https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/docs/slr-for-game-developers.md#native-linux-games-targeting-steam-runtime-3-sniper states that games may now move to the `Steam Linux Runtime 3.0 (sniper)` by adding an app_mappings config file like e.g. Battle for Wesnoth already did https://steamdb.info/app/599390/config/. I've come across two games (Factorio & shapez 2) which wouldn't launch on my machine

* https://forums.factorio.com/viewtopic.php?f=182&t=122412&p=643346
* https://steamcommunity.com/app/2162800/discussions/2/597388235197444790/

neither the native one nor when selecting a runtime excluding `Steam Linux Runtime 3.0 (sniper)` which worked for me in both cases. The problem is that it is not possible to easily select the 3.0 runtime via the compatibility tool dropdown list as that one only offers:

![image](https://github.com/user-attachments/assets/a64d6efa-994b-4c0c-95a3-03e582a04109)

Is there any reason to not also offer & allow to select the `Steam Linux Runtime 3.0 (sniper)` here as well? In my case it would've helped me to easily work around the problems instead of having to manually edit `~/.local/share/Steam/config/config.vdf` like:

```
			"2162800"
			{
-				"name"		"steamlinuxruntime"
+				"name"		"steamlinuxruntime_sniper"
				"config"		""
				"priority"		"250"
			}
```

#### Steps for reproducing this issue:

1.  Launch Steam
2.  Try to select `Steam Linux Runtime 3.0 (sniper)` as the compatibility tool for a game
3.  See it missing from the dropdown list

**Comment by kisak-valve** [comment]
Hello @tgurr, please see https://github.com/ValveSoftware/steam-for-linux/issues/7430#issuecomment-760932670, the short version is that the different runtimes are not ABI compatible with each other. Steam Linux Runtime 3.0 is not a straight upgrade with backwards compatibility.

If you have reasonable suspicion that there's a runtime issue with those two game, please file separate issue reports for each game in the [steam-runtime](https://github.com/ValveSoftware/steam-runtime/) issue tracker and include the requested information so that a runtime dev can ponder that with you.

**Comment by kisak-valve** [comment]
Regarding Factorio at least, it looks like you're forcing a build of SDL that doesn't have wayland to only try to use that before giving up. My guess would be that you've set `SDL_VIDEODRIVER=wayland` somewhere, and `SDL_VIDEODRIVER=wayland,x11` would behave better since it would allow SDL to fallback to x11 when its wayland backend isn't usable.

**Comment by tgurr** [comment]
Thanks for the explanations, looking forward for the respecting devs to opt-in to Steam Linux Runtime 3.0 then.

> Regarding Factorio at least, it looks like you're forcing a build of SDL that doesn't have wayland to only try to use that before giving up. My guess would be that you've set `SDL_VIDEODRIVER=wayland` somewhere, and `SDL_VIDEODRIVER=wayland,x11` would behave better since it would allow SDL to fallback to x11 when its wayland backend isn't usable.

I couldn't find anything relevant when trying to figure out why it stopped working `env | grep SDL_VIDEODRIVER` doesn't show anything and my SDL is compiled with both wayland an x11 support. I might open a steam-runtime bug like you've mentioned if I come across more issues as if I remember correctly things broken when the runtimes where updated, but that can always be a coincidence combined with system updates.
