### ISSUE TITLE
Windows apps downloading / installing in Linux (Feature request?!)

### ISSUE THREAD

**Issue by Vash63** [ValveSoftware/steam-for-linux#1989]
So, I decided to install Bioshock again after preordering Infinite... then rebooted 10% into the download to go back to my ArchLinux install. First thing I noticed... Steam is downloading Bioshock. I have 3 Steam Libraries, one of which is NTFS at the same location on both platforms. Surprisingly, this works perfectly so far.

The issue is there's no interface for it. Obviously the final install needs to be done in Windows for all the dependencies, but being able to manage a library across OSes is a great feature, even if accidental. My request would be an extra function to download and install incompatible games through a right-click menu under All Games in the library. I'm already doing it successfully so I'm fairly confident it would work and I think everyone who dual-boots (most gamers probably) would appreciate this.

The main issue I could see is games that are cross platform knowing which files belong to which platform... but you guys are Valve and you're brilliant; this is worth the effort, make it happen!

**Comment by StraToN** [comment]
This reason may be true for newer and not-released-yet games, but feels invalid to me when concerning old games. Steam sells a LOT of old games developed in the 90's, which are marked as Windows only and will never be ported to Linux ever.

Take the Thief series (1 & 2). They run fine under Wine. Although I'd like the developer to port it to Linux, those games are far too ancients for this to happen, whatever Valve desire is. 

My personal opinion is : I don't care the OS I am running. I paid a licence for a game, and this licence doesn't forbid me to use another OS than Windows - I'll just have no support for it, which is fine. Since I paid, I have to be allowed to easily have access to the files of the game. CLI means not "easy" to me. BTW, CLI doesn't always work to force-download Windows games under Linux.

**Comment by yogurt1** [comment]
Vendors can build they games native by Winelib linking against native MS libraries
Read more about Winemaker/WineGCC and winehq.org

**Comment by kisak-valve** [comment]
Closing per https://steamcommunity.com/games/221410/announcements/detail/1696055855739350561.
