### ISSUE TITLE
Game crash or interrupt causes game to not be terminated.

### ISSUE THREAD

**Issue by brl1214** [ValveSoftware/steam-for-linux#1997]
When css or tf2 crashes or has to be killed in terminal.

HL2_linux and gameoverlayui hang in top and cannot be killed. You cannot launch any other games and in order to use steam again you have to log off and log back in.

Steps to reproduce
Play game for a while and exit.
if game hangs and won't close continue to killing it via process id, killall hl2_linux, or xkill
check top and see hl2_linux still running in background and gameoverlayui
log off and log back in to force close them so you can relaunch the game.

The error you get if you try to restart steam without logging off is.

Fetal Error: Steam failed to load: *SteamStartEngine(0xffc01340) failed with error 1: A Steam Engine instance already exists.
and this is caused by a game crash or forced close game that just hangs in your task manager.

**Comment by kisak-valve** [comment]
Hello @brl1214, SIGKILL (kill -9) is for forcefully stopping a process instead of the default SIGTERM, which is the more polite way of asking a process to clean up what it's doing and close.

If you are still experiencing this issue on an up to date system, please open a new issue report in the game-specific issue tracker.
