### ISSUE TITLE
Steam cloud broken in FTL

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#2238]
I wouldn't be posting this here normally, however the developers have said it is managed by steam so they can't fix it. Is there any chance to get this working.

It works on windows but the linux version never does any sync.

http://www.ftlgame.com/forum/viewtopic.php?f=9&t=9823&sid=8fc72b8f8fd37e4c66c54a0847bdee82&start=10

**Comment by Goutte** [comment]
Lost all my progress after OS (kubuntu) reinstallation, despite having cloud sync enabled.

Just to mention that this issue is still very much alive, and that *someone* at valve should look into this, because FTL's unlocks are no cakewalk.

I should've stuck with the non-steam version of FTL. My mistake. :(

**Comment by not83** [comment]
Mate no point in bitching. Tell valve how to reproduce it and they'll do
their best to fix it. Valve says they want the best for gamers and I
believe they'll act in good faith to fix stuff to make it the best for
gamers

**Comment by Goutte** [comment]
You're right, I'm a bit pissed ; that's not constructive.

How to reproduce :

1. Install steam on an ubuntu variant
2. Install FTL
3. Play a game
4. Remove steam and steam files
5. Install steam again
6. Install FTL again
7. ???
8. Profit !

---

I did not try with the beta.

**Comment by daryltucker** [comment]
@not83 I appreciate where you're comming from with the attitude that one should provide as much information as possible and be polite when filing a bug.  However, it is unfortunate that it seems that both the Steam/Valve developers as well as the FTL developers keep blaming the other team for the issue.

This bug will be a year old very soon and it's frustrating to see something like this not resolved.  I frequently open FTL to give it a play, only to think about the pain of losing everything and deciding it's not worth the investment.

I think that a word about plans to resolve this, or anyting in general acknowledging it again would be nice.

Thanks

**Comment by chikitulfo** [comment]
This issue is still **unresolved after almost two years**... 
It definitely **should not be closed** as linux and mac users still suffer from it.

Steam cloud sync is actually working and doing its job well (when given the right conditions). The problem is the save file directory setup when doing a fresh install of FTL, due to  the fact that Linux and OS X file paths' are case sensitive.

It goes like this:
 - Install FTL for the first time on a Linux system. Steam will create the folder  
   ~/.local/share/**fasterthanlight** and sync your achievements there.
 - Run the game, it searches for the savegame directory and does not find it at 
   ~/.local/share/**FasterThanLight**  (the existing one is only lowercase). Therefore it creates it and starts a new fresh game with empty stats. Close the game.
 - Steam will sync from and to the lowercase folder, which will not be used by the game and therefore won't ever be updated. The user won't be able to access his previous saved stats and will be very sad.

This is an **extremely easy to solve problem**, just point the sync folder to the actual game folder **~/.local/share/FasterThanLight** instead of the lowercase one, this way it'll work on *all* operating systems. I can not believe that this issue is unresolved after almost two years despite how easy the solution is (if it is not as easy as I believe it to be, please tell me why, and think about it, because it's just three letters in a filepath...).
From what I can gather, it looks like the problem comes from valve, although it could also be the developers' fault if they are able to choose this path for cloud sync.

Yes, there are a number of workarounds to navigate around this issue, namely:
 1. Manually deleting the lowercase folder makes steam sync to the well capitalized one. Which leads me to think that steam knows the right folder is the well capitalized is there too, and falls back to it (Making this issue even more bizarre).
 2. Deleting one of them and symlinking one to the other (doesn't matter which one points to which).

However, the user shouldn't need to investigate these or even know about them, for it should be solved beforehand.

**Comment by ZanQdo** [comment]
Thanks @chikitulfo for the possible solution, will try it out with a symlink.

Please fix this thing!

**Comment by MathSquared** [comment]
Commenting to note that I recently switched laptops (old one ran Ubuntu, new one runs Debian) and upon installing Steam on my new laptop, my FTL profile synced from Steam Cloud without issue (to `~/.local/share/FasterThanLight`). Maybe they finally fixed it, though we'd need more users to confirm that before we deem this issue resolved.

**Comment by darkwisperer** [comment]
I have observed this on a fresh  install on ubuntu. Issue is still unresolved.

**Comment by cdusold** [comment]
Issue still unresolved. Freshly installed on Ubuntu after beating most of the game on Windows. I have developed for a Steam Game before, and would be willing to pick up this SUPER EASY TO FIX bug Pro Bono. Seriously guys. And it's definitely a Steam bug. I have seen it on other games. It used to affect Borderlands 2, but I think they fixed it. Probably with a workaround. Maybe Steam or the FTL team could ask 2K for help.

**Comment by reubenf-valve** [comment]
When the issue was closed, it was only fixed "going forward" -- accounts in a broken state remained in a broken state.  If anyone still in a broken state is willing to test a fix, send me your steamid and I can fix up the backend for you next week and see if that resolves it (and if so, I'll clean up the rest of the accounts in that state, too.)

This is only if you are still failing to see state persist across installs on the *same* OS, however -- the game is not configured for cross-platform saves.

**Comment by jck** [comment]
This issue appears to have been fixed for FTL. However, the same case-sensitivity issues still exist for SpaceChem.

More Info: http://steamcommunity.com/app/92800/discussions/0/604941528468708446/

**Comment by da2x** [comment]
@reubenf-valve, any chance you could fix this for all users? This is still an issue.

**Comment by SoptikHa2** [comment]
Still an issue. Creating symbolic links between uppercase-lowercase folders didn't help. @chikitulfo's solution doesn't work for me.

**Comment by sk3z** [comment]
still an issue

**Comment by MantasMikal** [comment]
Any news on this?

**Comment by cra0zy** [comment]
Here is an easy fix the devs can implement to fix this once for all, I sent an email to them, hopefully they notice it. The fix is to modify the FTL script in the game folder to do the following:

```sh
#!/bin/bash

# fix steam sync
if [ -d "$HOME/.local/share/fasterthanlight" ] && [ ! -d "$HOME/.local/share/FasterThanLight" ]
then
    ln -s "$HOME/.local/share/fasterthanlight" "$HOME/.local/share/FasterThanLight"
fi

# enter the game directory
cd ./data

# run FTL
exec ./FTL "$@"
```
