### ISSUE TITLE
verbose UserLocalConfigStore errors loading steam

### ISSUE THREAD

**Issue by sorokin** [ValveSoftware/steam-for-linux#2281]
I have a long list of error when I start steam:

KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file UserLocalConfigStore [offset: 49152]
UserLocalConfigStore, apptickets, 206690, (_41800_), (_CDDialog_), (_NameHistory_), 
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file UserLocalConfigStore [offset: 49152]
UserLocalConfigStore, (_apptickets_), (_206690_), (_41800_), (_CDDialog_), (_NameHistory_), 
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/tier1/../tier1/KeyValues.cpp (2388) : Assertion Failed: Error while parsing text KeyValues for resource UserLocalConfigStore
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file UserLocalConfigStore [offset: 49152]
UserLocalConfigStore, apptickets, 206690, (_41800_), (_CDDialog_), (_NameHistory_), 
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file UserLocalConfigStore [offset: 49152]
UserLocalConfigStore, (_apptickets_), (_206690_), (_41800_), (_CDDialog_), (_NameHistory_), 
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/tier1/../tier1/KeyValues.cpp (2388) : Assertion Failed: Error while parsing text KeyValues for resource UserLocalConfigStore
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file UserLocalConfigStore [offset: 49152]
UserLocalConfigStore, apptickets, 206690, (_41800_), (_CDDialog_), (_NameHistory_), 
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file UserLocalConfigStore [offset: 49152]
UserLocalConfigStore, (_apptickets_), (_206690_), (_41800_), (_CDDialog_), (_NameHistory_), 
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/tier1/../tier1/KeyValues.cpp (2388) : Assertion Failed: Error while parsing text KeyValues for resource UserLocalConfigStore

Everything works. But perhaps these errors could be fixed.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue with an up to date client?

**Comment by boltronics** [comment]
Haven't seen it in ages. Haven't ran out of space in ages either. :smiley:

**Comment by kisak-valve** [comment]
Closing in favor of #2543.

**Comment by zor1984qq** [comment]
Its not a space issue dude it something worse, I have the same on my Manjaro system and it can be possible corrupted due to power outage or recent bad system shutdown and I have a lot of space in there and it happens for me much more frequently under hipster Linux systems, on Ubuntu (or any flavour) I haven't had such problems like NEVER:

dev                3,9G            0  3,9G            0% /dev
run                3,9G         1,6M  3,9G            1% /run
/dev/sda3          908G         160G  702G           19% /
tmpfs              3,9G          26M  3,9G            1% /dev/shm
tmpfs              3,9G            0  3,9G            0% /sys/fs/cgroup
tmpfs              3,9G         7,0M  3,9G            1% /tmp
/dev/sda2          976M          97M  812M           11% /boot
tmpfs              799M          16K  799M            1% /run/user/1000
