### ISSUE TITLE
Can't click in TF2

### ISSUE THREAD

**Issue by mbloms** [ValveSoftware/steam-for-linux#2332]
Everything seems fine when I start TF2, but when I try clicking entries in the menu, nothing happens. I can't even quit normally I need to switch to the desktop and close it from there. I tried navigating with arrow keys. It works, but I can't select anything using Enter. (I guess you should be able to do that...)

I am running Linux Mint 13 maya 64-bit
GTX 680
Intel i5-3570K, 3.40 GHz
8 GiB DDR3

**Comment by kisak-valve** [comment]
Hello, is anyone still seeing this issue with an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by AuditeMarlow** [comment]
@kisak-valve I am, apparently. Same problem as @pepijndevos. I'm using Steam on Arch Linux with i3 as my WM. TF2 boots just fine, but after a while, everything becomes unresponsive to about anything. I can't click, I can't type. If I switch out of TF2, it refuses to respond, too.

**Comment by kisak-valve** [comment]
Hello @AuditeMarlow, it would probably be best to open a new issue report in the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games). In addition to the details here, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in that issue report. At a glance, it sounds like your issue is that TF2 stops rendering completely, while the issue described here indicates that the mouse keys still work in the menu.

**Comment by pseregiet** [comment]
I have the same issue on Arch Linux with i3. I had this system on this very computer for years and I used to play tf2 a lot, so I'm not sure what happened (I haven't played the game in few months). I can't click anything in the main menu, but the keyboard works. I can open the dev console with ~ and type in commands. I can also select the text with the mouse, but I can't close or move this window with the mouse.
![2024-10-27_00-40](https://github.com/user-attachments/assets/28a3deea-612e-44fb-9f08-3a018591b055)
