### ISSUE TITLE
With Nvidia Multi screen in portrait mode the game can't be bigger than a single screen

### ISSUE THREAD

**Issue by MathieuVillegas** [ValveSoftware/steam-for-linux#2392]
I have 4 1080p displays used in portait mode (side by side).
I would like to play source games (CSS, DOD source, TF2, portal, etc..) games on at least 3 of the monitors, but it is impossible to have a game bigger than a single screen (1080x1920).
I've tried all the display modes available (Full screen (0-3), and "Run in Window", and I can't have more than 1080x1920.
I even tried the command line in windowed mode, to force a larger window, but it every time fallback to 1080 pixels large.
Note that when in windowed mode, I can move the window on all screens and play with the windows on two screen at the same time.
Maybe the issue come from a check which prevent window bigger than a screen, but it should consider desktop size more than just a single screen size.

I have an Nvidia 660 GTX Ti with drivers 313.30 on ubuntu 13.04 ( same thing for ubuntu 12.10)

**Comment by beankylla** [comment]
Hello, 
this issue is common to all steam games I tried so far (Dota2, HL2, TF2(duh), Metro last light).
When i launch nexuiz, (from linux repository), it launches on all 3 monitors without any problem.
there seems to be a limit in steam somewhere that says, "1 screen at a time".

OS : Linux mint debian 2 (Betsy)
Nvidia 970 strix
amd x6 1055 T 
8 Go Ram

**Comment by kisak-valve** [comment]
Closing in favor of https://github.com/ValveSoftware/Source-1-Games/issues/1525
