### ISSUE TITLE
Middle clicking in the Steam client causes Steam to be unresponsive

### ISSUE THREAD

**Issue by TomasDuda** [ValveSoftware/steam-for-linux#2424]
UI (main menu, back/forward buttons etc.) is unresponsive when I middle click in the Steam client. Right clicking fixes the issue, but it's a little annoying.

This issue will be probably fixed when support for the PRIMARY selection will be added (#27), but I think it's still worth mentioning.

**Comment by bjwest** [comment]
Here we are almost two years and countless update later, and this is still a problem.  If you're going to start taking away features from my OS in the client, at least fix the problem so it doesn't become unresponsive.  Middle-click paste is a highly used feature in Linux, and an accidental middle click is easy to do on sensitive scroll wheels.  It's pretty much muscle memory to highlight something and middle click wherever you want to past it.  To have not only the Steam client, but my whole system become unresponsive due to this is completely unacceptable, especially **two years after** it was initially reported.

**Comment by ShabbyX** [comment]
I can also reproduce this issue, which I discovered by accidentally middle-clicking on a discussion (to open in a new tab, I know, I know).

**Comment by Yankee14** [comment]
I'm having the same issue. Glad I finally found a thread with others facing the same problem.

**Comment by Plaque-fcc** [comment]
Middle clicking in Steam Client window causes Steam UI to be
unresponsive, yes. Pages (webview) do respond, window elements do not.

Having this, yeah, and with the latest update.

**Comment by itzexor** [comment]
This is reproducible for me every time by middle clicking any link on the store page. All applications including the steam client except for the embedded browser become unresponsive to mouse clicks until you right click anywhere within the steam client.

**Comment by Yankee14** [comment]
It seems to be reproducible for me by middle clicking anywhere in the Steam client, on any page. Pages become responsive again in the same way you described.

**Comment by Goury** [comment]
So what?
Three years and still not fixed?
This is truely hows valve time is working =(

**Comment by Two-Tone** [comment]
Fixed in the latest client

http://store.steampowered.com/news/21717/

**Comment by not83** [comment]
can be closed now

**Comment by Holzhaus** [comment]
Fix is working, this can be closed now.

**Comment by TomasDuda** [comment]
:+1:
