### ISSUE TITLE
TF2 and Steam STILL crashing

### ISSUE THREAD

**Issue by ggabriel96** [ValveSoftware/steam-for-linux#2540]
Hello guys. I installed Fedora 18 on my ASUS G1S a few days ago and then installed the proper nVidia driver, updated everything, installed Steam and downloaded Team Fortress 2. But, I got that error about SELinux asking me to do this:

grep hl2_linux /var/log/audit/audit.log | audit2allow -M mypol
semodule -i mypol.pp

Okay, with that done, I tried again. It started normally, but when attempting to connect to a game, Steam crashed and gave me the execheap error. Searching for it, I've done what people told to:

setsebool -P selinuxuser_execheap 1
(and, detail, I did this too:) setsebool -P allow_execheap 1

Finally, happy that I would be able to play, I tried again. But... nothing! It still crashes when joining a game, or even when trying to use Big Picture. 
And two curious things: I'm able to play offline (the Training thing), and just found out that switching between apps (Alt+Tab) also crashes TF2... ;x
I don't know what else I can do... and yes, I read all the other topics about this problem and as I told you above, couldn't fix it ;/

**Comment by kisak-valve** [comment]
Hello @ggabriel96, if you are still experiencing this issue with an up to date system, please open a new issue report on the  [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker. Sounds like the last assessment was that this was most likely due to vram pressure on the nVidia driver. and lowering the graphics settings may have helped.
