### ISSUE TITLE
Closing the main steam window make steam exit

### ISSUE THREAD

**Issue by WhyNotHugo** [ValveSoftware/steam-for-linux#2685]
If I click on the "x" button at the upper-right corner of steam's main window, it'll minimize to the taskbar.

It I close the window in ANY other way, steam completely exits.
(other ways I close steam: alt+f4, with my WM's close-window functionality, via compiz's scale plugin, etc).

The funny this is that this does NOT happen with winsteam+wine.

**Comment by Yanpas** [comment]
Under XFCE Steam window will be always in windows list. Why doesn't it closes to tray?

**Comment by ibrokemypie** [comment]
any workaround for this?

**Comment by rosshadden** [comment]
It's not just the main steam window, by the way. It is any steam window at all, including the friends list and any of the dialogs that may pop up. For all of them the behavior is the same as what you mentioned: clicking the X works perfectly, but sending a `kill` signal to the window (the equivalent of alt+f4 in windows) exits steam.

**Comment by rosshadden** [comment]
I found [this reddit thread](https://www.reddit.com/r/i3wm/comments/9i81rf/close_steam_to_tray_instead_of_killing_the_process/) with some helpful info.

Two things there worked for me:

- `xdotool windowunmap`
- Mousing over a tab like Library and _then_ sending `kill` or alt+f4 or whatever. I bet this has to do with the popup somehow, but it's not very useful for me because it's only for the main window, and it requires the rodent :mouse: :computer_mouse:.

Like one person said, `xdotool windowclose` seemed to work at first but upon further investigation it actually put steam into a weird zombie state.

**Comment by Precrisk** [comment]
Same behaviour here, on Gnome 3.32 Manjaro Linux

**Comment by pastapojken** [comment]
> I found [this reddit thread](https://www.reddit.com/r/i3wm/comments/9i81rf/close_steam_to_tray_instead_of_killing_the_process/) with some helpful info.
> 
> Two things there worked for me:
> 
>     * `xdotool windowunmap`
> 
>     * Mousing over a tab like Library and _then_ sending `kill` or alt+f4 or whatever. I bet this has to do with the popup somehow, but it's not very useful for me because it's only for the main window, and it requires the rodent mouse computer_mouse.
> 
> 
> Like one person said, `xdotool windowclose` seemed to work at first but upon further investigation it actually put steam into a weird zombie state.

Ha! That's me! Wanted to add that I've been running into this weird behavior lately, when re-opening steam after a `windowunmap` steam handles a single left click as a multi-select click. It will highlight stuff in the store or select multiple games in library instead of just doing a single left click.

**Comment by My1** [comment]
same here for Kubuntu 18.04 LTS. using ANY methode to close steam except for the stupidly small x in the steam windows itself knocks it down completely instead of (like in windows) sending it to the systray, where you can only kill steam using the Exit option or the task Manager or other things to kill the process.

**Comment by pkillnine** [comment]
is there any workaround for this?

**Comment by wolfskream** [comment]
Guys, we're closing in on 8 years... Valve... I love you guys, but what are you doing, seriously?? Why is this so difficult to fix?

**Comment by wolfskream** [comment]
So, we're closing in on 8 years... Valve... I love you guys, but what are you doing, seriously?? Why is this so difficult to fix?

**Comment by wolfskream** [comment]
7 years and 8 months... Valve... I love you guys, but what are you doing, seriously?? Why is this so difficult to fix?

**Comment by akvadrako** [comment]
I have the opposite problem. When I close the steam window it DOES NOT exit. I wish I would.

**Comment by pkillnine** [comment]
@akvadrako try setting environment variable `STEAM_FRAME_FORCE_CLOSE=1` before running steam.

**Comment by tunbridgep** [comment]
I know this isn't a "fix", just a suggestion, but most Linux programs I know of that have a tray, do so by having it as a separate application.

If closing the window to tray was causing issues for people, maybe it would make the most sense to ship a separate steam-tray application that maintains steam state and destroys/creates the Steam application window.

That usually requires applications to realistically run a daemon though, and Steam is a lot more monolithic than that.

Anyway, the script provided in the reddit thread worked for me, however it's a very hacky workaround. Please fix. I am commenting here in the hopes that we can get a real fix for this.

**Comment by BlueCannonBall** [comment]
> Anyway, the script provided in the reddit thread worked for me, however it's a very hacky workaround. Please fix. I am commenting here in the hopes that we can get a real fix for this.

Where's the script in the Reddit thread?

**Comment by ReFleXzZ** [comment]
It's really annoying.. I have a dual-boot system With Garuda Linux (Arch-based), running KDE and Windows 10. On Windows 10 I close the steam window and then it minimizes to the tray icon. Just minimizing it, minimizes it to the taskbar (on KDE using Latte-Dock, it's the dock). I would expect the same on my Linux installation, since steam just takes space on my panel. So I close it as I would do it in Windows and bam steam shuts down itself and running games which are not saved. There isn't even a need to close steam via "x", since you can rightclick on the tray as on Windows and end Steam.
As a proposal, you could make it optional for Linux in the "UI-Settings" from Steam. Why is this still a thing though?

**Comment by tunbridgep** [comment]
> But clicking the really-tiny "X" on the upper-right corner of the screen minimizes to tray. The behaviour is rather inconsistant and unintuitive. Also, since steam has it's own widgets, the "X" has a fixed size and is hard to point at for people with poor motor skills.

It's actually worse than this.

It seems to be absolutely positioned so if you use a tiling WM like i3 and split the screen in half vertically (so the steam Window becomes tall), the X button disappears. Because the usual way to close applications with a tiling WM is a keyboard shortcut anyway (which, IIRC sends SIGQUIT), but Steam doesn't close the normal way (minimizing to tray) and instead just dies.

This means that, with a tiling WM, in certain window positions, there's no easy way to close steam to the tray.

They could probably fix this by making the exit button in steam do the standard application close behavior, and ensure that it closes correctly.

I think someone should try other close methods too, like alt-f4, to see if they break it

**Comment by austin5627** [comment]
This seems to be fixed in the current beta

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
