### ISSUE TITLE
Steam Desktop and Menu entrys don't work [+Solution]

### ISSUE THREAD

**Issue by OWKenobi** [ValveSoftware/steam-for-linux#2745]
Hi all,

On Linux Mint LMDE (and possibly other ubuntu based distros), I cannot start steam by clicking any desktop icon or menu entry, and I cannot start any steam game by clicking on the respective icons. It fails not finding files. However if I enter "steam" in a terminal, it all works fine.

I figured out that adding this line to the beginning of /usr/bin/steam solves the problem - with it all works like a charm:

```
 source ~/.bashrc
```

Apparently the bashrc file is not in memory in every user scenario. Another related bug: the .bashrc-file that steam creates confuses my compiler - if I try to compile any other code, when it should not, then it reads the misleading variable $LD_LIBRARY_PATH that steam has placed there and fails - that is no the intended behaviour. So an even better solution would be if Steam created, on install, another file, like ~/.steambashrc and put following line in the /usr/bin/steam

```
 source ~/.steambashrc
```

This would be GOLD solution :-)

**Comment by kisak-valve** [comment]
I'm going to close this as Debian provides steam packaging which does not require any workaround similar to this issue report. If you still need to have those overrides, you should consider adding it to the /usr/bin/steam script since that is provided by the steam package and not likely to change often.
