### ISSUE TITLE
steam has trouble with alsa plug pcm

### ISSUE THREAD

**Issue by buscher** [ValveSoftware/steam-for-linux#2962]
Hi,

I am a pure alsa user and while toying around with alsa I noticed that steam can't "handle" plug pcms.

I have the following pcm which duplicates the output and outputs its on 2 devices.

pcm.!default {
     type plug
     slave.pcm "xxx"
}

pcm.xxx {
    type plug
    slave.pcm {
        type multi
        slaves {
            a { channels 2 pcm "hw:2,0" }  # usb headset
            b { channels 2 pcm "hw:1,0" }  # intern pci soundcard
        }
        bindings {
            0 { slave a channel 0 }
            1 { slave a channel 1 }
            2 { slave b channel 0 }
            3 { slave b channel 1 }
        }
    }
    ttable [
        [ 1 0 1 0 ]   # left  -> a.left,  b.left
        [ 0 1 0 1 ]   # right -> a.right, b.right
    ]
}

when trying to play a video(non-flash) or play a game, I just get noise, or steam crashes.

NOTE: without steam it works fine, I tried ioquake3, ut2004, minecraft mplayer/mplayer2/mpv, speaker-test.

A good example is VVVVVV as it works without steam, and it does work fine without steam, but inside steam (all 32bit) I just get noise or no sound.

**Comment by kisak-valve** [comment]
Hello @buscher, are you still experiencing this issue on an up to date system?

**Comment by buscher** [comment]
Yes, I just retested with latest released (not beta) steam and up to date system.

`pcm.!default {
type plug
slave.pcm "null"
}`
in /etc/asound.conf

ALSOFT_DRIVERS=alsa SDL_AUDIODRIVER=alsa AUDIODEV=null steam

still causes problems. Video is way too fast and "choppy".

**Comment by kisak-valve** [comment]
I personally do not consider that test case as valid because there is no steam-compatible x86 hardware in the wild that does not have at least one audio device, which leaves this issue being about the type multi section of your originally posted config. Also, there most likely is something using the audio device before the steam game starts. Adding dmix before the type multi section may help.

Specific to video playback in steam, web content including the HTML5 videos on steam's store pages are rendered by libcef, and this would need to be pursued upstream.

**Comment by buscher** [comment]
Sorry, I lost interest in this bug report. What should we do? close it? leave it open forever?
As I think you are right that dmix would help here, I would go for upstream fix needed (aka libcef) and close the rest as invalid?

**Comment by kisak-valve** [comment]
If you don't want to pursue this further, that's totally fine. Closing.
