### ISSUE TITLE
Limit on how many recently launched games should be showed in steam unity indicator

### ISSUE THREAD

**Issue by fourzerofour** [ValveSoftware/steam-for-linux#3037]
There should be changeable limit for this. As of now, it's not clear whether or not there's hardcoded limit for the number of recently launched games showed in the indicator.  On my netbook, the indicator menu has grown rather long and reached the bottom of my screen so it's not pretty. I imagine the menu will be be even more longer after a while http://i.imgur.com/7D3oXEU.png

**Comment by dearlygparted** [comment]
This is still an issue, but I can see there is no one assigned. Please, do not ignore this. It's not critical but it is quite annoying and should be easy to fix. The limit should be 5, like on Windows, 20 is too much, my list is shows games that I haven't played in years.

**Comment by fishears** [comment]
Sad to see this has been overlooked for so long. My reason for wanting this changed is that
 it can cause the Steam menu to not appear at all on Ubuntu 18.04. With a game list of 20, if I have more than four destination links enabled as well the menu will not be shown when clicking the Steam icon. This is due to the appindicator system not having a scroll feature - if the menu won't fit on screen, it simply won't be displayed. 
On a side-note but still related, the list includes games that are not installed and even games that I have completely removed from my Library.

**Comment by Plagman** [comment]
Fixed in next Beta.

**Comment by vfjpl** [comment]
Is it in stable now? If yes then in what update it was pushed?

**Comment by kisak-valve** [comment]
Per "Fixed system tray including menu sometimes including too many recent game entries" in the [2019-01-16](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1703951108822305086) Steam client beta update, please retest this issue.

**Comment by kisak-valve** [comment]
This has shipped in the stable client.
