### ISSUE TITLE
Remove hard-dependency on NetworkManager (libnm-glib.so.4 and libnm-util.so.2)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#3129]
I'm not using NetworkManager, but steam still forces me to have the libraries installed for no reason when not using the runtime. Steam starts and runs just fine without NetworkManager, but obviously complains that it didn't find a running instance.

I would greatly appreciate if you could fix this.

**Comment by shoober420** [comment]
I don’t mind so much the dependency of libnm, but the dependency of the legacy version of libnm (libnm-glib) is a big issue, performance and security wise.

**Comment by GoLD-ReaVeR** [comment]
libnm in itself as a dependency *is* a problem. It means steam purports to
control the way the system functions. This would be no problem for Steam
OS, but for regular Linux distributions this is a hard NO-NO. Furthermore,
not everyone uses network manager, especially those with an ethernet card
have absolutely no use for it. It clogs the system with extra unnecessary
dependencies as well. Steam should by all accounts be able to live without,
as it is a gaming platform and not a control panel.

**Comment by shoober420** [comment]
I assumed Steam used libnm for streaming or something like that, I didn’t know it manipulated libnm like that. So I decided to look at the dependency tree for “networkmanager” and “libnm”, and here’s what I found.

networkmanager had no hard dependencies on my machine, so I ran “sudo pacman-Rs networkmanager” to uninstall the whole dependency tree. To my surprise, there was like 6 other packages that got removed (libteam, libpgm, and libnewt come to mind).

It made me wonder what I installed that required networkmanager to begin with. Anyway, I then investigated the libnm package, and found that this is what Steam truly depends on (libnm-glib technically).

Steam is also the only package on my system that requires libnm and libnm-glib. Upon learning all these things, I also totally advocate for the removal of the libnm dependency from Steam, especially since it’s also using the legacy version, libnm-glib.

**Comment by aspann** [comment]
Sadly in 2020 this is still an issue. Are there any plans to remove this deprecated and no longer supported libraries? Everybody who uses a native steam-runtime will be hit by this issue sooner or later.

Keep in mind, that it was removed in March 2019: https://github.com/NetworkManager/NetworkManager/pull/308

cheers.

**Comment by jojo-qa** [comment]
Steam is not working on my Fedora 33:

`[jonathan.souza@HOTBHZA004698 bin32] $ LD_LIBRARY_PATH=".:${LD_LIBRARY_PATH}" ldd $(file *|sed '/ELF/!d;s/:.*//g')|grep 'not found'|sort|uniq
	libnm-glib.so.4 => not found
	libnm-util.so.2 => not found
	libudev.so.0 => not found
`

**Comment by shoober420** [comment]
@jojo-qa 
Does fedora have libnm-glib in its repos? It is legacy software, although I would hope the Steam runtime includes it.

**Comment by kisak-valve** [comment]
Hello, Steam is no longer linked against these libraries.

**Comment by shoober420** [comment]
I can confirm that legacy libnm-glib isn't required, thank you.
