### ISSUE TITLE
OpenGL GLX context is not using direct rendering, which may cause performance problems.

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#3280]
https://gist.github.com/gutigen/1906a47bc63bf82f4a8f

Files Steam fails to loads are all there (checked). Tried adding my user to video group.

Ubuntu 14.04 64bit with Oibaf PPA (have to use it for optimal performance).

It started happening after updating my system today (I do that manually every few days with dist-upgrade). Unigine Benchmarks and non-source games work like before.

EDIT:

I reverted back to stack from Ubuntu repo (with ppa-purge) and problem is gone, so I guess there is something wrong with packages from Oibaf PPA.

**Comment by Ragers** [comment]
I worked on a solution for this issue yesterday.
please see it here:
http://askubuntu.com/questions/539858/ubuntu-14-04-could-not-find-required-opengl-entry-point-glgeterror/592692#592692

**Comment by touqeershafi** [comment]
I have intel Q33 Chipset, I've also installed the latest version of the display driver but every time when i run dota 2 it gives me same error "could not find required opengl entry point" 
What i'm doing wrong don't know

**Comment by RobLoach** [comment]
Switched to Ubuntu MATE, and was running into the r600 problem. The script @Half-Shot [posted above](https://github.com/ValveSoftware/steam-for-linux/issues/3280#issuecomment-47693038) fixed it, but I needed to run it a few times when Steam was updating itself.

**Comment by brodock** [comment]
As I still coming back here, I will share my solution, that survives steam updates:

Edit the file (with sudo) /usr/share/applications/steam.desktop and change the line 4 to:
```
Exec=env STEAM_RUNTIME=0 /usr/bin/steam %U
```

**Comment by francoisjacques** [comment]
@Half-Shot clear and concise, thank you!

**Comment by syslogic** [comment]
It seems the recent update of steam run-time reintroduced the issue - at least it worked all fine before.

**Comment by fortranbasic** [comment]
Hello,

I am facing problems when trying to play Mount&Blade Warband on Steam, i.e Steam launches without problems but the game mentioned above is not launching when pressing the play button. (I am able to launch and play other games.)

My operating system is Ubuntu 20.04.1 LTS. I am total newbie to Linux but willing/trying to learn more. I read a lot about the problem I am having with launching the game and these are the things that I tried so far:

1) Removed libgcc_s.so.1 from .../ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu
2) At some point the terminal told me that I am missing some 32-bit libraries, I installed them.
3) Tried “STEAM_RUNTIME=0 steam” but it returned “...Can’t find ‘steam-runtime-check-requirements’…”. I couldn’t find out what are exactly these requirements.
4) Installed libaudio2:i386
5) Tried the solution with drivers, i.e chose nvidia_driver_455 from Software&Updates and installed 32-bit Nvidia drivers with “sudo apt-get install libnvidia-gl-455:i386”
6) Found some missing runtime libraries but when trying to install themi terminal was unable to locate the packages for them.
7) Removed and installed Steam multiple times (also with purge).
8) Went back to the .../ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu (and to other similar steam runtime folders) and added  libgcc_s.so.1 but this time renamed it.
9) Tried the script given by @Half-Shot [here](https://github.com/ValveSoftware/steam-for-linux/issues/3280#issuecomment-47693038).(Steam is not in $HOME/.local/share/Steam/ in my case. Instead of that, I removed the libstd and libgcc from ~/.steam)

Non of them solved the problem. Still when pressing the play button it tries to launch for a second and then nothing happens.
Any advice/answer would be highly appreciated. Thanks!
