### ISSUE TITLE
No persistent notification for new chat messages

### ISSUE THREAD

**Issue by Macil** [ValveSoftware/steam-for-linux#3403]
I'm on Ubuntu 13.10, using the default standard Unity window manager.

Whenever I get a chat message from a friend, Steam makes some chat-alert noise at that moment, but otherwise has no sort of lasting notification letting me know I have new messages. Steam has an icon in the system tray at the top right, and an icon for its window on the left side. Most messaging programs like Pidgin and Skype will light up their system tray and/or window icons whenever I get a new message, and keep the icon lit up until I open the window. Steam does not do this, for me anyway. Instead, I'll decide I want to play a game, click the icon to bring up the Steam window, and the chat window will un-minimize too and show me chat messages that have been waiting for 12 hours for me. Or sometimes the chat window won't exist, and I'll only see the messages if I decide to chat with a friend, spawning a chat window, and the new chat window will already have multiple tabs lit up with old messages waiting to me.

**Comment by SweetieHD** [comment]
After about 1 month of this problem i finally had enough ! so i did multiple things that did not work. My final option WORKED so here is the sollution: 
Install a Steam Skin. i reccomend this one here: http://www.deviantart.com/art/PixelVision-Skin-for-Steam-211426153 It compleatly fixed my problem 100% i hope i can help you with this because i have seen for many users they have been trying to fix this for years :)

**Comment by Uramekus** [comment]
messages stay on notifications until read rn, but this can be " reassigned"  as system tray unread notification could be useful
