### ISSUE TITLE
Installing a game from command line with -applaunch or steam://install doesn't work anymore

### ISSUE THREAD

**Issue by Letiliel** [ValveSoftware/steam-for-linux#3474]
It works if Steam is already launched, otherwise it launches Steam but doesn't open the game install dialog.

Same thing with Windows Steam when trying it through Wine.

**Comment by tatsujb** [comment]
`steam steam://install/appid`
doesn't work for me both with steam closed and open. 

how do you guys get it to work?

**Comment by rokejulianlockhart** [comment]
@tatsujb, did you get it to work?

**Comment by tatsujb** [comment]
nope.

**Comment by rokejulianlockhart** [comment]
@tatsujb, I got it to work – https://github.com/ValveSoftware/steam-for-linux/issues/9442#issuecomment-1532237772. However, I'm rather disappointed by how the actual installation is performed graphically (apparently by design) and consequently that `steam` applications cannot be installed headlessly.

**Comment by tatsujb** [comment]
@rokejulianlockhart it works for me now.
