### ISSUE TITLE
Steam not running on Kubuntu 14.04

### ISSUE THREAD

**Issue by yohanleafheart** [ValveSoftware/steam-for-linux#3692]
Hey guys, 

I just installed steam on my Kubuntu 14.04 machine. Got the steam_latest.deb installed correctly, but when I run it I'm getting a package problem.

> Steam needs to install these additional packages: 
>        libcurl3-gnutls:i386, libpixman-1-0:i386, libtheora0:i386, libudev0:i386, libvorbisfile3:i386, libcairo2:i386, libgdk-pixbuf2.0-0:i386, libgtk2.0-0:i386, libnspr4:i386, libnss3:i386, libpango1.0-0:i386, libsdl1.2debian:i386
> 
> Reading package lists... Done
> Building dependency tree  
> Reading state information... Done
> Package libudev0:i386 is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> However the following packages replace it:
>   libudev0
> 
> E: Package 'libudev0:i386' has no installation candidate
> Press return to continue: 

I searched the issues and I saw some talk about STEAM_RUNTIME but I couldn't find how to install it.

**Comment by Oxalin** [comment]
STEAM_RUNTIME is an environment variable you can set to select if you want to use or not the Steam runtime libraries. In your case, if you didn't set STEAM_RUNTIME manually, it shouldn't be your problem.

When you say you "got the steam_latest.deb installed correctly", do you mean that you installed steam from Ubuntu Software Center, that you downloaded it from the Steam website or that you manually downloaded steam_latest.deb from somewhere and then installed it?

From what I can tell, libudev0 is not available on Ubuntu 14.04 (nor Kubuntu) and it would have been removed since Ubuntu 13.04. There seems to be a workaround by installing libdev1 and then symlinking it to mimic libdev0. Look completly at the bottom of the page: https://github.com/nwjs/nw.js/wiki/The-solution-of-lacking-libudev.so.0

**Comment by kisak-valve** [comment]
Closing pending feedback.
