### ISSUE TITLE
Automatic driver check(Ubuntu)

### ISSUE THREAD

**Issue by Sasszem** [ValveSoftware/steam-for-linux#3826]
When I start Steam, I ALWAYS get a message: `Your system is running older proprietary nVidia video drivers. Steam requires driver version 304.22 or higher.`, but my video card(_FX 5200_) **CAN NOT** run the newest driver, only an **old** version. I don't want to play any "big" games, that require good graphics cards, and I know, my video card CAN run TF2, Portal, HL2 & MC, and I don't need more. I just want to use Steam under Ubuntu. When I tried to use it under WinXP, there wasn't any problems. Can I fix it or I can play only under WinXP?

**Comment by Tele42** [comment]
Unfortunately, your video card is in a generation where directx and opengl did not have equivalent functionality, as well as steam for linux being released after nvidia dropped support for your video card. The nvidia 304 series is the extended support series for the FX 6xxx and 7xxx card, and even then, source games (TF2, Portal, etc) need an opengl extension that was added in the 310 series driver.

So ... where does that leave you, there's three less than likable options:
First, there's a chance that the missing opengl extensions are implemented in nouveau, but in general nouveau is not production-ready for the FX5200, those devs are primarily focusing on 8xxx GT cards and newer these days.
Second, you can use the steam for windows client with wine. Use wine 1.7.10 or newer and make sure dwrite is disabled, so steam will use the older text render method.
Lastly, you could try to bypass the above message by removing the steamdeps executable, possibly located in /usr/bin. By removing that, you're pretty much accepting that any problems you encounter are your own to solve, and do not ask valve for any more help with that computer.

It should be noted that even with the above options explored, you will still get worse framerate than on windows xp, due to how the games were ported to linux, and the limited amount of vram on the FX 5200. HL1 generation games have a better chance of being usable. Good luck.

**Comment by Sasszem** [comment]
I also have got a Radeon 9200 SE card at home. Is it better than this 
nVidia? I searched a lot in the web, but I couldn't find any sites that 
compared these cards. CAN I run steam with Radeon 9200 SE?


2015-04-30 00:25 keltezéssel, Tele42 írta:

**Comment by Tele42** [comment]
A radeon 9200 SE is a r200 chipset, which supports OpenGL 1.4. It is less capable than a FX 5200 (OpenGL 1.5 hardware). You can research the capabilities of most video cards by searching wikipedia for "List of <vendor> graphics processing units."

**Comment by Sasszem** [comment]
Thx, I'll try to run Steam w/ wine, but I couldn't locate Steamdeps.

2015-05-03 02:19 keltezéssel, Tele42 írta:

**Comment by kisak-valve** [comment]
Hello @Sasszem, pre-OpenGL 2 hardware is generally not expected to work with Steam on Linux and your mileage will vary for the worse. This is unlikely to change in the future.
