### ISSUE TITLE
Steam fails to launch

### ISSUE THREAD

**Issue by ekse** [ValveSoftware/steam-for-linux#3910]
Latest update of Steam fails to launch on Ubuntu 15.04. I tried a complete reinstall of the latest build on the website, same error.

```
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Installing breakpad exception handler for appid(steam)/version(1433441724)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[0629/211804:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20150604103540)
Installing breakpad exception handler for appid(steamwebhelper)/version(1433414140)
[0629/211804:ERROR:nss_util.cc(981)] Failed to load NSS libraries.
Installing breakpad exception handler for appid(steamwebhelper)/version(20150604103540)
Installing breakpad exception handler for appid(steamwebhelper)/version(1433441724)
Installing breakpad exception handler for appid(steamwebhelper)/version(1433441724)
ICE default IO error handler doing an exit(), pid = 22847, errno = 2
[2015-06-29 21:18:03] Startup - updater built Jun  4 2015 10:35:42
[2015-06-29 21:18:03] Verifying installation...
[2015-06-29 21:18:03] Verification complete
Assert( Assertion Failed: CFrameFunctionMgr::~CFrameFunctionMgr: non static FrameFunction[CHTTPClient::BFrameFuncHandleCompletedWorkItems] still registered ):/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/common/framefunction.cpp:120

Installing breakpad exception handler for appid(steam)/version(1433441724)
assert_20150629211810_2.dmp[22876]: Uploading dump (out-of-process)
/tmp/dumps/assert_20150629211810_2.dmp
/home/buildbot/buildslave_steam/steam_rel_client_ubuntu12_linux/build/src/common/framefunction.cpp (120) : Assertion Failed: CFrameFunctionMgr::~CFrameFunctionMgr: non static FrameFunction[CHTTPClient::BFrameFuncHandleCompletedWorkItems] still registered
```

**Comment by leonardocostadepaula** [comment]
I have the same problem with Opensuse KDE 13.2, see:

Running Steam on opensuse 13.2 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)

(steam:16841): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",

(steam:16841): Gtk-WARNING **: Unable to locate theme engine in module_path: "oxygen-gtk",
Installing breakpad exception handler for appid(steam)/version(1433441724)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[0715/044155:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Installing breakpad exception handler for appid(steamwebhelper)/version(20150604103540)
Installing breakpad exception handler for appid(steamwebhelper)/version(1433414140)
Installing breakpad exception handler for appid(steamwebhelper)/version(20150604103540)
Installing breakpad exception handler for appid(steamwebhelper)/version(1433441724)
Installing breakpad exception handler for appid(steamwebhelper)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
FillInMachineIDInfo took a total of 0 milliseconds
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Generating new string page texture 7: 128x256, total string texture memory is 131,07 KB
Generating new string page texture 8: 64x256, total string texture memory is 196,61 KB
Generating new string page texture 9: 48x256, total string texture memory is 245,76 KB
Generating new string page texture 10: 256x256, total string texture memory is 507,90 KB
Generating new string page texture 11: 8x256, total string texture memory is 516,10 KB
Generating new string page texture 12: 16x256, total string texture memory is 532,48 KB
Generating new string page texture 13: 24x256, total string texture memory is 557,06 KB
Generating new string page texture 14: 32x256, total string texture memory is 589,82 KB
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
Installing breakpad exception handler for appid(steam)/version(1433441724)
process 16841: The last reference on a connection was dropped without closing the connection. This is a bug in an application. See dbus_connection_unref() documentation for details.
Most likely, the application was supposed to call dbus_connection_close(), since this is a private connection.
[2015-07-15 04:41:55] Startup - updater built Jun  4 2015 10:35:42
[2015-07-15 04:41:55] Verifying installation...
[2015-07-15 04:41:55] Verification complete
[2015-07-15 04:42:09] Shutdown

**Comment by ekse** [comment]
The problem went away after an update of Steam. closing.
