### ISSUE TITLE
Unable to launch Steam via application shortcut (/usr/share/applications/steam.desktop)

### ISSUE THREAD

**Issue by Majkl578** [ValveSoftware/steam-for-linux#3912]
When I launch Steam from Gnome 3.16, I only get an error:

> Failed to launch "Steam"
> Failed to execute child process "/usr/games/steam" (No such file or directory)

Using Debian steam-launcher=1.0.0.50.

**Comment by LeonardKoenig** [comment]
What's the output of `which steam` and, if existant, compare to the exec path in `/usr/share/applications/steam.desktop`

**Comment by LeonardKoenig** [comment]
Verify that it is correctly installed.
Downloading from steam, running `dpkg -x` on the .deb shows me that the paths are correct. The changelog shows that it's version 1.0.0.50.

**Comment by heyhemi** [comment]
**The Steam desktop shortcut requires additional script in order to work.**
When I click on the desktop shortcut, the icon appears in the launchbar but soon disappears.
In order to run Steam, I had to write the following into the command field:

/bin/bash -c "LD_PRELOAD='/usr/$LIB/libstdc++.so.6' DISPLAY=:0 steam -tcp"

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x13
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  4100 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Ubuntu 16.04 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.0-24-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11803000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2016-02-23
    
Video Card:
    Driver:  X.Org Gallium 0.4 on AMD ARUBA (DRM 2.43.0, LLVM 3.8.0)

    Driver Version:  3.0 Mesa 11.2.0
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x1002
    DeviceID:  0x990c
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1680 x 1050
    Desktop Resolution: 1680 x 1050
    Primary Display Size: 17.09" x 10.63"  (20.12" diag)
                                            43.4cm x 27.0cm  (51.1cm diag)
    Primary VRAM: 768 MB
    
Sound card:
    Audio device: ATI R6xx HDMI
    
Memory:
    RAM:  7170 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  461591 Mb
    Largest Free Hard Disk Block:  417985 Mb
    VR Headset: None detected
```
    
    
Also, this was the second or third attempt to install Steam. The second time did work with the updated blue gear desktop icon, but was Steam said that I needed to update Steam ("Your Steam package is out of date."). So, I uninstalled and reinstalled Steam (from the multiverse), after further research. That led to the current version on my computer having a grey desktop icon. 

It would be nice if you had a simple webpage with instructions and links for people trying to run Steam games on Ubuntu 16.04.

Thanks!

**Comment by alexdcodes** [comment]
Steam runs perfectly fine if ran through Terminal. using command "steam" 
Shortcut still does not work! anyonefind a work around?

**Comment by kisak-valve** [comment]
Hello @Majkl578, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
