### ISSUE TITLE
L4D2 Segfault on launch after update 22/7/15

### ISSUE THREAD

**Issue by sadger** [ValveSoftware/steam-for-linux#3931]
Was working fine yesterday but after the recent steam update segfauls with error message from terminal

```
Game update: AppID 550 "Left 4 Dead 2", ProcID 4081, IP 0.0.0.0:0
ERROR: ld.so: object '/home/william/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/william/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 4083 != 4082, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/william/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/william/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
SDL video target is 'x11'
Using breakpad crash handler
Setting breakpad minidump AppID = 550
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197981179774 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561197981179774
[0722/221442:ERROR:resource_bundle.cc(411)] Failed to load /home/william/.local/share/Steam/SteamApps/common/left 4 dead 2/cef_gtk.pak
Some features may not be available.
[0722/221442:ERROR:object_proxy.cc(239)] Failed to call method: org.freedesktop.systemd1.LoadFailed: Unit dbus-org.freedesktop.NetworkManager.service failed to load: No such file or directory.
[0722/221442:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
The program 'hl2_linux' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'.
  (Details: serial 1380 error_code 8 request_code 42 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
SDL video target is 'x11'
SDL failed to create GL compatibility profile (whichProfile=0!
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system supports the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system supports the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system supports the OpenGL extension GLX_EXT_swap_control_tear.
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_EXT_texture_sRGB_decode: AVAILABLE
GL_NVX_gpu_memory_info: AVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_NVX_gpu_memory_info: Total Dedicated: 1048576, Total Avail: 1048576, Current Avail: 831760
GL_MAX_SAMPLES_EXT: 32
Did not detect any valid joysticks.
Querying for subscribed files
/home/william/.local/share/Steam/SteamApps/common/left 4 dead 2/./hl2.sh: line 67:  4085 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 550 "Left 4 Dead 2", ProcID 4085 

```

**Comment by gfaccin** [comment]
Same is happening here, and the problem is definitively the latest steam client update.

Running the game straight from the terminal, with the steam client not running, works (altough it won't let you play online, since it won't be VAC enabled without the Steam Client):
./hl2.sh -secure -game left4dead2

Now opening the Steam client and launching the game from inside it, this is what I get:

Game update: AppID 550 "Left 4 Dead 2", ProcID 6500, IP 0.0.0.0:0
ERROR: ld.so: object '/home/gfaccin/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/gfaccin/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 6502 != 6501, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/gfaccin/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/gfaccin/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
SDL video target is 'x11'
Using breakpad crash handler
Setting breakpad minidump AppID = 550
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198029032724 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198029032724
[0729/174220:ERROR:resource_bundle.cc(411)] Failed to load /home/gfaccin/.local/share/Steam/SteamApps/common/Left 4 Dead 2/cef_gtk.pak
Some features may not be available.
[0729/174220:ERROR:object_proxy.cc(239)] Failed to call method: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
[0729/174220:WARNING:proxy_service.cc(646)] PAC support disabled because there is no system implementation
The program 'hl2_linux' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'.
  (Details: serial 249 error_code 8 request_code 42 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
SDL video target is 'x11'
SDL failed to create GL compatibility profile (whichProfile=0!
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system supports the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system supports the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system supports the OpenGL extension GLX_EXT_swap_control_tear.
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_EXT_texture_sRGB_decode: AVAILABLE
GL_NVX_gpu_memory_info: AVAILABLE
GL_ATI_meminfo: UNAVAILABLE
GL_NVX_gpu_memory_info: Total Dedicated: 1048576, Total Avail: 1048576, Current Avail: 771311
GL_MAX_SAMPLES_EXT: 16
Did not detect any valid joysticks.
Querying for subscribed files
/home/gfaccin/.local/share/Steam/SteamApps/common/Left 4 Dead 2/./hl2.sh: line 67:  6504 Segmentation fault      ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 550 "Left 4 Dead 2", ProcID 6504

**Comment by Tele42** [comment]
@sadger @gfaccin: please include your system information as requested at https://github.com/ValveSoftware/steam-for-linux#reporting-issues, and any relevent CrashIDs so a valve dev can have an easier time taking a look into this.

**Comment by sadger** [comment]
System info

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x1e
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  2934 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Linux (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.1.2-2-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  awesome
    Steam Runtime Version:  steam-runtime-release_2015-06-12
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 460/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 352.21
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0xe22
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1680 x 1050
    Desktop Resolution: 1680 x 1050
    Primary Display Size: 18.66" x 11.65"  (21.97" diag)
                                            47.4cm x 29.6cm  (55.8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: VIA VT1828S
    
Memory:
    RAM:  7985 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  531366 Mb
    Largest Free Hard Disk Block:  180137 Mb
    
Installed software:
    
Recent Failure Reports:

```

**Comment by gfaccin** [comment]
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x1a
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  2668 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Gentoo Base System release 2.2" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.14.14-gentoo
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  awesome
    Steam Runtime Version:  steam-runtime-release_2015-06-12
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTS 250/PCIe/SSE2

    Driver Version:  3.3.0 NVIDIA 331.113
    OpenGL Version: 3.3
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x615
    Number of Monitors:  2
    Number of Video Cards Not Detected
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 18.74" x 10.55"  (21.50" diag)
                                            47.6cm x 26.8cm  (54.6cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: AV200
    
Memory:
    RAM:  12007 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  729736 Mb
    Largest Free Hard Disk Block:  81555 Mb
    
Installed software:
    
Recent Failure Reports:

**Comment by sadger** [comment]
I looked at what myself and @gfaccin had in common and it seemed to be the awesome WM. Given that I tried to launch it in xfce4 and L4D2 worked just fine so I assume it is some unintended interaction with awesome WM. Perhaps @gfaccin can confirm if his works in another WM?

**Comment by gfaccin** [comment]
Confirmed. I ran the game using Enlightenment and it worked. The latest steam client update had some kind of change that now affects the Awesome WM, preventing source games from running. I can confirm it for 2 Source games: Nuclear Dawn and Left for Dead 2.

**Comment by jongill** [comment]
I can confirm that I am having the same issue with Left 4 Dead 2. Other games work without issue but this one will not startup and gives the same aforementioned error. 

#### Here is my information for reference:
```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  2900 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.1.2-2-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11702000
    X Window Manager:  awesome
    Steam Runtime Version:  steam-runtime-release_2015-06-12
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 560M/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 352.21
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1251
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.91" x 11.77"  (23.98" diag)
                                            53.1cm x 29.9cm  (60.9cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 3072 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC269VB
    
Memory:
    RAM:  11996 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  661417 Mb
    Largest Free Hard Disk Block:  535707 Mb
    
Installed software:
    
Recent Failure Reports:
    Wed Jul 29 23:01:09 2015 GMT: file ''/tmp/dumps/crash_20150729160107_6.dmp'', upload no: ''HTTP response code said error''
    Wed Jul 29 23:01:22 2015 GMT: file ''/tmp/dumps/assert_20150729160104_1.dmp'', upload yes: ''CrashID=bp-3db60e1e-2008-40e2-8ce2-485d42150729''
```

**Comment by sadger** [comment]
This is fixed for me currently, working on awesome as expected.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
If anyone happens across this issue with L4D2, please check the [Source-1-Games](https://github.com/ValveSoftware/Source-1-Games) issue tracker for similar issues and open a new issue over there if there isn't one already.
