### ISSUE TITLE
Steam Controller input keeps breaking

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-for-linux#4130]
Suddenly in games the Steam Controller will only work as a mouse. In Steam Big Picture mode every touch to the stick is super fast.

The A button is also acting up, I go to settings, press A and suddenly i'm in my account settings and not the settings menu.

In Borderlands 2 the stick would let me turn left and right, but not actually move around, like it had suddenly taken on a new config.

And then suddenly it will work again, it's done this to me 2-3 times now.

**Comment by liamdawe** [comment]
It seems closing Steam Big Picture, and then re-entering it actually fixes the issue until it comes up again.

If that helps narrow it down. As it just happened yet again.

**Comment by liamdawe** [comment]
Okay more tests, restarting SBP mode does not fix it. I just had it yet again.

This time a combination of loading a game up, and going in and out of the button config and it eventually just started working normally again.

I think part of the issue is the mouse support, as when it happens the mouse cursor is visible as if i'm backing to using a mouse and keyboard (like the gamepad suddenly isn't picked up as a gamepad?).

**Comment by NaughtySquid** [comment]
More info for you.

Using the Steam button to bring up Steam, and then to bring up the big picture mode is what seems to cause it.

Using the mouse to go into big picture mode has not given me this bug once.

**Comment by calexil** [comment]
confirmed, issue is ongoing. multiple controllers usb wired... "a" button dies after a while. isolated to steam, tuxcart and jstest-gtk show it functioning fine.
