### ISSUE TITLE
IDirect3DQuery9::GetData(): Occlusion query flush took 0.544ms!.

### ISSUE THREAD

**Issue by TheBatman** [ValveSoftware/steam-for-linux#4133]
IDirect3DQuery9::GetData(): Occlusion query flush took 0.544ms!
IDirect3DQuery9::GetData(): Occlusion query flush took 0.681ms!
That appears in the console(alot) with the lastest AMD drivers on source games(TF2 & DoD Source for example).

PC specs:
Processor: AMD A8-6410 APU with AMD Radeon R5 Graphics × 4.
Graphic card: AMD R5 1GB VRAM
RAM: 8GB
HDD:500GB 
OS:Ubuntu 14.04LTS 64bits

**Comment by AlVeiluva** [comment]
Drew, can you please look into this further or let your cohorts know at Valve? This has been happening to me for months when playing every kind of Source game. I tried many other prescribed (Mac-centric) fixes like stopping Spotlight and other indexing, and none work. It is something that must be patched.

**Comment by Tele42** [comment]
This is a symptom of under-performing drivers. There is no specific fix beyond improving the drivers or making more hardware performance available. Since an APU is involved in the OP, allocating more vram (1.5 - 2 GB) in the bios potentially could potentially help as well as running the ram at a higher clock rate, but that can also reduce the life of the sticks of ram and/or cause system stability issues.

**Comment by TheBatman** [comment]
Games that are not source 1 based ran smooth for me with that hardware.

**Comment by AlVeiluva** [comment]
@Tele42  I don't believe it is a hardware issue or under-performing drivers. My computer has been running Source games flawlessly for years up until a few weeks ago. Pretty sure my problems started when Snow Leopard was dropped by Valve so switched to El Capitan (and updated Steam).

**Comment by kisak-valve** [comment]
Closing in favor of https://github.com/ValveSoftware/Source-1-Games/issues/1936.
