### ISSUE TITLE
SteamOS family sharing is broken/pointless

### ISSUE THREAD

**Issue by NaughtySquid** [ValveSoftware/steam-for-linux#4184]
So, I'm sat at my PC, and the girlfriend is on the Steam Machine. We do the family sharing, she loads up Shadow or Mordor, and I load up a totally different game on my PC.

Steam tells her I apparently need the game back? Then totally cuts her off after a few minutes.

Is this a bug, or can the people using a shared game ONLY play when the other isn't playing ANY game?

**Comment by Tele42** [comment]
This is the intended behavior, family sharing does not allow multiple people to use shared games at the same time.

**Comment by NaughtySquid** [comment]
You might want to re-read. We are not using the same game.

**Comment by Tele42** [comment]
I read it properly, one seat using the account, regardless of which game is in use.

**Comment by NaughtySquid** [comment]
Then the entire feature is quite pointless.

**Comment by ProfessorKaos64** [comment]
@NaughtySquid , if it was as you wished, there would be mass abuse. Guy1 gives account password to all his friends. Free games for all. Profit? nope.

**Comment by NaughtySquid** [comment]
Then you set a limit on it to how many people you can share it to, it's really not that difficult to grasp.

**Comment by ProfessorKaos64** [comment]
I really won't add much more to this, since we are not in agreement, which is fine. Imagine if you bough t 500 USD of games, and they allowed 1 person to play whatever they want at the same time. That is 1000 dollars of games for nothing. Your girlfriend paid 0 dollars to use the same license key of a game. A lot of this is based around that license. A license is for one user, regardless of our hey-days plopping in physical CD's into computers applying CD keys in hair-trigger fashion. I'd imagine it _is_ something Valve has grasped, and debated, and already decided upon.

**Comment by NaughtySquid** [comment]
Agree to disagree. I think it's a crappy feature then.

**Comment by CKWarner** [comment]
I agree with Liam here, entirely.

For Family Sharing to be worthwhile, you need to be able to share your library with your family.

**Obviously** you want to prevent two people playing the _same_ game at the same time, but if I'm playing Wolfenstein, say, there's no reason I should need to be kicked off Steam so that someone else can play Slime Rancher on a different computer with their account. That's not "Family Sharing," it's account sharing.

Being able to share a specific collection, using Steam's own collection feature, with members of your family would be a **great** feature for Steam to have. It would increase the utility of Steam, and keep the users in the Steam ecosystem. The current implementation fails to provide that; the current implementation is functionally identical to giving someone else your Steam password. Which is just daft.

The first user takes Steam offline, the second user makes use of the shared library: how does that benefit anyone? Steam gets no more money that way, gets _less_ user data, and is a completely unnecessary pain for the user.

**Comment by CKWarner** [comment]
Having to put Steam into offline mode before you can use the Family Library Sharing feature is going to be particularly obnoxious for those people who buy a Steam Deck.
