### ISSUE TITLE
RaceTheSun.x86 aborts with invalid pointer error

### ISSUE THREAD

**Issue by Oblomov** [ValveSoftware/steam-for-linux#4300]
After a recent system upgrade (Debian unstable), trying to run RaceTheSun fails. The program aborts after the "Importing game controller configs" with an invalid pointer error after `munmap_chunk()` or `free()`. I tried running the program within `gdb` to try and provide a stack trace, but in that case Mono receives a SIGPWR.

Typical logs when trying to run RTS:

```
Game update: AppID 253030 "Race The Sun", ProcID 9992, IP 0.0.0.0:0
ERROR: ld.so: object '/home/oblomov/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/oblomov/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/oblomov/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Set current directory to /oneforall/games/steam/oblomov/common/RaceTheSun
Found path: /oneforall/games/steam/oblomov/common/RaceTheSun/RaceTheSun.x86
Mono path[0] = '/oneforall/games/steam/oblomov/common/RaceTheSun/RaceTheSun_Data/Managed'
Mono path[1] = '/oneforall/games/steam/oblomov/common/RaceTheSun/RaceTheSun_Data/Mono'
Mono config path = '/oneforall/games/steam/oblomov/common/RaceTheSun/RaceTheSun_Data/Mono/etc'
displaymanager : xrandr version warning. 1.4
displaymanager : trying .X11-unix
client :0 has 1 screens
displaymanager screen (0): 3200 x 1800
Using libudev for joystick management


Importing game controller configs
*** Error in `./RaceTheSun.x86': munmap_chunk(): invalid pointer: 0x0c3c7c50 ***
Aborted
Game removed: AppID 253030 "Race The Sun", ProcID 9992 
```

or

```
Game update: AppID 253030 "Race The Sun", ProcID 9742, IP 0.0.0.0:0
ERROR: ld.so: object '/home/oblomov/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/oblomov/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/oblomov/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Set current directory to /oneforall/games/steam/oblomov/common/RaceTheSun
Found path: /oneforall/games/steam/oblomov/common/RaceTheSun/RaceTheSun.x86
Mono path[0] = '/oneforall/games/steam/oblomov/common/RaceTheSun/RaceTheSun_Data/Managed'
Mono path[1] = '/oneforall/games/steam/oblomov/common/RaceTheSun/RaceTheSun_Data/Mono'
Mono config path = '/oneforall/games/steam/oblomov/common/RaceTheSun/RaceTheSun_Data/Mono/etc'
displaymanager : xrandr version warning. 1.4
displaymanager : trying .X11-unix
client :0 has 1 screens
displaymanager screen (0): 3200 x 1800
Using libudev for joystick management


Importing game controller configs
*** Error in `./RaceTheSun.x86': free(): invalid pointer: 0xf7389898 ***
Aborted
Game removed: AppID 253030 "Race The Sun", ProcID 9742 
```

**Comment by gdrewb-valve** [comment]
You'll want to report this to the game developer also.

**Comment by eriktorbjorn** [comment]
I wonder if that's the same problem I've been seeing with a couple of other games recently, since I'm also running Debian unstable. For most of them, I don't get much output, but for some I'm also getting error messages about invalid pointers in free(), or in munmap_chunk().

For reference, the games I've been having trouble running so far are:

[Double Fine] Broken Age, Spacebase DF-9, Costume Quest, Costume Quest 2, Hack 'n' Slash, MASSIVE CHALICE, Brütal Legend, The Cave, Stacking

[Over The Moon] The Fall

[Koboldgames] Journey of a Roach

I don't know if it's significant, but all of these appear to be 32-bit games. (The 64-bit version of Journey of a Roach seems to work fine.) On the other hand, I have at least some other 32-bit games in Steam that still work fine. Also, a few of the problematic games work if I start them from a command prompt, but not if I start them from the Steam client.

Assuming this is the same problem, is there anything I can do to help narrow it down? (I did report the problem to Double Fine and Over The Moon, but this was very recently so they haven't been able to help me yet.)

**Comment by gdrewb-valve** [comment]
You can try disabling the Steam overlay.  If that doesn't help you'll have to wait to see what the Steam team says.

**Comment by bjwest** [comment]
I get this on Civ V as well.  I reported it to 2K games, but haven't heard anything back from them.  Is this a Steam problem, seeing as how it effects so many games?

**Comment by eriktorbjorn** [comment]
Unfortunately, disabling the Steam overlay doesn't seem to make any difference for me.

At first I thought the problem was triggered by a recent Steam update, because that's when I first noticed it. But reverting to an older Steam version from a backup (and reconnecting from the Internet to prevent it from updating itself) didn't help. Assuming I didn't make some silly mistake, that would seem to indicate that the problem was tiggered by some recent Debian updated instead.

But since some of the games (e.g. The Cave) start up just fine when launched from a command prompt, Steam seems to be at least somewhat involved... maybe. This is all just speculation on my part.

**Comment by Tele42** [comment]
@bjwest your issue is most likely unrelated to this unless @Oblomov and @eriktorbjorn are also using nvidia 358 or newer. There is a known general stability issue with nvidia 358 that is reported fixed with 361.18 and a separate issue between Aspyr games and libglvnd which has been <a href="https://github.com/NVIDIA/libglvnd/commit/ba0b05a5691006b8e954af6494a58c057514bb6e">fixed upstream</a>, but has not yet been bundled with a nvidia driver release.

**Comment by eriktorbjorn** [comment]
I'm using the open source "radeonsi" driver. ("X.Org Gallium 0.4 on AMD BONAIRE (DRM 2.43.0, LLVM 3.7.1)", according to the Steam - System Information dialog.) I don't have Civilization V, but Fahrenheit: Indigo Prophecy Remastered seems to work fine.

**Comment by eriktorbjorn** [comment]
I just realized that I, too, have Race the Sun, probably from one of the many Humble Indie Bundles, and it seems to crash the same way for me as for @Oblomov. I feel less bad about hijacking this bug report now. :-)

**Comment by rmbleeker** [comment]
I just played a game of Race the Sun without issues on Ubuntu 14.04 LTS kernel 4.2.0-27 on an nVidia 560Ti with driver 361.18. I used keyboard and mouse, no controller plugged in, so since @Oblomov mentioned a controller maybe the problem lies there?

**Comment by eriktorbjorn** [comment]
Probably not a controller issue - at least not solely - since I don't have one. I'm still more inclined to pin it on some reason change to Debian unstable, because that's something I _do_ have in common with @Oblomov.

**Comment by rmbleeker** [comment]
Perhaps, although a game like this shouldn't be affected too much by the distro you're using. RTS is a Unity3D game I believe, or at least comes with it's own version of mono that it needs to run. So as long as your glibc is of a high enough version and your Steam Linux runtime is up-to-date, it should just run.

**Comment by eriktorbjorn** [comment]
For what it's worth, the non-Steam version of Race The Sun works fine for me. It's just the Steam version that doesn't.

**Comment by DerBunman** [comment]
The problem seems to be present in all 64 bit steam games:

Cities Skylines:
*** Error in `/home/ichi/.steam/SteamApps/common/Cities_Skylines/Cities.x64': free(): invalid pointer: 0x00000000028e6d78 ***

Shovel Knight:
*** Error in `/home/ichi/.steam/SteamApps/common/Shovel Knight/64/ShovelKnight': free(): invalid pointer: 0x0000000001ed57a0 ***

Transistor:
*** Error in `./Transistor.bin.x86_64': free(): invalid pointer: 0x00007f7234000078 ***

Some of these games however run when you start them from an terminal.

**Comment by Cheeseness** [comment]
> Some of these games however run when you start them from an terminal.

Do those games still run if you launch them from a terminal using the Steam Runtime (this launches the game outside of Steam, but using the libraries that Steam is bundled with)? Depending on where Steam is installed to, that'd be something like this:

```
~/.steam/steam/ubuntu12_32/steam-runtime/run.sh /Transistor.bin.x86_64
```

**Comment by StarFscker** [comment]
Cheeseness, I have tested what you proposed. 

I am also running Sid, and when running games through the Steam Runtime, it does not work, and acts the same as though I'd launched the game through Steam .

When launching some games without, they seem to load fine. 

I'm guessing this is a problem caused by the Steam libraries, perhaps a conflict between them and the distro's libraries? 

Tabletop Simulator, for instance, runs through the terminal without steam. 

Cities launches, but gets stuck on a black screen.

**Comment by eriktorbjorn** [comment]
I spent some time looking at the list of packages @DerBunman provided in bug #4319, and found that I could get many - unfortunately not all - of the broken games, including Race the Sun, to work by downgrading the ALSA libraries (libasound2 etc.) to 1.0.29-1.

I've seen other bug reports about problems involving ALSA 1.1.0 and Steam, but they were all about missing sound, not game crashes.

**Comment by StarFscker** [comment]
So I just tested this on a Debian Testing box I have, and the same problem exists, all the same games are crashing in the same way.

**Comment by rmbleeker** [comment]
Have any of you tried to see if all the right libraries are in place with `ldd`?

**Comment by StarFscker** [comment]
WORKAROUND! 

LD_PRELOAD='/usr/$LIB/libasound.so.2 '${LD_PRELOAD} steam

when launching steam allows me to launch Cities: Skylines.

**Comment by javiercantero** [comment]
I've managed to fix the segfault in Broken Age. The solution should work with the other games too. You only need to remove or comment one line in `/usr/share/alsa/alsa.conf` (or apply this patch):
```
--- /usr/share/alsa/alsa.conf-1.1.0 2016-02-01 23:59:59.000000000 +0100
+++ /usr/share/alsa/alsa.conf   2016-02-25 11:46:36.099062833 +0100
@@ -367,7 +367,7 @@
    }
    type hw
    card $CARD
-   hint.description "Direct control device"
+###STEAM BUG###    hint.description "Direct control device"
 }

 ctl.shm {
```
See my comment in  #4139 for details.

**Comment by victorjchamorro** [comment]
Comment that line is working! Thanks javiercantero.

**Comment by Oblomov** [comment]
For what it's worth, after some more recent system upgrades Race the Sun seems to be working for me now even without any of the workarounds mentioned here.

**Comment by kisak-valve** [comment]
Hello, since this issue report was last commented on Steam's handling of the Steam runtime has changed to prefer host libraries over the runtime variants. Is anyone still experiencing this issue on an up to date system?

**Comment by eriktorbjorn** [comment]
I had forgotten all about this, but I tried installing the game on Debian (unstable). Even though it's not a Linux distribution you official support, the game started and seemed to run just fine.

**Comment by Oblomov** [comment]
I have not experienced the error in a long time anymore, I think the issue can be marked as solved.
