### ISSUE TITLE
Planetary Annihilation Titans crashes on Ubuntu 16.04

### ISSUE THREAD

**Issue by Zichtenhuber** [ValveSoftware/steam-for-linux#4389]
Hi Folks,

If I run the game on a Ubuntu 16.04 64 Bit installation it crashes and i recieve the following link in the terminal window:

http://crashes.uberent.com/report/index/51ecf2e6-952f-4431-90b5-4c6602160409

Can someone help?
It this the right place to post something like this at all?

Thanks!

**Comment by gdrewb-valve** [comment]
You'll want to contact the game developer as they'd be the primary investigator for a problem with their game.  However there are also a number of other Ubuntu 16.04 bugs here that are Steam runtime incompatibilities so it may be one of those, take a look at them.

**Comment by Zichtenhuber** [comment]
Thanks for the advice!

Kind regards,

**Comment by ksthiele** [comment]
starting steam with:
 `LD_PRELOAD="/usr/lib/i386-linux-gnu/libasound.so.2:/usr/lib/x86_64-linux-gnu/libasound.so.2" steam`
works just fine
https://wiki.palobby.com/wiki/Crashing_in_Ubuntu_16.04_when_using_Steam
'Launching PA in Steam while running Ubuntu 16.04 or any other distribution with alsa-lib 1.1.0 or higher causes PA to crash. This is actually due to an issue with the libasound.so.2 library that is distributed with Steam.
'

**Comment by furai** [comment]
Any news on this issue? I had to use the workaround as well which is less than ideal.

**Comment by kisak-valve** [comment]
Hello, since this issue was last commented on, Steam's handling of the Steam runtime has changed to prefer host libraries before the Steam runtime variants, which should avoid the libasound issue.

Is anyone still experiencing this issue?

**Comment by kisak-valve** [comment]
Closing as fixed some time ago.
