### ISSUE TITLE
Steam HTC Vive doesnt work on Linux

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/steam-for-linux#4490]
Why is not supported??

**Comment by gdrewb-valve** [comment]
This is a bug reporting forum for the Steam client, closing.

**Comment by ekaris** [comment]
And this bug is 100% complying with that, the HTC VIVE had steamOS advertising support in the early days, turns out its not supported.

**Comment by gdrewb-valve** [comment]
The Vive is not the Steam client nor is SteamOS, as I believe you are aware.  Your misuse of this forum is not helping anything, please do not post off-topic issues.

**Comment by ekaris** [comment]
You're telling me that you prefer me to not post at all than to post any actual issues like serious security problems that persist to this day?

**Comment by gdrewb-valve** [comment]
I'm telling you you're posting in the wrong place.  Your issues here are only being seen by people who work on the Linux and Mac ports of the Steam client.  When you post a question about the Vive you're reaching the wrong audience.

You've asked before about where else you should post and you have that information but you aren't using it.  For serious security problems you should be reporting those to Steam support.  You can also post in the regular Steam community forums.  There's an OpenVR forum right here, there are SteamOS and Vive forums and there's also HTC.  I'm not sure why you chose to post here rather than somewhere that has some connection to the question you're asking but please stop.
