### ISSUE TITLE
32bit libgl on 64bit

### ISSUE THREAD

**Issue by Jan200101** [ValveSoftware/steam-for-linux#4516]
#### Your system information

* Steam client version: latest from the 26th of June
* Distribution Debian 8
* Opted into Steam client beta?: No 
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I have all libgl files installed but when starting steam it askes for the 32 bit ones which should not be installed a) because I already have the 64 bit version b) because it would remove a lot of important things like xfce applications

#### Steps for reproducing this issue:

1. Install Steam on a (fresh or one without a 32bit libgl library) 64bit Debian (may work with other) System
2.  Start Steam
3. Get Steam to open a terminal where it is trying to get all libgl 32 bit

**Comment by Tele42** [comment]
Steam is a 32 bit application and you can not dynamically load 64 bit libraries with a 32 bit application. This is the expected behavior. You are using your package manager incorrectly or do not have multi-lib support enabled in your distro.

Note: you definitely should not uninstall 64 bit opengl libraries in order to install 32 bit opengl support.

**Comment by gdrewb-valve** [comment]
As Tele42 mentions Steam is 32-bit so this is expected.  There's already an request for a 64-bit client open here so closing this.
