### ISSUE TITLE
Steam Controller button brightness setting not being applied.

### ISSUE THREAD

**Issue by tatokis** [ValveSoftware/steam-for-linux#4519]
When in Big Picture with the controller connected either wired and wireless, the steam button brightness setting is not applied unless it is set to 0% (off) or 100% (full brightness).

Any value in between, does get previewed on the controller, but does not get saved once the Submit button is pressed. Instead, the light turns off completely.

Tested on two completely different computers, (both AMD and Intel based), running the Steam beta build (Jun 23) on Ubuntu 16.04LTS, fully updated.
This issue does not occur on Windows 7 running on the same hardware.

The following screen capture demonstrates the issue:
https://vps.tasossah.com/bugs/steamcontroller_brightness.webm

**Comment by MayeulC** [comment]
Hi, I would like to bump this issue.

The problem is seemingly related to the environment variable LC_ALL, or more generally the system locale.

My guess is that the steam client is using the printf function somewhere. On my system, it prints decimal number with a comma ( "0,05", for example). I think that the backend (controller firmware, settings file, or other, but more likely some settings file, since the brightness changes with the slider, and the value is discarded when saving) is expecting a dot ("0.05") as a decimal separator. Of course, I could be mistaken on the reason, but if I start steam with

    LC_ALL=C steam
then this issue disappears.

I seem to recall that this issue was fixed some time ago, but I got it again recently.

Thank you.

**Comment by Corben78** [comment]
Just bumped into the same issue while fiddling around with the Bluetooth Firmware update.
My locale is set to german, and I also remember it was working some time ago.

It was very irritating, as I had it set to ~90% brightness, which is then saved to 0% in the controller, making the controller appear offline after it syncs with Steam.

**Comment by cprn** [comment]
It is exactly this. I had `LC_NUMERIC` set in a way that all numeric values would use comma as fraction separator (I work with money). Setting `LC_NUMERIC=C` solves this and the audio settings issue (sliders resetting to zero after Big Picture restart).

**Comment by thackel** [comment]
I also confirm this issue. Only binary behaviour instead of discrete intervals.
All below 1(00%) will be 0 brightness(off) and 1 will be 100% brightness.

**Comment by cprn** [comment]
@thackel The cause is known and Valve should fix this soon. As a temporarily solution, if it isn't clear by now, you need to overload `LC_NUMERIC` environment variable. You can e.g. add it to your shortcut or do this whenever you want to adjust settings:
1. close Steam, if it's open
1. run terminal
1. run the Steam client with overloaded `LC_NUMERIC` environment variable like so:
    ```
    LC_NUMERIC=C steam
    ```
1. set whatever settings were problematic before, this time it will be saved
1. close terminal and restart Steam your normal way (without `LC_NUMERIC`)

**Comment by tatokis** [comment]
This seems to be fixed now on my end.
Can someone else affected verify that it is indeed fixed so that I can close the issue?

**Comment by thackel** [comment]
Using the current beta, the problem does no longer exist.

**Comment by actuallySIG** [comment]
The Brightness setting gets applied, but Haptics is reset after clicking Submit in the Configuration window, even if no setting was changed.

**Comment by kisak-valve** [comment]
Thanks for catching that this issue is resolved. @actuallySIG, please open a new issue report for the follow up issue.
