### ISSUE TITLE
Please add an inverted tray icon

### ISSUE THREAD

**Issue by ViBE-HU** [ValveSoftware/steam-for-linux#4575]
![icon](https://cloud.githubusercontent.com/assets/640109/17275563/b69ac96c-570c-11e6-9df3-d993245d5276.jpg)

Since Steam has been changed to this monochrome theme there is only a light coloured variant which is cool but looks weird (like a black sheep) on the default Radiance theme. I don't know how it looks like on other distros but I guess most distros has a lighter and a darker default theme so others may also prefer a reverted/dark one tray icon. Please add it.

**Comment by gdrewb-valve** [comment]
Essentially a duplicate of several other tray icon issues, but leaving open for coverage of the various cases.

**Comment by ViBE-HU** [comment]
Hope so cause it's a bit nonsense to find the Steam icon on the tray if the user set a light desktop theme. And the icon has a greyish colour which is very popular, it really fits but also hides it.

**Comment by stevethepocket** [comment]
I'm betting there's some special icon format that's just an alpha channel so the desktop environment can set the actual color itself, and Valve is using the obsolete full-color one. This has been an issue for me in KDE since always, but I had no idea Ubuntu had a built-in light theme too. This really does need to be dealt with.

**Comment by kisak-valve** [comment]
Closing in favor of #4281.
