### ISSUE TITLE
Running Steam client causes system title bar buttons to disappear (Linux Ubuntu)

### ISSUE THREAD

**Issue by okesokes** [ValveSoftware/steam-for-linux#4699]
#### Your system information

* Steam client version:

Built Oct 13 2016, at 00:48:25
Steam API: v017
Steam package versions: 1476379980
Steam runtime version: steam-rutime-beta-release_2016-09-02

* Distribution (e.g. Ubuntu): 

Ubuntu 14.04.5 LTS (64 bit)

* Opted into Steam client beta?: [Yes/No] 

No

* Have you checked for system updates?: [Yes/No]

Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Running Steam causes title bars of all programs to get bugged so that the title bar buttons disappear, when you move the mouse pointer over them, rendering them unusable. The issue appears every time Steam is running and is instantly fixed by exiting Steam client.

#### Steps for reproducing this issue:

1. Launch Steam client in Ubuntu

2. Open other programs like browser or e-mail client program

3. Try to use the system title bar buttons of other programs and notice that they disappear every time you move your mouse pointer over the buttons, rendering them unusable

![steambugreport_titlebar](https://cloud.githubusercontent.com/assets/10551631/20160014/f2acc6d2-a6ec-11e6-969e-83935310fa47.png)

**Comment by Tele42** [comment]
Hello @okesokes,
This issue sounds like your Desktop Environment is hitting a bug in it's handling of these buttons. Steam uses an in-house UI framework which does not include common window decorations and may not be as well tested as the bigger UI toolkits like GTK+ and QT by the DE devs. You should also reach out to your distro's bug tracker and/or the DE's bug tracker to increase the odds of resolving this issue and reference them here.

**Comment by Ruedii** [comment]
I've noticed this issue in KDE as well.

It seems Steam doesn't obey window manager hints properly.  This has been an issue for a while.

I don't think I've run into a window manager that doesn't have this problem with steam. 

The window manager interaction code might need a good check (or rewrite).

Honestly, I think the entire steam UI code is due for a rewrite.  It would be nice to see it redone with a modern toolkit such as GTK or Cairo.  It would reduce a lot of future UI bugs.  Since so much of the UI is written in XML/HTML5, the vast majority of it would simply port over transparently with almost no changes, and only the underlying framework would be replaced.

**Comment by kisak-valve** [comment]
Hello @okesokes, @Ruedii, are either of you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
