### ISSUE TITLE
Unable to use Steam In Home Streaming when UFW firewall enabled.

### ISSUE THREAD

**Issue by tominglis** [ValveSoftware/steam-for-linux#4803]
#### Your system information

* Steam client version: 1482202200
* Distribution (e.g. Ubuntu): Ubuntu 16.04.1
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

I have an HTPC which I use to stream games onto my laptop over an ethernet cable in my flat. This works fine when I turn off UFW on both machines, however I'd ideally like to keep UFW turned on!

I have followed the instructions about which ports to add to allow incoming traffic, and believe they are added correctly. Both machines give:

sudo ufw status

Status: active

To Action From

27031/udp ALLOW 27031/udp 
27036/udp ALLOW 27036/udp 
27036/tcp ALLOW 27036/tcp 
27037/tcp ALLOW 27037/tcp 
27031/udp (v6) ALLOW 27031/udp (v6) 
27036/udp (v6) ALLOW 27036/udp (v6) 
27036/tcp (v6) ALLOW 27036/tcp (v6) 
27037/tcp (v6) ALLOW 27037/tcp (v6) 

Both machines are on the same subnet, and are connected by ethernet cables to a Virgin Media SuperHub router.

Any help would be greatly appreciated.

#### Steps for reproducing this issue:

1. Create the ufw rules above on both systems.
2. Enable ufw firewall on both systems.
3. Start steam on both systems and see that they don't connect to eachother for streaming.

**Comment by sizeofbool** [comment]
You have to setup your firewall rules correctly. Source ports can't be always exactly the same as Destination ports.

**Comment by tominglis** [comment]
Thanks for the reply.

Do you have any suggested changes for my config?

In what circumstances would source and destination ports be different for Steam Streaming?

**Comment by sizeofbool** [comment]
@tominglis General rule of thumb is to move from simple configuration to complicated and testing along the way. Start with enabling ufw and allow all ports in any directions. Look in manual for ufw to enable the way to see logs for blocked connections, so you will see what ufw did and be able to adjust using that information.
Since your subnet already behind firewall (provided by Virgin Media SuperHub router), the best way to configure ufw is to allow any source ports and restrict only destination ports, on both machines.
