### ISSUE TITLE
"You are missing the following 32-bit libraries, and Steam may not run: libc.so.6"

### ISSUE THREAD

**Issue by Annonymousse** [ValveSoftware/steam-for-linux#4832]
#### Your system information

* Steam client version: The newest one? Downloaded it from official steam website.
* Distribution (e.g. Ubuntu): Kali Linux 
* Opted into Steam client beta?: [Yes/No] Uhhh... maybe? I think not. Most likely not.
* Have you checked for system updates?: [Yes/No] Yes, indefinetely.

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

So, i installed steam and ran it, "root user something something" so, i use leafpad (i think it is a kali program), and change some values, so it works without the error, but it gives out another one

"You are missing the following 32-bit libraries, and Steam may not run:
libc.so.6"

I have read numerous online guides and i have tried everything i could have. I am a linux noob and i just got it installed like 3 days ago.

#### Steps for reproducing this issue:

1. Get Kali Linux, (i dualbooted)
2. Get the official steam_latest.deb file from the steam website
3. Install it.
4. Open terminal.
5. leafpad /usr/bin/steam
6. (only if running as root user) Find these values and make sure they have the hashtag symbol in the start of the line.

.# Don't allow running as root
.#if [ "$(id -u)" == "0" ]; then
.#	show_message --error $"Cannot run as root user"
.#	exit 1
.#fi

without the dots

7. Run steam
8. "You are missing the following 32-bit libraries, and Steam may not run:
libc.so.6"
9. Spend many hours trying to find how to fix it.
10. End up here making a bug report.

**Comment by Annonymousse** [comment]
Note: i checked all other sources i could find and i tested all of them and none worked, so i need a new solution

**Comment by kisak-valve** [comment]
Hello @Annonymousse,
The short answer is that you are using the wrong distro for linux gaming in general. Kali Linux is a specialty distro for security auditors and tinkers. Per https://github.com/ValveSoftware/steam-for-linux/issues/2317#issuecomment-16477020 running steam as root is intentionally blocked for your own protection.

If you want continue trying to setup steam on this linux install, what you need to do is create a normal (non-root) user, reconfigure the system to have multilib support, and resolve any missing dependencies. This is technically possible since Kali Linux is based on Debian Testing and there's some documentation at https://wiki.debian.org/Multiarch/HOWTO, but not advised for beginners.

Your best bet is to reach out to your distro's community for support in this matter.

**Comment by Annonymousse** [comment]
please open the thread, root user isnt the problem at fucking all, what is it with the valve support sucking so much these days? i know i am using the wrong distro but who cares, my problem is the missing 32bit packages which are gone, just poof, they dont exist and you cant get them

**Comment by Annonymousse** [comment]
and also the multiarch doesent work, i installed the 32bit architecture

**Comment by Cheeseness** [comment]
If multiarch truly doesn't work or if the required 32 bit packages aren't available on your distro, then that's outside the scope of this bug tracker.

If (as I suspect), you've not correctly enabled multiarch or have failed to correctly install the dependencies you need for Steam to run, then that also is outside the scope of this bug tracker.

There's nothing that anybody here can do for you, and (distro commentary aside) I think that you probably owe him a thank-you for listing the things that you need to work on and giving you a URL for further information in the hope that it would help.

As @kisak-valve said, your best bet is to reach out to your distro's community for support in this matter. I hope you will be more civil with them.
