### ISSUE TITLE
Steam for linux on about to be unsuported Ubuntu 12 LTS

### ISSUE THREAD

**Issue by mosulache** [ValveSoftware/steam-for-linux#4896]
I was suggested by Valve Support to ask the community questions since I run an unsupported linux version. (duh!)

Like most linux desktop users, I tend to run a more recent version..
http://store.steampowered.com/hwsurvey/?platform=linux
this shows NOBODY is using Ubuntu 12LTS 

So the issue is
Are you gonna support a decently fresh version of linux? such as 16.04/ 16.10 

Ubuntu 12 LTS has EOL in 1 month!

https://www.ubuntu.com/info/release-end-of-life

Games expect latest hardware, latest drivers, but you only support a dated OS
Not even packaging as deb for a more recent distro is a pain..

FYI
initially reported that my steam library folder changed ... and games disappeared and did not wanted to re download 290GB of games data.. so asked support of Valve. Figured out (you changed some paths in a recent Steam update..) I fixed my issue by moving games (and games definitions) into a new declared directory as library folder.

best regards,
M

**Comment by Seegras** [comment]
What's more, just about nobody is running a 32bit Linux. Why is steam itself 32bit?

**Comment by BishopZen** [comment]
Yes, this is a mess. The latest updated failed for me and left me with only errors when I tried to run Steam. I went to Steam support followed the path to report a problem with the client crashing then contact support was the option. I can't understand why there isn't any thing there directing Linux users to the forums because they clearly have no intention to support Linux at all there. The slow response was only to drop a past that did not address my problem in anyway and only contained links for troubleshooting on Windows and Mac OS. As one of the errors mention missing 32-bit libraries I decided to try reinstalling. From "Install Steam" at the top of the page there. That installed the install launcher. But running steam then started the install launcher which failed with contact technical support. Anyway running from terminal showed that it was trying to remove ~./steam which failed, fortunately, as a non-empty directory. I then renamed that to save all my game data. And maybe allow the fresh install to proceed. That worked fine. Steam reinstalled and loaded, but didn't have any games installed. I shut it down and copied folders from the old installation to the new installation at ~.local/share/Steam. Some folders within that tree had also been moved and I had to be careful to copy them to their new locations. My games show up as installed again. Steam runs, but when run from terminal you can see a lot of warnings. Maybe I copied something that I shouldn't have. Or maybe this is just normal for Steam.

**Comment by aaronfranke** [comment]
Ubuntu 12.04 LTS has already EOL'd as of me posting this. The oldest supported release is Ubuntu 14.04 LTS which has a little under two years left.

**Comment by kisak-valve** [comment]
Hello @mosulache, the documentation should have been updated to reflect that the latest Ubuntu LTS is considered supported.

@BishopZen the incompatible folder layouts between the distro-provided steam package and Valve-provided steam package should have been resolved in an upstream Debian package, however, as of this writing, Ubuntu ships an altered variant of 1.0.0.54 which is from 2016 and needs to be resolved by the distro's package maintainer(s) for Steam.
