### ISSUE TITLE
Crusader Kings 2 DLC Tab Missing from Launcher

### ISSUE THREAD

**Issue by DreadPirateLynx** [ValveSoftware/steam-for-linux#4925]
#### Your system information

* Steam client version (build number or date): March 22, 2017 @ 23:45:04
* Distribution (e.g. Ubuntu): Linux Mint 17
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

After a fresh install, the DLC tab is missing from the Launcher. This is a problem with the DLC folder. The game is looking for a folder named "dlc", but the folder is installed as "DLC", which is a problem in linux due to filenames being case sensitive. The end user can fix this problem themselves by renaming the folder in question, but it took me ages to figure out what the problem was, and this shouldn't even be necessary in the first place. The previous issue open for this problem, #734, has been closed even though the problem still persists. 

#### Steps for reproducing this issue:

1. Fresh install CK2 on a linux machine
2. Run the launcher
3. Notice DLC tab is missing

**Comment by kisak-valve** [comment]
Hello @DreadPirateLynx, I'm going to go ahead and re-open the existing issue report.

#734 was closed because I got a report that the dlc folder was created lower case on a clean install of the game, but that wouldn't help you if the folder was created with upper case characters some time in the past.

Like the previous report, this should be reported to the game devs, it's only in this issue tracker for informational purposes.
