### ISSUE TITLE
Can't open a player's steam profile from the scoreboard

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/steam-for-linux#4957]
Issue transferred from https://github.com/ValveSoftware/csgo-osx-linux/issues/1403.
@boustrophedon posted on 2017-05-09T20:43:52:

#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/boustrophedon/989f6190f41ef4e17fca440347d4d936
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:

In CSGO, hitting tab, right clicking, and then left clicking on a player's name and clicking on "Community Profile" should bring up their steam profile. Instead it maybe flashes a window for a second and just leaves the overlay.

I think it started maybe after the most recent steam client update? Or it could have been a csgo update. Either way, within the past three or so days.

#### Steps for reproducing this issue:

1. Start a game of CSGO, casual, mm, dm, it doesn't matter.
2. Tab to open the scoreboard
3. Right click to enable mouse
4. Left click on player's name
5. Click on community profile
***
@kisak-valve commented on 2017-05-09T21:00:53

The 2017-04-25 steam beta client overlay does not have this behavior, and the 2017-05-08 steam beta client does. Most likely a regression from updating to CEF 58.

**Comment by kisak-valve** [comment]
This issue is more general than initially reported, with CS:GO and Dota 2, the steam overlay does not open a CEF window for any purpose other than clicking the web browser button.

**Comment by Cpt-Derp** [comment]
I'm reporting this bug. Using any Steam links within the overlay (and within any game that opens Steam links in the overlay) will not open a CEF window. Using the web browser button works however.

**Comment by boustrophedon** [comment]
Update to this: I think I may have gotten a steam update? Or maybe not. Viewing users' profiles from my friends list works now.

Either way I was looking at some workshop content and clicked on a youtube video. It popped out in a new window but when I tried to close it the video's audio could still be heard playing in the background and I couldn't interact with steam at all. I pkilled a few things, eventually steam realized it crashed, and eventually I could control-C steam from the terminal that I opened it in. The crash should be one of these (okay while trying to copy and paste from the system information it crashed again, which has happened before, filing a new bug): https://gist.github.com/boustrophedon/492d06a8c15bce2580788b7ce8cf7c2b

Anyway, then I restarted steam and here is the actual "bug" that I encountered:

When I click on a youtube video in steam it opens it in Firefox rather than in a CEF window. I don't know if this is intended or not, but I kind of prefer it this way.

**Comment by Cpt-Derp** [comment]
Opening the market from the inventory in CS:GO appears to work just fine.

**Comment by af7567** [comment]
I have the same problem using the steam beta client.  Opening the market from inventory seems to work but I can't open players profiles and I can't buy anything in CS:GO.  I just tried to buy the CS:GO operation and I got the window that told me to "add funds" but when I clicked add funds I just had a blank overlay.

Changing to the stable steam client fixes it.

**Comment by mastercoms** [comment]
Can also confirm this bug happens in the Steam beta client. Prevents me from buying Dota 2 items.

**Comment by mcgi5sr2** [comment]
This issue occurs in the stable client now as well. Since the latest update.

**Comment by af7567** [comment]
I also have this problem with the stable client too now.  Trying to look at a profile from inside CS:GO opens up the overlay but doesn't attempt to open a profile.

**Comment by evilarceus** [comment]
After the recent Stable client update, the same issue occurs as it did in the Beta client. It used to work fine in the Stable client before the update.

**Comment by GreenByteSoftware** [comment]
I can also confirm this.

**Comment by GUiHKX** [comment]
I've noticed that you can open pretty much any other URL except steamcommunity.com

**Comment by blur92** [comment]
too me same problem when update last bug big :( i can't buy windows

**Comment by kisak-valve** [comment]
Until a steam dev figures this out, you should be able to workaround this issue by putting steam into big picture mode before starting the game.

**Comment by sizeofbool** [comment]
@kisak-valve This behaviour was exactly the same on Steam Client Beta. Now, after recent CEF update this bug moved to default Steam Client.
I've opted out from Beta because of overlay stability issues and inability to open player's profile inside overlay. Why is Valve pushing buggy update into stable branch if you got various reports about beta client?

**Comment by Plagman** [comment]
This will be fixed in the next Beta.

**Comment by CSV-12** [comment]
same problem here, first with Steam Beta, then normal steam.
Linux Mint 18
opening overlay:
****loading serverbrowser_client.so
Installing breakpad exception handler for appid(steam)/version(1496897923)
Clearing web browser cache in game:

Assert( Assertion Failed: GenerateCEFLogFileName in unknown process ):chrome_ipc_client.cpp:112
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
crash_20170616232156_6.dmp[10105]: Uploading dump (out-of-process)
/tmp/dumps/crash_20170616232156_6.dmp
/home/user64/.steam/ubuntu12_64/steamwebhelper.sh: line 5: 10110 Segmentation fault      ./steamwebhelper "$@"
crash_20170616232156_6.dmp[10105]: Finished uploading minidump (out-of-process): success = yes
crash_20170616232156_6.dmp[10105]: response: Discarded=1
crash_20170616232156_6.dmp[10105]: file ''/tmp/dumps/crash_20170616232156_6.dmp'', upload yes: ''Discarded=1''

**Comment by evilarceus** [comment]
@CSV-12 Are you currently using Beta or Stable? It's fixed in the latest Beta version.

**Comment by CSV-12** [comment]
CS:GO Beta 1.35.8.9,  behaves just like Stable.
However, in "big picture"-mode the links do open.

**Comment by CSV-12** [comment]
June 8 2017 Beta of steam.
Steam API v017

After de-installing and reinstalling Steam the shortcuts no longer work.
Get a pop-up: 
"Couldn't set up Steam data - please contact technical support"

So I start it from the ~./steam folder.
./steam.sh

**Comment by CSV-12** [comment]
last game update 6/20/17 resolved the in-game community profile view.

**Comment by Damianu** [comment]
For me it's not only CSGO, I cant open anything that should open in browser but isnt http/https. For example achievements/guides.

**Comment by kisak-valve** [comment]
To reiterate, this is a steam overlay issue which was fixed in the 2017-06-12 steam beta client. Opt into the steam beta client to get the fixed behavior.

**Comment by MChelik** [comment]
I have still this issue. Why is this issue closed?
Actually it used to work but after an update it stopped working. Almost for a month, I can't see players' profile from game or even Last Players of steam overlay.

**Comment by mastercoms** [comment]
@MChelik 

> To reiterate, this is a steam overlay issue which was fixed in the 2017-06-12 steam beta client. Opt into the steam beta client to get the fixed behavior.

**Comment by tetration** [comment]
I´m experiencing the same problem some of the user complained some time ago.In the in-game overlay I cant open steam profiles, view guides, steam community discussion or open links. And sometimes if i try to click in the browser built for the in-game overlay nothing happens as well.

Currently running Steam for linux on Deepin OS 15.4

**Comment by CSV-12** [comment]
Are u you running 2017-06-12 steam beta client?

**Comment by CSV-12** [comment]
Why would you run Deepin OS? Too may unknowns.
There are better ones. Ubuntu, Kubuntu, Mint etc.

**Comment by tetration** [comment]
@CSV-12 

> Are u you running 2017-06-12 steam beta client?

>Why would you run Deepin OS? Too may unknowns.
There are better ones. Ubuntu, Kubuntu, Mint etc.

I´m an old linux user who has been using linux for almost a decade.

I´ve tested all popular linux distributions Ubuntu, Kubuntu, Mint, OpenSuse, Mandriva you name it. When I started out I was a heavy Ubuntu user, but then when Ubuntu made the decision  to switch to that weird GUI that was made for tablet I migrated to Linux Mint, which used to be my favorite Distribution since it didnt try to revolutionize the whole Desktop thing and looked as similar as a Windows Desktop. However after finding out about Deepin OS I got excited to try it out. Afterwards I feel in love with it from all the linux distribution for me Deepin OS is the only one that gives Linux that modern feeling that Windows 10 and Mac Os does. Its interface is clean, fast and efficient. 

Although the other distributions might be more popular and glitch-free. I just cant stand them anymore after using Deepin OS I feel in love with it and I´m now even contributing to them by reporting bugs and making suggestions to their code. Hopefully in some years from now DeepinOs will be as popular as the big giants like Ubuntu and Linux Mint. I´m  sure that if DeepinOS continue to offer an elegant UI as Windows 10/Mac Os, simpliticy and fast reliable GUI more and more people will be moving to it.

**Comment by CSV-12** [comment]
My first Linux was RedHat back at the 2.2 kernel age. USB support was then new and everything was pretty creaky.
After RH went commercial a few years later I switched to Debian, I dabbled a little with other distros but Debian was primary.
Ubuntu defaulted to the Gnome desktop which I never could get used to. I tried several desktop environments, but KDE remains my top choice. It can be customized much more than the alternatives.
When I used Gnome I also installed Konqueror or Dolphin, hit F4 and you get a terminal located in the directory you are in.
XFCE and other are OK, but Gnome keeps reinventing the wheel, and it has gone from octagonal to now triangular. KDE is getting better and better. The distros are reinventing the GUI, like it was necessary, I guess they need something to do, but I change it back to whatever I like anyway, not too hard with KDE. Gnome2 is a train-wreck. 
There is a KDE desktop for Win if you'd like to try, which I have not done.
Deepin is located in communist China, along with all their repos, likely because of national firewalling. 
It looks like it want to be a mac clone. I'm not sympathetic to China and their causes. It is contrary to the freedom Linux expresses. Mac I can live without, but I admire Steve Job's usability focus. It is needed.
Lately Linux has taken a step backwards with Systemd, a throwback to Microsoft's technical obscurity. But there are alternatives, but unfortunately much work is needed to bring full functionality back to non-systemd distros.

I had the same issues with the in-game overlay, which was resolved in a beta update, which you have to enable.

**Comment by mastercoms** [comment]
It seems like this issue is happening again.

**Comment by CSV-12** [comment]
maybe its DOTA2 specific?

**Comment by mastercoms** [comment]
Ah never mind, my settings just reset for some reason and I was back on stable. Switching to beta fixed it for me.

**Comment by tetration** [comment]
I did the same it worked for me as well in linux Deepin OS.

**Comment by olegantonyan** [comment]
Still doesn't work in csgo
