### ISSUE TITLE
Steam won't open

### ISSUE THREAD

**Issue by Eerosal** [ValveSoftware/steam-for-linux#5008]
#### Your system information

* Steam client version (build number or date): No idea
* Distribution (e.g. Ubuntu): Debian 8 64bit
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Steam won't launch.

#### Steps for reproducing this issue:

1. Try to open steam
2. Error.

```Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198085201948 [API loaded no]

(steam:2745): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'NMRemoteSettings'

(steam:2745): GLib-GObject-CRITICAL **: g_type_instance_get_private: assertion 'instance != NULL && instance->g_class != NULL' failed

(steam:2745): GLib-GObject-CRITICAL **: g_type_instance_get_private: assertion 'instance != NULL && instance->g_class != NULL' failed
assert_20170605192917_1.dmp[2801]: Uploading dump (out-of-process)
/tmp/dumps/assert_20170605192917_1.dmp
/home/MYNAMEHERE/.local/share/Steam/steam.sh: line 727:  2745 Segmentation fault      $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20170605192917_1.dmp[2801]: Finished uploading minidump (out-of-process): success = yes
assert_20170605192917_1.dmp[2801]: response: CrashID=bp-3badc89d-355f-4700-a2a0-7b3092170605
assert_20170605192917_1.dmp[2801]: file ''/tmp/dumps/assert_20170605192917_1.dmp'', upload yes: ''CrashID=bp-3badc89d-355f-4700-a2a0-7b3092170605''
Assert( CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected ):../common/pipes.cpp:765

crash_20170605192921_2.dmp[2810]: Uploading dump (out-of-process)
/tmp/dumps/crash_20170605192921_2.dmp
crash_20170605192921_2.dmp[2810]: Finished uploading minidump (out-of-process): success = yes
crash_20170605192921_2.dmp[2810]: response: Discarded=1
crash_20170605192921_2.dmp[2810]: file ''/tmp/dumps/crash_20170605192921_2.dmp'', upload yes: ''Discarded=1''
../common/pipes.cpp (765) : CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected
steamclient.cpp (714) : Assertion Failed: bufRet.TellPut() == sizeof(uint8)
../common/processpipe_posix.cpp (492) : Assertion Failed: CCrossProcessPipe::BWrite: 32 (Broken pipe)
```

**Comment by kisak-valve** [comment]
Hello @Eerosal, what distro are you using?

**Comment by Eerosal** [comment]
Debian 8 Wheezy if I remember correctly.

**Comment by kisak-valve** [comment]
Is this a new install or an existing install that stopped working after an update and did you install steam with the distro-provided steam package or the valve provided steam package?

**Comment by Eerosal** [comment]
Existing install that stopped working and Valve provided .deb package.

**Comment by kisak-valve** [comment]
Try running `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam` in a terminal and see if it helps.

**Comment by Eerosal** [comment]
Thank you. Works.

**Comment by pullasuti** [comment]
Getting the same error here since last night. Running Ubuntu 17.04. 

`Setting breakpad minidump AppID = 769
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded no]
Generating new string page texture 12: 48x256, total string texture memory is 49,15 KB
Generating new string page texture 13: 256x256, total string texture memory is 311,30 KB
Generating new string page texture 14: 128x256, total string texture memory is 442,37 KB
assert_20170610195010_1.dmp[13690]: Uploading dump (out-of-process)
/tmp/dumps/assert_20170610195010_1.dmp
/home/suti/.local/share/Steam/steam.sh: rivi 727: 13617 Muistialueen ylitys     (luotiin core-tiedosto) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20170610195010_1.dmp[13690]: Finished uploading minidump (out-of-process): success = yes
assert_20170610195010_1.dmp[13690]: response: CrashID=bp-f9b6d52e-f76c-498b-8027-469cb2170610
assert_20170610195010_1.dmp[13690]: file ''/tmp/dumps/assert_20170610195010_1.dmp'', upload yes: ''CrashID=bp-f9b6d52e-f76c-498b-8027-469cb2170610''
Assert( CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected ):../common/pipes.cpp:765

crash_20170610195013_2.dmp[13694]: Uploading dump (out-of-process)
/tmp/dumps/crash_20170610195013_2.dmp
crash_20170610195013_2.dmp[13694]: Finished uploading minidump (out-of-process): success = yes
crash_20170610195013_2.dmp[13694]: response: Discarded=1
crash_20170610195013_2.dmp[13694]: file ''/tmp/dumps/crash_20170610195013_2.dmp'', upload yes: ''Discarded=1''
`

Tried with DRI2 and 3, with "stable" and oibaf built driver, clean Steam install, Steam reset, not getting past login.

**Comment by tinspin** [comment]
Why is this closed? What is the permanent fix?

Is "STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam" the final fix?

**Comment by Eerosal** [comment]
^ true. I haven't been using steam because I'm too lazy to fix the desktop file or run it.

**Comment by andersonzanichelli** [comment]
STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam Doesn't work for me.
After the command, steam still breaks

[2017-09-17 01:28:58] Verifying installation...
[2017-09-17 01:28:58] Verification complete
assert_20170917012858_1.dmp[32329]: Uploading dump (out-of-process)
/tmp/dumps/assert_20170917012858_1.dmp
/home/<user>/.local/share/Steam/steam.sh: line 941: 32242 Aborted                 (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20170917012858_1.dmp[32329]: Finished uploading minidump (out-of-process): success = yes
assert_20170917012858_1.dmp[32329]: response: CrashID=bp-8d207190-686d-4ae0-924e-475ef2170916
assert_20170917012858_1.dmp[32329]: file ''/tmp/dumps/assert_20170917012858_1.dmp'', upload yes: ''CrashID=bp-8d207190-686d-4ae0-924e-475ef2170916''
Assert( CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected ):../common/pipes.cpp:766

ERROR: ld.so: object '/home/<user>/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
assert_20170917012919_3.dmp[32334]: Uploading dump (out-of-process)
/tmp/dumps/assert_20170917012919_3.dmp
assert_20170917012919_3.dmp[32334]: Finished uploading minidump (out-of-process): success = yes
assert_20170917012919_3.dmp[32334]: response: Discarded=1
assert_20170917012919_3.dmp[32334]: file ''/tmp/dumps/assert_20170917012919_3.dmp'', upload yes: ''Discarded=1''
pid 32334 != 32333, skipping destruction (fork without exec?)
Assert( CClientPipe::BWriteAndReadResult: BWaitResult failed, disconnected ):../common/pipes.cpp:766

Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
assert_20170917012921_6.dmp[32337]: Uploading dump (out-of-process)
/tmp/dumps/assert_20170917012921_6.dmp
assert_20170917012921_6.dmp[32337]: Finished uploading minidump (out-of-process): success = yes
assert_20170917012921_6.dmp[32337]: response: Discarded=1
assert_20170917012921_6.dmp[32337]: file ''/tmp/dumps/assert_20170917012921_6.dmp'', upload yes: ''Discarded=1''
[0917/012928.608538:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization

**Comment by epe07** [comment]
Bump. Why hasn't there been any fixing updates?

**Comment by Isty001** [comment]
@andersonzanichelli I have the exact same issue. I really hope there will be a fix for this issue.

**Comment by hamishmaku** [comment]
getting the same result, running beta client on debian unstable. have updated to latest packages.

**Comment by hamishmaku** [comment]
works using STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam, but is not ideal.
