### ISSUE TITLE
Steam keeps forgetting it ever saved my account every two days

### ISSUE THREAD

**Issue by neirenoir** [ValveSoftware/steam-for-linux#5035]
#### System information

* Steam client version: Jun 8 2017 
* Distribution: Debian Sid 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Issue:
Ever since a Steam update I had around half a month ago, if I stop logging in on Steam for two days, the client will simply "forget" I had ever logged in to Steam, and will prompt me with the "Create new account or Log In to an existing account" screen when booting Steam.

It is really weird, since it seems to be time-based and not reboot based. The computer does seem to keep information about previous logins, since I have two accounts authorized in this PC for family share, and one of them remembered this as the same computer, but the second one (my main account) required me to use Steam Guard to authorize this as a new computer.

It is not much of a problem, but it is really, really annoying. I have already tried using the tick-untick "remember my account" fix, but it doesn't work. Also tried reinstalling Steam by deleting ~/.steam, one time keeping the steamapps folder and the other deleting the whole thing, but it still doesn't work. Is there anything I can do to fix this?

#### Steps for reproducing this issue:

1. Login into account
2. Steam will keep remembering the account for more than 24 hours but approximately less than 48 hours after the first login without any problem
3. Wait two days
4. Steam will prompt you with the "Create new account or Log In to an existing account" window

**Comment by Damianu** [comment]
Happens to me after steam updates only.

**Comment by kmaterka** [comment]
The same for me, very annoying. It keeps forgetting credentials every few days, uasually after computer restart (Steam is autostarting on my system). Ubuntu 16.04 (Neon)

**Comment by HellishINC** [comment]
Arch Linux, Not steam beta (but also happens there), system updates everyday on login.

I'm getting this issue on almost every reboot/startup. Extremely annoying having to do to 2FA every single day.

**Comment by Dea1993** [comment]
same problem on debian 9, forgets login and language every time i restart pc.
some months ago there wasn't this problem, please fix if because is really annoying.

I've also tried beta channel but the problem still present.
instead on windows there aren't problems

**Comment by LucienPe** [comment]
@Dea1993 #5060 darealshinji's solution worked for me.

**Comment by lecbee** [comment]
I have the same issue with Steam and French language.
I'm on Fedora 25.

**Comment by Nivelfacile** [comment]
I have the same issue with Steam loggin and Spanish language
Mint 18.3

**Comment by Prime624** [comment]
Same issue with being logged out and getting login or create account every few days. Ubuntu 16.04, Steam Beta and non-beta.

**Comment by jackwickham** [comment]
I'm having the same issue with Steam on Fedora 27. I've tried the beta and release versions.

**Comment by Patola** [comment]
I am not sure if that is the same issue, but steam keeps forgetting I am logged in _while I am logged in_. Like, I am using steam and reading and responding to a bunch of forum messages, suddenly I can't reply, and I see that I am somehow logged out. Steam "tries to login" again but fails. To fix that is easy, I just need to exit steam and call it again, but it is annoying as hell.

**Comment by liuseemin** [comment]
I got both problems. It used to log me in automatically, but I have to login again sometimes like steam was "occasionally" forgetting my password. and when I get in, the language is reset to English from Chinese.
I'm using ubuntu gnome 16.04.

**Comment by tonehrk** [comment]
I've same problem.

**Comment by nightsky30** [comment]
I saw this back with Ubuntu 16.04.  I've not experienced this on 17.10.  I think I haven't seen this issue in over a year.  Though I've seen many other users with many different distributions report the problem.  Seems very random.

**Comment by brianinthered** [comment]
I've had this problem for a long time, months at least.  Online or Offline Steam will forget the password and I have to keep re-entering it.
This is very frustrating when I have 6 PCs running Mint 18.3 and do LAN Parties
I hope Valve fixes it soon.

**Comment by tonehrk** [comment]
Login and...

`chmod 444 $HOME/.steam/registry.vdf`

**Comment by sellth** [comment]
That's a hotfix at best, as Steam cannot save any changed settings with those permissions.

Am 10. Juli 2018 02:18:41 MESZ schrieb tonehrk <notifications@github.com>:
>Login and...
>
>`chmod 444 $HOME/.steam/registry.vdf`

**Comment by nightsky30** [comment]
Checked the normal permissions and they seem to be 664.  Yes, nothing more than a workaround when it kills normal write functionality.

So strange that it didn't affect me for almost a year, and then once I built a new system...it appears again.  I never needed to mess with that file's permissions values before.  The switch of hardware makes me think it is related to that.  Complete and utter speculation.

It doesn't appear to be distro or desktop environment specific given the variety of systems affected.  It would be nice if they could determine the cause.

**Comment by Leon422** [comment]
This still happens.

**Comment by TheSHEEEP** [comment]
Indeed it does. Quite the nuisance.

**Comment by TacoDelPaco** [comment]
I've been having this happen to me for the past few weeks out of the blue, was working fine until I believe an upgrade (may have been the deb upgrade not from Steam). `registry.vdf` was set to read only and had AutoLogin, I'm experimenting now but very frustrating since I too have F2A and every time I restart/reopen Steam I have to grab my phone... I honestly thought the Flatpak version got swapped somehow but that doesn't seem to be the case.

Thanks

**Comment by vfjpl** [comment]
Maybe this bug is related to "Don't save account credentials on this computer" check box?
https://www.reddit.com/r/Steam/comments/2g9wo6/steam_keeps_forgetting_my_login_details/

**Comment by lemmy04** [comment]
same here, openSUSE Leap 15.0, none of the workarounds help.
Additional detauil, my ~ is on nfs - game library is *not*

**Comment by bormolino** [comment]
Still happens under Ubuntu 16.04 LTS with Steam-Client build  Nov 10 2018.

**Comment by lemmy04** [comment]
is there actually anyone from valve reading this?

**Comment by brianinthered** [comment]
There are several other github posts about Steam password without any long term solution.
Apparently you can run this command in Terminal to fix it, but I have a feeling this will need to run after every Steam update...
chmod -w ~/.steam/registry.vdf

**Comment by aaronfranke** [comment]
What kind of system configuration causes this bug? I've never experienced this issue on any of my computers. Ubuntu 18.04 and previously 16.04, 64-bit, some dual-boots and some not, I run [this script](https://github.com/aaronfranke/Linux-tools/blob/master/ubuntu-only/setup.sh) on all new installs (includes some libs for Steam and Steam games).

**Comment by hhirsch** [comment]
Same problem on current Manjaro (Jan 2019). But I've had this problem on other distributions, too. For years.

**Comment by Ishidres** [comment]
@tonehrk's solution worked for me:
> Login and...
> 
> `chmod 444 $HOME/.steam/registry.vdf`

Thanks! :smiley:

**Comment by TTimo** [comment]
See https://github.com/ValveSoftware/steam-for-linux/issues/5030

**Comment by kisak-valve** [comment]
Hello everybody, it looks like we're at the point that this issue should be closed. Follow up issues should be tracked separately.

**Comment by Luticus** [comment]
I put this on a related issue (#6257) but posting here too in case someone else is googling to find a solution and ends up here like I did.

Just thought I'd throw my 2cents in on this because I've been dealing with this issue for, god, maybe years now and it's been driving me crazy.

I thought it was  a steam bug that would eventually get fixed so I kind of just left it alone and never bothered fixing it. Anyway I happened to notice it doesn't happen on a new laptop I got so I figured I'd take a second look.

The registry.vdf.old being the culprit is probably right. However I couldn't think of a good clean way to prevent file deletion without messing with the file ownership and setting a sticky bit on the directory above, or making the file immutable via chattr +i, or by setting the permissions to remove write. None of those sat well with me as I thought they might mess up other things with steam, possibly break updating, or have some side effect or unintended consequence. Fortunately I noticed that the registry.vdf.old file had a file size of '0' and that to me looked... not right. I used cat to view the file's content and sure enough, it was blank. So I deleted the file and simply started steam. This seems to have resolved the issue for me.

You can verify this by watching the files change as you launch steam. Use the watch -n 1 "registry.*" and launch steam. You can see it create a file registry.vdf000000000 where the 0's represent some random number, it seems.  That's the behavior that was happening when it WORKED, so that's what you want. For some reason the .old file was preventing that... some how.

Also, in my case I symlinked a steam directory to .steam in my home to create a non hidden version for easy access. Not sure if it helped or not but I used unlink steam in my home directory to remove that as well.

I hope this advice helps anyone else facing this issue as it was driving me crazy!
