### ISSUE TITLE
Crashes with nvidia-vulkan-developer-beta driver

### ISSUE THREAD

**Issue by ParkerMc** [ValveSoftware/steam-for-linux#5102]
#### Your system information

* Steam client version (build number or date): I think it is 1501097683
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I installed the [nvidia-vulkan-developer-beta](https://aur.archlinux.org/packages/nvidia-vulkan-developer-beta/) driver from the aur for steamvr now when I try to start steam with steam runtime it cashes. Steam native runs fine but it is missing some lib that steamvr needs.

Here is the log with back trace from gdb: https://gist.github.com/ParkerMc/8297e94b382a1a043d07d8418cfad582

#### Steps for reproducing this issue:

1. Replace drivers with the nvidia vulkan developer beta drivers from the aur
2. Start Steam runtime

**Comment by ParkerMc** [comment]
Forgot system info: https://gist.github.com/ParkerMc/a1ab40e096f432d9b12aa5f14bd18e41

**Comment by af7567** [comment]
@ParkerMc Can you start steam OK with the nvidia-vulkan-developer-beta driver if you delete or move your ~/.local/share/Steam/config/config.vdf file out the way and login again?
Just wondering if it is related to the crash I get https://github.com/ValveSoftware/steam-for-linux/issues/5099 since one of the packages I updated was the nvidia driver from 381.22 to 384.59 at about the same time.

**Comment by ParkerMc** [comment]
Wow, that worked.

**Comment by ParkerMc** [comment]
Only works one time after I remove the config file though.

**Comment by ParkerMc** [comment]
If I uncheck remember password it works every time.

**Comment by kisak-valve** [comment]
Hello @ParkerMc, thanks for testing the workaround at https://github.com/ValveSoftware/steam-for-linux/issues/5099#issuecomment-318520945. Closing in favor of #5099.
