### ISSUE TITLE
Wine: C:\Program Files\Steam\steamerr prevents wine from exiting

### ISSUE THREAD

**Issue by mtmkls** [ValveSoftware/steam-for-linux#5104]
#### Your system information

* Steam client version (build number or date): 2017 Jul 17
* Distribution (e.g. Ubuntu): Debian
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
When exiting the steam client the process mentioned in the title is left behind, and it has to be killed manually. This behavior started about a month ago.

#### Steps for reproducing this issue:
1. Start steam with wine
2. Exit steam
3. steamerr is still running

**Comment by aaronfranke** [comment]
Valve does not officially support Wine. Please contact the Wine developers instead. 

https://appdb.winehq.org/objectManager.php?sClass=version&iId=19444

**Comment by kisak-valve** [comment]
I'm going to close this because this issue tracker is for the native linux client.

That said, I can at least tell you that I do not experience this with wine-staging 2.12, which has an unrelated fix for https://bugs.winehq.org/show_bug.cgi?id=43315 and you may have similar success with a recent version of wine.
