### ISSUE TITLE
realloc(): invalid next size: 0x569eb120 (varies)

### ISSUE THREAD

**Issue by Valmar33** [ValveSoftware/steam-for-linux#5145]
#### Your system information

* Steam client version: today's, I guess?
* Distribution: Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam should run, but I immediately get this:
https://gist.github.com/Valmar33/a46be9701526510122edaa7320597c5f

I tried running the native Linux version when my Steam installation on Wine was giving the error. My Wine installation was working fine at 3am this morning... :(

**Comment by elmisto** [comment]
Hi,

I had the same problem today.
Checked the backtrace with gdb and the issue seems to be with the recent libdrm update. After downgrading the package to the previous version it is now working for me.

You could try downgrading libdrm from the package cache with:
` # pacman -U /var/cache/pacman/pkg/libdrm-2.4.82-1-x86_64.pkg.tar.xz`

Hope this helps.

**Comment by Valmar33** [comment]
Many thanks! :)
