### ISSUE TITLE
steam needs to be online to update please confirm your connection and try again

### ISSUE THREAD

**Issue by HarshilPatel007** [ValveSoftware/steam-for-linux#5147]
system information
Kali Rolling x86_64 >> Full Updated & Upgraded 4GB Ram i5 3rd Gen Processor 500 GB HDD﻿

Steam client version (build number or date): 
steam_latest.deb

Distribution : Kali Linux Rolling Debian Based 
 
* Opted into Steam client beta?: [Yes/No]

* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
It Update Till 99% But When It Go for 100% It Shows Me This Error.
"steam needs to be online to update please confirm your connection and try again"
But, My Internet Working Like Charm , No Any Issue With Internet Connection.

I Tried All Possible Fix / Trouble Shooting Means All Google Results / Each And Every Solution. Like ,
1) add IP Address media.steampowered.com In /etc/hosts
2) cd ./steam , rm -rf steam.pid , cd , rm -rf .steampid and restart 
3) add i386 arch. and it's dependency
But No Luck :'(
I Stuck With This Error From Past Week :'(

**Comment by kisak-valve** [comment]
Hello @HarshilPatel007, unfortunately steam is not supported by Kali Linux package maintainers, and by extension unsupported here.

That said, steam should be checking with networkmanager to see if the network is up, but doesn't actually require a running instance of networkmanager. You could try stopping that service if it is running and using something else to bring up your network connection.

If you want to do clean resets of steam, it may be easier to run `steam --reset` instead of manually. If you are using the steam beta client, you can manually opt-out of it by removing `~/.local/share/Steam/package/beta` (for troubleshooting purposes).

Closing due to the lack of support by the distro.
