### ISSUE TITLE
Steam.sh fails to regenerate some symlinks because Debian's packaging has folders there

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-for-linux#5270]
inxi -F here: https://i.imgur.com/VGepyp0.png

Issue highlighted here: https://i.imgur.com/pD3C5ig.png

* Steam client version:  Oct 30 2017, at 19:09:46
* Distribution: Xubuntu 17.10
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

Tried to run Opus Magnum from the terminal and noticed steam run rm on a couple of directories. While it stderr that it's a file and effectively does nothing, I still feel squeamish about it running rm for fun.

#### Steps for reproducing this issue:

1. Navigate to Opus Magnum directory
2. Run Lightning.bin.x86.64

**Comment by kisak-valve** [comment]
Hello @Managor, these messages are coming from ~ line 777 of `~/.steam/steam.sh` and the non-fatal failures are from Ubuntu's distro-provided steam packaging having a different folder layout for steam compared to the Valve-provided .deb and other (non-Debian) distros.

For the moment this is not likely to go away because part of it is for legacy compatibility and nothing should be functionally broken by this issue.

**Comment by cbacott** [comment]
The actual solution here is never do an rm like that. These should be changed to:
[[ -L foo ]] && rm foo

An rm should not be done that way without some sanity checking. The above tests if foo is a symlink, and only then does it do the rm. 

I would fix the script myself and send the patches to the project, except every time I edit that script it auto-downloads the shipped version which is broken. There's several other bugs here including .steampath symlink being created broken, with no sanity checking going on.

**Comment by kisak-valve** [comment]
This issue was resolved in the Debian variant of the steam package with 1.0.0.59-1, which was tracked at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916303.
