### ISSUE TITLE
[Gnome Shell] Steam closes after clicking "close" button in Shell's overlay

### ISSUE THREAD

**Issue by Majkl578** [ValveSoftware/steam-for-linux#53]
Steam closes and terminates itself after clicking on "close" ("X") button in Gnome Shell's overlay. This also happens when more than one window (e.g. Friends and Library) are opened which is weird and should close only the one window. In normal mode (clicking window's close) it is same as #11.

Debian experimental x86_64, Gnome Shell 3.6.

**Comment by 0x1f415** [comment]
I use i3wm and using the keyboard shortcut to close the window also shuts down steam.

I'd like to suggest a command-line flag to hide the main window, functionally identical to the steam client's close button, so that users can at least override the default WM_DELETE_WINDOW behavior in their configs.

roping in some other related issue threads: #1040 #2160 #1879

**Comment by rindo-eiji** [comment]
is it normal that I still have this issue?

**Comment by ssPedro1** [comment]
> is it normal that I still have this issue?

I also have this issue on Pop!_OS 20.04

**Comment by Allavaz** [comment]
I still have this issue. Expected behavior for me would be that when I close from overview/taskbar/alt-f4 it doesn't actually close Steam, it just closes the window, like in Discord for example. The worst part is when you have only a chat window open and a game running, you do alt-f4 on the chat window and it closes Steam and your game goes with it, kinda annoying.

**Comment by kisak-valve** [comment]
Hello @rindo-eiji, @Allavaz, this issue is currently being tracked at #2685.
