### ISSUE TITLE
pure 64bit client for Linux

### ISSUE THREAD

**Issue by Maschinenhans** [ValveSoftware/steam-for-linux#5324]
#### Slackware64 14.2 x.org

* Steam client version (build number or date): No one
* Distribution (e.g. Ubuntu): Slackware64 14.2
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

Is there a chance to get a steam-client without the need of having 32bit libraries? To install a multilib environment is no option for me.

IMHO 32bit libs are obsolet and more and more linux distributions doesn't support 32bit anymore. The Steam support told me to open an issue here and I doesn't find an similar issue in this tracker. 

Thank you very much in advance.
Best regards
Maschinenhans

**Comment by FreeSlave** [comment]
There are many 32-bit only games, so you'll need to install 32bit libraries (libc and opengl) if you want to play these anyway.

**Comment by kisak-valve** [comment]
Hello @Maschinenhans, your question regarding libraries has been answered at https://github.com/ValveSoftware/steam-for-linux/issues/179#issuecomment-267790879.

Since there are many 32 bit only games and support for these games isn't going away, it's largely irrelevant if the steam client itself is 32 bit or 64 bit.

If system-wide multilib isn't an option for you, running steam in a community-maintained container such as Docker may be worth looking into, but I do not know if that still needs some basic 32 bit support for libc and opengl to work.
