### ISSUE TITLE
Steam wants me to install weird packages

### ISSUE THREAD

**Issue by xuanruiqi** [ValveSoftware/steam-for-linux#5467]
Steam obviously wants me to install `libgl1-mesa-dri:i386` and `libgl1-mesa-glx:i386` whenever I start Steam. I know this happens and I can install them, but the problem is that the first one (for whatever reason) depends on `libllvm:i386` and installing it would remove all my important packages like `xserver-xorg-video-all`, which is bad. However, if I skip installing those, Steam just runs fine. I am not sure what's wrong here.

I have upgraded all my software packages and have enabled `universe` and `multiverse`. It didn't help.

I am on Ubuntu 18.04 LTS (just officially came out today!) and the Apr 2 2018 build

**Comment by xuanruiqi** [comment]
Hm, I use the `graphics-drivers/ppa` PPA, but no mesa PPAs. The former doesn't contain mesa, I think. Looks weird to me.

I didn't update my system from 16.04 but rather installed a fresh version of 18.04. So conflicting PPAs shouldn't be a problem.

**Comment by hanysz** [comment]
On my system (also Ubuntu 18.04 LTS), I was able to fix this by manually installing libgl1-mesa-glx:i386 using aptitude instead of apt.  Aptitude will suggest options for fixing the conflict, and if you say no then it will try a different option.  For me, the first suggestion was to uninstall a bunch of stuff; after I said no, the second suggestion was do nothing (don't install anything), and the third option was to downgrade libgl1-mesa-glx [18.0.5-0ubuntu0~18.04.1 (now) -> 18.0.0~rc5-1ubuntu1 (bionic)], which seems to do the trick for me.

**Comment by xuanruiqi** [comment]
I'm closing this, because I'm no longer using Ubuntu anymore, as of Dec 2018, so no longer a problem for me :smile: Hopefully this thread will be useful to some Ubuntu users though.

**Comment by nightsky30** [comment]
@pwaller You are very welcome.  I'm glad that helped :)

**Comment by IMidULti** [comment]
@pwaller thank you for posting this because it fixed my issue. I also had custom llvm repo on mine.

**Comment by bz2** [comment]
See also https://github.com/ValveSoftware/steam-for-linux/issues/2800#issuecomment-661855621 which gives specific guidance for working out if multiarch libllvm packages match, which is what had to be fixed to resolve this symptom for me (and also has some useful background on why this is a recurring problem).
