### ISSUE TITLE
Kubuntu 18.04 Steam won't start, steam --reset command and deleting ~/.steam directories no use

### ISSUE THREAD

**Issue by skyroz** [ValveSoftware/steam-for-linux#5476]
Hi everyone. I'm running Kubuntu 18.04 and I have been utterly incapable of getting it to open since I upgraded from 16.04 to 18.04.

* Steam client version (build number or date): 1.0.0.54+repack-5ubuntu1
* Distribution (e.g. Ubuntu): Kubuntu 18.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes, quite a few times

So what happens when I try to simply run
`steam` from the terminal
I get no obvious errors, these are the messages I see:
```
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
[2018-05-07 21:06:35] Startup - updater built Apr  2 2018 15:23:43
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2018-05-07 21:06:35] Checking for update on startup
[2018-05-07 21:06:35] Checking for available updates...
[2018-05-07 21:06:35] Download skipped: /client/steam_client_ubuntu12 version 1522709999, installed version 1522709999
[2018-05-07 21:06:35] Nothing to do
[2018-05-07 21:06:35] Verifying installation...
[2018-05-07 21:06:35] Performing checksum verification of executable files
[2018-05-07 21:06:36] Verification complete
```
also when I attempt `steam --reset` I get the error message:
`Error: Couldn't find bootstrap, it's not safe to reset Steam. Please contact technical support.`

Also, very common fixes I've seen for this online include installing libnss-resolve:i386 and deleting the various ~/.steam directories and starting anew; Clearly, none of that has worked for me or else I would not be here. I have even reached out to Steam customer Support and they too have been at a total loss as for what to do, other than repeating the steps I just mentioned. I haven't been able to log on to Linux Steam in weeks now and have been using the Windows version with Wine in order to hop on and chat with my friends. I don't just use steam for chatting with my friends, as I have nearly a hundred games, but that is my main usage for it, and I really wish there was something I could do to fix it. As you all may be able to tell I've tried really hard at attempting to fix this myself with no results to show for it.

Thanks in advance to any of those willing to help.

**Comment by kisak-valve** [comment]
Hello @skyroz, can you check if any 32 bit opengl application like `glxinfo` from `mesa-utils:i386` works?

**Comment by skyroz** [comment]
Hmm yes Kisak I downloaded mesa-utils and when I run glxinfo I get a very long list of OpenGL core profile extensios, OpenGL extensions, and a list of "228 GLX visuals" with a typical reading stating something such as
`0x021 24 tc  0  24  0 r  y .   8  8  8  0 .  s  4 24  8 16 16 16 16  0 0 None`

**Comment by skyroz** [comment]
Does anyone have anything to add to this? I'm at a total loss for what to do now.

**Comment by skyroz** [comment]
please help? Anyone?

**Comment by noobmagnet** [comment]
I know it doesn't fix your install really, but I would try using Ikey's snap with LSI on or off depending on your taste... [Ikey's Snap /w LSI](https://github.com/solus-project/linux-steam-integration)

Just follow the instructions and run the steam snap, you will know which one is running by which steam directory folder it looks for games it, and it will be in the snaps directory. If you want to keep running it, add your other library with your games in it and uninstall the Ubuntu version so you don't get confused because they go by the same name in your apps list.

**Comment by kisak-valve** [comment]
Hello @skyroz, are you still experiencing this issue on an up to date system?

Re-reading this issue report, it's unclear if you tested 32 bit opengl or 64 bit opengl. Also, distro modifications to the Steam package is why `steam --reset` does not work. If you're still experiencing this issue, please purge the distro variant of the Steam package, move/remove `~/.steam` so that it does not interfere, and retest with the Valve-provided Steam package from https://store.steampowered.com/about/.

**Comment by kisak-valve** [comment]
Closing pending feedback.
