### ISSUE TITLE
Steam does not start

### ISSUE THREAD

**Issue by Liger0** [ValveSoftware/steam-for-linux#5551]
#### Your system information

* Steam client version: I downloaded it today..
* Distribution: Kubuntu 18.04 LTS
* Opted into Steam client beta?: I guess no?
* Have you checked for system updates?: Yes

Hi there. I just downloaded and installed Steam for linux, but whenever I try to open it, I see the icon in the bottom bar of the OS with a turning circle for 2-3 seconds, then it closes itself and nothing happens. I tried to kill the process from the task manager and run it again, but it didn't do a thing.
I searched on the net and I saw other solutions to this problem but no one seems able to solve it.

**Comment by kisak-valve** [comment]
Hello @Liger0, does running steam from a terminal give any hints?

**Comment by Liger0** [comment]
So, I just tried it and it's what I see:
`name@name-SVE1511W1ESI:~$ steam
Running Steam on ubuntu 18.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
`

**Comment by kisak-valve** [comment]
What video card are you using?

Swrast is mesa's slower software renderer and this is telling you that steam is not trying to use a real video card. Does any 32 bit opengl application work like `glxinfo` from `mesa-utils:i386`?

**Comment by Liger0** [comment]
> Does any 32 bit opengl application work like glxinfo from mesa-utils:i386?
I'm pretty much new into Linux, what should I do to verify exactly?
The system is pretty much old but still usable, it's an i5 2450m with an AMD HD7000 serie.

**Comment by kisak-valve** [comment]
From a terminal, please run `sudo apt install mesa-utils:i386` and provided it doesn't want to do something silly, let the package manager install the package, followed by running `glxinfo | grep Device`.

**Comment by Liger0** [comment]
So, this is the result:

> name@name-SVE1511W1ESI:~$ glxinfo | grep Device
> Device: llvmpipe (LLVM 6.0, 256 bits) (0xffffffff)

**Comment by kisak-valve** [comment]
That confirms that you're effectively not using a video card right now to and that's generally not expected to work with Steam. You may have better luck asking around the Ubuntu community for help getting your system setup properly.

**Comment by zer0def** [comment]
@Liger0 could you provide outputs for:

* `dpkg -l | grep -E 'nvidia|fglrx|xorg-video'`
* `cat /proc/cmdline`
* `lsmod | grep radeon` ?

**Comment by Liger0** [comment]
[1.txt](https://github.com/ValveSoftware/steam-for-linux/files/2164519/1.txt)
[2.txt](https://github.com/ValveSoftware/steam-for-linux/files/2164520/2.txt)
[3.txt](https://github.com/ValveSoftware/steam-for-linux/files/2164521/3.txt)
Here you go. :)

**Comment by OvermindDL1** [comment]
Hmm, so it's falling back to the old radeon driver, what was your card, ah it's listed above, a `AMD HD7000m`, which is indeed not supported on AMDGPU due to its age, and the open source RADEON driver never supported it because of the mobile interfaces, so you will have to use the old closed-source fglrx driver (which you do not currently have installed), but I'm not sure it is new enough to support that card either (plus fglrx just flat-out isn't supported on your kernel version, you'd need to downgrade, or backup first, well backup anyway).

Regardless, this does not appear to even remotely be a steam issue, you need to get full 3d acceleration setup and working on your system first, in whatever form that takes, maybe check http://wiki.cchtml.com/index.php?title=Main_Page or https://www.youtube.com/watch?v=EDTLvJ9QK8w if you don't mind downgrading your system first.  That video card seems to be in that wiffly era before AMD open sourced their drivers but were also shutting down the old drivers (my video card, an HD5790, is also in that era, I have to keep my kernel (4.4.0) pretty old because of it, though I'll finally be updating in a month or so).

As I side note to the valve people, Steam really really should run fine on a modern MESA software pipeline (if a bit slow), if it doesn't then steam probably isn't following the OpenGL spec properly as the software pipeline requires it to be used *very* properly, though that still wouldn't cause `libGL error: unable to load driver: swrast_dri.so` to happen I would think...

**Comment by Liger0** [comment]
@zer0def thank you for the interest.

- (https://github.com/ValveSoftware/steam-for-linux/files/2174218/1.grep.mesa.txt)
- 
```
name@name-SVE1511W1ESI:~$ xrandr --listproviders | sed -n '/^Provider /{s/^Provider \([0-9]\+\): .*/\1/p}' | xargs -n1 -I'{}' -- /bin/sh -c 'DRI_PRIME={} glxinfo | grep Device'
    Device: llvmpipe (LLVM 6.0, 256 bits) (0xffffffff)
```

**Comment by zer0def** [comment]
Based on the last output, the system only sees one GPU and defaults to the software rendering pipeline, the former of which is unexpected, as it doesn't provide any additional information.

**If** the integrated GPU is in fact driving the display (and apparently there's a driver missing for it), it could mean the dGPU is already disabled (either in BIOS/UEFI or through ACPI using `acpi-call`). For the record, `fglrx` used to implicitly make the disabling ACPI call whenever the discrete GPU was switched off in options, but this isn't the case with `radeon`.

There's also the case of iGPU not being used at all, which would be even more puzzling.

At this point, there's too much guesswork, so I hope these pointers will help you (or whoever ends up following up to help) in resolving this issue.

**Comment by Dondor17** [comment]
`(steam:7360): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Mint-Y-Dark/gtk-2.0/main.rc:1085: error: unexpected identifier `direction', expected character `}'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
crash_20180710113817_1.dmp[7375]: Uploading dump (out-of-process)
/tmp/dumps/crash_20180710113817_1.dmp
./steam.sh: line 876:  7360 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
`

Same situation here with LinuxMint 19 and NVIDIA 390.67 drivers (GTX760).

**Comment by kisak-valve** [comment]
Hello @Dondor17, no, you are not seeing the same situation as this issue report. The nvidia driver install on your system is most likely missing 32 bit opengl support.

Maybe confirm you have `libc6:i386` and reinstall the nvidia driver?

**Comment by kisak-valve** [comment]
Hello @Liger0, are you still experiencing this issue on an up to date system?

**Comment by Liger0** [comment]
That hardware is dead, so not an issue anymore.
