### ISSUE TITLE
generic controller doesn't work on dying light anymore

### ISSUE THREAD

**Issue by aquiles23** [ValveSoftware/steam-for-linux#5596]
#### Your system information

* Steam client version (24/07/2018): 
* Distribution (Linux mint 18.3): 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
after steam client update in 24/07/2018 my generic controller stops working in dying light,in others steam games my generic controller still works.
i post the bug on the community topic of the game too: https://steamcommunity.com/app/239140/discussions/0/604941528488544773/?ctp=306

#### Steps for reproducing this issue:

1. just open dying light
2. the buttons of the controller doesn't gonna show a response.

**Comment by anxest** [comment]
Steam client version: steam-runtime-beta-release_2018-06-14
    Distribution: Arch Linux 64b (Kernel 4.17.10-1-Arch)
    Opted into Steam client beta?: No (but tried in beta, the issue is still there)
    Have you checked for system updates?: Yes

Hello, I have kind of the same problem, not sure I should create another ticket or if it's the same issue as here : I was using xboxdrv configured for a ps2 pad, that worked well until last week. 
I tried several games (SteamWorld Dig, The End is Nigh, Shovel Knight), none of them was working while using xboxdrv. The games offering support for ps2 pad will work without xboxdrv, depending on the quality of the support though, which doesn't satisfy me.
I've tried to configure xboxdrv with a pro switch controller, but the issue is the same.
Finally, I've plugged in my xbox360 controller and tried to play to those games without using xboxdrv, worked on Shovel Knight and The End is Nigh (both supports xbox 360 controller) but not in SteamWorld Dig (which doesn't support it).

Hope those info can help.

**Comment by S2-** [comment]
Same issue here. I tried with the steam controller and with the ps3 dualshock: with both I have the same problem: if i press a button or move the sticks, I can hear the steam user interface sound "swoosh" that gets played when you switch in the menu items, but in the game nothing happens.

**Comment by aquiles23** [comment]
the problems i had with my PS2 generic controllers are now gone in most of the games that i had this issue.
thanks.
