### ISSUE TITLE
Steam Chat issue

### ISSUE THREAD

**Issue by armangido** [ValveSoftware/steam-for-linux#5612]
#### Your system information

* Steam client version (build number or date): Aug 1, 2018
* Distribution (e.g. Ubuntu): ParrotOS(Kali Linux
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

The issue everytime I login on steam then it will say "Friends Network Unreachable
Screenshot:https://prnt.sc/kg5xvg (I can't upload here)

System Ver: 4.16.0-parrot16-amd64
Add:Linux parrot 4.16.0-parrot16-amd64 #1 SMP Parrot 4.16.16-2parrot16 (2018-07-08) x86_64 GNU/Linux
I contacted steam support already for this they recommend posting here.

**Comment by johndrinkwater** [comment]
Held off updating Steam because the beta client had this issue and Ti8 was just around the corner, however now updating into the latest beta shows it still remains.

Not only does friends network never get reachable, it breaks dota2
 
![20180826123045_1](https://user-images.githubusercontent.com/7708/44627826-102b7380-a924-11e8-8de3-103fe1ffbc8b.jpg)

Using steam runtime with a [pinned lib fix here for libnss](https://github.com/ValveSoftware/steam-for-linux/issues/5311#issuecomment-355162907), nothing obviously appears in logs for why this fails. No software firewall is running.

**Comment by kgdowner** [comment]
I'm getting this as well. Just installed a new system, and the chat will not connect. Running steam with `steam -nochatui -nofriendsui` works to bring back the old friends list, which connects fine, just stops me from using any of the new chat features. Bug is there in both beta and non-beta steam.

#### Your system information

* Steam client version (build number or date): 1533766730, Aug 8 2018, at 21:32:49
* Distribution (e.g. Ubuntu): Void Linux x86_64 Linux 4.17.18_1
* Opted into Steam client beta?: [Yes/No] both
* Have you checked for system updates?: [Yes/No] yes

**Comment by johndrinkwater** [comment]
Can you both share your TZ setting?

Had added the below code to my environment to resolve a Firefox bug that was triggering during early multiprocess work; setting to `TZ=Europe/London` resolved this issue for me.

```
# make our system stop stat-ing https://blog.packagecloud.io/eng/2017/02/21/set-environment-variable-save-thousands-of-system-calls/
export TZ=":/etc/localtime"  
```

**Comment by kgdowner** [comment]
Alright, got some spare time and did some more testing.
I didn't have TZ set on my system (although that was a good read, I'll probably set that now), however looking into my time zone was exactly what I needed. I had setup the system to use posix/US/Pacific, and setting it to just US/Pacific fixed the chat connection.

**Comment by majcherek2048** [comment]
Thank you @kgdowner !
The old version works just fine here as well, whereas the new one was broken in the latest non-beta release here. Steam API: v018, Built: Sep 8 2018 at 19:21:25

For reference, I'm using family mode here (which I unlock on my own PC) in case the issue is related to this.
As a bouns the client seems to be much more responsive again, now that I'm using these flags.

**Comment by Anonymous1157** [comment]
I had `TZ=:/etc/localtime` on my system and starting steam with `TZ=America/New_York` made the new Friends interface work. Thanks everyone in this thread for a simple workaround!

**Comment by Israphel** [comment]
I exectuted:

export TZ=America/Argentina/Buenos_Aires

and still the chat won't work. Am I missing something?

**Comment by Kreyren** [comment]
Same issue on bedrock linux
![image](https://user-images.githubusercontent.com/11302521/55369440-dabcb900-54f6-11e9-8bf2-1bde809e1684.png)

```
kreyren@dreamon ~ $ locale
LANG=en_CA.UTF8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

Using steam from gentoo.
http://dpaste.com/1VK19F3
