### ISSUE TITLE
SteamOS - no settings option to toggle "try with all games"

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/steam-for-linux#5631]
Issue transferred from https://github.com/ValveSoftware/Proton/issues/14.
@mtdeguzis posted on 2018-08-22T01:20:46:

Tested a few games from the list, and many many thanks! I saw you could enable the option to allow Proton to work with any game, even if not on the approved list (say you wanted to test one out). Is this possible to toggle on SteamOS?

![image](https://user-images.githubusercontent.com/27829577/44437355-ea9b1480-a587-11e8-954e-7857e1f7a1db.png)

```
Q: Can I try a game with Proton even if it's not marked as compatible?

Yes; head to the Steam Play options of your Steam Client and you'll be able to enable it for all games.
```

https://steamcommunity.com/games/221410/announcements/detail/1696055855739350561 posted at 
***
@mtdeguzis commented on 2018-08-22T01:27:07

As a work around:

1. Power > Exit to Desktop (enable in settings)
2. Open terminal
3. sudo -i -u steam
4. Kill and start steam again
```
pkill steam
steam
```
5. Enable the option in settings menu, per the above.
6. restart system or click "return to steam" from the desktop.

**Comment by flibitijibibo** [comment]
I think I found another way that can be done without using the desktop mode: In config/config.vdf you can add this to the bottom of the `Software/Valve/Steam` section:

```
				"Tools"
				{
					"enable"		"1"
				}
				"ToolMapping"
				{
					"0"
					{
						"name"		"proton_37"
						"config"		""
						"Priority"		"75"
					}
				}
```

Could be totally wrong, but it was the only mention of proton I saw when enabling this on my desktop.

**Comment by buckysrevenge** [comment]
I can confirm that editing the config.vdf directly and adding these lines works for me.

**Comment by JoneKone** [comment]
Ok, this issue is kinda related to my issue. So in some Edge cases namely Arma3 in my case had 2 different versions of game in steam Win and Linux, as the Linux version is behind in development and Win version of the game is newer version, I would want a way to choose in Linux steam to actually download the Win version of the game and maybe in the future it would be compatible with Proton and I could play true proton the Win version of Arma3 On Linux

So a toggle in game Properties to switch from Linux version to win version, maybe even a tab in the properties titled SteamForLinux

**Comment by pierrep** [comment]
I still prefer @mtdeguzis 's solution as it's much easier to select proton versions in the gui instead of remembering the version name as a string. However I needed to type 
`steam -nobigpicture`
in order to change the settings, otherwise it would go straight to BPM and then trying to exit that would cause steam to hang.

**Comment by dragonfly-lover** [comment]
anyway these is an important feature request for steamos.

**Comment by kisak-valve** [comment]
Global and per-game Proton settings in Big Picture Mode implemented in the [2019-03-06](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1798531141142819058) Steam client beta update.

**Comment by mtdeguzis** [comment]
Dude!!! can't watch to try this out the. Thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by buckysrevenge** [comment]
I can confirm the new UI is in BPM and appears to function properly

**Comment by kisak-valve** [comment]
Closing per "Added Steam Play configuration settings in Big Picture Mode" in the [2019-04-17](https://store.steampowered.com/news/50095/) Steam client update.
