### ISSUE TITLE
Torchlight 2 shipping version of libfontconfig.so.1 conflicts with Steam runtime

### ISSUE THREAD

**Issue by nanonyme** [ValveSoftware/steam-for-linux#5690]
#### Your system information

* Steam client version (build number or date): 
Current

* Distribution (e.g. Ubuntu): 
Flatpak'd Steam using Freedesktop runtime 18.08
* Opted into Steam client beta?: [Yes/No]
No
* Have you checked for system updates?: [Yes/No]
Yes

#### Please describe your issue in as much detail as possible:
Torchlight 2 should not be providing old version of library that Steam runtime ships and then setting LD_LIBRARY_PATH so that Steam runtime one is ignored.

#### Steps for reproducing this issue:

1. Run Torchlight 2
2. Observe crash
See https://github.com/flathub/com.valvesoftware.Steam/issues/95

**Comment by nanonyme** [comment]
Can you please advice what is the right place to make an official bug report against the game?

**Comment by kisak-valve** [comment]
https://www.runicgames.com/contact/ looks like a good starting place.

**Comment by nanonyme** [comment]
Looks like I'll be be sending an email then as Runic Games' support system has been shut down due to the account with their service provider having been cancelled. Thanks.

**Comment by nanonyme** [comment]
Never mind. Runic Games is defunct since 2017. https://en.wikipedia.org/wiki/Runic_Games
Reports say simply deleting file from their installation directory is enough to fix the crash.

**Comment by smcv** [comment]
> and then setting LD_LIBRARY_PATH so that Steam runtime one is ignored.

Strictly speaking it's a `DT_RPATH` ELF header, which is worse, because it takes precedence over `LD_LIBRARY_PATH`.

This bug is likely to appear in any environment where Fontconfig 2.13rc3+ was compiled after Freetype 2.9.1+. By pure luck, this doesn't include Debian 10 (where the latest version of Fontconfig was compiled 16 days before Freetype was upgraded to 2.9.1+), but it will start to be a problem in Debian 10 as soon as there is a security update for Fontconfig. Other recent distributions will either have this bug already, or gain it next time their Fontconfig is rebuilt.

**Comment by nanonyme** [comment]
@kisak-valve note that it's likely to be broken in generic on all Linux systems using native Steam client. We're finally almost ready to deploy a workaround into Flatpak Steam to allow us to start squishing quirks like this.

**Comment by nanonyme** [comment]
I'm closing this as pointless. The game works in Flatpak Steam and will never be fixed by game vendor because there's no one left to fix it.
