### ISSUE TITLE
Soft-linking to pre-downloaded game not works?

### ISSUE THREAD

**Issue by kisak-valve** [ValveSoftware/steam-for-linux#5693]
Issue transferred from https://github.com/ValveSoftware/Proton/issues/780.
@ssv-170379 posted on 2018-08-27T21:26:39:

(Sorry for bad English) The Evil Within 2. Created a soft-link to a folder with pre-downloaded game (from another Steam installation) in ~/.steam/steam/steamapps/common/ . When installing via Proton it checks for existing files for a moment but immediately starts to re-download the whole game, and finally fails to extract files to that linked folder (in passing ruining existing there installation). And only after removing soft link game files are deploying normally. But when installation is finished you may to move TheEvilWithin2 folder to other partition, create soft-link and play the game. i.e. soft-linking works correctly except the installation process.

**Comment by ssv-170379** [comment]
This is what I usually did before Proton was released. Wine + Steam for Windows + soft-linked 'steamapps' folder.
But with Steam for Linux + Proton I can't link whole 'steamapps' from Windows, because I have some native games installed, nor I can't pick pre-installed game folder itself, because Steam/Proton demands empty(!) folder when selecting custom.
So (in OP) I tried to link installed game folder to default '~/.steam/steam/steamapps/common/' folder, but without luck.
Just now I also tried to create empty folder and soft-link installed game there. Same result, it just re-downloads everything, ruining existing files in process.
Is there any way to make Steam believe that particular game is alreay installed, and theres's no need to download it, maybe ini-file or something?

**Comment by ssv-170379** [comment]
> Is there any way to make Steam believe that particular game is alreay installed, and theres's no need to download it, maybe ini-file or something?
---
Answering myself: Yes! Seems all we need is to copy 'appmanifest_%appid%.acf' to '~/.steam/steam/steamapps/' (one level above 'common' folder). For example to run Wreckfest with Proton we need soft-link 'Bugbear Entertainment' folder into '~/.steam/steam/steamapps/common/' and copy 'appmanifest_228380.acf' file to '~/.steam/steam/steamapps/'
---
Considering problem solved, though in a somewhat unnatural way.

**Comment by ssv-170379** [comment]
> Is there any way to make Steam believe that particular game is alreay installed, and theres's no need to download it, maybe ini-file or something?
===
Answering myself: Yes! Seems all we need is to copy 'appmanifest_%appid%.acf' to '\~/.steam/steam/steamapps/' (one level above 'common' folder). For example to run Wreckfest with Proton we need soft-link 'Bugbear Entertainment' folder into '\~/.steam/steam/steamapps/common/' and copy 'appmanifest_228380.acf' file to '\~/.steam/steam/steamapps/'
===
Considering problem solved, though in a somewhat unnatural way.

**Comment by kisak-valve** [comment]
Closing per the last comment. In general, sharing a Steam library between Windows and Linux is not supported and this is a rather odd way to mingle two Steam installs.
