### ISSUE TITLE
Update all queued instead of start immediately

### ISSUE THREAD

**Issue by legluondunet** [ValveSoftware/steam-for-linux#5703]
Hello, when I start Steam, update all queued instead of start immediately.
As you can see on this picture, on the downloads parameters, queued downloads are not activated. 

![capture d ecran de 2018-08-29 20-44-41](https://user-images.githubusercontent.com/325405/44808420-8225e600-abcc-11e8-9074-9457687ac4ea.png)

Thank you for your help.

my config:
https://gist.github.com/legluondunet/0f0a56fb4e9cb743f111385e554fce69

**Comment by kisak-valve** [comment]
Hello @legluondunet, I know there's something being lost in translation here, however, there is no setting to switch between queuing updates and immediate downloads.

I think you're referring to the option to restrict what hours steam should use for updates, and that is not expected to have an effect on the download queue, which reduces surges on Steam's CDN. As the load spreading is not likely to change in the near future, I'm going to close this issue instead of leaving it as an unanswered feature request.

**Comment by legluondunet** [comment]
@kisak-valve as you can see on this picture, all games autoupdated but "The Witcher:Enhanced Edition" sheduled tomorrow??? I don't understand why this game doesn't update now?

![capture d ecran de 2018-08-30 07-53-06](https://user-images.githubusercontent.com/325405/44832399-1161e680-ac2b-11e8-9960-61f2b6175e75.png)
