### ISSUE TITLE
CS:GO , blacksite issue. Game crashing when landing zone is seto to shipyard roof or near it. 

### ISSUE THREAD

**Issue by zzx999** [ValveSoftware/steam-for-linux#5981]
#### Your system information

* Steam client version (build number or date):  nov 26
* Distribution (e.g. Ubuntu):  xubuntu 18.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
CS:GO , blacksite issue. Game crashing when landing zone is seto to shipyard roof or near it. 
When game is about to start to drop you in the game (sceen is whitening) it just crashes. 
That only happens if landing is set on or near the shipyard. Otherwise everything always works well. 
Other games not crashing. Otherwise everything works perfectly normal and fine with CSGO and darkzone.
Except with this one.

Cache cleared. Did not help.
Game reinstalled. Did not help.

#### Steps for reproducing this issue:

1.  Play Darkzone blacksite. 
2. Set landing point on shipyard roof.
3. Wait till match begins.

**Comment by kisak-valve** [comment]
Hello @zzx999, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1908. Please use the [csgo-osx-linux](https://github.com/ValveSoftware/csgo-osx-linux) issue tracker for CS:GO issues. You may be able to avoid this issue by setting shader quality to medium or lower.

Closing as a duplicate.
