### ISSUE TITLE
Wolfenstein: The New Order - working fine until 2 weeks ago, now won't start: "Invalid Platform" 

### ISSUE THREAD

**Issue by GH-A-CC** [ValveSoftware/steam-for-linux#6084]
![screenshot_2019-02-09_13-30-40](https://user-images.githubusercontent.com/47477239/52521449-31341680-2c6f-11e9-9d74-966342ade13a.png)
# Compatibility Report
- Name of the game with compatibility issues: **Wolfenstein:The New Order**
- Steam AppID of the game: **201810**

## System Information
- GPU: GTX 1080
- Driver/LLVM version: Nvida 410.93
- Kernel version: 4.20.5-200.fc29.x86_64
- Proton version: 3.16

Everything was working _flawlessly_ until a two weeks ago - now there is no "Play Game" button in the Steam UI, and when I right click and click "Play Game" there is an error ..."An error occurred updating Wolfenstein:  The New Order (invalid platform)".

This problem happened after a Steam Update as far as I can tell, not any game update.

Steam support have directed me here.

## Symptoms 
See Above

## Reproduction
Load Steam.
Right Click on Game
Click "Play Game..."

https://gist.github.com/GH-A-CC/2e1a8fe386e74f6b8891b456f37a6399

**Comment by kisak-valve** [comment]
Hello @GH-A-CC, this sounds like there is no Proton version select either via the global override or per-game settings and when it stopped working lines up with "Fixed an issue with invalid Steam Play tool selections if user had previously opted in to enable Steam Play for all titles. (Note: this will cause a one-time reset of all Steam Play global and per-app selections to the default state)." in the [2019-01-18](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1703951108833155107) Steam client beta update.

Transferred to the steam-for-linux issue tracker because this message is coming from Steam, not Proton.

**Comment by GH-A-CC** [comment]
I can confirm this does indeed resolve the problem (I.e. "Settings -> Steam Play -> [X] Enable Steam Play for all Other Titles" + choosing "Proton 3.16"  from drop-down menu.).

I'm not sure if there is a better way to communicate this kind of thing in future - perhaps a sticky topic in the 'Steam for Linux' forum for common issues or generic "Steam on Linux" support article on Steam's Support pages.  Then again, perhaps everyone else figured it out and its just me who missed this!
