### ISSUE TITLE
Couldn't set up Steam data - please contact technical support

### ISSUE THREAD

**Issue by gituser823** [ValveSoftware/steam-for-linux#6094]
#### Your system information

* Steam client version (build number or date): steam:i386 (1:1.0.0.54+repack-5ubuntu1)
* Distribution (e.g. Ubuntu): Linux Mint 19.1
* Opted into Steam client beta?: [Yes/No] Yes (in Windows Client)
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I expect steam to open, it doesn't. Instead I get the Errormessage.

#### Steps for reproducing this issue:

1. Install Steam via apt-get install steam or download the *.deb and isntall with gdebi.

When I run "steam" it says
Running Steam on linuxmint 19.1 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!

but the Client does not open.

**Comment by kisak-valve** [comment]
Hello @gituser823, please confirm that any 32 bit opengl application like `glxinfo` from `mesa-utils:i386` works.

Which package are you currently trying to get working?

Did you purge the previous package before trying the other?

`steam --reset` should make steam act like it's being run for the first time, but if that doesn't make a difference, you can try to move/remove `~/.steam` and `~/.local/share/Steam`.

**Comment by gituser823** [comment]
glxinfo and glxgears work fine.
at the moment I have installed the package from ubuntus sources via apt-get install steam.
Yes, I already tried steam --reset, it doesn't help.

I have now removed the package, removed  ~/.steam and ~/.local/share/Steam, but I am still getting the same error, when I try to launch it.

**Comment by JesseTG** [comment]
I also have this issue.

**Comment by AydievMansur** [comment]
Guys try it 
```
cd ~
rm -rf .steam
```
start steam & Enjoy :+1:

**Comment by Rene2LeLorrain** [comment]
It seems I made a big mistake ... To install a new SSD nvme card for my OS, i move all my games to a new SATA III SSD since I did not have enough room on the nvme to have every thing I had on the old HDD.

Since I have Linux, I put in my home directory a logical pointer to the .steam directory on the other drive ( see attached file), now my problem:

When I try to start the program /usr/bin/steam, I get this error message "Couldn't set up Steam data - please contact technical support". I re-installed the Steam Client but I get the same message! Everything worked fine before, including SteamPlay...

Can you help me? I would not want to have to re-install all my games...

RD

System:
M.B.: Asus TUFF Gaming z390-Pro
CPU: Intel i7-8700 @ 4.3Ghz
RAM: 16GB PC3600
GPU: nVidia GTX 
[directory  of steam.txt](https://github.com/ValveSoftware/steam-for-linux/files/3299531/directory.of.steam.txt)
1070ti
O/S  : Ubuntu 18.04.2

**Comment by kisak-valve** [comment]
Hello @gituser823, are you still experiencing this issue on an up to date system?

Unfortunately, it's not really clear how Steam's bootstrap failed here, and the opening post reads more like what happens when you're using the nVidia proprietary driver, and recently updated the video driver version without rebooting. In that case the running nVidia kernel module isn't the same version as the userspace libraries and OpenGL applications can hang waiting on the video driver like that.

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by Hicks79** [comment]
> Guys try it
> 
> ```
> cd ~
> rm -rf .steam
> ```
> 
> start steam & Enjoy 👍

Thanks so much!

I turned on the computer and when I opened steam I didn't see any game (steam/steamapps folder empty).

I restarted. And then when running steam I got an error "Couldn't set up Steam data - please contact technical support" deleting this folder, steam runs the correct folder.

**Comment by laustoic** [comment]
> Guys try it
> 
> ```
> cd ~
> rm -rf .steam
> ```
> 
> start steam & Enjoy 👍

thank you, it worked on arch
