### ISSUE TITLE
Installing free weekend games via Proton

### ISSUE THREAD

**Issue by supagu** [ValveSoftware/steam-for-linux#6115]
I tried installing a game having a free weekend (https://store.steampowered.com/app/548430/Deep_Rock_Galactic/) and it says it wasn't for my platform - there was no way for me to try using Proton.

**Comment by kisak-valve** [comment]
Hello @supagu, Proton needs to be enabled for all titles because that game has not been whitelisted.

`Steam` -> `Settings` -> `Steam Play` -> Check `Enable Steam Play for all other titles` -> Hit `OK` and restart steam -> Install the game

**Comment by supagu** [comment]
Thank you!!!!
Can we maybe get a link on the error message about not being available to take the user to the settings or indicate its an option there? Might save some others some pain there.

**Comment by authentictech** [comment]
I found this problem with Free to Play games also (e.g. Cry of Fear). The same solution as [above](#issuecomment-468468393).

I think it would help to update the Steam UI because before I changed the setting, I could not play this game but did not know how to fix it. The Cry of Fear store page said the game was already in my Library but it did not show up in my Library. When I clicked "Play game" on the Store page I was told the game was incompatible. However, I could not make the game use the Proton compatibility tools because I thought we could only add the compatibility tools via the Library screen. The message that told me the game was incompatible could be updated to say "You can play this game with compatibility tools by changing the settings at ..." (as described above). OR the Steam Library UI could be changed, now that Proton exists, so that Free to Play games do show up in the Library even if they are Windows only.

Anyway, thanks for showing how it could be done.
