### ISSUE TITLE
steam controller on screen keyboard freezes steam

### ISSUE THREAD

**Issue by raenii** [ValveSoftware/steam-for-linux#6159]
#### Your system information

* Steam client version (build number or date): feb 18 2019, 22:09:18
* Distribution (e.g. Ubuntu): solus 4.0
* Opted into Steam client beta?: no
* Have you checked for system updates?: yes

#### Please describe your issue in as much detail as possible:
what i expected to happen was to open the steam controller keyboard and type "youtube.com" into firefox. what happened was the keyboard window froze after pressing "y" and my controller stopped functioning. restarting steam was the only way to keep using my controller.

#### Steps for reproducing this issue:

1. be on the desktop
2. open the steam controller keyboard
3. enter text

**Comment by fishears** [comment]
I have exactly the same issue. I'm using Manjaro Gnome. Also the OSK fills my screen which looks terrible. The only situation I have found where the OSK works as expected on the desktop is when entering my password on a policykit authorisation window.

**Comment by KaryotypeB** [comment]
I have this issue as well, on Arch with KDE Plasma and Nvidia 418.49.04. Same thing, On-Screen Keyboard opens normally, but once I select a letter, it stops responding and leaves my Steam Controller unusable in a normal way. I say "in a normal way" because using the Steam button chording still works. If I start a game (I used Hollow Knight) after I close the OSK because it stops responding, the Big Picture overlay will load for the game instead of the normal Steam overlay, and the controller will still be unusable. Once I close the game, Big Picture mode will load but it'll be blank (Big Picture background but nothing on it). Once I close that, the controller will function as normal, and running the game again will load the regular Steam Overlay. Hope this helps.

**Comment by Managor** [comment]
I believe this issue can be closed now because the OSK no longer steals focus and it stays on top of the stacking order.

**Comment by kisak-valve** [comment]
Closing per the last comment.
