### ISSUE TITLE
Latest Beta Client - Issues with Browser sections and Friends

### ISSUE THREAD

**Issue by dan-dr** [ValveSoftware/steam-for-linux#6278]
#### Your system information

* Steam client version (build number or date): Not sure, should be latest but I opted out to get a working version.
* Distribution (e.g. Ubuntu): Solus Linux
* Opted into Steam client beta?: [Yes/No] Yes when the bug occured.
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When opening Steam, the browser based sections such as store and community are blacked out, I seem as "Offline" in my friend list, without the ability to go online.

When I open steam through the terminal, I see these repeated errors:
```
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
./steamwebhelper: symbol lookup error: /usr/lib/libpangocairo-1.0.so.0: undefined symbol: pango_renderer_get_alpha
```
I have these packages installed for work: https://github.com/Automattic/node-canvas/wiki/Installation:-Solus

#### Steps for reproducing this issue:

1. Open steam

**Comment by TTimo** [comment]
Hey @dan-dr,

You may want to report this issue at https://github.com/solus-project/linux-steam-integration and work through it with the Solus developers.

Our recommendation is that all distributions should at least have a way to run Steam in "Genuine Steam" mode where the Steam Client binary (and all the games) are run within the Steam Runtime and using all official unmodified scripts to setup library pinning and related things.

Without this, we cannot ascertain if a problem lies with Steam on Linux or with the distribution modifications, which means we get fewer chances to identify and fix issues on our end.

Looking at your error, it looks like Solus does not support the new `steamrt:heavy` runtime that we are using for the `steamwebhelper` process. It should be using `/.local/share/Steam/ubuntu12_64/steam-runtime-heavy/libpangocairo-1.0.so.0` rather than the host's.

Here is more information about `steamrt:heavy`: http://repo.steampowered.com/steamrt/steamrt-heavy/snapshots/

**Comment by kisak-valve** [comment]
Closing pending feedback.
