### ISSUE TITLE
Steam not working at all on Ubuntu MATE 18.04

### ISSUE THREAD

**Issue by NathSoM** [ValveSoftware/steam-for-linux#6298]
#### Your system information

* Steam client version : I don't know how to check, it's the one from the Software Boutique in the Welcome menu (as of 1/6/2019 in case they update it)
* Distribution : Ubuntu MATE 18.04 (LTS)
* Opted into Steam client beta?: No
* Have you checked for system updates?: No

#### Please describe your issue in as much detail as possible:
When I installed Steam on my system, I expected it to work, but the 1st time I tried, it gave me the "Updating Steam" dialog box, but it never started, then the 2nd, 3rd and 4th times I reinstalled it, it gave a "Steam error- contact techincal support" error and now it doesnt even start or give me an error.

#### Steps for reproducing this issue:
1. Install Ubuntu MATE 18.04 (I have it as a dual boot with Windows 10, but I don't know if it affects anything.)
2. Install Steam from the software boutique
3. Reinstalling it multiple times as it doesn't work the 1st time will cause the problem I had.

**Comment by kisak-valve** [comment]
Hello @NathSoM, does does `~/.steam/error.log` have any hints? Does any 32 bit opengl application like `glxinfo` from `mesa-utils:i386` work?

**Comment by NathSoM** [comment]
Hi, I can't find ~/.steam/error.log and glxinfo seems to work, I just ran it in the Teminal, but I don't know if it's the 32bit or 64bit version.

**Comment by kisak-valve** [comment]
`apt policy mesa-utils:i386` should tell you if you if `glxinfo` which is installed is the 32 bit variant.

What video card / driver version are you using?

**Comment by NathSoM** [comment]
![image](https://user-images.githubusercontent.com/49078943/58749492-57ccc600-8487-11e9-88dc-18f609329ead.png)

This is what I get when i run apt policy mesa-utils:i386. I'm using an Nvidia Geforce 810M and the driver is this thing: 
![image](https://user-images.githubusercontent.com/49078943/58749530-ae3a0480-8487-11e9-84f0-ba9786bcd939.png)

Hope this helps, because I only recently switched to Ubuntu and don't really know stuff like what the output of apt policy mesa-utils:i386 means.

**Comment by kisak-valve** [comment]
`Installed: none`, tells you that the 64 bit `mesa-utils` is installed, so it gave you misleading feedback earlier.

Check if you have `libnvidia-gl-390:i386` with apt policy and install it with `sudo apt install libnvidia-gl-390:i386` to get nvidia's 32 bit userspace support for that driver series. If apt wants to uninstall a bunch of packages, don't let it proceed.

**Comment by NathSoM** [comment]
It looks like I apparently have it: 
![image](https://user-images.githubusercontent.com/49078943/58750775-9ae26580-8496-11e9-8226-3133e78baa9a.png)

**Comment by kisak-valve** [comment]
What does `glxinfo -B | grep Device` output? Can you also check if you have `libgl1-mesa-dri:i386`?

**Comment by NathSoM** [comment]
It doesn't output anything: 
![image](https://user-images.githubusercontent.com/49078943/58750906-15f84b80-8498-11e9-968b-e83e6a3192ed.png)

And I have lbgl1-mesa-dri:i386 : 
![image](https://user-images.githubusercontent.com/49078943/58750916-3fb17280-8498-11e9-9e99-618632d232a6.png)

**Comment by kisak-valve** [comment]
Thanks for checking mesa, maybe `glxinfo | grep OpenGL\ vendor` will tell us if the system is using the Intel or nVidia chipset. The distro-provided steam package can have a harder time setting up Steam on systems using mesa.

My current line of thought is that you're running on an Optimus laptop and the distro-provided Steam package is giving you trouble with the Steam runtime. Without a log, it's hard to tell, but Steam needs to successfully run once for it to setup the Steam runtime for it to continue to work as expected.

The [Valve-provided Steam package](https://store.steampowered.com/about/) has improved behavior around this compared to the distro-provided steam package. To use this you'd need to `apt purge steam` to remove the distro-provided variant, move/remove `~/.steam`, then download and install the package from Valve's website. This will setup steam in `~/.local/share/Steam` with some legacy and convenience paths in `~/.steam`.

Alternatively, you can try some of the workarounds at #4768 to try to get Steam to run for the first time, if that's what the issue is, then the workaround will only be needed once.

**Comment by NathSoM** [comment]
WAIT I REALIZED THAT I DIDNT TYPE ~ WHEN RUNNING CD

HERES THE LOG: 
[bootstrap_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/3243982/bootstrap_log.txt)

**Comment by NathSoM** [comment]
If its the wrong sorry, this is the only one that exists

**Comment by NathSoM** [comment]
Back to what you asked me to run, heres the output. 
![image](https://user-images.githubusercontent.com/49078943/58751172-7341cc00-849b-11e9-9a3f-45679f225098.png)

**Comment by NathSoM** [comment]
Finally got it to work, thanks. I'll now close this thread.
