### ISSUE TITLE
steamwebhelper heavy graphical glitches

### ISSUE THREAD

**Issue by omgitsaheadcrab** [ValveSoftware/steam-for-linux#6304]
#### Your system information

* Steam client version (build number or date): May 22, 1558567098
* Distribution (e.g. Ubuntu): Arch 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* System Information gist: https://gist.github.com/omgitsaheadcrab/c315499647b39894ce21e9621d4ab8e4

#### Please describe your issue in as much detail as possible:
steamwebhelper displays heavy graphical glitches when using steam-runtime.
Video of issue: https://youtu.be/m5nWMxzvB74

steamwebhelper in steam-native also fails due to (known) libpcre.so.3 error, so can't use this instead.

#### Steps for reproducing this issue:

1. Launch steam-runtime
2. View store, community or use overlay browser.

**Comment by kisak-valve** [comment]
Hello @omgitsaheadcrab, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by Myrddin-Wyllt** [comment]
Mesa 19.0.5:
https://bugs.freedesktop.org/show_bug.cgi?id=110721
https://github.com/void-linux/void-packages/issues/11907
https://bbs.archlinux.org/viewtopic.php?id=246621
https://www.reddit.com/r/archlinux/comments/bsfk1m/latest_mesa_1905_is_making_some_apps_glitch/

Fixed in Mesa-git:
https://cgit.freedesktop.org/mesa/mesa/commit/?id=12bf7cfecf52083c484602f971738475edfe497e

**Comment by omgitsaheadcrab** [comment]
Downgraded and it works. Will hold off from updating Mesa until its next release as switching to mesa-git involves moving to testing. Thanks!
