### ISSUE TITLE
Dota 2 with VULKAN won't start if the Steam Shader Pre-Caching is active.

### ISSUE THREAD

**Issue by MeGA-ct** [ValveSoftware/steam-for-linux#6322]
#### Your system information

* Steam client version (build number or date): Jun 16 2019 22:11:07
* Distribution (e.g. Ubuntu): Ubuntu 19.04 (64 bits) kernel: 5.0.0-16-generic
* Opted into Steam client beta?: [Yes/No] YES
* Have you checked for system updates?: [Yes/No] YES

#### Please describe your issue in as much detail as possible:
The game process appears in the system monitor but the game window doesn't comes up.

#### Steps for reproducing this issue:

1. Activate Steam Shader Pre-Caching in preferences.
2. Go to Dota2 and try to run the game, with Vulkan Render API.
3. The process appears in the system monitor but no window shown.
4. Proceed terminate the game process from the system monitor.
![Captura de pantalla de 2019-06-17 23-24-39](https://user-images.githubusercontent.com/3133372/59638331-6807c500-9158-11e9-89d4-6b10f44e6fde.png)

**Comment by kisak-valve** [comment]
Hello @MeGA-ct, this issue is already being tracked at https://github.com/ValveSoftware/Dota-2-Vulkan/issues/311 / https://github.com/ValveSoftware/Dota-2/issues/1619.

You should be able to workaround this issue by adding `-vulkan_disable_steam_shader_cache` or `-gl` to the game's launch options while we wait for the next Dota 2 update.

Closing as a duplicate.
