### ISSUE TITLE
Steam is randomly deleting entire games after a check, and then fully redownloading them

### ISSUE THREAD

**Issue by Valmar33** [ValveSoftware/steam-for-linux#6383]
#### Your system information

* Steam client version: Jun 17 2019, at 23:31:27
* Distribution: Arch Linux 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

For no apparent reason, Steam decided that it would do a full check on both Bayonetta, and Grandia II Anniversary Edition, and then somehow find them 100% mismatched, requiring deleting all of the files, and redownloading many gigabytes of data.

#### Steps for reproducing this issue:

1. Start Steam...
2. Hope that it doesn't randomly delete your game files. O_o

Also, here's my content log:

[content_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/3385447/content_log.txt)

**Comment by dreamer** [comment]
Did you use some not official Proton version (like e.g. `proton-tkg` or other) or did you maybe remove some older Proton version from your Steam Library tools? I see similar issue and it's correlated to the compatibility tool rewriting its *.vdf file.

**Comment by Valmar33** [comment]
Hmmmm.

I do use custom Proton via https://github.com/Tk-Glitch/PKGBUILDS

So, deleting old Proton versions can cause Steam to think that game files are somehow corrupt?

**Comment by dreamer** [comment]
> So, deleting old Proton versions can cause Steam to think that game files are somehow corrupt?

Compatibility tool *.vdf file defines a mapping that informs Steam client which depots should be used to install/update the game. When using official Proton installed from within Steam this interaction seems to be polished and working correctly, but when an unofficial tool is used (or even Proton compiled locally), then Steam often gets confused about which depot should be used to run the game. Perhaps your earlier upgrades did not change the internal name of the compatibility tool in *.vdf file, so Steam client did not care to double check if depots changed.

**Comment by Valmar33** [comment]
Hmmmm.

Sounds like a bug I should report to the maintainer of proton-tkg, then.

**Comment by dreamer** [comment]
Mention me or link this issue, please - if proton-tkg maintainer will find better solution for this problem than me, then I would like to know ;) (I simply stopped including versions in the internal name of my tool, so Steam gets confused much less often).

**Comment by Valmar33** [comment]
Sure.

**Comment by Valmar33** [comment]
There's your link. :)

**Comment by Tk-Glitch** [comment]
I have reported that to Plagman a while ago. If a game is bound to a proton version and you delete it, it's as if proton wasn't installed and your game will get nuked.
The "uninstaller" I'm offering shouldn't be needed in a perfect world but currently the Steam client doesn't have a fallback mechanism for proton builds.
I have never faced an issue again since I have pushed the uninstaller **as long as I haven't tried to set a custom proton globally**. Setting it per-game has been trouble free.

I'll add a note to a readme somewhere about that specific setting one should definitely avoid, but I'm convinced something has to be done on the Steam side. I think there was another issue open already regarding this, but I can't find it.

**Comment by cj360** [comment]
Another +1 to change how steam interacts with config.vdf. Would prefer if it could have a popup notification upon a games's config.vdf being 'incorrect' and stop a game from launching rather than just wiping the entire game from my library and trying to force a re-download. Real big pain when this & denvuo can make a game unplayable because it's been 'activated' too many times.

**Comment by kisak-valve** [comment]
Hello, per "Fix race condition that could cause some Proton-enabled games to redownload" in the [2020-03-03](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1706240323209971343) Steam client beta update, please opt into Steam's beta and keep an eye out for this issue.

**Comment by kisak-valve** [comment]
Closing as fixed in the [2020-03-26](https://store.steampowered.com/news/59842/) steam client update.
