### ISSUE TITLE
Getting Steam to work on the 5700 XT

### ISSUE THREAD

**Issue by xHatchx** [ValveSoftware/steam-for-linux#6554]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Artix (basically arch with openrc)
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

I just can't get steam to even start on my 5700 XT. I set my drivers up using the arch wiki tutorial (https://wiki.archlinux.org/index.php/Navi_10).

#### Steps for reproducing this issue:

1. Start steam on a 5700 XT running artix
2. 
3.

Output:
https://gist.github.com/xHatchx/26a5036038d357fed2d1d294a18407ad

**Comment by kisak-valve** [comment]
Hello @xHatchx, just a hunch, but do you have a 30 bit display? What monitor model are you using? (#4399)

**Comment by Myrddin-Wyllt** [comment]
@xHatchx I've dabbled in Artix; they lacked a lib32-libelogind last I used it. I literally had to create the PKGBUILD for 32-bit libsystemd so that Steam would open. The last straw for me on Artix was [gamemode](https://github.com/FeralInteractive/gamemode) being nonfunctional without systemd. The frequent memory leaks gamemode caused on an openrc system are the main reason I'd recommend against this distribution for gaming.

I'm sorry I can't offer much help for your 5700XT driver issue, but I'd recommend trying with vanilla Arch or Manjaro to see if this is distribution related. Lastly, try the Steam beta; I doubt it'll help, but it can't hurt to try.

**Comment by xHatchx** [comment]
> Hello @xHatchx, just a hunch, but do you have a 30 bit display? What monitor model are you using? (#4399)

@kisak-valve 
Thanks for the swift reply! I'm, in fact, using a 30 bit/10 bpc monitor. It is a LG 27UD68-W 4K Monitor ([amazon link for specifications](https://www.amazon.com/LG-27UD68-W-27-Inch-Monitor-FreeSync/dp/B01C3BZIIC/ref=sr_1_1?keywords=LG+27UD68-W&qid=1570133355&sr=8-1)). But I had Steam running on my GTX 970 on Arch (not artix) with this monitor a while ago.

**Comment by xHatchx** [comment]
> lib32-libelogind

@Myrddin-Wyllt 

Yeah, artix seems a bit weird and buggy. I might jump the ship at this point. I originally installed it because I wanted to try something that wasn't systemd.

In regards to the steam beta, is there a way to install the steam beta without a running steam installation?

**Comment by kisak-valve** [comment]
Thanks, there's a good chance you've encountered #4399.

To test that hypothesis, you should be able to add `DefaultDepth 24` to a Screen section in your xorg.conf and restart the X session.

**Comment by xHatchx** [comment]
> Thanks, there's a good chance you've encountered #4399.
> 
> To test that hypothesis, you should be able to add `DefaultDepth 24` to a Screen section in your xorg.conf and restart the X session.

@kisak-valve 

Awesome! That worked for me! My previous gpu probably didn't run my monitor at 10bpc, so this is why it worked back then. Luckily, I don't need 30bit color. Thanks for your help!
