### ISSUE TITLE
[Beta] Chromium GnomeKeyring or KWallet Prompt on login

### ISSUE THREAD

**Issue by Leopard1907** [ValveSoftware/steam-for-linux#6585]
#### Your system information

* Steam client version (build number or date): Oct 11 2019
* Distribution (e.g. Ubuntu): Linux Mint 19.2
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

After that update Steam started to ask for password , which was not the normal behaviour of Steam client.

https://wiki.archlinux.org/index.php/Chromium/Tips_and_tricks#Force_a_password_store

#### Steps for reproducing this issue:

Literally booting the pc and opening Steam

**Comment by Leopard1907** [comment]
A little note for testing ; that issue won't be visible if you don't set your system to auto login. Which means ; no password prompt when booting the system.

**Comment by Skiski** [comment]
I can confirm I have the same problem since the last update.

**Comment by JAAdrian** [comment]
Same for me with Oct 15 built.
System: Linux Mint 19.2 with autologin for my account.

**Comment by Myrddin-Wyllt** [comment]
#### You have three choices to solve this in KDE:
1. Disable Kwallet altogether
#### OR
2. Disable autologin & setup kwallet-pam (i.e., kdewallet as default & same as user password)
#### OR
3. Set an empty Kwallet password

Autologin still doesn't open the kdewallet by default; this has been an issue for a few years now. It complains about an empty password.

**Comment by Leopard1907** [comment]
That is not really a good answer because that behaviour from Steam is new. It wasn't like it before and we simply we want it to behave like it was before.

**Comment by Myrddin-Wyllt** [comment]
@Leopard1907 I agree that Steam's current behavior is undesirable if your wallet isn't configured right, yet the problem lies in how wallets are unlocked. For instance, I have this issue when using samba for VLC; if I use autologin, kdewallet-pam, & set kdewallet to use my user password I will get the same prompt from Kwallet. kdewallet-pam won't unlock your wallet if autologin is enabled. 

**If wallet integration is a security measure**, I don't see Valve removing it. Is it Valve's fault autologin won't unlock kdewallet with PAM?

I'm just giving users options/instructions on how to make it behave like before. This is a general issue beyond Steam & that is what I'm pointing out.

**Comment by jazztickets** [comment]
Can we put a space or dash in the title between gnome and keyring? Searching for keyring doesn't show this issue, and the proper name is "GNOME Keyring" according to their website.

**Comment by Yorper** [comment]
This is a complete PITA. Please fix this ASAP Valve!

At least build in the option some how to pass "--password-store=basic" for the browser like you can do with regular chrome/chromium!

**Comment by paulovilli** [comment]
Linux Mint 19.2
Auto-login enabled
Steam Beta (latest update applied)
System Updates all applied (and Padoka Stable PPA, and Kernel 5.3.[latest ubuntu kernel offered by mint update manager])

For me the issue didn't start as soon as the new library came in, I believe it appeared in the update prior to the latest (don't recall the exact day, but I'm positive I first saw it come up in late november).

I have the same thing happening since forever when opening Chromium.

This needs further confirmation, but I believe the popup will only appear on the first time I open one of them and doesn't when I open the other later (eg: if I boot and then open Chromium it will ask me to unlock the keyring and if I do so, then opening Steam won't ask for it again)... meaning possibly the same keyring is in use and depending on user habits may mask the issue.

@Plagman was the use of the keyring enabled on purpose due to user security/privacy concerns inside the webhelper? If it was then there is basically nothing to fix on Steam, just an upstream nuissance to solve with keychain devs.
ps: I'm unaware of any proper rationale that would make it a security necessity to show the keychain popup for users that autologin, but suspect there might be one too.

**Comment by Philippe734** [comment]
The unlock keyring popup is very annoying when starting steam.

Easy to reproduce that issue, with any Ubuntu variants with autologin enabled.

**System information to reproduce that issue:**
Steam client version (build number or date): Oct 11 2019
Distribution: Ubuntu, Xubuntu, Ubuntu Mate or Linux Mint
Opted into Steam client beta?: **Yes and No**
Have you checked for system updates?: Yes
Conditions: Enabled **autologin for Ubuntu + Autologin for steam**.

Workaround: start steam without browser
`steam -no-browser`

**Comment by KayKay91** [comment]
ArchLinux
Autologin Enabled
Steam Beta
Using KDE Plasma

KDE Wallet asks for a password each time i run Steam.

**Comment by h1z1** [comment]
Started getting this.  I don't use kde nor gnome keyring thus it's not setup.  

It's not even so much that wallets are used rather the popup happens regardless if one has been configured or not and defaults to 4 prompts.

Automatically authenticating to them completely defeats the point.  DO NOT DO THAT.  At least make it optional.  Why would Steam require it given at least in theory steam has already authenticated the user?  My guess is it's CEF and someone screwed up the compile on their last release.

**Comment by paulovilli** [comment]
In my mind, there is one case scenario where using keyrings inside CEF on
Steam would make sense: ensuring any login for a 3rd-party website can be
memorized in a safe database (the OS-provided keyring) if used inside
CEF... which can happen on Steam Overlay and on purchases when redirected
to 3rd-party payment provider websites (if purchasing from inside Steam).

IMPORTANT: Chromium (and by extension most likely CEF) has a built-in
password storage, which is completely unsafe (stores everything in
plaintext) and is the automatic fallback method for password storage when
no keychain is available (including when a user clicks cancel on the
keyring unlock dialog):
https://chromium.googlesource.com/chromium/src.git/+/master/docs/linux_password_storage.md

I believe (but this has to be confirmed) that CEF, Chromium and Google
Chrome share the exact same keyring on Linux so once unlocked Steam may
list the same memorized logins and passwords for autocomplete (if the
feature is enabled). This would be a small nicety about having keyrings
besides providing safe password storage...

...but nothing changes the fact that users may be exposing eg. PayPal login
and password, in plaintext storage, if memorized from that built-in browser.

Given that, the easiest thing to do is probably to just eliminate the
entire password memorization and autocomplete featureset from Steam's CEF.
Have no storage at all, period. That is one less attack surface on Steam
for Valve and users to worry about, one less popup annoyance for all users,
and not a lot of convenience lost.


Irony of CEF: the minute you start using a browser inside your app to
simplify development, you inadvertedly also become a browser developer.
🤷‍♂️

**Comment by emmandyar** [comment]
I'm having this as well. For what I understand, this is a chromium feature rather than a bug. So how can we disable it from within steam? I know it may pose a security risk, but if we do not use the keyring and have autologin enabled, security is already pretty weak/not a concern

**Comment by jkcdarunday** [comment]
Happens to me too. It's asking for access as "Chromium" which is misleading (would've been slightly more acceptable if it identified itself as Steam). Very concerning that they could have access to all login credentials stored in the wallet with a modified(?) version of chrome.

**Comment by Leopard1907** [comment]
>  It's asking for access as "Chromium" which is misleading

Why? Steam client is essentially a Chromium browser

**Comment by jkcdarunday** [comment]
>Why? Steam client is essentially a Chromium browser

Yes, and so are Opera, Brave, Electron Apps, etc. yet I would be concerned if any of these tried to open the keyring as "Chromium" instead of their respective names. First thought when I saw "Chromium" trying to unlock the keyring at start-up without chromium running was that I had a malware of some sort trying to access my login credentials.

**Comment by g572staem** [comment]
Confirming the issue and I'm surprised it's months old.  Brand new ubuntu 18.04 LTS install, up-to date packages, auto-login (secured by other means but just a gaming rig).

This misbehaviour/bug is dangerous.  A number of the suggestions that people are running with change the behaviour of their keyring without understanding the potential consequences.

I can also confirm this works as a but stops a lot of normal Steam functionality (e.g. library, in game friend thing etc)
`steam -no-browser`

I'd suggest this instead (which I've literally only just tried, seems OK) so that you can do non-game Steam tasks when you want to.
`steam -no-browser steam://rungameid/730`
(for me 730 is CS:GO, I don't know if that ID changes per install)

**Comment by g572staem** [comment]
Confirming the issue and I'm surprised it's months old. Brand new Ubuntu 18.04 LTS install, up-to date packages & auto-login (secured by other means but just a gaming rig).

This misbehaviour/bug is dangerous. A number of the suggestions that people are running with change the behaviour of their keyring without understanding the potential consequences.

steam -no-browser
I can confirm this works but stops a lot of normal Steam functionality (e.g. library, in game friend thing etc)

I'd suggest this instead, which I've literally only just tried and it looks OK, so that you can do non-game Steam tasks when you want to (i.e. have a shortcut for Steam, and create or modify your shortcut/launcher for each game)
steam -no-browser steam://rungameid/730
(for me 730 is CS:GO, I don't know if 730 will be CS:GO for you but there's a reasonable chance it is)

**Comment by TriMoon** [comment]
What happens when you decline access to the keyring?
If it doesn't cause problems i would suggest to just auto-decline access to all "Chromium" requests :stuck_out_tongue_winking_eye:

**Comment by emmandyar** [comment]
Nothing. You just deny the request 3 times and it stops asking until next
linux login

**Comment by Managor** [comment]
It's very annoying. As a temporary solution, anyone know how to disable KWallet?

**Comment by Kedstar99** [comment]
Hi @Managor,

I have come up with a solution that works for me if you would like to try. 

Basically, I make use of a program called firejail which isolates steam in various ways.
On ubuntu I installed this by running sudo apt install firejail.

Firejail already comes with a somewhat decent profile for steam. To add all the programs
with profiles defined simply run the command 'sudo firecfg'. This should populate your
/usr/local/bin directory with wrappers that run the command firejail '<profile>' <program>.
If your PATH environment variable has /usr/local/bin set, this wrapper should in theory
be called before the steam executable.

Now to use firejail to block steam, you need to block access to kwallet.

In /etc/firejail create a file called disable-secret.inc. Within that file, add the contents here 
https://raw.githubusercontent.com/ptoomey3/firejail/master/etc/disable-secret.inc .

After that simply edit steam.profile in /etc/firejail to add a line 'include disable-secret.inc' below
'include disable-programs.inc'.

Restart steam.

Now when you run steam it shouldn't ask you to unlock you wallet.

I hope this helps.

Kind regards,
Krish

NOTE: I don't take any responsibility if you face problems caused by these instructions.

**Comment by g572staem** [comment]
I imagine that hoping for the best with Ubuntu 20.04 LTS will end up being more realistic.

https://store.steampowered.com/hwsurvey/  See OS Version. Valve is unlikely to address this issue.

I stopped using my method above and just click cancel (x3) otherwise too much normal functionality breaks.

**Comment by TriMoon** [comment]
I have no more popups with this in my `~/.config/kwalletrc` :+1: :tongue: 
```
[Auto Deny]
kdewallet=Chromium
```

**Comment by Philippe734** [comment]
> I have no more popups with this in my `~/.config/kwalletrc` +1 tongue
> 
> ```
> [Auto Deny]
> kdewallet=Chromium
> ```

Very interesting. What is the equivalent for Gnome?

**Comment by TriMoon** [comment]
> @Philippe734 
> Very interesting. What is the equivalent for Gnome?

I think you don't realize this topic is about **K**Wallet, hence KDE...
Feel free to try it, as it is a setting that the program uses self...

**Comment by autotoxicus** [comment]
This topic is about "Chromium GnomeKeyring or KWallet Prompt on Login".

**Comment by kisak-valve** [comment]
Hello, per "Disabled CEF keyring integration by default. The -enable-keyring option can be passed to the Steam client to reinstate it." in the [2020-03-03](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1706240323209971343) Steam client beta update, please opt into Steam's beta client and retest.

**Comment by Managor** [comment]
Yep. No KWallet in sight by default now.

**Comment by Philippe734** [comment]
> Hello, per "Disabled CEF keyring integration by default. The -enable-keyring option can be passed to the Steam client to reinstate it." in the [2020-03-03](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1706240323209971343) Steam client beta update, please opt into Steam's beta client and retest.

I confirm, with buil built Mar  3 2020 20:49:55, with Gnome, no more popup GnomeKeyring for password prompt. Wonderfull! Thanks for Steam staff.

**Comment by Leopard1907** [comment]
I can confirm that latest beta fixed the issue on my end too.

**Comment by kisak-valve** [comment]
Closing as fixed in the [2020-03-26](https://store.steampowered.com/news/59842/) steam client update.

**Comment by paulovilli** [comment]
Confirmed fixed using Steam Beta on Linux Mint 19.3 (which is based on
GnomeKeyring) as well.

@kisak-valve
Thank you so much for taking time to look into this!

Em qui, 26 de mar de 2020 21:34, kisak-valve <notifications@github.com>
escreveu:
