### ISSUE TITLE
Unable to run Steam (Linux)

### ISSUE THREAD

**Issue by mdziczkowski** [ValveSoftware/steam-for-linux#6594]
#### Your system information

* Steam client version (build number or date): latest
* Distribution (e.g. Ubuntu): Ubuntu 14.04 (Trusty), i686 (32-bit)
* Opted into Steam client beta? [Yes/No]: Yes
* Have you checked for system updates? [Yes/No]: Yes

#### Please describe your issue in as much detail as possible:

When I try to start Steam, it launches the update with get interrupted with following error:

`Fatal Error: Unable to load steamui.so `

Going ahead of future question: no, I'm unable to take and send any screenshoot

**Comment by kisak-valve** [comment]
Hello @mdziczkowski, support for Ubuntu 14.04 ended in April when upstream dropped support as well.

That set aside, there's a good chance running steam from a terminal would give you a hint and you're most likely missing 32 bit opengl support. You should be able to check this with `glxinfo` from `mesa-utils:i386`.

Also, `realpath` is needed for Steam's library pinning logic.

Closing due to previously mentioned end of life for Ubuntu 14.04.
