### ISSUE TITLE
Steam Client detects Logitech G920 as generic gamepad

### ISSUE THREAD

**Issue by flukejones** [ValveSoftware/steam-for-linux#6664]
#### Your system information

* Steam client version (build number or date): 
* Distribution: openSUSE - kernel 5.3.8 and 5.4.0-rc6
* Opted into Steam client beta?:Yes and No, tried both
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Per title. Additionally some wheel features such as accelerator seem to be stuck in "down" button mode.

## Solution

1. Upgrade to 5.4 series kernel
2. Run in a console `steam --reset`
3. ...
4. Profit!

The 5.4 series  kernel includes fixes to a regression which happened around the 5.1.x kernel

**Comment by luzemario** [comment]
**Your system information**

    Steam client version (build number or date): latest
    Distribution: Ubuntu 18.04 - 4.15.0-70
    Opted into Steam client beta?:Yes and No, tried both
    Have you checked for system updates?: Yes

**Please describe your issue in as much detail as possible:**

Steering Wheel is not detected on some games as DiRT and DiRT4
It turns to the left end after initialization in ETS2 and ATS

**Comment by flukejones** [comment]
I had forgotten I opened this issue. There were some FFB regressions and I think some other regressions in the kernels 5.1 to 5.3.

I solved every issue I had with this wheel and Steam by upgrading my kernel to 5.4 (release candidates), and then doing `steam --reset`.

@luzemario I don't know how feasible or appropriate it is for you, but perhaps try upgrading to Ubuntu 19.10 then installing 5.4 kernel.

**Comment by juszczakn** [comment]
Same problem but with my G29 being recognized as a PS3 controller.

**Comment by flukejones** [comment]
> Same problem but with my G29 being recognized as a PS3 controller.

G29 and G920 use completely different drivers. Unsure of the fix for that issue.

**Comment by luzemario** [comment]
> I had forgotten I opened this issue. There were some FFB regressions and I think some other regressions in the kernels 5.1 to 5.3.
> 
> I solved every issue I had with this wheel and Steam by upgrading my kernel to 5.4 (release candidates), and then doing `steam --reset`.
> 
> @luzemario I don't know how feasible or appropriate it is for you, but perhaps try upgrading to Ubuntu 19.10 then installing 5.4 kernel.

@flukejones, thank you for your suggestion. I updated my notebook to Ubuntu 19.10, and most of problems were gone. The wrong FFB turning to the left after initialisation is a kernel driver issue, not anything Valve can do. Wheel's LSB button was turning down volume, but I remapped the key with Steam controller config.

The thread at [http://www.draisberghof.de/usb_modeswitch/bb/viewtopic.php?t=2510](url) helped me a lot too.

Since my primary use for the G920 wheel is to play ETS2 and ATS, I am satisfied with the results. ETS2 and ATS overcome the initialization bug of the driver by sending continuous updates, so the wheel works after the game has started driving. SCS is aware of the issue, and plans to do something more elegant in the next updates of their software.

However, I still cannot find a solution for DiRT/DiRT4 and Feral seems to not going to resolve this in the near future.

So my advice to all willing to use Logitech G29/G920 is to update your distro at first, then try to configure buttons with Steam settings, and at last ask for game manufacturer for support. This has shown good results for me.

**Comment by flukejones** [comment]
@luzemario you really need to be running the 5.4.x kernel, and you definitely need to do `steam --reset` to be sure old settings that steam has for the device are cleared.

**Comment by luzemario** [comment]
Hi, @flukejones, sorry for the delay in the feedback.

Actually most of people will not do `steam --reset`, since the Steam client blocks it as a security measure. Moving my game data is not an option right now.

I am using kernel 5.3.0-40 on Ubuntu 19.10 (latest kernel while I wrote this), and all problems with games gone. Even the Feral ones, works seamlessly.

Since I am not using any of Steam controller features, It is solved for me. The weel is not even seen by Steam client, but it is acceptable now.

**Comment by alvarlagerlof** [comment]
I can't get my G29 to show up at all in Flatpak steam

**Comment by kisak-valve** [comment]
Hello @flukejones, are you still experiencing this issue on an up to date system?

**Comment by flukejones** [comment]
@kisak-valve, not sure sorry, I've not used the wheel set in quite a while.

**Comment by kisak-valve** [comment]
Closing pending confirmation this issue is still around.

**Comment by alvarlagerlof** [comment]
I have done a little testing with the steam flatpak. I added /run/udev as read-only in flat-seal, and then my G29 does produce some input in games. Without that I get no input from the wheel at all. Major things like turning the steering wheel has no effect though. Steam big picture mode. Does not however detect any devices. I do have the steam-devices package installed on my system.
