### ISSUE TITLE
Steam client causing text rendering problems on ubuntu

### ISSUE THREAD

**Issue by Anode194** [ValveSoftware/steam-for-linux#6768]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: [Yes/No] N
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

launching the steam client in KDE causes text to not to render throughout the whole system.

kernel version: 5.3
AMD 5700 xt
[img](https://imgur.com/tC6SXwa)

#### Steps for reproducing this issue:

1. install steam through apt
2.  launch steam in KDE or other display manager/desktop under ubuntu
3. should see black bars underneath text

**Comment by kisak-valve** [comment]
Hello @Anode194, this looks like a video driver issue. Can you give [kisak-mesa PPA](https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa) a try?

**Comment by Anode194** [comment]
Ok so I added the PPA, updated the system, rebooted and the problem persists. {driver info](https://gist.github.com/Anode194/04fe3e0642237569778249f82ad80257).

**Comment by kisak-valve** [comment]
`Mesa 19.2.0-devel` from glxinfo is suspicious and predates any support for AMD Navi. Something fishy is going on here. Maybe something like `apt policy libgl1-mesa-dri libgl1-mesa-dri:i386` would give a hint as to where that is coming from.

**Comment by Anode194** [comment]
[more info](https://gist.github.com/Anode194/768e7ec1c87addb4efdca761ecf1717c)

**Comment by Edznux** [comment]
Hey

I had the same issue until today and it was very annoying, I fixed it with the following:
(after trying & failing with the things said above with the ppa)

I installed the latest [amdgpu driver](https://drivers.amd.com/drivers/linux/19.50/amdgpu-pro-19.50-967956-ubuntu-18.04.tar.xz) (the -pro name in the name is misleading, there is both the pro and non-pro version, you can find it [here](https://www.amd.com/fr/support)) on a 5.5 kernel (not sure if it changed anything). It's just a matter of `download && tar xvf && cd amd-gpu..... && ./amdgpu-install`. Don't use the -pro version, only the standard one will work.

Had to uninstall the old driver with `amdgpu-uninstall` first (and this broke the UI, kind of expected, so had to get to rescue root shell @ boot). You will probably get some complain about KMS/nomodeset enabled at the end of the install, since the boot param is there for the rescue boot, but it should be an issue once booted with standard boot params (no `nomodeset` nor `vga=` apparently)

Hope it help & so we can close :)

**Comment by Anode194** [comment]
Thank you for the reply feel free to close this I ended up switching distros, hopefully this can be helpful for other folks that run into this problem.

**Comment by kisak-valve** [comment]
Closing per the last comment.
