### ISSUE TITLE
PC freezes when updating large game

### ISSUE THREAD

**Issue by TomRoussel** [ValveSoftware/steam-for-linux#6776]
#### Your system information

* Steam client version (build number or date): Dec  16 2019, at 16:49:05
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When updating a game my system freezes when reaching the "installing" step. After forced reboot, the updating resumes as normal and succesfully ends. This seems to only be a problem with large games, as I encountered this issue when updating Path of Exile (plays fine through Proton). I do not have issues when updating a smaller game (such as Factorio).

Sidenote, since the updating process uses a lot of diskspace, I have symlinked my downloading directory to a folder on my HDD. Maybe this is a part of the problem, but I don't know why it would be.

I do not have a swap partition.

#### Steps for reproducing this issue:

1. Symlink downloading folder to different hard drive: `ln -s /data/steam_downloads ~/.local/share/Steam/steamapps/downloading `
2. Update Path of Exile
3. Computer freezes and needs a hard reboot.

**Comment by byte1024** [comment]
You don't need a swap partition but can make a swap file any time you want and activate it always on boot. This is what I do normally for swap because I like to minimize partitions.

I assume Arch has a system info/monitor that you can leave open pre-download, push off to the side, and look at it during a freeze to see if eg ram is maxed, cpu is maxed, etc.

Sometimes freezes can take 10 or 30 minutes to unfreeze. You don't say how long you've waited. Other times it could be an OS problem, not Steam.

It could be Steam in a very specific situation where the code can't cope but I really can't think of anything. It probably would throw and error and exit the code loop.

You can make sure it doesn't happen outside of Steam by doing an equally large download from Origin or EGS, along with the symlink, etc.

**Comment by TomRoussel** [comment]
The reason I mentioned not having a swap file is because swapping RAM also causes full system freezes, but that's not what's happening here.

Some additional information: this has happened 3 times to me. Next update, I'll keep a system monitor tool open and see if I see any spikes in CPU or RAM usage when the freezing happens.
The first time I waited for about 15 minutes before hard rebooting, it didn't seem like it would recover.

The symlink was a hacky solution to my disk problem. I'm working with a pretty small SSD partition, so I can't reserve twice the disk space for my games. I was wondering if it was known that using a symlink for you download folder could cause some funky behavior like this.

I think it's pretty strange that steam would cause this, but I can't find any other reason. The drives are in good health and less than a year old (as is the whole PC), so hardware doesn't seem like the problem.

**Comment by kisak-valve** [comment]
Hello @TomRoussel, it should be noted that symlinking another drive like that isn't the expected method to add additional space to Steam. You should be able to go to Steam -> Settings -> Downloads -> Steam Library Folders and add a second Steam Library.

If a game update needs to temporarily use more space than a smaller Steam Library has available, it should try to use another Steam Library folder as staging to complete the update.

**Comment by TomRoussel** [comment]
Oh Steam will use any library folder available for staging updates? That would make my symlink approach obsolete. I'm going to try that and remove that link.

Small update, my PC froze again after another game update. This time I had a system monitor running and there were no spikes in CPU or RAM usage. Still very strange, hopefully using a second library solves this problem.

**Comment by TomRoussel** [comment]
I just ran into the same issue. I'm no longer using the symlink, I just have a second library steam can use to stage large downloads. When it reaches the "installing" step of the game update process, my whole PC freezes.

**Comment by sabian2008** [comment]
Same thing happens to me. I found this related bug: https://github.com/ValveSoftware/steam-for-linux/issues/5404, where the same thing is reported. It seems it was never fixed. I'm installing GTA V right now (86 GB) and this is a PITA, I can only download at nights because otherwise it could end up hanging the entire OS (which happend today while playing Shadow of the Tomb Rider while also downloading). 

Spikes are, well... spikes. So I guess there could be some problem with the IO scheduler. It isn't a throughput problem because my internet is 12Mb/s (~1.2 MB/s) so, although the primary Steam Library is in an HDD (secondary is in a small SDD) it shouldn't be a problem.

I am using standard Fedora 31.

**Comment by TomRoussel** [comment]
Quick update, after updating my kernel from 4.19 to 5.5, I no longer have this issue.

Might've been caused by an obscure kernel bug?

**Comment by kisak-valve** [comment]
Hello @TomRoussel, have you seen this issue since your kernel update in the last comment?

Hello @sabian2008, are you still experiencing this issue on an up to date system?

**Comment by TomRoussel** [comment]
Nope! I haven't encountered this problem since that comment. For me the issue is resolved and can be closed.

**Comment by sabian2008** [comment]
I'm going to try. Since that moment I never updated a game while I was using the system. Just leave the updates to be applied overnight.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.

**Comment by AJenbo** [comment]
I'm seeing this on my stem running ubuntu 23.10

**Comment by Fotkurz** [comment]
Having the same issue on Pop!_OS 22.04 LTS

**Comment by AJenbo** [comment]
For me it turned out that my SSD had been filled to a point where it's performance had degraded, only reformatting it resolved the issue.
