### ISSUE TITLE
Client crash - Fatal assert failed: ../common/pipes.cpp, line 770.

### ISSUE THREAD

**Issue by h1z1** [ValveSoftware/steam-for-linux#6858]
#### Your system information

* Steam client version (build number or date): built Jan 25 2020 17:26:11
* Distribution: CentOS
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Client crashes shortly after launch.  No further interactions required.

[gist](https://gist.github.com/h1z1/c7b6ce08be7210cb7b23419de162a31b)

#### Steps for reproducing this issue:

1.  Launch client
2.  See it update
3. Login
4. Interface hangs shortly after (can't click anything)
5. client crash
6. go back to playing nethack

**Comment by h1z1** [comment]
This is still a problem.  Steam is unusable, as is any content purchased.

**Comment by davispuh** [comment]
I've also had this issue for a while. Steam was working fine and then one day it just stopped starting and was crashing exactly like this. Nothing that useful in log. In #5899 someone wrote to try set `PULSE_SERVER=/dev/null` but that didn't change anything. Anyway I managed to narrow it down. If I delete `~/.local/share/Steam` then steam redownloads everything and works fine. So clearly there's some file that causes this crash and with some trial and error I found it :partying_face: 

Remove `BaseInstallFolder_1` line from `~/.local/share/Steam/config/config.vdf` (or just delete file) and `"1"` line from `~/.local/share/Steam/steamapps/libraryfolders.vdf` (you need to remove from these both files as otherwise Steam will add them again)

So for me this how it looked like when Steam was crashing
`config.vdf`
```
"InstallConfigStore"
{
        "Software"
        {
                "Valve"
                {
                        "Steam"
                        {
                                [...]
                                "BaseInstallFolder_1"           "/mnt/игры/Steam"
                        }
                }
        }
        [..]
}
```

`libraryfolders.vdf`
```
"LibraryFolders"
{
        "TimeNextStatsReport"           "1596445714"
        "ContentStatsID"                "3742678903240012345"
        "1"             "/mnt/игры/Steam"
}
```

Removing these it works fine now :tada:

**Comment by felipepiovezan** [comment]
Monster Train would not launch with this same error message on the console. I removed `~/.steam/steam/linux64`  and the problem went away.

**Comment by MajorGonzo** [comment]
I found in ~/.steam/error.log a message that the directory ~/.steam/Bin could not be deleted because it was a directory
I manually deleted that directory, exited Steam, restarted it, and Steam completed an update.
My games then worked again.

**Comment by kisak-valve** [comment]
Hello @h1z1, are you still experiencing this issue on an up to date system?
