### ISSUE TITLE
Sometimes Steam Library does not load

### ISSUE THREAD

**Issue by XakepSDK** [ValveSoftware/steam-for-linux#7016]
#### Your system information

* Steam client version (build number or date): Apr 3 2020, at 22:37:31
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* System Information: https://gist.github.com/XakepSDK/cfb1bad897216147d58cf9b7958fd9dd

#### Please describe your issue in as much detail as possible:
Sometimes steam library does not load, it only shows steam icon and three blinking boxes under it

I can provide logs if you want, but i don't know which logs. I don't know how to reproduce issue.

#### Steps for reproducing this issue:

1. Start steam

**Comment by reddog357** [comment]
Can verify this happened to me as well. Steam updated today and the library wouldn't load.
I'm also on Arch Linux and in the client beta. I unsubscribed to the client beta so I could get to the library for now.

**Comment by Zamundaaa** [comment]
Also happens rather often for me (especially after boot when it's autostarted). Simply restarting Steam makes it work again though.

**Comment by Lightsockie** [comment]
This happens to me sometimes, too. Restarting it will also sometimes fix it. I am also on the beta channel and running Arch (btw). Just switched back to the non-beta build, and it's working, but is it working because I restarted or cuz I'm not in the beta channel anymore? I'm not sure. Never had problems with Store or any other part of the interface. Nothing noteworthy shows up in any logs. Library just hangs on the loading screen

```
Steam Built: Jul 31 2020, at 09:12:33
kernel: 5.7.10-arch1-1
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.1.4
[AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
```

**Comment by BillFleming** [comment]
I believe I am affected by this issue also on arch.
When I kill the main parent steamwebhelper. process then the library will load like normal. But every couple of steam launches the issue will randomly crop up. 
I suspect the issue could be due to the amount of games that I have installed? (462+proton and some non-game software)

**Comment by CommanderAlchemy** [comment]
Arch, similar issues and more, not sure if all are the same.
Steam system info: https://gist.github.com/CommanderAlchemy/aadf973abda51bf2c372bd9e08b879e1

1. Stuck when logging in: Just after you enter your account information and it displays "connecting to account..."
![image](https://user-images.githubusercontent.com/3089330/91756696-73180b00-ebcd-11ea-8c8f-2765edd99a6f.png)

2. Displaying Steam Library loading icons Never loads.
![image](https://user-images.githubusercontent.com/3089330/91756490-19afdc00-ebcd-11ea-96c6-2e5bea2a3e74.png)

3. Even store had issues loading

**Comment by zv0n** [comment]
Same issue here, from what I can tell first steam launch after boot always has this issue, then restarting the client fixes it

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as outdated.
