### ISSUE TITLE
Steam hangs at: Installing breakpad exception handler for appid(steam)/version(1586022601)

### ISSUE THREAD

**Issue by b4raba** [ValveSoftware/steam-for-linux#7031]
#### Your system information

* Steam client version (build number or date):  **steam 1.0.0.61-4**
* Distribution: **Arch Linux** 
* Opted into Steam client beta?: **Yes**
* Have you checked for system updates?: **Yes**

#### Please describe your issue in as much detail as possible:

After a recent update, when launching steam it hangs with this message: 

```Installing breakpad exception handler for appid(steam)/version(1586022601)```

#### Steps for reproducing this issue:

1. Update to latest kernel 5.6.4-arch1-1 and nvidia 440.82-3
2. run steam

**Comment by kisak-valve** [comment]
Hello @b4raba, this is an nVidia driver issue. The proprietary nVidia driver requires that the currently running kernel module version, the 64 bit userspace library versions, and 32 bit library versions match, otherwise this scenario happens. All OpenGL applications hang waiting on the video driver in this situation, which you can verify with `glxinfo` from `mesa-demos`.

Please verify that `nvidia-dkms`, `nvidia-utils`, and `lib32-nvidia-utils` have the same version. If you recently updated, you may need to reboot to get the updated kernel module loaded.

**Comment by Starkie** [comment]
This happened to me while trying to play Resident Evil 4 or some other DX8 games.  The problem was that, during the upgrade to Ubuntu 22.04, some files from the nvidia 495 drivers were left over. I had files from both the 495 and 515 drivers. 

To fix it, I executed the commands to remove the old drivers, their dependencies and reinstall the recommended drivers, if needed:
 ```bash
sudo apt remove nvidia-driver-495
sudo apt autoremove
sudo ubuntu-drivers autoinstall
```

Now I cant boot RE4 and Geometry Wars again :)

**Comment by Matthew0x** [comment]
I have a similar problem on AMD.

The Client opens up, starts loading its stuff and basically hangs for around 5-15 seconds with this one message displayed over and over. Then it un-freezes and seemingly works.

Sometimes it takes ages.

RPM package here
