### ISSUE TITLE
No stdout logging

### ISSUE THREAD

**Issue by GoTeamAnt** [ValveSoftware/steam-for-linux#7114]
#### Your system information

Version:
* steam_1.0.0.62
* Archlinux

#### Please describe your issue in as much detail as possible:

Steam stopped logging stdout to /tmp/dumps/$USER_stdout.log

**Comment by kisak-valve** [comment]
Hello @GoTeamAnt, this is an intentional change in the 1.0.0.62 steam packaging related to #6901.

My understanding was that there wasn't interest in unconditionally logging stdout anymore. You can create an equivalent log by completely closing Steam, then running `steam 2>&1 | tee /path/to/logfile` from a terminal (or creating a shortcut).

**Comment by kisak-valve** [comment]
Closing because this is the intended behavior.
