### ISSUE TITLE
Latest Steam Client update crashes on startup

### ISSUE THREAD

**Issue by longshanks197** [ValveSoftware/steam-for-linux#7115]
#### Your system information

* Steam client version (build number or date): 1589513816
* Distribution (e.g. Ubuntu): Devuan beowulf/Debian 10.0
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
After update to latest steam build, crashes on startup. System was working perfectly with prior build. 

Running Steam on debian 3 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/dustin/.steam/ubuntu12_32/steam -nominidumps -nobreakpad
[2020-05-16 07:57:51] Startup - updater built May 15 2020 03:04:07
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2020-05-16 07:57:52] Checking for update on startup
[2020-05-16 07:57:52] Checking for available updates...
[2020-05-16 07:57:52] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
[2020-05-16 07:57:52] Download skipped: /client/steam_client_ubuntu12 version 1589513816, installed version 1589513816
[2020-05-16 07:57:52] Nothing to do
[2020-05-16 07:57:52] Verifying installation...
[2020-05-16 07:57:52] Performing checksum verification of executable files
[2020-05-16 07:57:53] Verification complete
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
/data/src/common/ipcserver.cpp (1231) : Assertion Failed: CPipeWaiter::BRemove(59) -- not present

No clear indication of issue from gdb. 

gdb logfile and error.log:

https://gist.github.com/longshanks197/160bf05bed8616926058dcddb8fef1c7

If needed i can provide dumps.

#### Steps for reproducing this issue:

1. Run steam
2. Checks for update, all good...waits...
3. Crashes

**Comment by longshanks197** [comment]
Update: System during initial event was Nvidia Driver 418.113 with Linux kernel 4.19.98. Upgraded to Nvidia driver 440.82 via backports, no change. Upgraded to Linux Kernel 5.5.17 via backports, no change.

**Comment by Seegras** [comment]
Same. Crashes here too with different errors. See https://github.com/ValveSoftware/steam-for-linux/issues/5899

```
/data/src/common/pipes.cpp (770) : Assertion Failed: fatal stalled cross-thread pipe
/data/src/common/pipes.cpp (770) : Assertion Failed: fatal stalled cross-thread pipe
/data/src/common/pipes.cpp (770) : Fatal assert failed: /data/src/common/pipes.cpp, line 770.  Application exiting.

/data/src/common/pipes.cpp (770) : Fatal assert failed: /data/src/common/pipes.cpp, line 770.  Application exiting.

Installing breakpad exception handler for appid(steam)/version(1589513816)
```
nvidia-drivers were 440.82-1 and kernel 5.6.12; with which I think it worked.

It might have started crashing after the the libc-upgrade from the 11th of may. It's a bit difficult to tell, because I started steam, which worked. Some time later it upgraded, and haven't worked since then. beta or no beta, new install or not; VR enabled or not.

**Comment by dpanter** [comment]
You guys using the Debian package (steam) or the Valve package (steam-launcher)?
If you suspect the Nvidia driver, you could give the nouveau driver a shot.

My AMD system works correctly, offering data for comparison and troubleshooting:
```
Siduction (Debian sid based) 5.6.13-towo.1-siduction-amd64 x86_64
Radeon VII, Mesa 20.2.0~git20200516-1
steam:i386 1.0.0.62-2
Steam beta client, built May 15 2020, at 18:18:24, package version 1589568628
Steam Runtime Version:  steam-runtime_0.20200417.0
```
Since it's a bit of a mess currently, here's a list of installed libc6 and gcc packages on my system (updated yesterday).
https://pastebin.com/k3PNsqJE

**Comment by longshanks197** [comment]
Thanks @dpanter  and @Seegras for the follow up. My issue appears to be related to #7117 as I was able to get the client running with a smaller installed library. Closing this to #7117.

**Comment by Seegras** [comment]
Oh-oh.
$ ls *.acf | wc -l 
3766
