### ISSUE TITLE
When is the linux client steam (1:1.0.0.62) going to be out of beta?

### ISSUE THREAD

**Issue by romulasry** [ValveSoftware/steam-for-linux#7156]
I want to package it but it is currently in beta...

**Comment by Evernow** [comment]
It's already in the Manjaro repos, where does it say it's in beta?

**Comment by romulasry** [comment]
http://repo.steampowered.com/steam/archive/precise/steam_1.0.0.62_amd64.changes

Changes: 
 steam (1:1.0.0.62) beta; urgency=medium

**Comment by smcv** [comment]
1.0.0.62 was (meant to be) "promoted" from beta to stable status a little while ago. https://repo.steampowered.com/steam/archive/precise/steam_latest.tar.gz and https://repo.steampowered.com/steam/archive/precise/steam_latest-stable.tar.gz both point to it.

The apt metadata in https://repo.steampowered.com/steam/dists/ didn't get updated at the time for some reason, which should now be fixed. Once the CDN cache updates (which might take an hour or two) it should now show 1.0.0.62 as the latest in both the stable and beta channels.

That changelog just says it was *originally* a beta. Debian-format changelogs contain the suite to which the upload originally took place, which is why most packages in Debian have `unstable` in their changelogs - but it was copied from beta to stable without modification, so that the version that is considered stable is exactly the same version that was successfully tested as a beta.

**Comment by smcv** [comment]
> didn't get updated at the time for some reason, which should now be fixed

I've kicked this again... please retry.

I cannot tell when the latest updates are visible to you, because you are probably seeing a different CDN endpoint, but the worst-case scenario should be that it becomes visible to you 1 hour from now.

> link to the change log

If what you want is an indication of what is currently a beta and what is currently stable, then the `.changes` file and the `debian/changelog` are not the tool you are looking for. Those are generated at the time the package is first built, and are not subsequently modified. This is the same way official Debian packages work: if you look at the version of `tar` in Debian 10, you'll see that its changelog says `unstable`, because that version was *originally* released to the `unstable` rolling release, then copied from there to `testing`, and from there to Debian 10 stable.

The reason why the various versions are copied around without rebuilding or re-numbering them is that doing it that way prevents introducing a regression while rebuilding the package (for example with newer dependencies). The idea is that what was tested is what you get.

If what you want is to see what changed since 1.0.0.61, the `.changes` file and the `debian/changelog` *are* useful for that.

The symbolic links `steam_latest-stable.tar.gz` and `steam_latest.tar.gz` should always point to the version of `steam_x.y.z.w.tar.gz` that is considered stable, and `steam_latest-beta.tar.gz` should always point to the version that is the latest beta.

Would it be useful for packagers if everything (both beta and stable) continued to appear in https://repo.steampowered.com/steam/archive/precise/, and there was a new archive directory https://repo.steampowered.com/steam/archive/precise/stable/ (or something similar) that only contains releases that have been promoted to stable?
