### ISSUE TITLE
Mandatory Steam restart after starting Dota 2 / CS:GO

### ISSUE THREAD

**Issue by xnaxe29** [ValveSoftware/steam-for-linux#7163]
#### Your system information

* Steam client version (build number or date): v020
* Distribution (e.g. Ubuntu): Ubuntu
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

When I click on play game, Steam client prompts a message saying: "Steam Client Crashing every time I want to start a game with message: Steam must now be restarted in order to receive the latest update. You won't be able to continue using steam until it has restarted."

This is annoying because steam, as well as all the games I play, are completely updated. After this message, the steam client just forcefully restarts without any warning. And again, after it restarts and I click on play game, the same cycle repeats. 

I have tried restarting my computer, reinstalling steam from scratch, etc. None of it has worked. Also, I have looked for any programs that might hinder with the running of steam, and there are none.

Please help.

#### Steps for reproducing this issue:

1. Start steam 
2. Click on "Play" on either CS:GO or Dota
3.

**Comment by kisak-valve** [comment]
Hello @xnaxe29, I tried to reproduce this issue on an couple test boxes and did not encounter an issue. Can you clarify a few details?

What distro release are you using?

If you go to Help -> About Steam, does it have Built: Jun 1 2020 / Steam package versions: 1591052255, which is the current mainline Steam release?

What does `apt policy steam` give you?

When you re-installed Steam from scratch, what steps did you take to do this? If you removed the Steam package and re-added it, that would have re-installed Steam's bootstrapper, but not the client itself. The Steam client ends being put in `~/.steam` or `~/.local/share/Steam` depending on if you're using the Valve-provided or distro-provided variant of the Steam package.

Those questions set aside, I'd try to immediately start a client update cycle by going to Steam -> Settings -> Beta participation change button and switch between the mainline and beta version. If that has no effect, then I'd completely close Steam and try running `steam --reset` which tells Steam to run as if it were a fresh install or move `~/.steam` and `~/.local/share/Steam` somewhere out of the way so that the Steam client will be re-bootstrapped the next time it is.

**Comment by xnaxe29** [comment]
Hi,

Here is the information on my distribution -
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

When you re-installed Steam from scratch, what steps did you take to do 
this?
I just did -
sudo apt-get remove steam
and then -
sudo apt install steam


If you go to Help -> About Steam, does it have Built: Jun 1 2020 / Steam 
package versions: 1591052255, which is the current mainline Steam release?

Here is my steam current build -
Built: March 26 2020, at 22:46:20
Steam API: v020
Steam Package versions: 1585264767
Also please note that steam does not any pending upgrade that I can see 
in my system.

My "which steam", gives me the address - /usr/games/steam
Although my cd "~/.steam" gives me a valid address, but not "cd 
~/.local/share/Steam"


I will do the beta participation and get back to you.


Cheers

Adarsh

**Comment by TTimo** [comment]
We recommend removing the distribution package and using the official Valve package to install steam. See http://repo.steampowered.com/steam/

**Comment by kisak-valve** [comment]
Hello @xnaxe29, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.

**Comment by xnaxe29** [comment]
The issue is resolved. Thanks.
