### ISSUE TITLE
Cannot connect to Steam Network upon startup, needs -tcp

### ISSUE THREAD

**Issue by brauliobo** [ValveSoftware/steam-for-linux#7232]
Works with `-tcp` option and used to work without it until last week. How to proceed without this workaround?

System: updated Archlinux 
![image](https://user-images.githubusercontent.com/41740/86060245-be316880-ba3a-11ea-89a9-75d9fd3a14d7.png)

**Comment by henriquebecker91** [comment]
I have the exact same problem. The login only works if `-tcp` is used, otherwise it accuses lack of network connection. But even with `-tcp` I have the problem the games do not update as they should, they instead: (1) have a red message `No Internet Connection` in the Downloads tab; or (2) have a red message `Content Servers Unreachable` in the same place; or yet (3) they have no error message (the case of the "Deep Rock Galatic" game), but if I try to force the download they try starting it for some seconds and then give up.

**Comment by kleja** [comment]
I have the same problems as the previous poster. Manjaro latest release. Running Steam client (runtime not native) I can usually start the client without problems, but seemingly randomly I will have to reset Steam to get it working (tcp or not does not matter). Even if running I experience faulty updates with reason listed being "No Internet Connection". Sometimes also "content unreachable". forcing downloads fails like previous poster.

**Comment by henriquebecker91** [comment]
What solved my problem was a full system update. I think some packages in the network stack must have ended up incompatible with each other but not catastrophically so (i.e., a partial upgrade). After I did a full system update I do not even need the `--tcp` and had no more problems with updates.

**Comment by kleja** [comment]
I have now tried a full system reinstall. Wiped disk, reinstalled Manjaro (latest KDE version), deinstalled preinstalled steam. Re-installed steam. Same error regardless of tcp or not. Basically not able to start Steam - at all...

**Comment by kleja** [comment]
System: Manjaro 21.2.2 KDE version (Plasma 5.24.2), kernel 5.16.11-2-MANJARO (64-bit).
Nvidia 3090 GPU, proprietary driver, 510.

As I mentioned in last post, totally wiped disk starting from scratch. Uninstalled Steam that comes with Manjaro, deleted folders .steam and .local/share/steam. Then reinstalled steam-manjaro (runtime) not Steam native. When starting up, I get to login screen, log in, then when I get to the Updating user info bit, I immediately get "Could not connect to Steam Network..." error.

No steam --reset helps, neither when starting with just steam or steam -tcp.
This is getting to be very frustrating, since steam mostly has been working great until january, and then not at all for the last 3-4 days.

Enclosing some relevant log files.

[bootstrap_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/8232383/bootstrap_log.txt)
[cef_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/8232384/cef_log.txt)
[configstore_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/8232385/configstore_log.txt)
[connection_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/8232386/connection_log.txt)

**Comment by kisak-valve** [comment]
Hello @brauliobo, are you still experiencing this issue on an up to date system?

Hello @kleja, you've described a different issue from the opening post. If you're still seeing it, then please open a separate issue report.

**Comment by kleja** [comment]
> Hello @brauliobo, are you still experiencing this issue on an up to date system?
> 
> Hello @kleja, you've described a different issue from the opening post. If you're still seeing it, then please open a separate issue report.

My issues have been resolved, but thanks for the feedback!

**Comment by kisak-valve** [comment]
Closing pending feedback.
