### ISSUE TITLE
[lastest beta] steam-runtime fontconfig is unable to run libcef

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#7285]
in the log, libcef is complaining about a missing symbol FcConfigGetSysRoot

**Comment by kisak-valve** [comment]
Hello @sylware, this is a repeat of #7059, which points back to https://github.com/ValveSoftware/steam-runtime/issues/253#issuecomment-619064429.

It's unlikely that anything has changed since you encountered this 2 months ago, but please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by sylware** [comment]
https://gist.github.com/sylware/be7ddb53c4d05470b8cafcb89156f1f6

**Comment by sylware** [comment]
the steam-runtime is almost able to run google libcef, only the dbus stuff is missing.
