### ISSUE TITLE
Replace the term "PC" with "Windows"

### ISSUE THREAD

**Issue by DASPRiD** [ValveSoftware/steam-for-linux#737]
The term "PC" was misused for a long time already, but didn't matter that much, as long as there was only Windows present. Now with more Linux games popping up in the store, it'd make a lot of sense to replace the term "PC" with "Windows", as Linux itself runs on PCs as well.

One could argue that Mac OSX technically runs on PCs as well, but that could be seen as a special case as Macs are PCs specifically built by Apple.

**Comment by Leopard1907** [comment]
Gaben won't do that.

Because he is earning well and most of it comes from Windows aka PC. He will not gonna do anything that may offend Windows people.

In fact ; if Microsoft wouldn't put their own store into Windows and wouldn't announce UWP project, Gaben won't be interested with SteamOS/Linux.

We are just a spare tire to them ( companies are living for money) to just in case, against that possible successful Ms Store. If Ms announce ; we just decided that Ms Store and Uwp are bad ideas and we're shutting them forever , all of a sudden SteamOS project will vanish

Sorry but that is the truth.

**Comment by DASPRiD** [comment]
I'm not entirely sure, but this issue seems to be fixed across the entire store by now. A quick check reveals the following terms used across the entire site:

- Windows
- Mac OS X
- SteamOS + Linux

I assume this issue can be closed then, unless I oversaw something?

**Comment by stevethepocket** [comment]
As far as I know, yeah.

**Comment by h1z1** [comment]
Thread is hillariously PC..   PC in computer venacular is correct.  It's describing the hardware.  Mobile would describe a modbile device.    I certainly wouldn't disagree additional labels could be added for specific support but there are logistical and challenges since many of them are registered trademarks.  Developer may not necessarily endorse nor fully comply with those even if they do technically run.

It's really not much different from "SteamOS".  Though it's based for the most part on Ubuntu, they can't say Ubuntu as it's not completely.  It's a fairly critical distinction since it goes to the heart of why people insist on saying "GNU/Linux".  Not surprising any vendor, like hosting companies, who claim to have X dsitro but include their own changes, fall under the same legal trouble.

**Comment by eiglow** [comment]
Seems like this issue can be closed now, it's been fixed for more than a year.
