### ISSUE TITLE
Incorrectly installed Steam or outdated guide (NSS error code)

### ISSUE THREAD

**Issue by humancfg** [ValveSoftware/steam-for-linux#7431]
### SysInfo

- Steam client: Build Oct 23 2020, at 20:26:58; Package versions: **1603487799**
- Distribution: **Debian buster 10.06** _(netinstalled)_
**`Linux debian 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux`**
- Opted into Steam client beta?: **[No]**
- Have you checked for system updates?: **[Yes]**

### Issue in detail

Everything went well for almost a week. But I decided to installing Steam by the rules on 
[http://repo.steampowered.com/steam/](url)

> [**dpkg.log:**](https://gist.github.com/sukavpn/29d323a6c2a9966742b3fea5a51d354a)

Actually, before that, when I launched Steam through the terminal, I didn't have so many lines and mostly nothing serious, just like this time. With the exception of one line:

**`[1026/032643.300168:ERROR:nss_util.cc(283)] After loading Root Certs, loaded==false: NSS error code: -8018`**

I didn't expect that. Because this isn't the first time I've installed Steam on Linux. By the way I have tested SteamOS on mine desktop PC. Anyway. I think this warning with this error-line is more important than others. 
I mean, all of this is interesting. Wanna know how to fix them too.

> [**steam-runtime.log:**](https://gist.github.com/sukavpn/c7e267a0d06348743783593d8f97a357)

Anyway. Thank you in advance for your feedback!

#### Steps for reproducing this issue:

1. Read rules [http://repo.steampowered.com/steam/](url)
2. Add REPO
3. Unpacking [**dpkg.log:**](https://gist.github.com/sukavpn/29d323a6c2a9966742b3fea5a51d354a)

**Comment by kisak-valve** [comment]
Hello @sukavpn, looking around, that NSS error message also appeared in #3501, but that wasn't the focus of that issue report. 

Historically, the distro-provided Steam package and the Valve-provided Steam package had incompatible folder layouts due to distro modifications on their side and the transition can cause trouble. Can you move `~/.steam` somewhere out of the way and retest?

**Comment by sukavpn** [comment]
Hey, @ kisak-Valve!
I have an LVM. So I'll try to take your advice when I remember how LVM works. 
I have a neighbor's question, and since you are in the administration of the valve. Can I ask you something? Which folders can I move for security reasons before reinstalling the distribution? 
It's not about rescue disk. It's about creating separate Steam disk part. And maybe with some kind of symlinks. I'm not very competent in this matter and I'm trying to imagine it. 
Maybe some working URL's u have seen. I'd appreciate it.
I just want edit system files without problems and with simplicity. Without any reinstall. Some kind of "rescue mode" but easiest.
Thank you,  in any way

**Comment by kisak-valve** [comment]
The Valve-provided Steam package bootstraps the Steam client to `~/.local/share/Steam` and sets up some things in `~/.steam` while the Debian altered Steam package puts everything inside of `~/.steam`. Separately, some native games may put config and save files elsewhere, but most Steam-related things end up between those two folders. It's not clear what you mean with regards to 'security reasons'.

Friendly note that I'm a moderator for Valve's issue trackers on Github and not a Valve developer myself.

**Comment by kisak-valve** [comment]
Hello @humancfg, are you still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing pending feedback.
