### ISSUE TITLE
DualSense on Linux - Gryo, LED, Rumble Not Working

### ISSUE THREAD

**Issue by cow-killer** [ValveSoftware/steam-for-linux#7473]
#### Your system information

* Steam client version: **November 17 beta**
* Distribution: **Pop!_OS 20.10**
* Opted into Steam client beta?: **Yes**
* Have you checked for system updates?: **Yes**

#### Please describe your issue in as much detail as possible:
Today's [beta update](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2896339990496271925) added support for the DualSense's gyro, LED, rumble features, but doesn't seem to work on my end. I was told by one of the employees at Valve, "you have to update your udev rules to allow steam to do feature/output reports to the device over USB."

So, I'm not exactly sure how to go about doing this. I'm aware udev rules are located in `/lib/udev/rules.d`, but I'm not sure if there's an existing file that I need to modify or add a new one.

#### Steps for reproducing this issue:

1. Opt-in in to Steam client beta
2. Plug DualSense in via USB
3. Test the pad in BPM. Only the on-screen buttons have been updated

**Comment by byte1024** [comment]
Could be I'm missing something, but don't think that's it. Steam controller settings shows the trackpad works without udev rules if you go into BPM controller defaults and set something to the trackpad click.

Adding the controller to udev for wired USB same as DualShock 4 but updated for DualSense product id didn't do anything new. Don't see anything else to do there on the user side. It shouldn't require anything more than the DualShock 4.

I'd be surprised if udev was the only thing here especially since it didn't do anything for me in that regard.

**Comment by cow-killer** [comment]
So [udev rules have been added for the DualSense](https://github.com/ValveSoftware/steam-devices/blob/master/60-steam-input.rules):
```
# PS5 DualSense controller over USB hidraw
KERNEL=="hidraw*", ATTRS{idVendor}=="054c", ATTRS{idProduct}=="0ce6", MODE="0660", TAG+="uaccess"

# PS5 DualSense controller over bluetooth hidraw
KERNEL=="hidraw*", KERNELS=="*054C:0CE6*", MODE="0660", TAG+="uaccess"
```
Added these to `60-steam-input.rules`, reloaded the rules, restarted the system, still no vibration or LED color...

**Comment by Bleuzen** [comment]
Can confirm this on Manjaro.
Using Steam Beta from Nov 20, also added the udev rules and rebooted.
Still no LED, Gyro, Touchpad and Rumble. Both with USB and bluetooth.

**Comment by byte1024** [comment]
> So [udev rules have been added for the DualSense](https://github.com/ValveSoftware/steam-devices/blob/master/60-steam-input.rules):
> 
> ```
> # PS5 DualSense controller over USB hidraw
> KERNEL=="hidraw*", ATTRS{idVendor}=="054c", ATTRS{idProduct}=="0ce6", MODE="0660", TAG+="uaccess"
> 
> # PS5 DualSense controller over bluetooth hidraw
> KERNEL=="hidraw*", KERNELS=="*054C:0CE6*", MODE="0660", TAG+="uaccess"
> ```
> 
> Added these to `60-steam-input.rules`, reloaded the rules, restarted the system, still no vibration or LED color...

That's exactly what I tested. I think its just BPM, etc that doesn't offer these features, though the controller config in Steam doesn't change the light either, but from what I understand they might actually work in games that supports said feature.

Definitely, not yet right in the sense that we expect.

**Comment by kisak-valve** [comment]
Hello, per "Enabled enhanced functionality for PS5 controllers on Linux (may require steam-devices package update)" and "Fixed LED color changes on PS5 controllers connected over Bluetooth" in the [2020-11-24](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2896339990517078189) Steam client beta update, please retest this issue.

**Comment by cow-killer** [comment]
Can now confirm LEDs are working, as well as rumble and gyro, both through wireless and wired. Thanks a lot!!

**Comment by byte1024** [comment]
Requires the above mentioned changes that the cow-killer mentioned. After that and eg a reboot (or loading the changes probably), the LED color changes and trackpad are definitely working in Steam controller preferences.

I have nothing known to test rumble and gyro on.

**Comment by cow-killer** [comment]
To test the vibration you can simply press `Cross` on the "Identify" button in Steam BPM in the controller settings menu. As for gyro, just download any FPS, enable PlayStation controller support, then configure the gyro to act as a mouse for the game.

**Comment by byte1024** [comment]
> To test the vibration you can simply press `Cross` on the "Identify" button in Steam BPM in the controller settings menu. As for gyro, just download any FPS, enable PlayStation controller support, then configure the gyro to act as a mouse for the game.

All that is beyond my simple use lol.

Thanks for pointing it out. Very interesting and unexpectedly never seen stuff for me.

**Comment by Settyness** [comment]
After today everything works, however is there a better way to test gyro than the aforementioned?

**Comment by xDShot** [comment]
Games in Proton can't recognize the controller as gamepad. It does work if emulate WASD and Mouse, though 'd like it to imitate Xbox controller.

**Comment by xDShot** [comment]
@Settyness 
> Is it normal for the touchpad to move the mouse with inertia? It doesn't feel like a laptop at all, it feels more like a touchscreen smartphone.
The feature is called trackball mode. You can adjust inertia or disable it in game's controller configuration for touchpad.

**Comment by xDShot** [comment]
Figured out. It's two devices appearing as separate controllers in wine: "Wireless Controller" and "Microsoft X-box 360 pad". All inputs are translated to virtual xbox pad and wireless controller stands still. Most games expect inputs from first one and have no effect.

Solution:
1. Open wine control panel for game prefix ex. `WINEPREFIX=/home/xdshot/.steam/steam/steamapps/compatdata/227780/pfx wine control`
2. Open Game Controllers
3. Disable Wireless Controller, both js and event.
![image](https://user-images.githubusercontent.com/4261659/100399177-d0074e00-3062-11eb-8560-692a199e8904.png)

**Comment by cow-killer** [comment]
> is there a better way to test gyro than the aforementioned?
You can configure the controller's settings while using the desktop; in Steam BPM Settings, under Controller, select Base Configuration. Select Desktop configuration, then you can configure the gyro to use the mouse or the like. The gyro feature is selected where the mute button is on the controller layout.

**Comment by Settyness** [comment]
Thanks, ya'll. Confirm that gyro is working now. And was able to remove inertia from the mouse inputs.

**Comment by AryToNeX** [comment]
Gyro, LED and rumble still not working on latest Steam beta on Artix Linux. Udev rules seem to not be the full story here.

**Comment by xDShot** [comment]
In-game custom LEDs no longer work.

**Comment by cow-killer** [comment]
> In-game custom LEDs no longer work.

Sounds like a good excuse to use [my program](https://github.com/cow-killer/dualsense-led-configurator) ;-)

**Comment by xDShot** [comment]
> > In-game custom LEDs no longer work.
> 
> Sounds like a good excuse to use [my program](https://github.com/cow-killer/dualsense-led-configurator) ;-)

I'm implementing LED interactive support in my game using Steamworks

**Comment by ashkitten** [comment]
rumble works for me in the controller gui, but not in rocket league.

**Comment by xDShot** [comment]
LED appears working in random conditions in Big Picture mode. Have to restart several times to get it working.

**Comment by leinardi** [comment]
Hi, I'm having some issues with the DS and Steam.

Fist of all, I played 15 hours of Detroit: Become Human with a DS4 and it worked perfectly. I just had to plug it via USB cable and it just worked.
I was expecting a similar exprience with the DS, since [full support was announced](https://store.steampowered.com/news/group/4145017/view/2924487488167580235) in November. Unfortunately this is not what I experienced: after being sure that [the latest udev rules](https://github.com/ValveSoftware/steam-devices/blob/master/60-steam-input.rules) were loaded, I plugged my new DS and fired up Big Picture. The controller was recognized but only basic input was working on BP (no gyro, LED colors, trackpad, etc).

After some digging I found out that the `Settings -> Controller Settings -> PlayStation Configuration Support` was not checked. This is pretty strange, since I played with a DS4 before and I am pretty sure I never changed that setting. Anyway, after enabling it, most of the issues with the DS were solved, after going to Base Configurations and selecting the Official configuration for both the Desktop and Big Picture.

Is the user supposed to check the `PlayStation Configuration Support` manually? Shouldn't this be automatically checked when a Play Station controller is recognized?

Anyway, I still have a pretty annoying issue:
Detroit: Become Human is still recognizing the DS as an XBox controller:
![20210104201955_1](https://user-images.githubusercontent.com/273338/103573091-f32ce500-4ecd-11eb-9f00-63a91328ae6b.jpg)
This is pretty annoying because, with the DS4, I was able to use the Gyro and the Trackpad to do certain actions but and the LED color was reflecting the stress level of the android but, with the DS, it only uses the analog sticks and the buttons use the XBox naming convention.

Is this a known bug or do I have another misconfiguration somewhere?

System Info:
https://gist.github.com/leinardi/b1f2a314b383f88c45b146881b317e81

**Comment by kisak-valve** [comment]
Hello @xDShot, @leinardi, follow up issues should be reported separately if they haven't been already, and issues with games run with Proton should be mentioned on their compatibility report on the Proton issue tracker.

Closing because the original issue reported here appears to be resolved.

**Comment by prez** [comment]
I'm on the latest steam beta client, have the udev rules loaded yet pressing cross on the identify button doesn't make it vibrate, and changing LED colour still doesn't work for me.
What could possibly be wrong? Thanks.
