### ISSUE TITLE
Payday 2 won't launch

### ISSUE THREAD

**Issue by mymatebilly** [ValveSoftware/steam-for-linux#7509]
#### Your system information

* Steam client version (build number or date): Oct 28 2020
* Distribution (e.g. Ubuntu): Ubuntu 20.04.1 LTS
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes, updates installed

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I had very bad stuttering on Payday 2 Native so I decided to launch it with Proton. When I selected Proton 5.13-2 in the game properties it made me download a 28 Go update for Payday 2 for no apparent reason because I had already used Proton on other games and never had to download more than 1 Go.
But I downloaded it anyway and after that I tried to launch Payday 2 but it didn't, it said 'Preparing to launch' in a Pop-up window then 'running' in green but just a second after it goes back to the big green 'Play' button as if the game never started

I tried going back to Native but I can't since it requires me to download 28 Go again and my connection isn't good enough to do that quickly.

Please help me I don't know what to do.

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @mymatebilly, we're tracking issues with games run with Proton in the [Proton issue tracker](https://github.com/ValveSoftware/Proton/issues). If you want to continue experimenting with using the game with Proton, please open a new [compatibility report](https://github.com/ValveSoftware/Proton/issues/new?template=compatibility-report.md) and fill it out since there isn't one already for this game. (Note: We use one compatibility report per unofficially supported game title run with Proton.)

Regarding the size of the download, game developers can chose to set aside separate content for different platforms and setting the game to use Proton in Steam tells Steam to remove the Linux-specific content and give you the Windows variant of the game. It sounds like this game doesn't share much content between the Windows and Linux game builds.
