### ISSUE TITLE
Steam Icon on Gnome top tray is not working (Right click doesn't work)

### ISSUE THREAD

**Issue by ebolducgirard** [ValveSoftware/steam-for-linux#7539]
#### Your system information

* Steam client version (build number or date): 7th December 2020, at 18:04:33
* Distribution (e.g. Ubuntu): Ubuntu 20.04 LTS 64 Bits, Gnome 3.36.3
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When I click on the Steam icon on the top tray, nothing shows up.
I can't use Steam unless I  go into the terminal, type "steam" and press Enter.
Only now I can use Steam. (The icon tray menu still doesn't work)

#### Steps for reproducing this issue:

1. Start Steam either by using the terminal or the UI  
2. Wait for it to show up after updates checks have passed
3. Click on the Steam icon at the Gnome top tray.

(Expected result: the tray menu should've appear)

**Comment by kisak-valve** [comment]
Hello @ebolducgirard, can you check the contents of `<steam install folder>/ubuntu12_32/steam-runtime/pinned_libs*`, then delete the `pinned_libs*` folders so that Steam will regenerate them on the next start of the Steam client.

If that doesn't help, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by ebolducgirard** [comment]
In steam/ubuntu12_32/steam-runtime/pinned_libs32 and pinned_lib64, there isn't any folders. Are you talking about the pinned_libs* folders in */steam-runtime/ ?
