### ISSUE TITLE
steam starts slow if you're connected to VPN 

### ISSUE THREAD

**Issue by damianatorrpm** [ValveSoftware/steam-for-linux#7569]
steam starts slow if you're connected to VPN:
During start it hangs for ~7 seconds. In the command line there is this
error while it hangs:
** (steam:157): WARNING **: 14:42:27.546: replace_settings: error updating connection /org/freedesktop/NetworkManager/Settings/12 settings: (3) type

Fedora 33
openVPN (https://www.expressvpn.com/) configured via gnome-control-center (NetworkManager)
if steam is started before you are connected to the VPN there is no problem.

The problem is only if you are connected to the VPN and than start steam.
[steam.txt](https://github.com/ValveSoftware/steam-for-linux/files/5742357/steam.txt)

**Comment by kisak-valve** [comment]
Hello @damianatorrpm, in general, running Steam through a VPN is not supported per `You agree that you will not use IP proxying or other methods to disguise the place of your residence, whether to circumvent geographical restrictions on game content, to purchase at pricing not applicable to your geography, or for any other purpose. If you do this, Valve may terminate your access to your Account.` in the [Steam Subscriber Agreement](https://store.steampowered.com/subscriber_agreement/) and since this is a non-fatal issue, I don't see any action to take here.

**Comment by damianatorrpm** [comment]
@kisak-valve ah I see, that's good to know. In my case this is not for such restrictions, just using stuff I already have,
and being secure on the net (I'll even use the VPN gateway from my country, since expressVPN offers many in that case),
so I guess then above will not apply.
