### ISSUE TITLE
Install button greyed out for Far Cry 3 - Blood Dragon (233270)

### ISSUE THREAD

**Issue by alex9k1** [ValveSoftware/steam-for-linux#7604]
# Compatibility Report
- Name of the game with compatibility issues: Far Cry 3 - Blood Dragon
- Steam AppID of the game: 233270

## System Information
- GPU: Vega 56
- Driver/LLVM version: Mesa 20.3.2
- Kernel version: 5.10.6-zen
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/alex9k1/c05d310bb112b6b554404a57385bb2cf
- Proton version: Not applicable

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Steam client wouldn't let me install the game. The install button is grayed out:

![grafik](https://user-images.githubusercontent.com/46139159/104641130-aa351780-56a9-11eb-97bf-ee686b6165d1.png)

I've been using Steam's Proton since it got out and IIRC this is the first time I'm encountering this issue.

## Reproduction

Just try to install the game

**Comment by kisak-valve** [comment]
Hello @alex9k1, this reads like a config issue with the Steam client and not Proton itself, so I've transferred this issue report to the steam-for-linux issue tracker.

In general, this is the expected behavior for any non-native game that has not been whitelisted for use with Proton.

If you want to test a game with Proton, the user needs to opt-in to that behavior, either in the per-game settings or the Steam-wide global settings. Can you confirm what settings you have in Steam -> Settings -> Steam Play and/or if you've told Steam to force the use of a specific Steam Play compatibility tool in the Compatibility section of the per-game properties.

**Comment by alex9k1** [comment]
Hi @kisak-valve , thanks for moving the issue. I wasn't too sure where to post this.

My SteamPlay settings look like this:
![grafik](https://user-images.githubusercontent.com/46139159/104646039-36e2d400-56b0-11eb-9663-f850e271bf89.png)

It does not say "Runs on this computer via Steam Play". I've checked this on a few other random games, and everywhere else this information actually appears.

**Comment by alex9k1** [comment]
Ok, it seems to affect multiple games now. Same thing with Serious Sam 4, although I already have it installed but now I can't launch it :D Just shows me a grayed out INSTALL button.

**Comment by alex9k1** [comment]
Got it resolved. Disabled SteamPlay in settings and unchecked the per game force option. Restarted Steam and re-enabled both. Not it's working again. Guess I can close the issue then.
