### ISSUE TITLE
ArcheAge: Unchained will not update.

### ISSUE THREAD

**Issue by staffen** [ValveSoftware/steam-for-linux#7609]
#### Your system information

* Steam client version (build number or date):  Dec 20, 2020
* Distribution (e.g. Ubuntu):  Kali
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
The game installed ok, but on first launch said it needed an update (18.62 GB Download) but when I actually tried to download it it said that it required 61.51 GB of disk space and I only had 15.67 GB.  Since I have 124 GB free on that partition, I don't know what it is on about.  16 GB is the default size of tempfs (I have 32 GB of ram) but that's the only thing I can think of even in the range of having only 15.67 GB free.  I will attach my df -h and a screenshot of the error.
![steam_support-2](https://user-images.githubusercontent.com/77555318/104824990-e50f8a80-5824-11eb-9e9f-e96fe569c7e4.png)
![steam_support-1](https://user-images.githubusercontent.com/77555318/104824991-e5a82100-5824-11eb-97cd-6eddaff6eafd.png)

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment]
Hello @staffen, this appears to be an issue between wine and a third party updater for Windows. Separately, running Steam-for-Windows is not supported here and running Steam-for-Linux is not supported for Kali Linux because it's not intended for use as a general purpose desktop system. You'll most likely have better luck asking around in the wine community forums.

Closing as out-of-scope for this issue tracker.
