### ISSUE TITLE
Steam client stuck on startup when connecting to account

### ISSUE THREAD

**Issue by amalkus** [ValveSoftware/steam-for-linux#7632]
#### Your system information

* Steam client version (build number or date): 1.0.0.61-2ubuntu3 Feb 20 2020
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: [Yes/No] dont know
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

When starting Steam the loading screen appears: "connecting to Steam-Account ..."
Then nothing happens anymore
[Error.log](https://gist.github.com/amalkus/55be8f0e3898cea173f4ee550e1e8e7c)
[console output](https://gist.github.com/amalkus/c1331424d6f2b89972481d75f2a8e514) (looks almost the same)

I tried already:
- explore google, ubuntu forums, GitHub issue list, steam community
- "STEAM_RUNTIME=0 steam"
- steam --reset
- uninstall / reinstall steam via Ubuntu software
- ldd for ~/.steam/bin32/steam & vgui2_s.so
- managed to manually reinstall missing libs (except: libvstdlib_s.so and libvstdlib_s.so)
  even manually installed libff6 from downloaded deb package as there is only libff7 in repositories available
- kickin against the case and smashing the keyboard didn't work either

It still only shows the connecting to account box and that's it.
Now I'm desperate and created a GitHub account, hopefully someone can help me.

I've got the same PC available twice (with different user and steam account) but there all seems working fine.
Connection is possible and steam is asking for a password (i didn't open the library yet)

**Comment by kisak-valve** [comment]
Hello @amalkus, `./steamwebhelper: error while loading shared libraries: libffi.so.6: wrong ELF class: ELFCLASS32
` looks abnormal in your log. The 64 bit variant of this library which steamwebhelper uses should be provided by the Steam runtime in `<steam install dir>/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libffi.so.6`.

Can you make sure Steam is not trying to run, then delete the `~/.steam/ubuntu12_32/steam-runtime` folder so that Steam can regenerate it on the next run and see if that makes a difference?

**Comment by amalkus** [comment]
Hey kisak-valve that was like a golden shot. It worked straight away, thanks a lot.

You're right, the libffi.so.6 comes with steam. I was already wondering why I got the error.
