### ISSUE TITLE
steam won't recognize my external home partition when installing certain games.

### ISSUE THREAD

**Issue by KevinMichaelDaley** [ValveSoftware/steam-for-linux#7639]
#### Your system information

* Steam client version (build number or date): Dec 20, 2020 at 23:07:25
* Distribution (e.g. Ubuntu): Ubuntu LTS 20.04.1
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
(see below)

#### Steps for reproducing this issue:

1. Log into a user called kmd with an empty /home/kmd directory.
2. sudo mount /dev/sdb5 /home/kmd
3. install Quake 1 via Proton.  It installs to the empty directory, not the mount point as expected.

**Comment by kisak-valve** [comment]
Hello @KevinMichaelDaley mounting another partition on top of the home directory of an active use sounds strange. Can you explain why you are choosing to do that after login instead of before?

**Comment by KevinMichaelDaley** [comment]
Hi,
It is indeed a bit strange but it's never not worked before in any application.  I should probably mention that I am using steam from flatpak; this is the only one that works with up-to-date nvidia drivers.

I tried doing that but it keeps saying "drive is read-only", even when I use a folder on the same partition it is installing steam games to.

**Comment by kisak-valve** [comment]
Sounds like the same Flatpak issue as https://github.com/flathub/com.valvesoftware.Steam/wiki#i-want-to-add-external-disk-for-steam-libraries / https://github.com/flathub/com.valvesoftware.Steam/issues/55. Your issue is with the nature of Flatpak's sandboxing and not Steam.

Regarding nVidia's drivers, what issue are you seeing with them? The nVidia kernel module, 32 bit userspace, and 64 bit userspace need to have exactly the same version to work properly. On Ubuntu, it's not uncommon for `libnvidia-gl-460:i386` (changing 460 to match the rest of the driver series) to get missed in a driver update.

**Comment by KevinMichaelDaley** [comment]
Yeah that was it (on both counts).  Feel free to close the issue I guess.
