### ISSUE TITLE
Steam Icon Context Menu not showing after Right Clicking

### ISSUE THREAD

**Issue by Feindfluglp** [ValveSoftware/steam-for-linux#7643]
#### Your system information

* Steam client version (build number or date): Feb 5 2021 - 02:23:56
* Distribution (e.g. Ubuntu): Debian 10 whit KDE Plasma
* Opted into Steam client beta?: [Yes/No] no
* Have you checked for system updates?: [Yes/No] Yes

I see the Icon and Steam is running.
The right click on the steam icon, dont go.
no context menu, nothing.

Whit left click, dont go.
before the last 4 updates, whas all ok.
My system and steam its up-to-date, that is not the problem.

in my opinion, steam is to blame for the fact that the context menu no longer works. is it a bug?

**Comment by kisak-valve** [comment]
Hello @Feindfluglp, can you check the contents of `<steam install folder>/ubuntu12_32/steam-runtime/pinned_libs*`, then delete the `pinned_libs*` folders so that Steam will regenerate them on the next start of the Steam client.

If that doesn't help, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by Feindfluglp** [comment]
Ok.
pls delete this issues, i have fix this whit delete all files and reinstall whit purge steam.
its running for me :)
thx for help
