### ISSUE TITLE
Shaders compiled from amdvlk are executed on mesa radv. Is this intentional?

### ISSUE THREAD

**Issue by sinatosk** [ValveSoftware/steam-for-linux#7723]
#### Your system information

* Steam client version (build number or date): Mar 23 2021, at 20:11:07
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

mesa radv has a commit which is causing shaders to be incorrect which in turn is causing DOTA 2 to not start. I later installed Doom Eternal using proton 5.13-6 within steam using mesa radv and sometimes it would start and sometimes not, then I installed amdvlk and the shaders were recompiled and configured Doom Eternal to use amdvlk and it worked. I tried DOTA 2 ( still using mesa radv ) and it worked. I uninstalled amdvlk and shaders were recompiled and DOTA 2 no longer worked and Doom Eternal ( reconfigured to use mesa radv again ) didn't start like DOTA 2.

The shader issue is a bug with mesa radv and I've reported that but I was wondering if it was intentional for amdvlk compiled shaders to be executing on mesa radv?

**Comment by kisak-valve** [comment]
Hello @sinatosk, generally speaking, a video driver's on-disk shader cache is a driver-specific detail. There shouldn't be a mechanism in Steam that forces one video driver to use a shader cache of another video driver.

It sounds like the video driver issue you've encountered might be non-fatal if the on-disk shader cache is manually removed or otherwise invalidated. That's a detail to ask your video driver vendor about, and not a Steam client issue.
