### ISSUE TITLE
Steam doesnt open anymore after update

### ISSUE THREAD

**Issue by LinoBigatti** [ValveSoftware/steam-for-linux#7758]
#### Your system information

* Steam client version (build number or date): not sure
* Distribution (e.g. Ubuntu): Gentoo
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I opened steam as always, and it rebuilt pins. However, unlike normal fashion, it didnt open. I tried it on a console, and it doesnt output any error, alltough it is cut short. Relevant log: https://dpaste.com/E344UA6TY

**Comment by kisak-valve** [comment]
Hello @LinoBigatti, did you recently do a system update that included the nVidia driver? You should be able to do a simple test with `glxinfo -B` from `mesa-progs`.

If you did, then it's likely that all OpenGL applications are broken on your system in the same way, and it's because the nVidia proprietary driver requires that the running kernel module, 32 bit userspace, and 64 bit userspace versions all match for it to work properly and the simplest method to resolve the issue is to reboot the system.

**Comment by LinoBigatti** [comment]
I do not have a nvidia gpu, nor did I update system drivers recently. Ill still try a reboot.

**Comment by LinoBigatti** [comment]
A restart fixed it. Sorry for the trouble.
