### ISSUE TITLE
Steam won't boot

### ISSUE THREAD

**Issue by awsdert** [ValveSoftware/steam-for-linux#7811]
#### Your system information

* Steam client version (build number or date):  Cannot get because won't boot
* Distribution (e.g. Ubuntu): Manajaro Cinnamon x64
* Opted into Steam client beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I'm unable to boot steam now, I tried re-installing steam but that didn't get it to boot either

#### Steps for reproducing this issue:

1. Try to boot
2. Tells me I need 32bit pipewire 0.3 library which is still in alpha or beta
3. Won't finish booting
4. Tried looking for pipewire libraries, libraries for 0.2 available, probably both 64bit and 32bit
5. Tried building pipewire, had build errors so manjaro would not install it

**Comment by kisak-valve** [comment]
Hello @awsdert, this issue was already evaluated on #7807 and should already be resolved in a re-release of yesterday's Steam client beta update.

You should be able to manually opt out of Steam's beta update channel by deleting `~/.steam/steam/package/beta` which should trigger an update cycle the next time you try to run Steam, then both the mainline release and the current beta should work.

**Comment by awsdert** [comment]
I'll give that a try but I opted into the beta specifically for the controller settings, you seem to not allow mapping to anything but keyboard and mouse when running stable, also if I remember rightly some games won't run without beta enabled because you don't allow proton without beta enabled. I'll go ahead and try now

**Comment by awsdert** [comment]
ty, that did resolve the booting issue, will check my games later as I need to go looking for work, btw do you know of any blogs or anything that describe what it's like to work as a programmer in gaming? I programme as a hobby but never tried taking up work as a programmer
