### ISSUE TITLE
X Error of failed request:  BadValue (integer parameter out of range for operation) 470 NVIDIA drivers

### ISSUE THREAD

**Issue by lmarianski** [ValveSoftware/steam-for-linux#7875]
#### Your system information

* Steam client version (build number or date): not sure where to find that
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I'm getting this error when running steam after updating Nvidia drivers to 470.42.01
```
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Can't find 'steam-runtime-check-requirements', continuing anyway
WARNING: Using default/fallback debugger launch
/home/m00n/.local/share/Steam/ubuntu12_32/steam
[2021-06-23 20:32:00] Startup - updater built Mar 23 2021 20:11:00
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
Installing breakpad exception handler for appid(steam)/version(1621394999)
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
```

**Comment by kisak-valve** [comment]
Hello @lmarianski, the nVidia proprietary driver requires that the running kernel module, 32 bit userspace libraries, and 64 bit userspace libraries are installed and have exactly the same version to work properly.

Whatever method you used to install the 470 series driver did not include the 32 bit userspace libraries (typically found in the `lib32-nvidia-utils` package). This is a distro packaging issue with the nVidia driver, not a Steam issue.

I'm guessing that you're using `nvidia-utils-performance` from the AUR, but have not updated `lib32-nvidia-utils-performance` to the matching version since I'm not seeing any other Arch packages that have this driver series yet.

**Comment by lmarianski** [comment]
Ah, yeah there's no official packages for the 470 driver version yet so i grabbed the beta packages from the AUR and updated the driver version there myself, didn't know that i also need the 32 versions, thanks!
