### ISSUE TITLE
/bin/steam and /bin/steam-runtime keep getting overwritten every update along with system autostart options.

### ISSUE THREAD

**Issue by NolanSyKinsley** [ValveSoftware/steam-for-linux#7912]
#### Your system information

* Steam client version (build number or date): june 8 2021
* Distribution (e.g. Ubuntu): Manjaro
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Almost every update(it's not every update, but it is common during updates) steam stops being able to be minimized to the system tray when I close it and I keep having to go back to /bin/steam to reset the export "STEAM_FRAME_FORCE_CLOSE=" flag to 1. This is a config file! STOP OVERWRITING IT EVERY UPDATE. And stop taking over my startup command! I do not have steam set to handle startup(okay, I keep SETTING it to not launch on startup because I have my own scripts but apparently it sees my custom startup script and just goes "Oh, That's mine, I can do with it what I want" and then sets steam to manage the startup. WHICH IS WRONG.), I am managing the launching of steam through my system controls and randomly on updates steam will see the startup command I have set and wipes it and replaces it with it's own launch settings. I keep having my "usr/bin/steam -silent" replaced with the default launch options. Both of these NEED TO STOP. These are our configuration files and settings, they should not be constantly overwritten every update (Well, again, not EVERY update, but the events coincide with updates, and the script replacement is much more common than the startup command replacement, both are annoying as hell and should not be happening). They are set to what we need for the program to run properly on our system and steam just keeps wiping them out.

These problems had been a thing a while back, like a couple years ago, but they stopped. It stopped for so long I completely forgot how to fix it when it started happening again and had to google it up, but now that it has restarted doing it again, it is doing it more often, like 3x in the past 90 days when it hadn't happened in years.

#### Steps for reproducing this issue:

1. Have settings.
2. wait for update
3.Have settings go away because it keeps overwriting startup files.

**Comment by kisak-valve** [comment]
Hello @NolanSyKinsley, files in /bin and /usr/bin are managed by your package manager and Steam does not have the rights to change the contents of anything in those folders. Your modifications were overridden by the package manager, not Steam.

If you want to Steam to start on session start with a customized desktop shortcut, then:
1) Copy `/usr/share/applications/steam.desktop` to somewhere not managed by your package manager.
2) Go to `Steam` -> `Settings` -> `Interface`  and uncheck `Run Steam when my computer starts` so that the Steam's desktop shortcut is not used.
3) Add your customized and renamed steam.desktop shortcut to your desktop environment's autostart settings.

You should be able to set the exec line in your modified steam.desktop to something like `Exec=env STEAM_FRAME_FORCE_CLOSE=1 /usr/bin/steam %U -silent` to get the behavior you're looking for.

Closing because this is a package manager issue, not a Steam client issue.
