### ISSUE TITLE
libllvm:i386 wants to delete system components

### ISSUE THREAD

**Issue by rileyhawk1417** [ValveSoftware/steam-for-linux#7932]
#### Your system information

* Steam client version (build number or date):  Can't Acess
* Distribution (e.g. Ubuntu): Pop_OS 20.04 LTS
* Opted into Steam client beta?: [No] 
* Have you checked for system updates?: [Yes]

#### Please describe your issue in as much detail as possible:
Tried using steam after a while to play Terraria and had to wait for it to update which failed. So I ended up uninstalling it and tried installing it from the site via .deb package which didn't work and it even failed when using apt. Went through dependency hell trying to install missing packages one by one, which wouldn't install because they all needed a specific 32bit library package called  'libllvm:i386'. Whenever I try to install this library it targets removing core components of Pop_OS don't know why, even downgrading some libraries didn't help. I pasted the print out here [libllvm:i386 installation print out](https://gist.github.com/rileyhawk1417/a495b58b0c692df003f3ca5a42f96192), am really avoiding distro hopping since I found a distro that I really like. Would appreciate any help or pointers with this.

#### Steps for reproducing this issue:

1. sudo apt-get install steam
2. 
3.

**Comment by kisak-valve** [comment]
Hello @rileyhawk1417, not letting apt proceed in this case is definitely the right answer. This is a distro packaging issue, not a Steam client issue.

In general, apt requires that the 32 bit variant and 64 bit variant of a package have exactly the same version, and it doesn't like to downgrade packages ever, so if you added a PPA which updated libllvm11, or some installed package was downgraded in Ubuntu's package repository and your system was not downgraded to match that version, that could lead to this scenario.

You could try to run something like `sudo apt install libllvm11 libllvm11:i386`, and see if apt finds a matching version, then use something like `apt policy libllvm11 libllvm11:i386` to inspect what package versions are available.

**Comment by rileyhawk1417** [comment]
@kisak-valve I see ran those commands turns out one repository is causing an issue. Although that same repo is the one I get the mesa drivers from. Tried removing libllvm11 turns out am screwed either way it will still remove system components

**Comment by kisak-valve** [comment]
Since apt didn't like that, instead of removing libllvm, maybe try to get apt to install an exact version that is available for both variants of the package at the same time? I'm guessing something similar to `sudo apt install libllvm11=11.0.0-2~ubuntu20.04.1 libllvm11:i386=11.0.0-2~ubuntu20.04.1`? (https://askubuntu.com/questions/935241/install-a-specific-package-version)

**Comment by rileyhawk1417** [comment]
Thanks that seemed to do the trick it ended up downgrading the package but at least steam is running now :). When dealing with drivers its a pain because the graphics card on this laptop is old [AMD R5 M230](https://www.techpowerup.com/gpu-specs/radeon-r5-m230.c2415), tried checking AMD website and the only version for this graphics card is for Ubuntu 14. Will just have to save up and try get a PC with NVIDIA.

**Comment by kisak-valve** [comment]
Glad to hear you got it working.

AMD's Southern Islands generation cards are fairly well supported out of the box by the mainline kernel and mesa, without the need to install a driver from outside of Ubuntu / Pop OS's repositories. If you need something newer than that, I'd look at mesa from a PPA like [oibaf](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers) or [kisak-mesa](https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa) before trying to deal with AMD's proprietary driver.

Besides the detail noted at https://github.com/ValveSoftware/Proton/wiki/For-AMD-users-having-issues-with-non-OpenGL-games, it should have been working well for you out of the box.

Closing because this was a package management issue, and not a Steam issue.

**Comment by rileyhawk1417** [comment]
Maybe its because the distro is Pop OS the configurations are different, Pop OS doesn't use grub boot-loader.
