### ISSUE TITLE
Keeps re-downloading shaders for some Proton games

### ISSUE THREAD

**Issue by ranplayer** [ValveSoftware/steam-for-linux#7980]
#### Your system information

* Steam client version (build number or date): Jul 20 2021
* Distribution (e.g. Ubuntu): Manjaro/Arch
* Opted into Steam client beta?: No
* GPU/Driver: Nvidia: 470.57.02
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Some Proton game shaders keep being re-downloaded eventually (even without updates to kernel or graphic drivers). I've noticed this issue in titles such as **Mortal Kombat 11** and **Spyro Reignted Trilogy**

**Comment by kisak-valve** [comment]
Hello @ranplayer, this issue is already being tracked at #6299. In particular to that issue report, if the size of the shader cache download is changing each time, then this is the current, expected behavior for Steam's shader pre-cache. Shader pre-cache updates (server-side) are independent from (local) video driver updates.

Closing in favor of the older issue report.
