### ISSUE TITLE
Cannot enter library in steam app

### ISSUE THREAD

**Issue by IrenvanderBeekPXL** [ValveSoftware/steam-for-linux#8018]
#### Your system information

* Steam client version (build number or date): I think I installed it 2 weeks ago as of writing
* Distribution (e.g. Ubuntu): Pop OS 20.04
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I cannot open my library on the steam app, it just gives me a blank window

#### Steps for reproducing this issue:

1. Install steam
2. install game
3. open game library

**Comment by kisak-valve** [comment]
Hello @IrenvanderBeekPXL, if you completely close Steam, then run `steam` from a terminal, does the terminal spew give a hint? Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by eNTi** [comment]
Having a similar issue:

https://gist.github.com/eNTi/86c2579af5dc46fab40a3d447578bc1a

**Comment by kisak-valve** [comment]
Hello @eNTi, you've encountered #7935, and not the issue reported here.

**Comment by rvdwalt** [comment]
I believe I'm having the same issue as above, posting here instead of creating a new ticket. This might be considered a different issue as the above poster have stated he's opted out of beta while this is a beta participation issue for myself. 

System Information:
    Ubuntu 20.04.2 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.4.0-80-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12011000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime_0.20210817.0
    
Issue in Detail:
Upon opening the steam client all of the 'browser' windows are left blank (No content is loaded). Impacted areas includes but is not necessarily limited to 'Store', 'Library', 'Community', 'Profiles', Sales notifications on open. Dialogues like 'Settings' and 'Server List' are not impacted. Most recent games and applications can be run. 

This is specific to the current Beta option, changing settings to opt out of the beta participation resolves the issue which results in runtime Version: Steam Runtime Version:  steam-runtime_0.20210630.0

wrt. the above request to the running it via console there is no console output that would give any indication what could be the impacting factor. 

Steps for reproducing this issue:
Enable beta participation.

**Comment by IrenvanderBeekPXL** [comment]
Hello. A possible hint steam gives in the terminal is 
`STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy

Forced create but already created for SharedObjectEvent`
My system information according to steam is here: https://gist.github.com/IrenvanderBeekPXL/0b5aee69b8290600bcc330777648f2e8

**Comment by IrenvanderBeekPXL** [comment]
And a little update, it does work sometimes, not always

**Comment by Qwerty-Space** [comment]
I'm also having this issue:
![image](https://user-images.githubusercontent.com/6967592/132041644-3baff119-816d-47e2-901a-a30fce440165.png)


It's like Steam has no access to the internet.  Clicking "online" does nothing, the friends list doesn't open. 
![image](https://user-images.githubusercontent.com/6967592/132041705-bfdbd7a1-3aee-4f14-9d47-a85656fb6bc4.png)


Steam output in terminal 
https://yaso.su/ZEk3kEh5

**Comment by kisak-valve** [comment]
Hello @Qwerty-Space, `./steamwebhelper: symbol lookup error: /usr/lib/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language` in your log points towards #7935, and not this issue report. Opt into Steam's client beta in the settings.

**Comment by IrenvanderBeekPXL** [comment]
And another update, I did a system upgrade, clean install and am using a different ssd, and it seems to not appear anymore...
