### ISSUE TITLE
[beta][steamwebhelper] last update wants "--quiet" md5sum option

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-for-linux#8032]
In steamwebhelper.log, the steam runtime heavy tar.xz failed to be verified because the "--quiet" option from your md5sum command is used and the busybox version of the md5sum command does not have the "--quiet" option (I created a wrapper to remove this option, then I did hit the libcups hard dependency error, see the corresponding ticket).

**Comment by smcv** [comment]
Steam for Linux is designed to run on GNU/Linux systems, and does not support use of non-GNU core utilities.

But, since avoiding the `--quiet` option is straightforward, the latest Steam update (2021-09-13, 1631572918) avoids it anyway.

This should not be interpreted as a commitment to support non-GNU core CLI utilities in the future. The only officially supported platform is (still) the latest Ubuntu LTS.

**Comment by kisak-valve** [comment]
Closing per the last comment.
