### ISSUE TITLE
Steam not considering all disks to calculate avaible space

### ISSUE THREAD

**Issue by Enzodtz** [ValveSoftware/steam-for-linux#8062]
#### Your system information

* Steam client version (build number or date): Sep 10 2021
* Distribution (e.g. Ubuntu): Linux Mint
* Opted into Steam client beta?: I don't think so
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I have 2 disks, one with 27gb remaining, and other one of 1tb that is empty.

I'm mounting the 1tb disk in `/mnt/big-drive`, and I've added a steam library in `/mnt/big-drive/Games`, via `Steam > Settings > Downloads > Steam Library Folders`.

When I try to install a game, it gives me the option to select the new folder, but the space available keeps the same: 27gb, and as the game is bigger than that, I can't install it. It is not calculating the size via all the disks, it's just looking at the one that it is installed, that is the smaller one.

#### Steps for reproducing this issue:

1. Have 2 drives connected
2. Mount the drive with `gedit /etc/fstab`
3. Reboot
4. Add disk permissions to user
5. Add mounted directory into steam via `Steam > Settings > Downloads > Steam Library Folders`
6. Try to install any game
7. See that disk space is not considering the 2 drives, only the one that steam is installed

**Comment by bjwest** [comment]
If your primary drive is full, this may be due to Steam using the system /tmp directory to download the file before installing?  You can move your user temporary directory to the larger drive by setting in your .profile.  Create /mnt/big-drive/tmp directory and add 'TMPDIR=/mnt/big-drive/tmp' to your .profile file, then log out and log back in or reboot for it to take effect.  Make sure you're mounting big-drive on boot though, or you'll have to mount it manually before logging in.

This is assuming Steam uses the system tmp directory and not a custom one.  A custom temp directory would be within it's file tree somewhere on the primary drive, so won't have enough space to even download the game before installing it.  What I've done in the past when I was running low on space was to move the entire Steam file tree to a larger drive and sym link it to my home directory.  Shut down Steam, and make sure you move and link both the ~/.steam and ~/.local/share/Steam trees.

**Comment by Enzodtz** [comment]
Well actually it was a pretty dumb mistake, seems that the gedit syntax was wrong, and the disk was not mounting, sorry.
