### ISSUE TITLE
[SteamCMD] app_info_update 1 and app_status show "Fully Installed" even if an application requires updating. Makes it impossible to check if an app needs updating.

### ISSUE THREAD

**Issue by PhonicUK** [ValveSoftware/steam-for-linux#8075]
#### Your system information

* Steam client version (build number or date): SteamCMD, latest revision. (No version info available)
* Distribution (e.g. Ubuntu): Ubuntu 20.04 LTS
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
It's not possible to know if an update is available for any application has a pending update, as SteamCMD always reports an install state of "Fully Installed" and never "Update Required" regardless of the current state.

#### Steps for reproducing this issue:

1. Install App ID 740 (CSGO Server in this case for testing) via SteamCMD into a directory called 740.
2. Wait for a new update to be released.
4. Check for updates using the following command: 
```
.\steamcmd.sh +@NoPromptForPassword 1 +login anonymous +force_install_dir 740 +app_info_update 1 +app_status 740 +quit`
```

#### Expected behaviour: 

In the output, under `install state` the state should be `Fully Installed,Update Required,`

#### Actual behaviour:

In the output, under `install state` the state is always `Fully Installed,` despite the presence of an update, and the fact that you can install an update via `app_update 740`

**Comment by PhonicUK** [comment]
Related information: `app_info_update 740` always returns the *latest* data rather than what's currently on-disk.

My suspicion is that whatever underlying mechanism does the update check is using the same incorrect data and basically comparing the latest data to the latest data and completely ignoring what's on disk.

**Comment by TTimo** [comment]
The newly released public beta of steamcmd addresses this.

You can switch to the public beta of steamcmd by creating a `beta` file in the `packages` directory containing the string `publicbeta` - e.g. `echo publicbeta > ~/.steam/steamcmd/package/beta`

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by cameronSchneider** [comment]
Your system information

    Steam client version (build number or date): SteamCMD, version 1705108307
    Distribution (e.g. Ubuntu): Windows 11
    Opted into Steam client beta?: [Yes/No] No
    Have you checked for system updates?: [Yes/No] Yes

Please describe your issue in as much detail as possible:

This issue is still present as of the 2023 version of SteamCMD. I am using force_install_dir prior to logging in. app_status is still only displaying "Fully Installed," when there is an app update available. I've checked build IDs separately (I'm using Palworld 2394010 for example), and the latest build ID reported by app_info_print does not match the local build ID.

    Install App ID 740 (CSGO Server in this case for testing) via SteamCMD into a directory called 740.
    Wait for a new update to be released.
    Check for updates using the following command:

+force_install_dir 740 +login anonymous  740 +app_info_update 1 +app_status 740 +quit`

Expected behaviour:

In the output, under install state the state should be Fully Installed,Update Required,

Actual behaviour:

In the output, under install state the state is always Fully Installed, despite the presence of an update, and the fact that you can install an update via app_update 740

I believe this issue should be reopened and re-investigated, as it has been 3 years.
