### ISSUE TITLE
[Regression]Black steam chat windows in steam overlay (after latest update?)

### ISSUE THREAD

**Issue by echaskaris** [ValveSoftware/steam-for-linux#8174]
#### Your system information

* Steam client version (build number or date): 1634882040
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: [Yes/No] y
* Have you checked for system updates?: [Yes/No] y

If you move the windows they go back to normal. They also need to move in order for their contents to be updated.
Tested with TF2.

**Comment by NoXPhasma** [comment]
> edit: it seems that it works when you turn on GPU and hardware acceleration from steam settings.
That's actually a bad idea, as this opens up a [VRAM memory leak](https://github.com/ValveSoftware/steam-for-linux/issues/6715), which is present in Steam for almost 2 years.

**Comment by echaskaris** [comment]
Enabling hardware accel fixes the issue, but steam chat windows in the overlay are not usable at all...

**Comment by DonKatsu** [comment]
#### Your system information

* Steam client version (build number or date): 11/11/2021
* Distribution (e.g. Ubuntu): Fedora 35 KDE
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam System Information: [Gist](https://gist.github.com/DonKatsu/d804139783806a7c9862dcca1eedba92)

I've got similar issues as well. Unfortunately I forget exactly when it started.

In the Library, there's this bar across the bottom between the bottom header and the content of the window. Changing games doesn't get rid of it.
![library](https://user-images.githubusercontent.com/8627704/141605497-3d850ccc-798d-4051-9029-c423963cdab3.png)

If I go to any Community tab, it renders this.
![community](https://user-images.githubusercontent.com/8627704/141605526-14dab87f-136f-47a6-a9aa-a7fa8b1763a7.png)

Resizing the window fixes both of these cases as long as Steam is still running. Closing and opening the window remains fixed.
Loading the Store page instead will fix Community tabs, but not the Library.

These issues are not present if "Enable GPU accelerated rendering in web views" is enabled. I've been keeping it disabled since it was breaking friend chat windows when enabled in the past, and there's that memory leak as well.

None of this occurs when opted out of Steam beta with "Enable GPU accelerated rendering in web views" disabled.

**Comment by kisak-valve** [comment]
Hello, "Fix Steam chat and browser windows sometimes becoming unresponsive in Steam Overlay" in the [2021-11-19](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3117049348998970575) Steam client beta update may be related to this issue. Please retest.

**Comment by echaskaris** [comment]
Yes, fixed for me.

**Comment by xpander69** [comment]
yeah overlay seems fine now, but the web content not being rendered (small part on top left only renders) issue still remains with hardwarel accel off. have to resize the steam window once to make it show up. that needs different issue ticket maybe?

**Comment by kisak-valve** [comment]
Hello @xpander69, that sounds like #8246.

**Comment by kisak-valve** [comment]
Closing as fixed in the [2021-11-23](https://store.steampowered.com/oldnews/101607) Steam client update.
