### ISSUE TITLE
[Feedback] Collaboration With Vortex Mod Manager for Linux-Steam

### ISSUE THREAD

**Issue by ThisNekoGuy** [ValveSoftware/steam-for-linux#8224]
#### Your system information

* Steam client version (build number or date): N/A (Unrelated to the topic)
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I'm aware that Steam has a workshop but I'm also aware that [Nexusmods](https://www.nexusmods.com/) also has a reputation for having a large population in regards to mod authors and users that might even exceed the Steam Workshop's.

With that said, while I value the Steam Workshop (especially since it's the only mod tool Linux has for games), a more comprehensive one would be greatly appreciated and could also be potentially beneficial for the Steam Deck later (I'll get around to explaining/talking about that).

NexusMods has their own open-source mod manager they've been working on for a while, and while it is currently Windows only, it uses cross-platform technologies and actually has an open issue page for Linux support it on its [Github](https://github.com/Nexus-Mods/Vortex). My feedback for you is to pioneer the first major general purpose mod manager, with Proton support, for Linux for a consistent feature parity of this kind of technology with Windows.

I actually [had some things in mind with how the groundwork could be laid to help achieve this](https://github.com/Nexus-Mods/Vortex/issues/2862#issuecomment-965987268), but manpower that is interested in bettering the Linux ecosystem is necessary to make this happen.

Similarly, your efforts with Proton and the Steam Deck are great boons for the Linux community and I think working on Vortex and integrating it into Steam as an extension of the Steam Workshop (and [nexusmods.com](https://www.nexusmods.com/)) would be a massively beneficial achievement for Linux gaming as a whole that would not only make game modding viable for existing and prospective users but also mod authors since this would be a new opportunity that actually has efficient support to do so. Also efficiently making PC games mod-able and port-ably via the Steam Deck would cement it even further as a powerful platform.

I would like to hear your thoughts about the potential of extending Steam modding and Linux gaming as a whole in regards to this.

**Comment by kisak-valve** [comment]
Hello @ThisNekoGuy, this issue tracker is primarily focused on the Steam for Linux client, and you're requesting a Windows-oriented third party tool to be integrated into Steam. As a Linux-only feature, I doubt the Steam devs are interested in the integration of a third party service, but as a general feature request, you might have luck generating interest over at https://steamcommunity.com/discussions/forum/10/.

**Comment by ThisNekoGuy** [comment]
@kisak-valve 
To be clear, it's again an open-source tool - this by extension doesn't explicitly make it third-party because you have free reign to do what you want with it. :/

Similarly, the same could be said about Wine, Proton, and every version of SteamOS - which is exclusively for Linux, and Wine itself is "third-party" by your definition. That's not even mentioning the fact that the tool itself *works on Windows* and can be integrated as a **_Steam tool_** or what have you for both operating systems because the lisence permits you to do so.

Just because it was made with a specific site in mind doesn't explicitly make it a third-party "service" - mods are mods; by that same stretch of the definition you could say any Steam Workshop author is also "a third-party service."

That said, I'm not trying to be rude but what you're saying doesn't add up with Valve's actions.

**Comment by somebody1234** [comment]
@ThisNekoGuy it's explicitly third party in that it's not made by valve (hence, not first-party)...

importantly, please be aware that not everyone has an infinite amount of time... plus the fact that valve doesn't exactly have an excess of manpower.

also just because a modding tool is open source doesn't mean the studio that created the game is now suddenly obligated to work on the modding tool as well? same applies here

**Comment by ThisNekoGuy** [comment]
@somebody1234 I wasn't implying obligation, I was at least expecting a modicum of legitimate insight or at least an acknowledgement of a potential improvement of the workshop, not a complete dismissal simply on the basis of: "someone besides us touched it."

**Comment by somebody1234** [comment]
@ThisNekoGuy note that third-party mod tools have nothing to do with the workshop. i believe workshop items require support in the base game - this is why any third party mod tools with workshop support (e.g. tmodloader) are a separate item on steam from the base game

that said, i believe it should be possible for nexusmods themselves to possibly add vortex to steam and add workshop integration... but then that's an issue for nexusmods to solve.

also worth noting is that it is ***impossible*** to create a "general purpose mod manager" since different games have different functions to patch. and if you say "but you can just add support for each game individually"... well yes that's a thing called steam workshop integration.
