### ISSUE TITLE
Installing games in a secondary steam library on a secondary drive causes games that are run through proton to fail to launch

### ISSUE THREAD

**Issue by DevenBL** [ValveSoftware/steam-for-linux#8263]
#### Your system information

* Steam client version (build number or date):Nov 2021, at 22:12:42 
* Distribution (e.g. Ubuntu): Pop Os NVIDIA (fresh install)
* Opted into Steam client beta?: [Yes/No]Yes
* Have you checked for system updates?: [Yes/No]Yes

#### Please describe your issue in as much detail as possible:
installing games in a secondary steam library on a secondary drive causes games that are run through proton to fail to launch

#### Steps for reproducing this issue:
1. Enable Steamplay for all titles
2. Settings>Downloads>Steam Library Folders
3. Add new Steam Library Folder and set said folder as default
4. Install a new steam game
5. Attempt to run game
6. Game fails to launch 
at this point the issue has been recreated and the rest was my additional troubleshooting steps:
7. Move steam game that just failed to launch into the original steam library folder
8. IT MAGICALLY STARTS!

**Comment by kisak-valve** [comment]
Hello @DevenBL, what game did you test and what filesystem are you using with the second Steam library folder?

**Comment by DevenBL** [comment]
I primarily tested BeamNG.drive and Risk of Rain 2 and the second Steam library folder is using NTFS the primary is using ext4

**Comment by kisak-valve** [comment]
Thanks, Proton is known to have finicky behavior with NTFS partitions and this is where your issue came from, not the fact a secondary library folder is in use. We already have [several issue tracking NTFS in general in Proton's issue tracker](https://github.com/ValveSoftware/Proton/search?q=NTFS&type=issues) which cover your issue. The general recommendation is to use a Linux native filesystem with Proton.

Closing as a duplicate.
