### ISSUE TITLE
libcef fails to initialize with invalid opcode; `-no-cef-sandbox` workaround

### ISSUE THREAD

**Issue by jpenala** [ValveSoftware/steam-for-linux#8373]
#### Your system information

* Steam client version (build number or date): Built: Feb 1 2022, at 03:46:37
* Distribution: OpenSUSE Tumbleweed, KDE Wayland session, Kernel 5.16.2, open source amdgpu driver , Mesa 21.3.4
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam client opens, but the UI shows only black screen where store,library, community etc should be, with no way to interact with anything. Steam web helper also hogs CPU running one core plus change at full blast. Disabling hardare acceleration has no effect, only switching to stable branch fixes the issue.

![Screenshot_20220201_095517](https://user-images.githubusercontent.com/59263827/151934943-56572e5a-dfd6-4033-8694-4f44272ce31b.png)

#### Steps for reproducing this issue:

1. Open Steam client beta for linux
2. Observe broken UI

**Comment by tgurr** [comment]
Just wanted to report this as well. `dmesg` is showing Chromium Embedded Framework (CEF) is constantly crashing

```
[   57.440050] traps: Chrome_IOThread[2231] trap invalid opcode ip:7f8893bbffe4 sp:7f888a1c2720 error:0 in libcef.so[7f8891475000+6fc6000]
[   81.126938] traps: Chrome_IOThread[2897] trap invalid opcode ip:7f64dc5eafe4 sp:7f64d2bed720 error:0 in libcef.so[7f64d9ea0000+6fc6000]
[  104.705789] traps: Chrome_IOThread[3204] trap invalid opcode ip:7f8055031fe4 sp:7f804b634720 error:0 in libcef.so[7f80528e7000+6fc6000]
[  128.647375] traps: Chrome_IOThread[3457] trap invalid opcode ip:7f5560d0dfe4 sp:7f5557310720 error:0 in libcef.so[7f555e5c3000+6fc6000]
[  152.392767] traps: Chrome_IOThread[6193] trap invalid opcode ip:7fa686766fe4 sp:7fa67cd69720 error:0 in libcef.so[7fa68401c000+6fc6000]
```
Also causing systemd-coredump to jump in causing additional load on the system until steam is closed.

Reverting back to stable `rm ~/.steam/steam/package/beta` allows the Steam client to work again, the previous beta was running fine as well.

Steam system log: [steam-system-info.log](https://github.com/ValveSoftware/steam-for-linux/files/7977005/steam-system-info.log)

**Comment by CamBanfield** [comment]
I can confirm the same issue here.

- Steam client version (build number or date): Built: Feb 1 2022, at 03:46:37
- Distribution: Fedora 35, Cinnamon DE, Kernel 5.16.4, open source amdgpu driver, Mesa 21.3.5
- Opted into Steam client beta?: Yes
- Have you checked for system updates?: Yes

**Comment by RPGHiro** [comment]
Same issue on Fedora 35 (on desktop with NVIDIA/Plasma and on laptop with amdgpu/Gnome).
Browser in BPM also isn't working which I suspect might be related.

**Comment by apcolvin** [comment]
I too have the same issue on opensuse tumbleweed immediately after today's update of steam beta client.    
Starting steam with -no-cef-sandbox makes the tabs function again.

[System Info](https://gist.github.com/apcolvin/85e111dca7d73e1d73ff6078e96633e5)

**Comment by rodehoed** [comment]
Can I have a #metoo? Same version, dmesg messages and also on Fedora35.

Only way to play games is using Big Picture Play modes.

**Comment by DonKatsu** [comment]
Linking my comment in another issue here.
https://github.com/ValveSoftware/steam-for-linux/issues/8349#issuecomment-1026580093

Launching with -no-cef-sandbox works for me as well.

**Comment by echaskaris** [comment]
I am NOT experiencing this issue. Ubuntu 20.04

**Comment by agurenko** [comment]
Same problem on Fedora 35, KDE Wayland, Kernel 5.16.4, open source amdgpu driver, Mesa 21.3.5 and also `-no-cef-sandbox` workaround helped

**Comment by zaggynl** [comment]
Same on OpenSUSE TW, [systeminfo](https://gist.githubusercontent.com/zaggynl/d2286d6cd674671413831d5fb3ff0a34/raw/22dbd1376498145c117537058bc1cbc8205a58e9/gistfile1.txt).

**Comment by virnik0** [comment]
Have the same problem. Checked library linking, seems to be fine. Attaching steam info report:
https://pastebin.com/xfe6D8Hw

The crash of steamwebhelper looks like this:
```
virnik@Mainframe:~/.local/share/Steam/ubuntu12_32$ /home/virnik/.local/share/Steam/ubuntu12_64/steam-runtime-heavy.sh --unpack-dir=/home/virnik/.local/share/Steam/ubuntu12_64 --runtime=steam-runtime-heavy -- ~/.steam/steam/ubuntu12_64/steamwebhelper
setup.sh[331807]: Steam runtime environment up-to-date!
Neoprávněný přístup do paměti (SIGSEGV) (core dumped [obraz paměti uložen])
virnik@Mainframe:~/.local/share/Steam/ubuntu12_32$ 
```
[assert_20220201135802_36.dmp.zip](https://github.com/ValveSoftware/steam-for-linux/files/7978636/assert_20220201135802_36.dmp.zip)

**library linking details are to be found here:**
https://pastebin.com/2bLR0Pbg
https://pastebin.com/8c4qW84k

**Library Pins**
https://pastebin.com/buU4L7AY

**Comment by Turmfalke2** [comment]
@kisak-valve Gentoo is also affected

**Comment by sylware** [comment]
custom distro: AMD dev linux kernel(git), xorg (git), mesa(git) vulkan/GL, busybox.

same crash, same workaround.

**Comment by LeonidFilbert** [comment]
manjaro same issue

**Comment by BafDyce** [comment]
I can confirm the same issue here.

    Steam client version (build number or date): Built: Feb 1 2022, at 03:46:37
    Distribution: Arch Linux, KDE, Kernel 5.15.16-hardened1-1-hardened, AMD gpu, Mesa 21.3.3 
    Opted into Steam client beta?: Yes
    Have you checked for system updates?: Yes

I can also confirm that the aformentioned workaround (`-no-cef-sandbox`) works.

**Comment by TheNamelessWonderer** [comment]
Same issue on Arch with the steam flatpak.

**Comment by stuarthayhurst** [comment]
@kisak-valve Same issue on Debian Sid, with or without flatpak

**Comment by sobkas** [comment]
Same issue on Debian Sid, works with -no-cef-sandbox.

**Comment by Druco** [comment]
Running Tumbleweed, same issue, workaround works but since I don't see that anyone else has included this, here is a chunk of 'journalctl -r' (run as user) which shows one of the systemd-coredump outputs which are occurring about 5 times a second:
[steam_journalctl.txt](https://github.com/ValveSoftware/steam-for-linux/files/7983273/steam_journalctl.txt)

**Comment by Pistos** [comment]
Steam (beta) client built: Feb 1 2022 at 03:46:37
Gentoo Linux.
Was seeing black/blank screens in the UI everywhere.
`-no-cef-sandbox` workaround works for me to restore the UI panes.

**Comment by yvanoff** [comment]
Not sure it's useful at this point, but same issue on my Gentoo install
`-no-cef-sandbox` fixed the issue for me too
Not posting more info because redondant with the rest, I also have the `libcef.so` related logs in `dmesg` if not running with `-no-cef-sandbox`

**Comment by DarkWav** [comment]
Also happens on openSUSE Tumbleweed 20220201 with Plasma 5.23.90 on Xorg here.
_Just a quick side note that excessive crash dumping in_ `/tmp` _for extended periods of time can also negatively affect the rest of your system if_ `/tmp`_'s capacity is limited on your system. It can then prevent other apps from being able to create their respective temp files correctly due to out-of-memory, potentially causing them to crash. Read more: https://wiki.archlinux.org/title/Steam/Troubleshooting#Preventing_crash_memory_dumps_

**Comment by darsparx** [comment]
On fedora 35(even w/GE's tweaked nobara project after the fact of originally noticing it) and still same issue too. Works with -no-cef-sandbox.

**Comment by pauliuszaleckas** [comment]
Still the same issue with Feb 3 build on Fedora 35

**Comment by Taulim** [comment]
Same issue here.
Just received an update a few minutes ago for the client (could not read the update log as it was black) but the problem is still present.

Pop_OS 21.10 
Steam flatpak
Steam build: Feb 3 2022, at 00:45:52

**Comment by fartboxmk2** [comment]
Another workaround if you don't want to disable sandbox and just want to launch a game is to use "small mode" under view > small mode.

**Comment by Nuitari** [comment]
@kisak-valve I confirm that the workaround here works for me.

**Comment by jpenala** [comment]
> Another workaround if you don't want to disable sandbox and just want to launch a game is to use "small mode" under view > small mode.

I'm running steam currently with `-no-browser` and then small mode, otherwise the steamwebhelper process runs wild in the background. Better than disabling sandbox, I think...

**Comment by virnik0** [comment]
> > Another workaround if you don't want to disable sandbox and just want to launch a game is to use "small mode" under view > small mode.
> 
> I'm running steam currently with `-no-browser` and then switch small mode, otherwise the steamwebhelper process runs wild in the background. Better than disabling sandbox, I think...

Thanks for the tip. In order to avoid steam and its spawns to slowly kill my system over period of time, I was using big picture mode, then killing remainder of webhelper processes. Using `-no-browser` is much better.

**Comment by Radagast** [comment]
May as well leave my comment. 

openSUSE Tumbleweed - 20220126
Nvidia 1650S
AMD FX8300
Steam Beta - Feb 3rd 2022 - 00:45:52
Steam Package Version 1643850988

Update resulted in black screen, unable to access any menu items.

Dmesg shows:

> [21475.730781] steamwebhelper[23417]: segfault at d8 ip 00007ff02a858110 sp 00007ffee025f408 error 4 in libX11.so.6.4.0[7ff02a846000+8c000]

Curiously, the steamwebhelper.log shows:

> [0204/134707.917873:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye



Which is a known glibc issue with Electron apps - [see](https://github.com/electron/electron/pull/31091) hence why ```no-sandbox``` works.

**Comment by virnik0** [comment]
> May as well leave my comment.
> 
> openSUSE Tumbleweed - 20220126 Nvidia 1650S AMD FX8300 Steam Beta - Feb 3rd 2022 - 00:45:52 Steam Package Version 1643850988
> 
> Update resulted in black screen, unable to access any menu items.
> 
> Dmesg shows:
> 
> > [21475.730781] steamwebhelper[23417]: segfault at d8 ip 00007ff02a858110 sp 00007ffee025f408 error 4 in libX11.so.6.4.0[7ff02a846000+8c000]
> 
> > [21497.846294] traps: Chrome_IOThread[23906] trap invalid opcode ip:7fdc2dc3cfe4 sp:7fdc23c90420 error:0 in libcef.so[7fdc2b4f2000+6fc6000]
> 
> Curiously, the steamwebhelper.log shows:
> 
> > [0204/134707.917873:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye
> 
> Which is a known glibc issue with Electron apps - [see](https://github.com/electron/electron/pull/31091) hence why `no-sandbox` works.

Can confirm, I had AMD FX8350 two months back, also black screen. But no Xlib errors, had the same libcef like I have with Ryzen7 now.

**Comment by Turmfalke2** [comment]
I can confirm that it is the glibc issue @Radagast pointed out. After rebuilding glibc-2.34 to not use clone3 steam no longer crashes.  
For the general mass we probably need an updated electron.

**Comment by g2p** [comment]
The patch to the chromium seccomp sandbox is here:

- https://bugs.chromium.org/p/chromium/issues/detail?id=1213452
- https://chromium-review.googlesource.com/c/chromium/src/+/2936184
- https://chromium.googlesource.com/chromium/src/+/218438259dd795456f0a48f67cbe5b4e520db88b

Via https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468

**Comment by GloriousEggroll** [comment]
tacking onto g2p's comment:
https://github.com/ValveSoftware/steam-for-linux/issues/8373#issuecomment-1030242780

Here is the TLDR:

(1) glibc 2.34 enabled clone3, which breaks applications that use an outdated version of CEF:

https://github.com/ValveSoftware/steam-for-linux/issues/8373#issuecomment-1029616820
```
Curiously, the steamwebhelper.log shows:

    [0204/134707.917873:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye

Which is a known glibc issue with Electron apps - https://github.com/electron/electron/pull/31091 hence why no-sandbox works.
```

(2) The workaround for now is to build glibc with clone3 disabled:

https://github.com/ValveSoftware/steam-for-linux/issues/8373#issuecomment-1030166869
```
I can confirm that it is the glibc issue @Radagast pointed out. After rebuilding glibc-2.34 to not use clone3 steam no longer crashes.
For the general mass we probably need an updated electron.
```

(3) This approach was applied to ubuntu's glibc for the time being:
https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468/comments/20
https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468/comments/36
```
...
I've made a patched glibc package with clone3 disabled at https://launchpad.net/~mwhudson/+archive/ubuntu/devirt/+packages?field.name_filter=glibc, would be interesting to hear if it helps.
...
...
This bug was fixed in the package glibc - 2.34-0ubuntu3

---------------
glibc (2.34-0ubuntu3) impish; urgency=medium

  * d/patches/git-updates.diff: Update from release/2.34/master branch.
    - d/patches/ubuntu/Fix-close_range-closefrom-tests.patch,
      d/patches/ubuntu/fix-iconvconfig-directory.diff: removed as now
      upstream.
  * d/patches/ubuntu/disable-clone3.patch: Disable use of clone3 syscall
    to give Electron apps more time to get rebuilt. (LP: [#1944468](https://bugs.launchpad.net/bugs/1944468))

 -- Michael Hudson-Doyle <email address hidden> Tue, 28 Sep 2021 14:38:09 +1300
...
```

(4) The actual root cause, and proper fix, is to update the applications affected (in this case, steam beta) with a CEF version that contains a commit missing from older versions:

https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468/comments/9
```
Oh looks like these electron apps were built with a chromium that lacks
this commit
https://chromium.googlesource.com/chromium/src/+/218438259dd795456f0a48f67cbe5b4e520db88b
- which was only 4 months ago. And Chromium's sandbox defaults to crashing
on unknown syscalls. So I guess we're back to the "do we disable clone3 for
impish" question.
```

**Comment by folknor** [comment]
Same issue on ubuntu jammy (dev version 22.04), all the workarounds listed here also work. Stable version works fine. libc 2.35-0ubuntu1, glib 2.71.1-1.

**Comment by doraskayo** [comment]
To add some more information, it seems that the actual change that was made in Steam's Beta update was to enable CEF's sandboxing in `steamwebhelper`.

This resulted in at least three separate issues:
1. In runtime environments **where `glibc` supports the new `clone3(2)` syscall** (which allows sandbox escape), the `steamwebhelper` process is terminated with `SIGSYS`. This is because Steam's outdated `libcef.so` is missing the logic that forces `glibc` to fall back to the `clone(2)` syscall. (described by @GloriousEggroll in [#8373 (comment)](https://github.com/ValveSoftware/steam-for-linux/issues/8373#issuecomment-1030509625))
2. In runtime environments **where unprivileged user namespaces aren't allowed**, CEF's sandbox initialization fails. This is because the only two options for setting up CEF's sandbox aren't possible: it can't be set up using user namespaces, and a SETUID binary to set it up using the root user (usually called `chrome-sandbox`) is not present in Steam's runtime environment.
3. In **sandboxed runtime environments such as Flatpak**, the sandbox initialization also fails. This is because Flatpak's own sandbox disallows both user namespaces and the use of SETUID binaries, since both allow sandbox escape, but CEF doesn't  support Flatpak's subsandboxing natively. The usual solution to this is to use [`Zypak`](https://github.com/refi64/zypak), but Steam's elaborate runtime means that `Zypak` needs to be taught additional tricks to execute binaries inside Steam's runtime environment.

The three issues above all result in a similar user experience, but each of them is an entirely different issue with an entirely different solution. Perhaps it's better to disable the sandboxing in an update and enable it again only when all three are all handled.

@kisak-valve, @smcv, @refi64

**Comment by nanonyme** [comment]
IMHO ideally rather than teach zypak new tricks Steam would run inside pressure-vessel and use zypak directly. Then it would work in same guaranteed way everywhere and this entire "Steam runtime libraries clash with host libraries" could be gradually forgotten.

**Comment by smcv** [comment]
> IMHO ideally rather than teach zypak new tricks it would make more sense if Steam ran inside pressure-vessel and use zypak directly

pressure-vessel is not (currently) designed to be able to run Steam: it is designed to run individual games, and relies on setup that has been done by Steam itself.

Similarly, Steam is not designed to run inside pressure-vessel. Steam is not really designed to run in a container *at all*, and the Steam Flatpak app is not supported by Valve.

**Comment by smcv** [comment]
> To add some more information, it seems that the actual change that was made in Steam's Beta update was to enable CEF's sandboxing in `steamwebhelper`.
> 
> This resulted in at least three separate issues

Thanks for breaking down these separate root causes: that'll make it much more likely that some or all of them can be fixed.

**Comment by danilw** [comment]
`-no-cef-sandbox` works (OpenSuse)

**Comment by Jeoshua** [comment]
Also having this issue on Ubuntu Jammy, Kernel 5.16, under both X11 and Wayland, KDE Plasma. Commenting for updates.

**Comment by nanonyme** [comment]
Just for the record, GitHub has subscribe button at the right-hand panel so comments are just for sake of comments.

**Comment by sobkas** [comment]
Debian experimental is also affected:
libc6:
  Installed: 2.34-0experimental2
  Candidate: 2.34-0experimental2
  Version table:
 *** 2.34-0experimental2 501
        501 http://ftp.icm.edu.pl/pub/Linux/debian experimental/main amd64 Packages
        501 http://http.debian.net/debian experimental/main amd64 Packages
        500 /var/lib/dpkg/status
     2.33-5 500
        500 http://ftp.icm.edu.pl/pub/Linux/debian unstable/main amd64 Packages
        500 http://ftp.icm.edu.pl/pub/Linux/debian testing/main amd64 Packages

**Comment by grgrzybek** [comment]
Works now with latest update (Steam package version: 1644454953) on Fedora 35.

**Comment by zaggynl** [comment]
OK as well on OpenSUSE TW.

**Comment by Scrumplex** [comment]
Arch has updated the toolchain today in `testing`. This issue now affects Arch Linux (testing) users.

**Comment by Scrumplex** [comment]
@DanMan I can confirm that updating the Steam Client fixes the issue. Unfortunate timing I guess :D

**Comment by smcv** [comment]
> Works now with latest update (Steam package version: 1644454953) on Fedora 35.

This update avoids the first of the three root causes for this symptom that @doraskayo enumerated (glibc >= 2.34 with clone3() enabled). I've edited [my comment above](https://github.com/ValveSoftware/steam-for-linux/issues/8373#issuecomment-1033855419) to reflect that.

As far as I know, this update does not address the second root cause (distros like Debian 10 that restrict user namespace creation). Workaround: run Steam with `-no-cef-sandbox`, or switch from the beta branch to the default (general availability) branch.

As far as I know, this update also does not address the third root cause (running in a Flatpak sandbox). Workaround: run Steam with `-no-cef-sandbox`, or switch from the beta branch to the default (general availability) branch.

**Comment by virnik0** [comment]
Went ahead and upgraded to Jammy Jellyfish (Kubuntu 22.04 beta).

Steam client updated, the release date is 09.02.2002 (yesterday). Steamwebhelper still crashes:
`(steam:2031723): LIBDBUSMENU-GLIB-WARNING **: 13:09:19.760: Trying to remove a child that doesn't believe we're it's parent.
Installing breakpad exception handler for appid(steam)/version(1644454953)
Installing breakpad exception handler for appid(steam)/version(1644454953)
Installing breakpad exception handler for appid(steam)/version(1644454953)
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
Installing breakpad exception handler for appid(steam)/version(1644454953)
assert_20220210130923_42.dmp[2033555]: Uploading dump (out-of-process)
/tmp/dumps/assert_20220210130923_42.dmp
steamwebhelper.sh[2033558]: Runtime for steamwebhelper: defaulting to /home/virnik/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
assert_20220210130923_42.dmp[2033555]: Finished uploading minidump (out-of-process): success = yes
assert_20220210130923_42.dmp[2033555]: response: CrashID=bp-51a7087b-e7d9-4a1f-a521-194642220210
assert_20220210130923_42.dmp[2033555]: file ''/tmp/dumps/assert_20220210130923_42.dmp'', upload yes: ''CrashID=bp-51a7087b-e7d9-4a1f-a521-194642220210''
Illegal instruction (core dumped)
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 2031734 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 2031734 -- steam
Installing breakpad exception handler for appid(steam)/version(1644454953)
assert_20220210130924_45.dmp[2033754]: Uploading dump (out-of-process)
/tmp/dumps/assert_20220210130924_45.dmp
assert_20220210130924_45.dmp[2033754]: Finished uploading minidump (out-of-process): success = yes
assert_20220210130924_45.dmp[2033754]: response: CrashID=bp-2b6879a8-265a-4dd9-8609-82fff2220210
assert_20220210130924_45.dmp[2033754]: file ''/tmp/dumps/assert_20220210130924_45.dmp'', upload yes: ''CrashID=bp-2b6879a8-265a-4dd9-8609-82fff2220210''
Installing breakpad exception handler for appid(steam)/version(1644454953)
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[2037418]: Runtime for steamwebhelper: defaulting to /home/virnik/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 2033556 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 2033556 -- steam
Illegal instruction (core dumped)`

Remainder of logs is the same.

**Comment by smcv** [comment]
@virnik0: if running Steam as `steam -no-cef-sandbox` does not work around the crash, then you are experiencing a different issue that *also* has the symptom of breaking the web interface.

**Comment by mhalano** [comment]
I just updated to the version 1644454953 and the web pages are being exhibited again.

**Comment by virnik0** [comment]
@kisak-valve Hello, thank you. I have cut down my prior post, using pastebin link instead.

I have also raised new ticket, hopefully it would reflect the issue properly:
https://github.com/ValveSoftware/steam-for-linux/issues/8405

**Comment by smcv** [comment]
> Can you give us more information what exactly the `-no-cef-sandbox` disables/changes? For me it sounds like it does not sandbox certain processes/applications or removes certain constraints? What I am most interested in: Does passing this flag have any security impact on the running steam (or child) applications?

Everything has a security impact, and in something as complicated as a modern web browser, few things are as simple as "this is good" or "this is bad".

When Steam displays web content, either trusted (Steam's own user interface and the Steam store) or untrusted (games' web pages), it is using a component called `steamwebhelper` which is based on CEF, an embeddable version of Chromium. The CEF sandbox is a security hardening feature that puts an extra boundary between some of the parts of CEF: it's the same as the sandboxing in the Chromium web browser, and means that even if an untrusted web page manages to exploit a bug in CEF's renderer, it can't escape from the sandbox to affect the rest of Steam, or the rest of your system.

A lot of security-hardening features are trade-offs that have a cost and a benefit, rather than being purely benefit, and this is one of them: it adds protection, but reduces portability and robustness. On some systems it protects CEF against some attacks, but on some systems it just doesn't work.

The CEF sandbox is not used in the current general-availability branch of Steam, and was newly enabled in recent beta versions of Steam, which is why those versions no longer work in some system configurations. Passing the `-no-cef-sandbox` option to a beta version of Steam returns it to (approximately) the behaviour of the general-availability branch.

There are three common reasons for the CEF sandbox to fail, as previously summarized in https://github.com/ValveSoftware/steam-for-linux/issues/8373#issuecomment-1030699670 and https://github.com/ValveSoftware/steam-for-linux/issues/8373#issuecomment-1033855419.

1. If your glibc is too new, it uses system calls that the CEF sandbox wasn't expecting, resulting in a crash. This is a bug in the version of CEF that Steam is using. The ideal solution would be to patch that version of CEF to be more compatible with new glibc, but the people who could do that [are probably quite busy at the moment](https://www.google.com/search?q=steam+deck+release+date). The next best thing is to disable the CEF sandbox on these systems for now, which should happen automatically in a new Steam beta at some point.

2. If your kernel is in an extra-paranoid configuration, the CEF sandbox might not be allowed to use the OS features that it needs. Some older operating systems like Debian 10 are set up like this, because disabling those features protects the OS from certain attacks; the cost of this is that unprivileged components like Chromium, Steam and Flatpak cannot use those features to protect themselves from *different* attacks. The CEF sandbox cannot work on these OS configurations, and the only thing Steam can do to resolve this is to disable the CEF sandbox if one of these operating systems is detected. This should happen  automatically in a new Steam beta at some point. If you have one of these OS configurations, you should reassess whether disabling user namespaces is actually helping you: in Debian, there was some discussion between the kernel team, the security team and maintainers of apps that need these features, which led to these features being [enabled by default](https://www.debian.org/releases/bullseye/amd64/release-notes/ch-information.en.html#linux-user-namespaces) since Debian 11.

3. If you are running Steam as a Flatpak app, then all of Steam and all Steam games are already running in a sandboxed environment. The problem is that the CEF sandbox is not compatible with this: the two layers of sandboxing fight with each other. I've been looking into applying the same techniques that are used in Electron-based Flatpak apps, which would result in the CEF sandbox being replaced by a separate, more-restrictive Flatpak sandbox, but it's complicated and hard to get right. The next best thing is to disable the CEF sandbox automatically when running under Flatpak, which should happen automatically at some point in either a new Steam beta, or [a new version of the Flatpak app](https://github.com/flathub/com.valvesoftware.Steam/pull/867), or both.

**Comment by jpenala** [comment]
I'm closing this as it's working now.

**Comment by TheNamelessWonderer** [comment]
Has this been fixed officially? If you are running the three scenarios listed here: https://github.com/ValveSoftware/steam-for-linux/issues/8373#issuecomment-1039339935 does the Web-UI work? I'm running the flatpak and I'm pretty sure it is still broken.

**Comment by jpenala** [comment]
> Has this been fixed officially?

I guess since the official steam beta works. Flatpak build afaik isn't officially suppoted by valve, but there's already [MR for it though](https://github.com/flathub/com.valvesoftware.Steam/pull/867)

**Comment by TheNamelessWonderer** [comment]
What about scenarios 1 and 2? Shouldn't it detect if the configuration is invalid and then disable the sandbox? As far as I know it doesn't do this yet. Maybe OpenSUSE Tumbleweed have patched something (maybe glibc) to fix the issue.

**Comment by smcv** [comment]
There are at least three known root-causes for this symptom, so it isn't quite as simple as "it's fixed" or "it isn't fixed".

> 1. If your glibc is too new, it uses system calls that the CEF sandbox wasn't expecting, resulting in a crash.

As I said [before](https://github.com/ValveSoftware/steam-for-linux/issues/8373#issuecomment-1033855419), more recent Steam beta clients have a workaround for this. `pgrep steamweb | xargs ps ww` will show that the `--disable-seccomp-filter-sandbox` parameter has been passed to the `steamwebhelper`. This is a narrower version of the `-no-cef-sandbox` workaround. I have checked this on Fedora 35 (another affected OS) and it works.

This is the one that the initial reporter of this issue, @jpenala, was suffering from, so I think we can say that if it works for @jpenala then it's fixed.

> 2. If your kernel is in an extra-paranoid configuration, the CEF sandbox might not be allowed to use the OS features that it needs. Some older operating systems like Debian 10 are set up like this

This is not fixed. I have reported it separately as #8420.

> 3. If you are running Steam as a Flatpak app

This is not fixed. I have reported it separately as #8421. (@TheNamelessWonderer: this is the one that is affecting you.)

**Comment by darkguy2008** [comment]
> Also having this issue on Ubuntu Jammy, Kernel 5.16, under both X11 and Wayland, KDE Plasma. Commenting for updates.

Maybe related, or unrelated to Steam for Linux, but running Teams with `--no-sandbox` (like in real Chrome) makes it work. I'm thinking there's something wrong going on in libcef and the latest >= 5.15.x kernels.

I don't know much but it seems to be due to a paranoid security setting in those kernels (I guess?). Is there a way to fix this without making a full kernel build from source? I'm also getting the invalid opcode error:
```
[  364.373909] traps: Chrome_IOThread[6142] trap invalid opcode ip:55bfd2a27774 sp:7f42c5162490 error:0 in teams[55bfd042c000+5fc7000]
```
Thanks!

**Comment by smcv** [comment]
@darkguy2008: this is the Steam for Linux issue tracker, we cannot support non-Steam products.

The usual reason for the Chromium sandbox to have problems on upgraded systems is that after upgrading either glibc or the kernel, glibc automatically makes use of newer system calls provided by the new kernel; but the Chromium sandbox uses a strict seccomp filter that deliberately crashes the sandboxed process if it tries to use a system call that the sandbox wasn't expecting.

The short-term solution is for the developer of the crashing process (in this case Valve) to upgrade their version of Chromium/CEF/Chrome/Electron/etc. to one that knows about the newer system calls and will either allow them, or make them fail gracefully with `ENOSYS`, so that glibc thinks it is running on an older kernel and will fall back to an older code path.

The long-term solution is for Chromium to stop crashing on syscalls that it doesn't yet know about, and instead make them fail with `ENOSYS` so that glibc can fall back.

**Comment by lockie** [comment]
> As I said https://github.com/ValveSoftware/steam-for-linux/issues/8373#issuecomment-1033855419, more recent Steam beta clients have a workaround for this.

I'm still affected by this bug on Gentoo as of now, both regular and beta Steam client versions.

**Comment by smcv** [comment]
> I'm still affected by this bug on Gentoo as of now, both regular and beta Steam client versions.

Please report a separate bug with full details, logs etc., mentioning Gentoo in the bug title.

If disabling `clone3()` in glibc does not work around the problem, then you have probably found a *different* way in which the CEF sandbox in Steam's version of CEF is incompatible with newer or rolling-release host systems, and Steam's developers will need enough information to figure out what.
