### ISSUE TITLE
unable to launch game

### ISSUE THREAD

**Issue by jinp6565** [ValveSoftware/steam-for-linux#8376]
#### Your system information

* Steam client version (build number or date):  steam:i386 is already the newest version (1:1.0.0.61-2ubuntu3).

* Distribution (e.g. Ubuntu):  Ubuntu 20.04
* Opted into Steam client beta?: [Yes/No]  not sure
* Have you checked for system updates?: [Yes/No]  not sure

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.cu
#### Steps for reproducingl this issue:

1. install steam on ubuntu 20.04
2.  run steam, install America's Army
3. try to launch America's Army 

A window popup:
Steam Error
An error occurred while updating America's Army: Proving Grounds Dedicated Server (missing executable):
/home/me/.steam/steam/steamapps/common/AAPG Dedicated Server/Binaries/Win32/AAGameServer.exe

it is a game working on linux, so the install button is enabled, why it looking for exe file?

**Comment by kisak-valve** [comment]
Hello @jinp6565, it looks like this game server has a linux depot (203303) that is updated along with the Windows variant of the server. It is their headless dedicated server and not the game client. The error message comes from Steam trying to use the only launch config for the server and it is missing a launch config for the Linux variant of the server, which is not usually needed on a server since most server admins run the dedicated server software directly without using the full Steam client.

This is something which should be evaluated by the game's dev(s).
