### ISSUE TITLE
Civilization IV throws up Windows error dialogs, doesn't run, and Steam BPM window is borked after

### ISSUE THREAD

**Issue by someg33zer** [ValveSoftware/steam-for-linux#8384]
#### Your system information

* Steam client version (build number or date): Jan 16 2022, at 17:43:49
* Distribution (e.g. Ubuntu): Ubuntu 21.10
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
From Big Picture Mode (BPM), tried to run Civilization IV with Proton.  Got two error message dialog boxes show up complaining about XML issues, then the BPM interface comes back but it's like a non-fullscreen window over the desktop:

![Screenshot from 2022-02-03 16-38-06](https://user-images.githubusercontent.com/37599789/152389456-f80dcba9-f378-4fbd-8466-09a7684b8e48.png)
![Screenshot from 2022-02-03 16-38-16](https://user-images.githubusercontent.com/37599789/152389496-dd828b32-0616-43db-b217-af0b933c1b6f.png)
![Screenshot from 2022-02-03 16-38-50](https://user-images.githubusercontent.com/37599789/152389508-24d5b498-f4f8-4eec-b3c4-25cab35631fb.png)

The same happens from the non-BPM Steam interface with the same dialog boxes but the Steam interface windows are fine.

#### Steps for reproducing this issue:

1. Run Civilization IV

**Comment by kisak-valve** [comment]
Hello @someg33zer, for the Big Picture mode half of this issue report, this issue is already being tracked at #8280.

For Civilization IV side, we're tracking issues with games run with Proton in the Proton issue tracker. Additionally, we're using one issue report per unofficially supported game title. Feel free to add your experience with the game to https://github.com/ValveSoftware/Proton/issues/1973.

Closing in favor of the older issue reports.
