### ISSUE TITLE
After today's(2022-03-04) update browser is completely black

### ISSUE THREAD

**Issue by farmboy0** [ValveSoftware/steam-for-linux#8451]
#### Your system information

* Steam client version (build number or date): March 4, 2022, at 17:59:32
* Distribution (e.g. Ubuntu):  Gentoo
* Opted into Steam client beta?: [Yes/No] Happens with beta and stable
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

The browser part of the steam window is completely black. The menu and bottom part of the steam window are shown normally.
Console prints alot of the following:
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 18004 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 18004 -- steam
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[20363]: Runtime for steamwebhelper: defaulting to /mnt/daten/Home/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
Steam worked before the March 4 update and after it this happens.

#### Steps for reproducing this issue:

1. start steam
2. 
3.

**Comment by Apfelwurm** [comment]
I have the same problem with Debain 10, so its not only gentoo specific

**Comment by asciiscry3r** [comment]
Have the same problem 
`Linux mksredmibook14ii 5.16.12-arch1-1 #1 SMP PREEMPT Wed, 02 Mar 2022 12:22:51 +0000 x86_64 GNU/Linux
`

`[  536.283363] show_signal: 745 callbacks suppressed
[  536.283371] traps: steamwebhelper[7592] trap invalid opcode ip:7f9cd568afe4 sp:7ffeaeeea360 error:0 in libcef.so[7f9cd2f40000+6fc6000]
[  541.537467] traps: steamwebhelper[7749] trap invalid opcode ip:7ff25b200fe4 sp:7ffcce056320 error:0 in libcef.so[7ff258ab6000+6fc6000]
[  551.752614] traps: steamwebhelper[7856] trap invalid opcode ip:7f06d288efe4 sp:7ffff0890230 error:0 in libcef.so[7f06d0144000+6fc6000]
[  561.874873] traps: steamwebhelper[7946] trap invalid opcode ip:7f4b90f5efe4 sp:7ffe98cdb5a0 error:0 in libcef.so[7f4b8e814000+6fc6000]
[  572.066457] traps: steamwebhelper[8033] trap invalid opcode ip:7f016b057fe4 sp:7fff77624ff0 error:0 in libcef.so[7f016890d000+6fc6000]
[  582.329043] traps: steamwebhelper[8117] trap invalid opcode ip:7f93a3b21fe4 sp:7fffaaf3bf30 error:0 in libcef.so[7f93a13d7000+6fc6000]
[  592.391194] traps: steamwebhelper[8225] trap invalid opcode ip:7f7a4e69afe4 sp:7ffc4421d350 error:0 in libcef.so[7f7a4bf50000+6fc6000]
[  602.540655] traps: steamwebhelper[8329] trap invalid opcode ip:7f6f93417fe4 sp:7ffd8a9775e0 error:0 in libcef.so[7f6f90ccd000+6fc6000]
[  612.687534] traps: steamwebhelper[8388] trap invalid opcode ip:7f00ae9dbfe4 sp:7ffde58a0b90 error:0 in libcef.so[7f00ac291000+6fc6000]
[  622.785324] traps: steamwebhelper[8492] trap invalid opcode ip:7f5373a58fe4 sp:7ffebd2cc720 error:0 in libcef.so[7f537130e000+6fc6000]
[  632.961748] traps: steamwebhelper[8655] trap invalid opcode ip:7f55b37c7fe4 sp:7ffdc19ebe90 error:0 in libcef.so[7f55b107d000+6fc6000]
[  643.170126] traps: steamwebhelper[8753] trap invalid opcode ip:7f89be583fe4 sp:7fff386a2310 error:0 in libcef.so[7f89bbe39000+6fc6000]
[  653.298072] traps: steamwebhelper[8838] trap invalid opcode ip:7f65cabb2fe4 sp:7ffd66320d20 error:0 in libcef.so[7f65c8468000+6fc6000]
[  663.377876] traps: steamwebhelper[8966] trap invalid opcode ip:7f584e445fe4 sp:7ffd177764d0 error:0 in libcef.so[7f584bcfb000+6fc6000]
[  674.343237] traps: steamwebhelper[9111] trap invalid opcode ip:7fcb6fd4bfe4 sp:7ffd885d5470 error:0 in libcef.so[7fcb6d601000+6fc6000]
[  683.818387] traps: steamwebhelper[9226] trap invalid opcode ip:7f5d0d7dbfe4 sp:7fffd64aa3e0 error:0 in libcef.so[7f5d0b091000+6fc6000]
[  693.856468] traps: steamwebhelper[9419] trap invalid opcode ip:7faa74bbffe4 sp:7fff238a98f0 error:0 in libcef.so[7faa72475000+6fc6000]
[  703.997732] traps: steamwebhelper[9504] trap invalid opcode ip:7f2c29473fe4 sp:7ffe13d1d830 error:0 in libcef.so[7f2c26d29000+6fc6000]
[  714.137871] traps: steamwebhelper[9754] trap invalid opcode ip:7f1ddb15dfe4 sp:7ffc1646cc20 error:0 in libcef.so[7f1dd8a13000+6fc6000]
[  724.334750] traps: steamwebhelper[9830] trap invalid opcode ip:7f5cd8f92fe4 sp:7ffe0495ca90 error:0 in libcef.so[7f5cd6848000+6fc6000]
[  734.410727] traps: steamwebhelper[9913] trap invalid opcode ip:7f234a320fe4 sp:7ffd19bdd0c0 error:0 in libcef.so[7f2347bd6000+6fc6000]
[  744.466152] traps: steamwebhelper[10011] trap invalid opcode ip:7fbdf9a8dfe4 sp:7ffca27bcaa0 error:0 in libcef.so[7fbdf7343000+6fc6000]
[  754.735321] traps: steamwebhelper[10097] trap invalid opcode ip:7fcb23121fe4 sp:7ffe455b2950 error:0 in libcef.so[7fcb209d7000+6fc6000]
[  764.910858] traps: steamwebhelper[10171] trap invalid opcode ip:7fb5b7228fe4 sp:7ffc450ec1a0 error:0 in libcef.so[7fb5b4ade000+6fc6000]
[  775.058127] traps: steamwebhelper[10252] trap invalid opcode ip:7f008bf5bfe4 sp:7ffc93f91350 error:0 in libcef.so[7f0089811000+6fc6000]
[  785.194402] traps: steamwebhelper[10393] trap invalid opcode ip:7f8a9c37dfe4 sp:7ffc1ed585e0 error:0 in libcef.so[7f8a99c33000+6fc6000]
[  795.288792] traps: steamwebhelper[10479] trap invalid opcode ip:7f4736173fe4 sp:7ffeee625720 error:0 in libcef.so[7f4733a29000+6fc6000]
[  805.435877] traps: steamwebhelper[10572] trap invalid opcode ip:7f995e358fe4 sp:7ffdb1b42830 error:0 in libcef.so[7f995bc0e000+6fc6000]
[  815.587690] traps: steamwebhelper[10618] trap invalid opcode ip:7f9ec5aecfe4 sp:7ffed2b70ce0 error:0 in libcef.so[7f9ec33a2000+6fc6000]
[  825.682450] traps: steamwebhelper[10715] trap invalid opcode ip:7f581a28efe4 sp:7ffe86453600 error:0 in libcef.so[7f5817b44000+6fc6000]
[  835.843256] traps: steamwebhelper[10770] trap invalid opcode ip:7fed83915fe4 sp:7ffd01fbde00 error:0 in libcef.so[7fed811cb000+6fc6000]
[  845.907531] traps: steamwebhelper[10860] trap invalid opcode ip:7f689987efe4 sp:7ffcaa00e640 error:0 in libcef.so[7f6897134000+6fc6000]
[  856.134706] traps: steamwebhelper[10970] trap invalid opcode ip:7fbbffc1cfe4 sp:7fffaa1b6f90 error:0 in libcef.so[7fbbfd4d2000+6fc6000]
[  866.246751] traps: steamwebhelper[11093] trap invalid opcode ip:7f23cdc5efe4 sp:7ffd6ab123d0 error:0 in libcef.so[7f23cb514000+6fc6000]
[  876.455327] traps: steamwebhelper[11161] trap invalid opcode ip:7fca38310fe4 sp:7ffee01c6a00 error:0 in libcef.so[7fca35bc6000+6fc6000]
[  886.323738] traps: steamwebhelper[11440] trap invalid opcode ip:7ffbe6453fe4 sp:7fffd30fb4a0 error:0 in libcef.so[7ffbe3d09000+6fc6000]
[  896.728990] traps: steamwebhelper[11565] trap invalid opcode ip:7f0df0e91fe4 sp:7ffd5b95ac60 error:0 in libcef.so[7f0dee747000+6fc6000]
[  906.865839] traps: steamwebhelper[11644] trap invalid opcode ip:7f4d9a8c3fe4 sp:7ffe56bad770 error:0 in libcef.so[7f4d98179000+6fc6000]
[  917.037531] traps: steamwebhelper[11741] trap invalid opcode ip:7f03d56edfe4 sp:7ffe1e3b3780 error:0 in libcef.so[7f03d2fa3000+6fc6000]
[  927.080837] traps: steamwebhelper[11942] trap invalid opcode ip:7f1e785affe4 sp:7ffc68894b10 error:0 in libcef.so[7f1e75e65000+6fc6000]
[  937.695560] traps: steamwebhelper[11989] trap invalid opcode ip:7f60c2019fe4 sp:7ffe9f2d1b30 error:0 in libcef.so[7f60bf8cf000+6fc6000]
[  947.359059] traps: steamwebhelper[12090] trap invalid opcode ip:7f3d7f657fe4 sp:7ffef8e30210 error:0 in libcef.so[7f3d7cf0d000+6fc6000]
[  957.521430] traps: steamwebhelper[12168] trap invalid opcode ip:7f005f3f3fe4 sp:7ffec57f84c0 error:0 in libcef.so[7f005cca9000+6fc6000]
`

`[max@mksredmibook14ii ~]$ steam
steam.sh[11285]: Running Steam on arch rolling 64-bit
steam.sh[11285]: STEAM_RUNTIME is enabled automatically
setup.sh[11359]: Steam runtime environment up-to-date!
steam.sh[11285]: Steam client's requirements are satisfied
[2022-03-04 23:25:32] Startup - updater built Mar  4 2022 17:59:04
Installing breakpad exception handler for appid(steam)/version(1646418560)
[2022-03-04 23:25:33] Loading cached metrics from disk (/home/max/.local/share/Steam/package/steam_client_metrics.bin)
[2022-03-04 23:25:33] Using the following download hosts for Public, Realm steamglobal
[2022-03-04 23:25:33] 1. https://cdn.akamai.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2022-03-04 23:25:33] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2022-03-04 23:25:33] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1646418560)
[2022-03-04 23:25:33] Verifying installation...
[2022-03-04 23:25:33] Verification complete
Loaded SDL version 2.0.21-7110979
Installing breakpad exception handler for appid(steam)/version(1646418560)
Fontconfig warning: line 5: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/48-spacing.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
steamwebhelper.sh[11440]: Runtime for steamwebhelper: defaulting to /home/max/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
Installing breakpad exception handler for appid(steam)/version(1646418560)
Installing breakpad exception handler for appid(steam)/version(1646418560)
Installing breakpad exception handler for appid(steam)/version(1646418560)
Installing breakpad exception handler for appid(steam)/version(1646418560)
Installing breakpad exception handler for appid(steam)/version(1646418560)
Installing breakpad exception handler for appid(steam)/version(1646418560)
CAppInfoCacheReadFromDiskThread took 32 milliseconds to initialize
Installing breakpad exception handler for appid(steam)/version(1646418560)
Installing breakpad exception handler for appid(steam)/version(1646418560)
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Installing breakpad exception handler for appid(steam)/version(1646418560)
Installing breakpad exception handler for appid(steam)/version(1646418560)
Installing breakpad exception handler for appid(steam)/version(1646418560)
Installing breakpad exception handler for appid(steam)/version(1646418560)
Installing breakpad exception handler for appid(steam)/version(1646418560)
Installing breakpad exception handler for appid(steam)/version(1646418560)
Installing breakpad exception handler for appid(steam)/version(1646418560)
Installing breakpad exception handler for appid(steam)/version(1646418560)
Installing breakpad exception handler for appid(steam)/version(1646418560)
Installing breakpad exception handler for appid(steam)/version(1646418560)

(steam:11416): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()
Installing breakpad exception handler for appid(steam)/version(1646418560)
Connectivity test: result=Connected, in progress=0
roaming config store loaded successfully - 165 bytes.
migrating temporary roaming config store
BRefreshApplicationsInLibrary 1: 19ms
Installing breakpad exception handler for appid(steam)/version(1646418560)
Failed to init SteamVR because it isn't installed
ExecCommandLine: "'/home/max/.local/share/Steam/ubuntu12_32/steam'"
System startup time: 3.58 seconds
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
Installing breakpad exception handler for appid(steam)/version(1646418560)
assert_20220304232543_26.dmp[11563]: Uploading dump (out-of-process)
/tmp/dumps/assert_20220304232543_26.dmp
steamwebhelper.sh[11565]: Runtime for steamwebhelper: defaulting to /home/max/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
assert_20220304232543_26.dmp[11563]: Finished uploading minidump (out-of-process): success = yes
assert_20220304232543_26.dmp[11563]: response: CrashID=bp-aed2f6a8-8298-464d-838e-1f9b02220304
assert_20220304232543_26.dmp[11563]: file ''/tmp/dumps/assert_20220304232543_26.dmp'', upload yes: ''CrashID=bp-aed2f6a8-8298-464d-838e-1f9b02220304''
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 11439 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 11439 -- steam
Installing breakpad exception handler for appid(steam)/version(1646418560)
assert_20220304232545_29.dmp[11636]: Uploading dump (out-of-process)
/tmp/dumps/assert_20220304232545_29.dmp
assert_20220304232545_29.dmp[11636]: Finished uploading minidump (out-of-process): success = yes
assert_20220304232545_29.dmp[11636]: response: CrashID=bp-5d6e5f3b-fbfb-42e5-84ed-b9e0a2220304
assert_20220304232545_29.dmp[11636]: file ''/tmp/dumps/assert_20220304232545_29.dmp'', upload yes: ''CrashID=bp-5d6e5f3b-fbfb-42e5-84ed-b9e0a2220304''
Installing breakpad exception handler for appid(steam)/version(1646418560)
Installing breakpad exception handler for appid(steam)/version(1646418560)
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[11644]: Runtime for steamwebhelper: defaulting to /home/max/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 11564 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 11564 -- steam
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[11741]: Runtime for steamwebhelper: defaulting to /home/max/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 11643 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 11643 -- steam
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[11942]: Runtime for steamwebhelper: defaulting to /home/max/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 11740 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 11740 -- steam
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[11989]: Runtime for steamwebhelper: defaulting to /home/max/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 11941 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 11941 -- steam
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[12090]: Runtime for steamwebhelper: defaulting to /home/max/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 11988 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 11988 -- steam
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[12168]: Runtime for steamwebhelper: defaulting to /home/max/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12089 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12089 -- steam
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[12241]: Runtime for steamwebhelper: defaulting to /home/max/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12167 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12167 -- steam
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[12330]: Runtime for steamwebhelper: defaulting to /home/max/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12240 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12240 -- steam
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[12432]: Runtime for steamwebhelper: defaulting to /home/max/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12329 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12329 -- steam
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[12507]: Runtime for steamwebhelper: defaulting to /home/max/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12431 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12431 -- steam
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[12624]: Runtime for steamwebhelper: defaulting to /home/max/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12506 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12506 -- steam
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[12696]: Runtime for steamwebhelper: defaulting to /home/max/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12623 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12623 -- steam
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[12767]: Runtime for steamwebhelper: defaulting to /home/max/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12695 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12695 -- steam
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[12846]: Runtime for steamwebhelper: defaulting to /home/max/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12766 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12766 -- steam
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[12915]: Runtime for steamwebhelper: defaulting to /home/max/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12845 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12845 -- steam
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
src/common/html/chrome_ipc_client.cpp (410) : m_hCEFHandle == INVALID_PROCESS_HANDLE
steamwebhelper.sh[12988]: Runtime for steamwebhelper: defaulting to /home/max/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12914 -- steam
src/steamexe/main.cpp (253) : Assertion Failed: reaping pid: 12914 -- steam
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  40 (X_TranslateCoords)
Resource id in failed request:  0x40013f
Serial number of failed request:  184589
xerror_handler: X failed, continuing

(steam:11416): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed

(steam:11416): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(steam:11416): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed

(steam:11416): GLib-GObject-CRITICAL **: g_object_unref: assertion `G_IS_OBJECT (object)' failed
[2022-03-04 23:28:35] Shutdown
[max@mksredmibook14ii ~]$ 
`

**Comment by kisak-valve** [comment]
Hello @farmboy0, please give #8420 a read and see if you're missing or have restricted user namespace support in your kernel as described in that issue report.

@Apfelwurm, #8420 is definitely relevant to your system.

@asciiscry3r, that may apply to you as well. As a side note, please use a [gist](https://gist.github.com) or other pastebin service in the future instead of copy/pasting large walls of text as it makes it more difficult to hold a conversation along with the logs.

Regardless, if your issues are sandbox-related, then completely closing Steam, then running `steam -no-cef-sandbox` from a terminal should workaround the issue. If it's not sandbox-related, then each issue with libcef running on separate distros needs to be evaluated separately.

**Comment by Apfelwurm** [comment]
> @Apfelwurm, #8420 is definitely relevant to your system.

Thanks for the fast reply, the `-no-cef-sandbox` parameter works for me as workaround, on the long term i will upgrade to debian 11!

**Comment by farmboy0** [comment]
@kisak-valve Thanks for the pointers, my kernel didnt support user namespaces.

**Comment by teslatheg0d** [comment]
`-no-cef-sandbox` WORKS....
STILL needs to be fixed

**Comment by snostormjp** [comment]
Still an issue on ArchLinux Latest updates , beta and  standard. The option above does still work around issue

**Comment by FlyingWombat** [comment]
Same here on Arch Linux using `steam-native` -- launching steam with its bundled runtime, `steam-runtime` works.  So, this must be an incompatibility the steam client has with some newer library version.
```
steamwebhelper.sh[1614]: Runtime for steamwebhelper: disabled by environment (this is unsupported)
steamwebhelper.sh[1614]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
...
src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 2179 -- steam
```

A steam-beta update broke like this a few weeks ago, reverted to stable and it still worked. Today, stable got that update, and now both are broken.

**Comment by kisak-valve** [comment]
Hello @FlyingWombat, running Steam with the Steam runtime disabled is not supported. Any issues you have with `steam-native` must be evaluated by the package maintainers who helped you disable the runtime.

That said, https://bugs.archlinux.org/task/75600 is the issue you're looking for. Your comment is unrelated to the issue which was reported here.

**Comment by FlyingWombat** [comment]
OK, thank you for your help.
