### ISSUE TITLE
CS:GO launches a black window and then disappears

### ISSUE THREAD

**Issue by RickAndTired** [ValveSoftware/steam-for-linux#8480]
#### Your system information

* Steam client version (build number or date): Built: Mar 9 2022 at 05:48:15 (non-beta) and Mar 10 2022 at 20:44:57 (beta)
* Distribution (e.g. Ubuntu): Ubuntu 21.10
* Opted into Steam client beta?: [Yes/No] No and yes (I have tried both non-beta and beta)
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

Launching CS:GO opens a black screen window and then it disappears about 20 seconds later
I have already tried "Verify integrity of game files..."

#### Steps for reproducing this issue:

1. Launch CS:GO
2. Crash

**Comment by kisak-valve** [comment]
Hello @RickAndTired, this issue is already being tracked in various issue reports like https://github.com/ValveSoftware/csgo-osx-linux/issues/2659 / https://github.com/ValveSoftware/csgo-osx-linux/issues/2815 and/or https://github.com/ValveSoftware/csgo-osx-linux/issues/1757. Closing as a duplicate.
