### ISSUE TITLE
[Feature Request] Add global launch option.

### ISSUE THREAD

**Issue by LyrixCaz** [ValveSoftware/steam-for-linux#8495]
System information:
* Steam client version: Recent/Latest
* Distribution: OpenSUSE Tumbleweed 
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]

Adding the use of a global launch option would help specially users that use gamemoderun or even variables like DRI_PRIME=1. The other reason for this  is because its tiddeous to go tittle by tittle disabling the same options when for example a user deletes tools like mangohud or gamemode; the game would fail to launch and hence you would have to delete said launch parameters..

#### Steps for reproducing this issue:

1. Launch Steam Client
2. Search for a global launch option
3. Realize there is no global launch option.

**Comment by kisak-valve** [comment]
Hello @LyrixCaz, this feature request is already being tracked at #3453. Closing as a duplicate.

**Comment by LyrixCaz** [comment]
> Hello @LyrixCaz, this feature request is already being tracked at #3453. Closing as a duplicate.

Just saw #3453 i dont mean to add it to the steam client, but with launching the games.

**Comment by damster101** [comment]
> > Hello [@LyrixCaz](https://github.com/LyrixCaz), this feature request is already being tracked at [#3453](https://github.com/ValveSoftware/steam-for-linux/issues/3453). Closing as a duplicate.
> 
> Just saw [#3453](https://github.com/ValveSoftware/steam-for-linux/issues/3453) i dont mean to add it to the steam client, but with launching the games.

I think environment variables Steam is launched with should be inherited by the games Steam launches. The effects of running Steam with prime-run or similar scripts as well.

**Comment by damster101** [comment]
> Hello [@LyrixCaz](https://github.com/LyrixCaz), this feature request is already being tracked at [#3453](https://github.com/ValveSoftware/steam-for-linux/issues/3453). Closing as a duplicate.

That is a different feature being requested. Setting global game launch options as requested here, instead of Steam launch options that indirectly apply to everything Steam launches, can have the significant benefit of allowing to easily override them per game (could be disabled for individual games by just entering `%command%` to their launch options, for example). Especially scripts like prime-run, that set a bunch of environment variables, cannot practically be reverted otherwise; and you don't want Steam to constantly run on the dedicated GPU, wasting power, anyway. I think this issue should be re-opened.
