### ISSUE TITLE
Steam Controller Support With 3rd Party Flatpak Games

### ISSUE THREAD

**Issue by tmcd35** [ValveSoftware/steam-for-linux#8599]
#### Your system information

* Steam client version: latest stable
* Distribution: Any (Manjaro KDE) 
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I've reported this over on Flatpaks Github but think it should be looked at here as well. 

When adding a Non Steam Game to the Library that has controller support and was installed as a Flatpak, the Steam Controller does not pass to the game. Controls are forced into Desktop Configuration mode. 

This happens because the hooks used by the Steam Client to inject the Steam Overlay into the game fail to pass through Flatpak virtual container security.  Without the Overlay running Controller mapping is unavailable and thus the system defaults to Desktop Configuration. 

With the new SteamOS UI (-gamepadui) seemingly not supporting Desktop Configuration for controllers, and SteamOS promoting Fkatpaks for 3rd party application delivery, a way needs to be found to properly support Steam Controls through Flatpak for non SteamOS Linux users. 

Neither "switch to SteamOS" or "Don't use Flatpaks" feel like fair or sensible options. 

#### Steps for reproducing this issue:

1. Install a 3rd party game to the OS using Flatpaks (eg. RetroArch) 
2. Add installed game to Steam Library via Non Steam Shortcut
3. Setup Big Picture Mode Controller mappings, eg default Gamepad configuration 
4. Run game from Steam Client
5. Controller configurations will be ignored, controller will default to Desktop Mode configuration 
6. Pressing Guide button on controller WILL NOT display Steam Overlay (it should).

**Comment by kisak-valve** [comment]
Hello @tmcd35, this issue is already being tracked at #8583. Closing as a duplicate.

**Comment by tmcd35** [comment]
Not sure this is a duplicate issue.  #8583 seems to be referring to general controller profiles.  This issue is specifically regarding interfacing with Flatpak installed apps/games.

**Comment by GorrillaRibs** [comment]
Am having this same issue on steamos on a Deck, FWIW - in game mode, controller configuration with flatpaks works as expected (tested in GZDOOM and Retroarch) but in desktop mode it doesn't (no controller config or steam overlay). Regular steam games and non-flatpak nonsteam games both work as expected in desktop mode

**Comment by creativecoder** [comment]
Having the same problem here... Steam controller configuration (and Steam overlay) does not work with Flatpak games.

This issue is separate from #8583, which has to do with accessing _controller profiles_ for specific games. This issue is about the controller configuration _not working at all_ with Flatpak games.

As noted by @GorrillaRibs ... game mode on Steam Deck is the exception, as the one place I can get a controller profile to work with a Flatpak game, after adding it as a non-Steam game and making a controller profile for it.

But running Steam on a desktop linux machine, the only work around I can find is to change the desktop controller configuration to the one I use for the game, and then launch the game... kind of a pain. And that doesn't fix the overlay not working.

Please re-open this issue!

**Comment by TTimo** [comment]
This should be fixed in latest beta, Steam Input can now be used with flatpak shortcuts.

**Comment by kisak-valve** [comment]
Closing per the last comment.
