### ISSUE TITLE
Steam Runtime Soldier and Proton Experimental are installed to the wrong location

### ISSUE THREAD

**Issue by Mitsunee** [ValveSoftware/steam-for-linux#8633]
#### Your system information

* Steam client version (build number or date): latest as of today
* Distribution (e.g. Ubuntu): Fedora 36 (seen the same on Kubuntu 19.04 to 21.10)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Upon setting up my games library (`/mnt/LAMBDA-Storage/Games/SteamLinux`) on my NTFS HDD and opening any game steam will attempt to install Steam Runtime Soldier as well as Proton Experimental as per Settings. The problem lies within it ignoring the default install location and for some reason attempting to install Soldier and Proton onto the NTFS HDD, which results in a broken install that will not work even after moving it and not even `rm -rf common` following by verifying the files fixes this issue.

#### Steps for reproducing this issue:

1. Add Library on NTFS drive
2. Attempt to launch game on that drive while runtimes/proton are not yet installed
3. It will download and install them to the same drive
4. Enjoy your broken install.

#### What I expected to happen:

- Steam should honor the default install location, which is still my EXT4 SSD
- Steam should avoid installing runtimes to NTFS drives even if that would be the default install location
- Likely that it would make sense to always install such things to the main system drive as per `$HOME/.steam`
- Runtimes should be uninstallable, dependency conflicts be dammned. Problems happen and preventing uninstallation makes troubleshooting harder as you cannot reinstall things. If a dependency is missing upon game starting steam should then use the usual prompt informing the user of a required download happening and ideally also ask where to install to.

**Comment by kisak-valve** [comment]
Hello @Mitsunee, this issue is already being tracked in various issue reports including #8274, https://github.com/ValveSoftware/steam-runtime/issues/434, #8473, #7407.

My expectation is that game dependencies should get installed to the same Steam library folder as the game, but I personally don't have insight into how Steam makes that choice currently.

Closing in favor of the older issue reports.

**Comment by Mitsunee** [comment]
> My expectation is that game dependencies should get installed to the same Steam library folder as the game, but I personally don't have insight into how Steam makes that choice currently.

Why would that be expected when it literally leads to broken installs? I had to delete the entire `~/.local/share/Steam` directory and restart my install from scratch just to be *able to chose* to have Proton and Runtimes go to the correct drive (that I had already selected as the default install location prior to attempting to launch a game)

**Comment by nightowl286** [comment]
> Closing in favor of the older issue reports.

I believe this issue should be re-opened as it's about a more generic problem, those older issues are all mainly about different problems *(ie. uninstalling components, or specifically about NTFS).*

> My expectation is that game dependencies should get installed to the same Steam library folder as the game, but I personally don't have insight into how Steam makes that choice currently.

This assumption is wrong because it *does not* do that, for me *(running on Linux Manjaro)* Steam forces a storage library in my `/home` and it *does not* let me remove it, I have manually created a different location where I would like *everything* to be installed, and this is what I have marked as the default, all of my games do default to installing there.

However, Steam still makes all of the components *(Steamworks Common Redistributables; Proton versions; Stream Linux Runtimes and probably other things)* install onto the `/home` drive by default *(and again, Steam will not let me remove this drive).* I am forced to let them finish downloading onto the `/home` before I can tell Steam to move them which is quite annoying.

Additionally, the `Steamworks Common Redistributables` **cannot** be moved, it errors with:

```
Moving content for the following apps has failed :
- Steamworks Common Redistributables : has shared content
```

This is also annoying because well, I would like to have just one steam library *(but in a location of my own choosing, not the one that Steam forces to exist)*, but this component is forced to exist on a specific drive, I can only assume that this is because Steam has hardcoded the location of it, which is obviously just bad practice and should be fixed.

**Comment by Mitsunee** [comment]
> I believe this issue should be re-opened as it's about a more generic problem, those older issues are all mainly about different problems _(ie. uninstalling components, or specifically about NTFS)._

I believe you should not be causing email and notification spam on 3 year old issues. I do no longer have an NTFS drive and thus cannot reproduce my own issue report, thus it should remain closed.

**Comment by nightowl286** [comment]
> should not be causing email and notification spam

<img width="418" height="193" alt="Image" src="https://github.com/user-attachments/assets/4d4b3336-43e7-4338-bc16-7ba2c08000b7" />

<sub>I would also love to know how *one* comment on a relevant issue is considered spam...</sub>

**Comment by Mitsunee** [comment]
@kisak-valve can this thread be locked? I am not interested in entertaining this childish conduct
