### ISSUE TITLE
Steam won't launch on Debian testing

### ISSUE THREAD

**Issue by Vitix1** [ValveSoftware/steam-for-linux#8660]
#### Your system information

* Steam client version (build number or date): 1654574690
* Distribution (e.g. Ubuntu): Debian testing (amd64)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam stopped working on my system. This might be caused by recent system update, apt history: https://gist.github.com/Vitix1/844778fdef4906b7515a6c181f4d4a91.
I tried reinstalling steam, I uninstalled it with `apt autoremove steam-*`, deleted folders `~/.steam`, `~/.local/share/Steam` and installed official steam-latest.deb package.
When i run steam with STEAM-RUNTIME=0 it launches, but crashes on login.
Console output when running `steam`: https://gist.github.com/Vitix1/1c67a91072307ca2478bddf51aeb44ac
Console output when running `STEAM_RUNTIME=0 steam`: https://gist.github.com/Vitix1/d92e365530effe02097fdd21045f184d
System info: https://gist.github.com/Vitix1/9e7450152d252f8a02c0e133e98ba647

#### Steps for reproducing this issue:

1. Install Debian testing (amd64)
2. Install Steam
3. Run Steam

**Comment by kisak-valve** [comment]
Hello @Vitix1, can you check if any 32 bit OpenGL application like `glxinfo.i386-linux-gnu` from `mesa-utils-bin:i386` works?

`libGL error: MESA-LOADER: failed to open radeonsi: /usr/lib/dri/radeonsi_dri.so: cannot open shared object file: No such file or directory` in your terminal spew reads like mesa/radeonsi is broken or incomplete.

**Comment by Vitix1** [comment]
Hello, here is the output from glxinfo.i386-linux-gnu: https://gist.github.com/Vitix1/79c4551dd6291247a8a533cef867a646
I also tested 32bit glxgears which works ok.

**Comment by cr1ogen** [comment]
The problem is related to some i386 packages in the Debian repositories that are not yet up to date with the amd64 packages, which allow Steam to work.
This is the output when trying to boot steam for the first time, after installing the deb package.
`/home/cr1ogen/.local/share/Steam/steam.sh: línea 124: VERSION_ID: variable sin asignar
Package libegl1:i386 needs to be installed
Package libgl1-mesa-dri:i386 needs to be installed
Package libgl1:i386 needs to be installed
Package steam-libs-i386:i386 needs to be installed
/home/cr1ogen/.local/share/Steam/steam.sh: línea 124: VERSION_ID: variable sin asignar
steam.sh[7486]: Running Steam on debian  64-bit
/home/cr1ogen/.local/share/Steam/steam.sh: línea 124: VERSION_ID: variable sin asignar
steam.sh[7486]: STEAM_RUNTIME is enabled automatically
setup.sh[8129]: Steam runtime environment up-to-date!
steam.sh[7486]: Error: You are missing the following 32-bit libraries, and Steam may not run:
libGL.so.1
steam.sh[7486]: Steam client's requirements are satisfied
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
[2022-06-29 22:15:31] Startup - updater built Jun  7 2022 03:18:19
Installing breakpad exception handler for appid(steam)/version(1654574690)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2022-06-29 22:15:32] Loading cached metrics from disk (/home/cr1ogen/.local/share/Steam/package/steam_client_metrics.bin)
[2022-06-29 22:15:32] Using the following download hosts for Public, Realm steamglobal
[2022-06-29 22:15:32] 1. https://cdn.akamai.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2022-06-29 22:15:32] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2022-06-29 22:15:32] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1654574690)
[2022-06-29 22:15:32] Checking for update on startup
[2022-06-29 22:15:32] Checking for available updates...
[2022-06-29 22:15:32] Downloading manifest: https://cdn.akamai.steamstatic.com/client/steam_client_ubuntu12
[2022-06-29 22:15:32] Manifest download: send request
Installing breakpad exception handler for appid(steam)/version(1654574690)
[2022-06-29 22:15:32] Manifest download: waiting for download to finish
[2022-06-29 22:15:32] Manifest download: finished
[2022-06-29 22:15:32] Download skipped: /client/steam_client_ubuntu12 version 1654574690, installed version 1654574690, existing pending version 0
[2022-06-29 22:15:32] Nothing to do
[2022-06-29 22:15:32] Verifying installation...
[2022-06-29 22:15:32] Performing checksum verification of executable files
[2022-06-29 22:15:37] Verification complete
Failed to load steamui.so - dlerror(): libGL.so.1: wrong ELF class: ELFCLASS64
[2022-06-29 22:15:43] Shutdown
Installing breakpad exception handler for appid(steam)/version(1654574690)
Installing breakpad exception handler for appid(steam)/version(1654574690)`

**Comment by kisak-valve** [comment]
Hello @cr1ogen, exactly which packages are you referring to? https://packages.debian.org/sid/libgl1-mesa-dri looks consistent across arches.

**Comment by cr1ogen** [comment]
> Hello @cr1ogen, exactly which packages are you referring to? https://packages.debian.org/sid/libgl1-mesa-dri looks consistent across arches.

Hi @kisak-valve , This is the console output.
The following packages have unmet dependencies:
  libgl1-mesa-dri:i386 : Depends: libllvm14:i386 but will not install
E: Problems could not be corrected, you have held broken packages

**Comment by cr1ogen** [comment]
libgl1-mesa-dri:i386 needs libllvm14:i386 version 1:14.0.6-1  but the i386 version that is in the Debian repositories is the 1:14.0.5-1.
Sorry if you don't understand much but I'm using the translator

**Comment by kisak-valve** [comment]
Thanks, llvm 14.0.5 also had unstable llvm build tests on i386 failing out debian-based builds (https://buildd.debian.org/status/fetch.php?pkg=llvm-toolchain-14&arch=i386&ver=1%3A14.0.6-1&stamp=1656298705&raw=0)

**Comment by smcv** [comment]
> The problem is related to some i386 packages in the Debian repositories that are not yet up to date with the amd64 packages

This is a problem with Debian unstable (sid), not a problem with Steam. Steam requires working 32-bit graphics drivers, and Debian unstable does not always have working 32-bit graphics drivers.

The versions of mesa and llvm-toolchain-14 in Debian testing (bookworm) should always work correctly together.

The versions of mesa and llvm-toolchain-14 in Debian unstable (sid) are sometimes broken. unstable is a development branch that does not always work correctly.

If you install these packages from Debian testing (bookworm):

* `libgl1-mesa-dri:amd64 22.0.5-1`
* `libgl1-mesa-dri:i386 22.0.5-1`
* `libllvm14:amd64 1:14.0.5-1`
* `libllvm14:i386 1:14.0.5-1`

then those should work correctly together.

**Comment by smcv** [comment]
> When i run steam with STEAM-RUNTIME=0 it launches, but crashes on login

This is not supported. Steam requires some libraries from the Steam Runtime which might be newer than the versions on the host system, in particular Vulkan-Loader.

**Comment by kisak-valve** [comment]
Thanks @Vitix1, ```libGL: MESA-LOADER: failed to open /usr/lib/i386-linux-gnu/dri/radeonsi_dri.so: /home/vitix/.steam/root/ubuntu12_32/steam-runtime/lib/i386-linux-gnu/libgcc_s.so.1: version `GCC_7.0.0' not found (required by /usr/lib/i386-linux-gnu/dri/radeonsi_dri.so)``` is the more valuable line of feedback from the extended diagnostics information

**Comment by kisak-valve** [comment]
Just for a sanity check, can you share the output of `apt policy libgcc-s1 libgcc-s1:i386`?

**Comment by Vitix1** [comment]
Sure, here it is:
```
vitix@vitix-pc:~$ apt policy libgcc-s1 libgcc-s1:i386
libgcc-s1:
  Installed: 12.1.0-2
  Candidate: 12.1.0-2
  Version table:
 *** 12.1.0-2 100
        100 /var/lib/dpkg/status
libgcc-s1:i386:
  Installed: 12.1.0-2
  Candidate: 12.1.0-2
  Version table:
 *** 12.1.0-2 100
        100 /var/lib/dpkg/status
```

**Comment by smcv** [comment]
> on my system, folder /etc/ld.so.conf.d/ contained only pipewire-jack-x86_64-linux-gnu.conf

FYI, you're missing other files in that directory which might cause similar problems later: you should have at least `/etc/ld.so.conf.d/libc.conf` from `libc-bin`, `/etc/ld.so.conf.d/i386-linux-gnu.conf` from `libc6:i386`, and `/etc/ld.so.conf.d/x86_64-linux-gnu.conf` from `libc6:amd64`.

**Comment by amuuth** [comment]
hi @smcv, I am running a fairly fresh copy of Debian bookworm, and also cannot install steam! Please advise, thanks!!

`apt policy libgcc-s1 libgcc-s1:i386
libgcc-s1:
  Installed: 12.2.0-13
  Candidate: 12.2.0-13
  Version table:
 *** 12.2.0-13 500
        500 http://deb.debian.org/debian testing/main amd64 Packages
        100 /var/lib/dpkg/status
libgcc-s1:i386:
  Installed: (none)
  Candidate: 12.2.0-14
  Version table:
     12.2.0-14 500
        500 http://deb.debian.org/debian testing/main i386 Packages
`

I have created the i386-linux-gnu.conf file you mentioned above.

**Comment by amuuth** [comment]
Installing libgcc-s1:i386 doesn't work, even when using dpkg: 

```
aku@desktop:~/Downloads$ sudo dpkg -i libgcc-s1_12.2.0-14_i386.deb 
Selecting previously unselected package libgcc-s1:i386.
(Reading database ... 347211 files and directories currently installed.)
Preparing to unpack libgcc-s1_12.2.0-14_i386.deb ...
De-configuring libgcc-s1:amd64 (12.2.0-13), to allow configuration of libgcc-s1:i386 (12.2.0-14) ...
Unpacking libgcc-s1:i386 (12.2.0-14) ...
dpkg: error processing package libgcc-s1:i386 (--install):
 package libgcc-s1:i386 12.2.0-14 cannot be configured because libgcc-s1:amd64 is at a different version (12.2.0-13)
dpkg: error processing package libgcc-s1:amd64 (--install):
 package libgcc-s1:amd64 12.2.0-13 cannot be configured because libgcc-s1:i386 is at a different version (12.2.0-14)
Processing triggers for libc-bin (2.36-8) ...
Errors were encountered while processing:
 libgcc-s1:i386
 libgcc-s1:amd64
```

**Comment by smcv** [comment]
@amuuth: the versions of `libgcc-s1:amd64` and `libgcc-s1:i386` available on your Debian mirror are out of sync. This is a Debian infrastructure problem, not a Steam problem.

Versions going out of sync should never happen in testing (only in unstable/experimental), but apparently something has gone wrong with the mirror/CDN mechanism: https://tracker.debian.org/pkg/gcc-12 says the version of `libgcc-s1` in testing should be 12.2.0-14 as of today, but you are getting a slightly outdated version 12.2.0-13 for amd64.

There isn't really any reliable solution for this, other than waiting for them to be back in sync. It might be possible to work around this by temporarily adding an alternative Debian mirror from https://www.debian.org/mirror/list in addition to `deb.debian.org`, so that apt has more options that it can try.
