### ISSUE TITLE
 I can't add my Steam Library folder, 'cause it doesn't exist? I guess?

### ISSUE THREAD

**Issue by widkit** [ValveSoftware/steam-for-linux#8674]
* Jun 7, 22 build (flatpak)
* Artix Linux, s6 init
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]
* Drive is NTFS, and mounted on correct directory.

 I can't add my Steam Library folder, 'cause it doesn't exist? I guess?
 The folder exists and mounted on the correct directory. 
 
![image](https://user-images.githubusercontent.com/75989700/177820222-a31fbd57-7643-455d-9831-a7be74697224.png)
here, the folder "Downloaded Program Files" has SteamLibrary folder inside.
but there is no plus sign like any other folder with subfolders.

#### Steps for reproducing this issue:

1. get on Artix Linux with s6 init
2. install steam via flatpak
3. try to add your existing steamlibrary folder

**Comment by kisak-valve** [comment]
Hello @widkit, this issue sounds like the same Flatpak issue as https://github.com/flathub/com.valvesoftware.Steam/wiki#i-want-to-add-external-disk-for-steam-libraries / https://github.com/flathub/com.valvesoftware.Steam/issues/55. Your issue is with the nature of Flatpak's sandboxing and not Steam.
