### ISSUE TITLE
Suggestion: Allow games to not be kept updated to increase platform engagement

### ISSUE THREAD

**Issue by Mikael-Lovqvist** [ValveSoftware/steam-for-linux#8711]
#### Your system information

* Steam built: 2022-07-07 3:18.43
* Distribution: Arch Linux
* Opted into Steam client beta?: I don't think so but I do use the compatibility layers
* Have you checked for system updates?: Not last few days

#### Please describe your issue in as much detail as possible:
Currently there are 3 modes for game updates

1. Always keep this game updated
2. Only update this game when I launch it
3. High Priority - Always auto-update this game before others

I suggest a 4'th option:

4. Never update this game automatically

##### Rationale for option:

The current workaround is to keep steam in offline mode whenever you launch the title you don't want to have updated. Since I tend to worry about launching it accidentally in online mode I will keep steam in offline mode. This means that I will not engage with the steam store, I will not engage with new contents, I will not engage with the forums. An option to prevent a game from being updated would allow users of the platform to still engage with all the other games and aspects of the platform.

##### Rationale for why not updating a game
A game might have breaking changes and you may have invested hundreds of hours into game play. If the game is updated this may corrupt your saves or change core aspects of the game leading to lots of frustration. Some games are just too early access and you may want to keep them in one state until they are further along, until next new world.

**Comment by kisak-valve** [comment]
Hello @Mikael-Lovqvist, this is a request for an anti-feature. If you're that concerned about game devs making changes to games, especially while they're in heavy development, then you should consider having a backup strategy in place.

**Comment by Mikael-Lovqvist** [comment]
> Hello @Mikael-Lovqvist, this is a request for an anti-feature. If you're that concerned about game devs making changes to games, especially while they're in heavy development, then you should consider having a backup strategy in place.

Thank you for responding. I don't really understand why it is an anti-feature but more importantly, I don't understand what backup strategy I could possibly have other than not play the game until it is finished which seems unrealistic for games that have been in development for a decade and keeps making breaking changes.

**Comment by kisak-valve** [comment]
You're right, I understated my reasoning.

This is a request to take away a game developers ability to reliably update their game across their entire player base so that they only need to support the currently released version. Steam was designed from the start to solve that exact problem. Changing this fundamental design choice would require internal discussion by Steam developers and is not really open to external (public) debate.

**Comment by prmbittencourt** [comment]
The option to roll back to a previous version that's known to be working when an updated version no longer works is not an anti-feature. It's a way to improve stability and the gaming experience when something breaks, as well as to guarantee that the customer is able to play a game that he paid for, owns, and should therefore be able to play whenever he wants to. Such a feature is good for the user and for the public image of the game developer and distributor.

More choice is not a bad thing, but broken updates are. If you're concerned about players exploiting some bug to cheat online, the solution is simple: block people using older versions from playing online PvP, which is reasonable. In non-competitive gameplay, including co-op multiplayer, "cheating" is not an issue.

I don't usually play online and being blocked from playing a single-player offline game that I paid for because the developer didn't test a patch suficciently before pushing it is simply unacceptable. It's more than enough reason for me to not buy anything from that studio ever again.

**Comment by Tea23** [comment]
Hi, this wouldn't be an anti-feature. Rather, it's a means for allowing game preservation/archiving (Steam will go offline someday!) and maintaining compatibility with mods. There might be renewed interest in this as, for example, the recent Fallout London mod requires an older version of Fallout 4 to work. GOG have worked with the modders to create a way to distribute to GOG owners of Fallout 4 a "downgraded" version of the game, but for Steam we have to play around with manually downloading older depots and preventing Steam from automatically re-upgrading the game.

GOG do support this for all of their titles. You might consider consulting with them on their messaging and mechanism of how it works. I think it's really quite clear from how they do it that this is not something that can easily be classified as an "anti-feature".

I DO understand that it can create a support headache, since a user might be running an older title and ask a developer for help. Part of the debugging will be to check what version of the game a user is running, a check which automatic updates prevents from happening. The messaging thus would need to make it clear how using an older version of a game would break support contracts between players and developers.

An update that breaks a game is uncommon, as developers are generally pretty good at what they do, but they can happen. In more extreme examples, the update system can even radically modify a game so far from its base that it could be considered a different product (e.g. Team Fortress 2), which might make playing an older version just simply desirable for a player.

Mods though, I think, might be the biggest reason for this to be a nice thing to have. Plenty of Steam updates throughout the years have already been released to make obsolete workarounds for things. I think all the various tricks for preventing game updates can also be built into the client.

Please reconsider.
