### ISSUE TITLE
SELinux is preventing /home/michael/Steam/ubuntu12_32/steam from using the execheap access on a process. 

### ISSUE THREAD

**Issue by mikefaille** [ValveSoftware/steam-for-linux#88]
OS : Fedora 18 
Main updates repos : updates-testing
Arch : x64
When : Add new Humble Bundle Keys
:-1:  
SELinux is preventing /home/michael/Steam/ubuntu12_32/steam from using the execheap access on a process.

Plugin: catchall_boolean 
you want to allow steam to have execheap access on the processIf vous souhaitez allow unconfined executables to make their heap memory executable.  Doing this is a really bad idea. Probably indicates a badly coded executable, but could indicate an attack. 
setsebool -P selinuxuser_execheap 1

**Comment by amitavmohanty01** [comment]
I understand that you would like to pass the ticket to Webkit team as it is their ownership. However, as steam made the choice of going with Webkit, I think steam at the very least should track this issue. I would rather have a status like "waiting on dependent team/project" than have the issue closed.

**Comment by h1z1** [comment]
This is hilarious.  Seriously these threads go back to 2013.

 Started getting it again, finally looked around to find out why and now I remember..   Literally searching for execheap and steam turns up some awesome security fails on Valves part.  Threads all being closed by them of course.  So why is this popping up again?

In my case, tf2 and I suspect mp3 related.  Joined a server with quakesounds which sent the client into a ballistic fit since it couldn't decode the mp3s.
