### ISSUE TITLE
[Bug] Remote play together fails to render to the screen (but otherwise it's working)

### ISSUE THREAD

**Issue by rcano** [ValveSoftware/steam-for-linux#8800]
#### Your system information

* Steam client version: sep 14 2022, 00:06:33 
* Distribution: Ubuntu 20.04 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The stream is set up correct and inputs work, I can see the remote mouse with the custom icon and sound gets streamed correctly, but the window is completely black, steam doesn't even render the typical UI it shows up before the stream comes up about loading:

![remoteplaytogetherfail](https://user-images.githubusercontent.com/759769/190292449-f14e7e7f-e9ea-48d5-9377-f3671053b528.png)

This started happening right after the update yesterday, since I was using remote play together, restarted steam to do the update, and after it it no longer worked.
I tried opting out of the beta client and the problem persists.

#### Steps for reproducing this issue:
Doing any Remote Play, either "remote play together" or remote stream by connecting same account to two computers.

**Comment by joshuaboniface** [comment]
Same problem here.

I run headless on xfce, it's worked fine for years. Within the last 2 weeks (since I last played), this same issue started happening. Nothing stands out as unusual in the logs. 

Tried disabling HWA on the server side (was already disabled on the client side), to no change. Tried upgrading video drivers, to no change.

I am able to get it to "work" if I start Steam through an X11-forwarded SSH session, but at that point performance is abysmal.

**Comment by slouken** [comment]
This is fixed for the next update, thanks!

**Comment by slouken** [comment]
The fix is now live in the Steam beta client. Please let us know if you have any other issues!
