### ISSUE TITLE
Feature request: freeze game updates

### ISSUE THREAD

**Issue by Alex-Bujorianu** [ValveSoftware/steam-for-linux#8802]
#### Your system information

* Steam client version (build number or date): Not relevant
* Distribution: Pop OS 
* Opted into Steam client beta?: Tried both
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Some games break when an update is pushed. This has become distressingly frequent and is really hurting the game experience on Steam. This is not a Linux-specific issue, but it disproportionately affects Linux users. For example: the Skyrim update on September 15th 2022 breaks SKSE, effectively rendering the game unplayable. Some months ago, an update to Dragon Age: Inquisition made it incompatible with Proton.

I would like a way to prevent games from updating, and to easily rollback an update.

**Comment by kisak-valve** [comment]
Hello @Alex-Bujorianu, please see #8711.

This is a request for an anti-feature.

**Comment by Techwolf** [comment]
Not a anti-feature, this is required for millions of mods to not break untill everything is properlly updated. This is required in some areas by law.

**Comment by Alex-Bujorianu** [comment]
I am going to have rethink any Steam purchases in the future because of this. No customer wants to pay money for a game that unpredictably breaks, or which requires workarounds like being offline. Being a gamer, especially a Linux gamer, feels like playing roulette against the Software Development Gods. I am tempted to give up on PC gaming altogether as the number of technical issues (not just Proton or mod-related but also performance, drivers, hybrid graphics, anti-cheat) extinguishes the joy. At least this issue has an easy fix.

**Comment by prmbittencourt** [comment]
The option to roll back to a previous version that's known to be working when an updated version no longer works is not an anti-feature. It's a way to improve stability and the gaming experience when something breaks, as well as to guarantee that the customer is able to play a game that he paid for, owns, and should therefore be able to play whenever he wants to. Such a feature is good for the user and for the public image of the game developer and distributor. 

More choice is not a bad thing, but broken updates are. If you're concerned about players exploiting some bug to cheat online, the solution is simple: block people using older versions from playing online PvP, which is reasonable. In non-competitive gameplay, including co-op multiplayer, "cheating" is not an issue. 

I don't usually play online and being blocked from playing a single-player offline game *that I paid for* because the developer didn't test a patch suficciently before pushing it is simplying unacceptable. It's more than enough reason for me to not buy anything from that studio ever again.
