### ISSUE TITLE
In-game notification are not being displayed

### ISSUE THREAD

**Issue by dmarcosl** [ValveSoftware/steam-for-linux#8942]
#### Your system information

* Steam client version: 1668654410
* SteamOS version: 3.3.2
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

The in-game notifications (achievements, screenshot taken, low battery indicator, etc.) are not being displayed nor make any sound since the last update on the stable channel.

The "disable" slider of the notifications settings is off, and the notifications are there because by pressing the "..." button I can see them.

Here some more people with the same problem:

https://steamcommunity.com/app/1675200/discussions/0/3541546590703729877/
https://www.reddit.com/r/SteamDeck/comments/yzrhbl/randomly_missing_notifications/

#### Steps for reproducing this issue:

1. Open a game
2. Take a screenshot

**Comment by UFeindschiff** [comment]
Can confirm this on regular Steam (no SteamOS). From my observation taking a screenshot causes all Steam Overlay processes (gameoverlayui) to crash (the screenshot is actually being taken though). This crash is not instanteneous, yet the Steam overlay function ceases the moment a screenshot is taken. The issue was introduced with the latest stable patch

**Comment by TTimo** [comment]
Next beta update has a fix for this and various related issues.

**Comment by UFeindschiff** [comment]
Can confirm that the Steam Beta build of the 19th December 2022 22:01:34 fixes this issue. Taking screenshots no longer causes gameoverlayui to crash and the "Screenshot taken" popup shows as expected.
