### ISSUE TITLE
Multiple instances of the same controller template in the controller layout config 

### ISSUE THREAD

**Issue by popsUlfr** [ValveSoftware/steam-for-linux#8986]
#### Your system information

* Steam client version (build number or date): 1670661350 Dec 10 2022, at 02:13:15
* Distribution (e.g. Ubuntu): SteamOS on Steam Deck
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

The Templates section in the controller layout configuration is crowded with multiple instances of the same template. **Keyboard (WASD) and mouse** appears like 12 times.

![Screenshot_20221212_171409](https://user-images.githubusercontent.com/1030423/207097240-f61c2408-02cc-4b9c-b86f-a3c32547f825.png)

#### Steps for reproducing this issue:

1. Open the Controller layout configuration for a game
2. Go to Templates

**Comment by Glowing0rb** [comment]
Same issue here on 3.4.2.

**Comment by brianx87** [comment]
I have three or four duplicates for each type of template

**Comment by vicnett** [comment]
I also have this problem.

Note: I use EmuDeck. I mention this because EmuDeck creates extra controller templates for use with some of the emulators that it installs.

I have no idea whether this has anything to do with the duplication of the default templates from the Steam Deck we're reporting...

**Comment by Glowing0rb** [comment]
Good point, I'm also using emudeck.
-------- Ursprüngliche Nachricht --------Von: Vincent Capelle ***@***.***> Datum: 29.12.22  01:37  (GMT+01:00) An: ValveSoftware/steam-for-linux ***@***.***> Cc: Glowing0rb ***@***.***>, Comment ***@***.***> Betreff: Re: [ValveSoftware/steam-for-linux] Multiple instances of the same controller template in the controller layout config  (Issue #8986) 
I also have this problem.
Note: I use EmuDeck. I mention this because EmuDeck creates extra controller templates for use with some of the emulators that it installs.
I have no idea whether this has anything to do with the duplication of the default templates from the Steam Deck we're reporting...

**Comment by Kazlehoff** [comment]
I have this issue, and im NOT using EmuDeck. im using RetroDeck. Everyhting is up to date on the stable branch of SteamOS.

**Comment by popsUlfr** [comment]
This seems to have been fixed in the latest Steam Beta Client :)

**Comment by Kazlehoff** [comment]
I cant update to the Beta / Preview client (rEFInd dualbooting windows and Steam OS, and beta/preview channels cause a lot of issues with dualboot setups.

I also came back to post that yes, this appears to be fixed in an upcoming update. 
https://steamcommunity.com/app/1675200/discussions/1/3709307511569660940/

Still frustrating lol

**Comment by popsUlfr** [comment]
> I cant update to the Beta / Preview client (rEFInd dualbooting windows and Steam OS, and beta/preview channels cause a lot of issues with dualboot setups.

@Kazlehoff What you could do is `Enable Developer Mode` in `System` and then under `Developer` > enable `Show Advanced Update Channels`. Now when you go back to `System` you'll see separate `OS Update Channel` and `Steam Client Update Channel` here you can set just the Steam client to follow the `Steam Deck Beta` channel without modifying the system os version.

**Comment by Kazlehoff** [comment]
> What you could do is Enable Developer Mode in System and then under Developer > enable Show Advanced Update Channels. Now when you go back to System you'll see separate OS Update Channel and Steam Client Update Channel here you can set just the Steam client to follow the Steam Deck Beta channel without modifying the system os version.

![image](https://user-images.githubusercontent.com/52207847/211059403-087f07b1-4ff9-449a-b93b-5af17278383d.png)

**Comment by popsUlfr** [comment]
I'm suggesting you update only the Steam Client to Beta and not the OS.

**Comment by popsUlfr** [comment]
> I must have misread as i thought you were discussing the the OS beta. Apologies. work nights, and its getting pretty late in my day here lol. I'll look into it. thanks :)

No worries :) This gives you separate control over the OS and Steam Client update channels which is very useful. This way you can keep your system on stable while having the Steam Client on beta for instance (just keep in mind that the Steam Client Beta might need beta system updates for all new features to work)

**Comment by Kazlehoff** [comment]
This worked btw. enabling advanced update channels, and updating just Steam to beta while leaving the OS on stable worked to correct the issue. :D

**Comment by kisak-valve** [comment]
Closing as fixed in the 2023-02-01 Steam client update.
