### ISSUE TITLE
Pop OS grey box at login

### ISSUE THREAD

**Issue by C4T4P1LL4** [ValveSoftware/steam-for-linux#9023]
#### Your system information

* Steam client version (build number or date): I reinstalled the latest from the website a number of times and I tried it from the repository to no avail.
* Distribution (e.g. Ubuntu): Pop! OS
* Opted into Steam client beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I wasn't using this computer for a while and then decided to use it again so I ran all the updates and I think I could've corrupted something because when steam was updating the disc space filled up. I freed up some space then tried to redo the steam update. It wouldn't launch so I reinstalled it from the website and it was able to download the latest package update but when it gets to the login screen it's just a grey box and I can't type anything in. Waiting for something to show up doesn't work. I tried to reinstall it again and make sure everything was up to date again and rebooted and all that and nothing fixes it. I tried to launch games directly from lutris and lutris tried to redownload the latest package for steam and asked me to login which of course was just a grey box again. I don't know what I need to do to fix this. Ples halp.

#### Steps for reproducing this issue:

1. Update & Upgrade on a machine with no disc space.
2. Free up a fair amt of disc space and try again.
3.  Launch Steam... & broken.

**Comment by kisak-valve** [comment]
Hello @C4T4P1LL4, the .deb packaging is primarily a launcher used to bootstrap the Steam client in your home folder.

If you're still opted into the Steam client beta, then you could try manually opting out of the beta in order to get Steam to start an update cycle by completely closing Steam and deleting `~/.steam/steam/package/beta` and trying to run Steam again. If that helps, then you go to Steam's settings and opt back into the Steam client beta and verify that you're not seeing a recent regression of some kind (versus missing files from an incomplete Steam update cycle).

Alternatively, you could try completely closing Steam, then running `steam --reset` from a terminal. This should tell Steam to try to run as if it was the first time it ran on your system.

**Comment by C4T4P1LL4** [comment]
> 

Thank you kisak. I ran steam --reset and tried to launch it and it totally worked. :)
