### ISSUE TITLE
no option to select where to install the game

### ISSUE THREAD

**Issue by Frambooisier** [ValveSoftware/steam-for-linux#9063]
#### Your system information

* Steam client version (build number or date):  Dec 19 2022 package version:1671501303
* Distribution (e.g. Ubuntu): Opensuse Tumbleweed 20221224-0 kernel:6.1.0-1-default 
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
There should be option to select to witch steam library a game should be installed, for some game there is for some not.
#### Steps for reproducing this issue:

https://user-images.githubusercontent.com/15931041/210279176-8ca54405-05a3-419d-9023-6b4ab57f73ee.mp4

**Comment by kisak-valve** [comment]
Hello @Frambooisier, several goldsrc games share game content and need to be installed in the same Steam Library to work properly. Steam is forcing those specific games to use the same library so that you're not left with a broken game install.

If you want to change which library they're installed in, then uninstall the other goldsrc era games and Steam will let you select a different Steam library folder.

**Comment by Frambooisier** [comment]
Thank you, quite logical.
