### ISSUE TITLE
Separate DXVK and Proton distribution

### ISSUE THREAD

**Issue by orowith2os** [ValveSoftware/steam-for-linux#9148]
#### Your system information

* Steam client version (build number or date): Any
* Distribution (e.g. Ubuntu): Any
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Steam currently ships Proton with DXVK. This is fine, but shipping DXVK separately can allow for newer DXVK on systems that support it and older DXVK on systems that don't. This will allow for Proton to update faster without worrying about leaving older GPUs in the dust (as many older GPUs might not support the newest Vulkan extensions) while having improved game compatibility and performance.

#### Steps for reproducing this issue:

1. Download Proton
2. Want to use newer DXVK, such as for gpl extensions and improved performance
3. Have to modify the installed Proton files rather than having a dedicsted DXVK Steam tool

**Comment by kisak-valve** [comment]
Hello @orowith2os, providing support for multiple render paths makes this request a non-starter.

In general, only the newest point release of DXVK is supported, however, Proton 7.0 is keeping the DXVK 1.10 release branch as an exception because DXVK 2.0 comes with a significant increase in the features it needs from Vulkan drivers, and some drivers can't or won't provide them at this time.

`This will allow for Proton to update faster without worrying about leaving older GPUs in the dust`
Proton Experimental and Proton Experimental [bleeding-edge] already does exactly this, bleeding edge DXVK is automatically integrated into that release channel.

**Comment by orowith2os** [comment]
Would it be possible for the Steam client to provide a part of this functionality, using manually-provided builds of DXVK without deleting main Proton files? You can sort of do this already with custom compatibility tools, so it could be an extension to that.
