### ISSUE TITLE
SN30 Pro 2 Not Detected

### ISSUE THREAD

**Issue by toast-t-bread** [ValveSoftware/steam-for-linux#9283]
#### Your system information

* Steam client version (build number or date): Mar 17 2023, at 18:27:00 PST
* Distribution (e.g. Ubuntu): Garuda Linux
* Opted into Steam client beta?: **No**
* Have you checked for system updates?: **Yes**

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

I connected a _brand-new_ 8bitdo SN30 Pro 2 to my laptop wirelessly and opened up steam, after I opened up the controller settings, It didn't show up, I then installed xpad and rebooted, but it didn't work. I've tried every mode on the controller and none of them work.
#### Steps for reproducing this issue:

1. Connect SN30 Pro 2 to machine running Garuda Linux
2. Open Steam to controller settings.
3. Notice that there is no controller detected

**Comment by toast-t-bread** [comment]
Seems to only work in apps when wired, will look elsewhere.

**Comment by Balderick** [comment]
I had to use ds4windows on windows pc to get 8BitDo Pro 2 working in Steam using A (macos) and D (android) modes by emulating ds4 controller.  S (switch) and X (windows +xbox) modes just worked out of the box but using usb causes it show as xbox 360 controller but using BT makes steam see a xbox one controller.

Awesome device to see how broken Steam Input is today by just using one single controller.   All modes have at least broken share and guide buttons, or steam maps nintendo type button layout unwantedily and unneedingly.  There are myriads of issues for each mode.     None work like expected - neither do all my other controllers.

**Comment by toast-t-bread** [comment]
I updated using the software for android on my phone, since it doesn't work in my wine config. I really don't want to use windows for steam.

**Comment by Balderick** [comment]
Am pretty sure what you are describing is related to a known upstream sdl issue which is being discussed at 
https://github.com/libsdl-org/SDL/issues/6686


I just uninstalled steam for windows due to myriad of issues with usb devices, controllers no longer making BT connection, steam input preventing me from using T500 RS wheel and pedals in games that natively support it and even my physical mouse stopped working after i switched from wireless to usb cable for charging, just because Steam Input was applying desktop mode to 8BitDo Pro 2 controller.

Was watching the issues here and on Deck forum i steam discussions.   But the steam experience is completely broken there too.

It really does sadden me to see Steam in such a state on all "supported" platforms.  It just  a bug ridden messs .


I'm out.

**Comment by SeanyMCP** [comment]
I am having a similar issue with Gamesir T3s in nintendo switch pro controller mode. Before the major update to steam 1686880776 yesterday it was working fine. Now the client UI states the controller is not detected.
Firing up steam through the terminal, i can nevertheless read : 

`Local Device Found
  type: 057e 2009
  path: sdl://232
  serial_number:  - 0
  Manufacturer: 
  Product:      Nintendo Switch Pro Controller
  Release:      0
  Interface:    -1`


Seems like the controller is detected properly, but nothing in the UI or in game
