### ISSUE TITLE
EverQuest game port freezes during account switch

### ISSUE THREAD

**Issue by FreedomFaighter** [ValveSoftware/steam-for-linux#9367]
#### Your system information

* Steam client version (build number or date): 1681864962
* Distribution (e.g. Ubuntu):  
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] No

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Launch game into character, switch accounts, come back and still have active playable game window

#### Steps for reproducing this issue:

1.  Load EverQuest into game character
2.  Switch accounts
3.  Return to account executing client for black game screen
4.  Requires action outside client to exit game

**Comment by kisak-valve** [comment]
Hello @FreedomFaighter, there's multiple games that could be summary called EverQuest, and none of them appear to have a Linux native variant. There's not enough information to start to ponder this feedback.

In general, we're tracking issues with games run with Proton in the [Proton issue tracker](https://github.com/ValveSoftware/Proton/issues), and there is feedback on one EverQuest title being tracked at https://github.com/ValveSoftware/Proton/issues/1885.

Please check if the appid matches the game you're playing, and if it does, then please add your feedback to the existing compatibility report, otherwise, open a new compatibility report for the Proton devs to ponder.

Closing as not a Steam client issue.

**Comment by FreedomFaighter** [comment]
there is EverQuest and EverQuest 2, others may include the EverQuest name and a list if them is included https://en.m.wikipedia.org/wiki/EverQuest under the Franchise section to help with the Proton database
