### ISSUE TITLE
Steam beta: No way to skip processing of vulkan shaders

### ISSUE THREAD

**Issue by pizzadude** [ValveSoftware/steam-for-linux#9379]
#### Your system information

* Steam client version (build number or date):  1682634349
* Distribution (e.g. Ubuntu): Fedora KDE (wayland) - Steam flatpak
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The popup when a steam game is launching no longer shows anymore, so I can't skip processing of vulkan shaders, which takes a lot of time on my system.

#### Steps for reproducing this issue:

1. Launch game
2. Notice it's processing vulkan shaders
3. No way to skip

**Comment by pukmajster** [comment]
This is even worse when Steam takes literal ages to process said shaders. Tried running Apex Legends on Fedora 38 (Gnome, X11, nVidia) and after 10 minutes it only got to 56%. An option to skip would be great.

**Comment by deanrih** [comment]
I play Dota 2 and this also infuriates me, the previous UI shows the small window about launching the game and shows the Processing Vulkan Shader progress which can be skipped, and in Dota 2, you don't actually need to pre-process the shader, it's redundant, but in the new UI, you can't skip it, so the CPU do something literally useless for minutes now.

**Comment by sonic2kk** [comment]
This affect some other dialogs that previously used the old UI (VGUI?) such as selecting custom game artwork.

**Comment by rurigk** [comment]
I also noticed this with Apex Legends
Since Apex has a DX12 beta and it works amazing with Proton you can skip entirely the vulkan shaders processing

Now i need to pre-process the Vulkan shaders even if i dont use them

**Comment by apocalyptech** [comment]
Yeah, this is super frustrating.  Shader compiling for Borderlands 2 and The Pre-Sequel can take many tens of minutes to complete, and doesn't even seem to make any noticeable difference in the game.  I've been hitting "cancel" on those reflexively for ages now.  I don't even want to launch those games anymore on my laptop because it makes my fans run at full tilt for ages.

Relatedly, I'd very much appreciate getting the dialogs back which inform me that an "external" update is happening -- like when Steam is updating Proton or Steam Linux Runtime.  Those operations are usually pretty quick, but more information is better than less.  I want to know what my system's doing.  If you're gonna hide stuff by default, fine.  At least give me the option of turning it back on, though.

**Comment by Gladox114** [comment]
For me, Apex Legends Shader Compilation takes multiple Hours and the bad thing is that on the next day I still need to compile the Shaders but mostly for a shorter time like 1h to 30min or less if I am lucky.

I always skipped them but now I just can't

**Comment by etoven** [comment]
Yea, really annoying.. I see the pros and cons. But I rather deal with a bit of stuttering and jump right into the game. The wait time on this one game absolutely brutal.. Nearly 45 minutes.

**Comment by kudu9** [comment]
Apex take for ever to finish Shader Compilation and sometimes I just skip it when I just wanna play friends really fast, so It's nice important to have the skip button back

**Comment by deanrih** [comment]
As for version `1684535786`, they finally added a dialog to skip the Shader Compilation process, however, if you don't skip and wait until the process is finished, Steam become 100% unusable because the backdrop/blocker thingy still covers the entire Steam UI (but the dialog has already disappeared), even after the game has been closed, if you skip, however, the dialog and the backdrop disappear and Steam is usable.

Here's the screenshot when you wait until the process completed:

![image](https://github.com/ValveSoftware/steam-for-linux/assets/16235605/db5ff54a-feb5-44d4-9270-aca627869cb7)

Yes, it darkens the entire UI. No, it's not a "Not Responding" kinda thing, it's just a backdrop covering the whole UI. No, it's not clickthrough and can't be dismissed by any shortcut, closing (by using ALT+F4 in this case) and re-opening the Steam UI doesn't fix it, you have to **exit** steam and re-open it to be able to use it.

**Comment by Skeletonek** [comment]
Can confirm this is a problem when you don't skip shader processing in the newest Steam Client version

> In the version `1684535786`, they finally added a dialog to skip the Shader Compilation process, however, if you don't skip and wait until the process is finished, Steam become 100% unusable because the backdrop/blocker thingy still covers the entire Steam UI (but the dialog has already disappeared), even after the game has been closed, if you skip, however, the dialog and the backdrop disappear and Steam is usable.
> 
> Here's the screenshot when you wait until the process is completed:
> 
> ![image](https://user-images.githubusercontent.com/16235605/239704231-db5ff54a-feb5-44d4-9270-aca627869cb7.png)
> 
> Yes, it darkens the entire UI. No, it's not a "Not Responding" kinda thing, it's just a backdrop covering the whole UI. No, it's not clickthrough and can't be dismissed by any shortcut, closing (by using ALT+F4 in this case) and re-opening the Steam UI doesn't fix it, you have to **exit** steam and re-open it to be able to use it.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by GenocideStomper** [comment]
I get a prompt to skip the shader compilation or cancel the launch. As far as I know both options work.
![image](https://github.com/ValveSoftware/steam-for-linux/assets/5098895/98f59d95-1e98-4f00-a823-d38f0b178db9)

**Comment by deanrih** [comment]
@kisak-valve So far no problem and work fine, it's just the user experience is not as good as the previous Steam version since it needs to open up the Steam Client main window to show this dialog compared to the previous standalone shader processing dialog. Also if you accidentally click anywhere outside the dialog it cancels the shader processing and won't run the game.

**Comment by GenocideStomper** [comment]
> it's just the user experience is not as good as the previous Steam version since it needs to open up the Steam Client main window to show this dialog compared to the previous standalone shader processing dialog. Also if you accidentally click anywhere outside the dialog it cancels the shader processing and won't run the game.

Experiencing the same, it's actually annoying that the Steam main window pops up and doesn't automatically close again after.

**Comment by etoven** [comment]
This appears to have been addressed in new build. Issue was only relevant in this commit. The option was missing completely.

**Comment by kisak-valve** [comment]
Closing as fixed.

The followup issue is being tracked at #10032.
