### ISSUE TITLE
Q.U.B.E. 10th Anniversary

### ISSUE THREAD

**Issue by ChrisLauinger77** [ValveSoftware/steam-for-linux#9404]
I already filed an issue directly in steam client. They asked me to file it here.
[Link](https://help.steampowered.com/en/wizard/HelpRequest/HT-4KVJ-PKQR-2477)

The game just does not download any files. The folder is created but thats it.
https://gist.github.com/ChrisLauinger77/ac3f8a7cf89c1499688617bbad1d0cdb
Other games download though - but Q.U.B.E. 10th Anniversary just wont download any files.
I tried already everything described in help but still have the problem

**Comment by kisak-valve** [comment]
Hello @ChrisLauinger77, the download and management of game content in handled by the Steam client, not Proton itself, so I've transferred this issue report to the steam-for-linux issue tracker.

Can you completely close Steam, then run `steam -console` from a terminal, switch to the console tab, type `licenses_for_app 1564220` and share the output?

**Comment by ChrisLauinger77** [comment]
here we go:

License packageID 552552:
 - State   : Active (flags 0x0) - Purchased : Thu Mar 16 17:09:02 2023 in "DE", CD Key
 - Apps	: 1564220,  (1 in total)
 - Depots   : 1564222,  (1 in total)

**Comment by kisak-valve** [comment]
Thanks, 552552 -> This is "Q.U.B.E. Remastered for Beta Testing" instead of the sub available in Steam's store page for this game.

The game dev(s) have not bound depot 1564221 to the beta testing sub, which why the main game content is not downloaded. This is something that would need to be evaluated by the game dev(s).
