### ISSUE TITLE
[beta] ctrl+f search missing (broken?)

### ISSUE THREAD

**Issue by arrowgent** [ValveSoftware/steam-for-linux#9407]
#### Your system information

* Steam client version (build number or date): 1682707471 apr 28
* Distribution (e.g. Ubuntu): 
* Opted into Steam client beta?: [Yes/No] y
* Have you checked for system updates?: [Yes/No] y

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

press CTRL+F for search box
search

#### Steps for reproducing this issue:

1. open a steam store or steam community page
2.  press on a physical real hardware keyboard the button combination "CONTROL PLUS F" (ctrl+F)
3.  nothing happens.

**Comment by dsalt** [comment]
Seeing this here too.

As this works as expected in the stable build, “feature request” is the wrong label.

**Comment by kisak-valve** [comment]
Hello @arrowgent, from the notes on #9483, please retest this issue.

**Comment by dsalt** [comment]
It works. (Return & Shift-Return don't, but I don't immediately recall if they work in the current stable build.)

**However**, it's implemented as an *unparented* pop-up menu so it has the same problematic characteristics (wrong transparency etc.) re. what should be its parent window – that window is handled as “unfocused” or “most recently lost focus” (depending on the window manager) rather than as if it still had the input focus.

**Comment by kisak-valve** [comment]
Closing as fixed.

Hello @dsalt, please open a new issue report for your follow up issue.

**Comment by dsalt** [comment]
@kisak-valve, having just done a search of the open issues, I believe that my ‘follow-up’ problem is covered by #2355.
