### ISSUE TITLE
[New Steam UI] DPI scaling no longer working

### ISSUE THREAD

**Issue by ReillyBrogan** [ValveSoftware/steam-for-linux#9454]
#### Your system information

* Steam client version (build number or date): 1683078372
* Distribution (e.g. Ubuntu): Solus
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* DE: Plasma (Wayland) 5.27.4
* xwayland version: 22.1.9

#### Please describe your issue in as much detail as possible:
After switching to the latest Steam beta I observed that window scaling is no longer working. My display is set to 200% scaling and the client was correctly scaled prior to switching to the beta. Steam is now ignoring the scaling setting resulting in a window that is too small to be usable on my display.

#### Steps for reproducing this issue:

1. Set window scaling to 200% on Plasma Wayland (untested in x11 session)
2. Switch to Steam beta
3. Open Steam client and observe that scaling settings are ignored.

Note that this is a regression as it worked previously and switching back to the non-beta channel causes Steam to start scaling correctly again.

Thread on the Steam forums with other users experiencing this issue (not sure why Lionking says it was working before): https://steamcommunity.com/groups/SteamClientBeta/discussions/3/3826413850821502932/

**Comment by kisak-valve** [comment]
Hello @ReillyBrogan, this issue is already being tracked at #9209. Closing as a duplicate.

**Comment by lionking102** [comment]
So the reason I was saying it never worked is simple: I fogot to write that I use fractional scaling, I'm at 150%. 
Integer Scaling (1x, 2x) maybe worked and was sharp before, but fractional scaling never worked good. There is only the option to not scale steam or to have a blurry UI. With KDE's "Apps scale by themself" (which is the only great experience for linux scaling right now) it is not even possible to have a blurry UI, people streight up can't read it and can do nothing about it, because steam doesn't support fractional scaling.

**Comment by andyczerwonka** [comment]
I have a similar problem, in that when I use fractional scaling, for many games the I get the game rendering in the bottom left corner of the screen and the rest of the monitor is black.
