### ISSUE TITLE
Steam not launching on Ubuntu 22.04: An X error occurred

### ISSUE THREAD

**Issue by lgmventura** [ValveSoftware/steam-for-linux#9559]
#### Your system information

* Steam client version (build number or date): 1:1.0.0.74-1ubuntu2
* Distribution: Ubuntu 22.04
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

After installing Steam by using `apt`, the programme won't launch. I get the following output:
```
[2023-06-03 19:40:57] Startup - updater built Nov 22 2021 22:06:59
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)

```
…and it freezes at this line. I have the proprietary NVidia 530 drivers installed and running.

#### Steps for reproducing this issue:

1. Install Steam using `sudo apt install steam`
2. Reboot the PC
3. Run Steam from the command line to see the output: `steam`

**Comment by kisak-valve** [comment]
Hello @lgmventura, does any 32 bit OpenGL application like `glxinfo` from a 32 bit build of mesa-utils work? Unfortunately, Ubuntu doesn't provide a 32 bit builds of this package on 22.04, so maybe try unpacking https://packages.ubuntu.com/bionic/i386/mesa-utils/download with an archive utility and using the utility without installing it to the system.

**Comment by lgmventura** [comment]
The application `glxinfo` generates a long output starting with:
```
$ glxinfo
name of display: :1
display: :1  screen: 0
direct rendering: Yes
server glx vendor string: NVIDIA Corporation
server glx version string: 1.4
server glx extensions:
    GLX_ARB_context_flush_control, GLX_ARB_create_context, 
    GLX_ARB_create_context_no_error, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_multisample, GLX_EXT_buffer_age, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_framebuffer_sRGB, GLX_EXT_import_context, GLX_EXT_libglvnd,
```

So, I guess it is working…

**Comment by lgmventura** [comment]
I tried downloading `mesa-utils` from Bionic from [this link](https://launchpad.net/ubuntu/bionic/i386/mesa-utils/8.4.0-1) (because the link you provided is broken) and unpacked it here, but `glxinfo` there does not work:
```
~/Downloads/temp/usr/bin$ ./glxinfo
name of display: :1
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  110
  Current serial number in output stream:  111
```

**Comment by kisak-valve** [comment]
Thanks, the difference being that your first test was a 64 bit build of glxinfo testing 64 bit OpenGL, and the second tested 32 bit OpenGL.

The NVIDIA proprietary driver requires that the driver's running kernel module, 32 bit userspace libraries, and 64 bit userspace libraries are all installed and exactly the same version to work properly. It's likely that you're missing the driver's 32 bit userspace libraries.

Since you wrote that you're using the NVIDIA 530 series video driver, please check that guess with something like `apt policy libnvidia-gl-530 libnvidia-gl-530:i386` and install the latter if it is missing with something like `sudo apt install libnvidia-gl-530:i386`.

Thanks for noting the broken link. I missed that packages.ubuntu.com has removed all bionic packages from their index.

**Comment by lgmventura** [comment]
Yes, I understand. But I just checked and the i386 libraries are already installed:
```
$ apt policy libnvidia-gl-530 libnvidia-gl-530:i386
libnvidia-gl-530:
  Installed: 530.30.02-0ubuntu1
  Candidate: 530.30.02-0ubuntu1
  Version table:
     530.41.03-0ubuntu0.22.04.2 500
        500 http://de.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages
        500 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages
 *** 530.30.02-0ubuntu1 600
        600 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        100 /var/lib/dpkg/status
libnvidia-gl-530:i386:
  Installed: 530.30.02-0ubuntu1
  Candidate: 530.30.02-0ubuntu1
  Version table:
     530.41.03-0ubuntu0.22.04.2 500
        500 http://de.archive.ubuntu.com/ubuntu jammy-updates/restricted i386 Packages
        500 http://security.ubuntu.com/ubuntu jammy-security/restricted i386 Packages
 *** 530.30.02-0ubuntu1 600
        600 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages
        100 /var/lib/dpkg/status
```

**Comment by 4164696f73** [comment]
I'm having issues with Steam myself. I'm on Manjaro Linux (did not want to make another thread just for that), just reinstalled the system, installed everything as I always do, Steam launched just fine, no issues, but after opting in for beta updates, I'm getting this error after launching Steam again:

```src/steamUI/steamuisharedjscontroller.cpp (449) : Failed creating offscreen shared JS context
src/steamUI/steamuisharedjscontroller.cpp (449) : Failed creating offscreen shared JS context
src/steamUI/steamuisharedjscontroller.cpp (449) : Fatal assert; application exiting
src/steamUI/steamuisharedjscontroller.cpp (449) : Fatal assert; application exiting
06/04 20:45:44 Init: Installing breakpad exception handler for appid(steam)/version(1685664179)/tid(5051)
assert_20230604204544_29.dmp[5378]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230604204544_29.dmp
_ExitOnFatalAssert
assert_20230604204544_29.dmp[5378]: Finished uploading minidump (out-of-process): success = yes
assert_20230604204544_29.dmp[5378]: response: CrashID=bp-e4ab354a-bce1-496e-a509-4c5442230604
assert_20230604204544_29.dmp[5378]: file ''/tmp/dumps/assert_20230604204544_29.dmp'', upload yes: ''CrashID=bp-e4ab354a-bce1-496e-a509-4c5442230604''
```

Full Steam output here: https://pastebin.com/raw/L7vv31ub

**How I installed my system, what was happening before etc (not sure if anything in here will be helpful):**
Everything was working just fine until yesterday/today. I chose to update my system, and I did not notice anything breaking, so I rebooted and got welcomed with some kernel stuff missing, so I had to reinstall Manjaro (because I have no idea what other Arch-based Linux to use, and I want Arch-based). Something from my own install script apparently broke, and all the install script does is to invoke pacman commands (literally nothing else, [here's what I installed](https://pastebin.com/raw/2bBVznhW)). I experienced the same failure - got thrown back to login screen, so I logged as normal, but this time I decided to install Linux kernel again (and this time rebooting didn't break anything). However, trying out Steam Beta made Steam never launch again - I see the processes, they run fine, but then they break as in the error above. I also have an issue with some applications loading very, very slowly (e.g. Thunar takes up to 30 seconds to launch, but other applications work normally), so I assume there's an issue with one of the packages I'm installing. Btw, yes, I know my issue is using Manjaro :) I'm working on that.

**Comment by kisak-valve** [comment]
Hello @4164696f73, your issue report is unrelated to the issue reported here. You might be seeing #9321.

**Comment by lgmventura** [comment]
@kisak-valve what is the current state? Did you figure that out?

**Comment by lgmventura** [comment]
Problem solved on my PC after upgrading NVIDIA drivers from version 530 to version 535.
