### ISSUE TITLE
[New Steam UI] Shader processing stuck at 0% for long time with no feedback

### ISSUE THREAD

**Issue by Nyamiou** [ValveSoftware/steam-for-linux#9567]
#### Your system information

* Steam client version (build number or date): 1685664179
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When I launch a game (tested with Rocket League and CS:GO) the shaders processing window open up stuck at 0% for a very long time (felt like 3/4 minutes) with no feedback whatsoever about what is happening. Eventually it climb up the percentage fast and reach 100% after that it get stuck for a more reasonable delay before launching the game.

Also it does this on every boot of those games, which it didn't do before (that was only on GPU driver upgrade). 

I have a NVidia 2060 if it's relevant.

#### Steps for reproducing this issue:

1. Launch Steam on Linux
2. Launch a game
3. Wait for shader processing and notice it gets stuck at 0% for a long time

**Comment by kisak-valve** [comment]
Hello @Nyamiou, if you monitor `~/.local/share/Steam/logs/shader_log.txt` while this issue is happening, are there any interesting hints? This might be Steam waiting on the video driver and disk I/O, and the subsequent game starts either have the shader pre-cache already up to date for the game or there's more of the relevant files cached in system memory.
