### ISSUE TITLE
Steam overlay + notifications white or invisible in CS:GO MacOS Catalina 10.15.7

### ISSUE THREAD

**Issue by lowdub-hub** [ValveSoftware/steam-for-linux#9654]
![Bildschirmfoto 2023-06-17 um 14 56 16](https://github.com/ValveSoftware/steam-for-linux/assets/99488480/a17f828f-45de-4f42-8718-d8c5ea3b39a8)
iMac Pro 2017
MacOS Catalina 10.15.7
AMD Radeon RX 5700 XT 8 GB
3,6 GHz 8-Core Intel Core i9
RAM 32 GB 2666 MHz DDR4

Steam Client Ver. 1686880776
Not opted in to Steam Beta

Steam overlay stays either invisible or creates a large white area on the screen that can be dragged around.
Buttons seem to be there and working but are not displayed.
Upon closing the window in the top left corner by clicking in to the white space it disappears.
Pressing Shift+Tab again opens an invisible steam overlay that blocks the user from clicking buttons in csgo.

Steps for reproducing this issue:
1. Start CS:GO
2. Press Shift + Tab

**Comment by kisak-valve** [comment]
Hello @lowdub-hub, in general, Steam for Mac issues are not tracked on Github. Please use [Steam Support](https://help.steampowered.com) for to give feedback on that.

Having written that, this issue is already being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/3192. Closing as a duplicate.
