### ISSUE TITLE
steam stopped working after recent update

### ISSUE THREAD

**Issue by TerryF0ld** [ValveSoftware/steam-for-linux#9665]
#### steam stopped working after recent update

* Steam client version: 1686880776
* Distribution: manjaro
* Opted into Steam client beta?: [No]
* Have you checked for system updates?: [Yes]
* Steam Logs: [steam-logs_tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11781326/steam-logs_tar.gz)
* GPU: AMD

#### Please describe your issue in as much detail as possible:
it won't start after steam 
```
(process:2399): GLib-GObject-CRITICAL **: 13:03:08.331: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(process:2399): GLib-GObject-CRITICAL **: 13:03:08.331: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xe8628db0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xe8627500
GetWin32Stats: display was not open yet, good
```

**Comment by TerryF0ld** [comment]
The steam process appears, after a while it closes, nothing else happens

**Comment by knedl1k** [comment]
Same issue here. After the recent UI update.

**Comment by Jusix** [comment]
It works for me when started through bash. But startup needs about 5 minutes...

**Comment by serhii-nakon** [comment]
I have the same problem on Debian 12, where steam client installed from Flatpak and I also can run it using bash only.

**Comment by kisak-valve** [comment]
Hello @Jusix, @serhii-nakon, you've described the symptoms of the issue being tracked at #9383.

**Comment by serhii-nakon** [comment]
Hello @kisak-valve , I think no, because I don't set DRI_PRIME=1

**Comment by Jusix** [comment]
I don't use any hybrid GPU solution.

**Comment by TerryF0ld** [comment]
solution to this problem helped me:

**Comment by kisak-valve** [comment]
Hello @TerryF0ld, glad to hear you found a workaround. due to the abundance of cross-posting of unrelated issues, I'm going to close this in favor of the older issue report.

Hello again @Jusix, @serhii-nakon, https://github.com/ValveSoftware/steam-for-linux/issues/9383#issuecomment-1584898530 has the main detail for the common case where the desktop environment is setting `DRI_PRIME` in reaction to `PrefersNonDefaultGPU=true` in Steam's desktop shortcut. You can have an Intel GPU or AMD APU hanging out in the background, even if you don't usually use it because you (assumedly) have a discrete GPU as well.

The common caparison to troubleshoot that is to compare starting Steam from a terminal versus from the desktop short cut. If you're seeing an issue that happens when Steam is started from a different terminal, but behaves when called from a bash terminal, please open a separate issue report focusing on that detail.
