### ISSUE TITLE
Just Listing a Bunch of Bugs That I've Found.

### ISSUE THREAD

**Issue by salar-shdk** [ValveSoftware/steam-for-linux#9687]
OS: Arch Linux x86_64 
Host: ROG Zephyrus G14 GA401QM_GA401QM 1.0 
Kernel: 6.3.8-arch1-1 
Resolution: 1920x1080 
WM: Openbox 
CPU: AMD Ryzen 9 5900HS with Radeon Graphics (16) @ 3.300GHz 
GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q 
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
Steam Version:  1686880776
Steam Client Build Date:  Thu, Jun 15 19:41 UTC +03.3:30
Steam Web Build Date:  Thu, Jun 15 19:10 UTC +03.3:30
Steam API Version:  SteamClient020

List:
```
    you can't open properties in normal mode, in general buttons on the pop-op menu doesn't work.

    back button or alt+left doesn't go back.

    when you are in a steam web browser and switch between desktop, whole page goes black.

    you can't uninstall a game. (it just remains on uninstalling)

    if you play a soundtrack and open it's window( the icon that appears on top right, it's just resizing 5-6 times per second.)

    sometimes when you exit steam, it remains in the background and you should kill it.

    and at last, in big picture mode its super slow, like 2-3 frame per second.
```
btw, one of the reasons that I love steam is that it was always solid and mature software, now with the new update, even tho the new UI isn't bad, nothing works and the huge amount of bugs is just ...

**Comment by kisak-valve** [comment]
Hello @salar-shdk, in general, multi-issue issue reports are bad for any issue tracker. Please search for the individual issues and if one doesn't exist, then open a new issue report focusing on a single issue per issue report.

Off hand:
`you can't open properties in normal mode, in general buttons on the pop-op menu doesn't work.` #9273
`when you are in a steam web browser and switch between desktop, whole page goes black.` #9598

Closing because this feedback is untrackable.
