### ISSUE TITLE
Notification rendered outside screen after UI update with -forcedesktopscaling

### ISSUE THREAD

**Issue by Flowneee** [ValveSoftware/steam-for-linux#9704]
#### Your system information

* Steam client version (build number): 1687386907
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/11839831/steam-logs.tar.gz)
* GPU: Intel + Nvidia

#### Please describe your issue in as much detail as possible:
When I set `-forcedesktopscaling 2`, notifications partially rendered outside screen (see screenshot below). Without `-forcedesktopscaling 2` everything works fine, notifications rendered correctly in the right bottom corner.

![image](https://github.com/ValveSoftware/steam-for-linux/assets/10746427/6335951e-2fee-4f23-ac81-f81731f45fbd)

**Comment by Caffeineix** [comment]
XFCE, Pop_OS

It seems scaling is severely broken in this update. Here are all of the problems I've run into specific to scaling:

- Login window is too small for window contents
- Steam's in-game overlay is scaled at double the specified forcedesktopscaling value, so it uses 4x scaling instead of 2x scaling when it's set to 2.
- Windows only move when they are dragged from the left side, this can make smaller windows near impossible to move.

**Comment by Flowneee** [comment]
> scaling is severely broken in this update

I agree, with scaling enabled in CLI and "Scale text and icons to match monitor settings" disabled all dropdown menus breaks, like size of the widget is the same, but content doesn't fit in it.

**Comment by Flowneee** [comment]
One of the latest updates fixed issue for me, now notifications rendered correctly with `-forcedesktopscaling 2`, I'm going to close this issue.
