### ISSUE TITLE
Inconsistent installation and update windows

### ISSUE THREAD

**Issue by rokejulianlockhart** [ValveSoftware/steam-for-linux#9745]
<details>

0. **Your system information**

    *Type*                                                                                                                               | *Data*
    -------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------
    **Steam client version (build number or date)**                                                                                      | 1687918139 (2023-06-28T02:44-08:00)
    **Distribution**                                                                                               | [OpenSUSE Tumbleweed 20230625](cpe:/o:opensuse:tumbleweed:20230625)
    **Opted into Steam client beta?**                                                                                                    | Yes
    **Have you checked for system updates?**                                                                                             | Yes
    **Steam Logs**  |
    **GPU**                                                                                                                              | AMD Radeon RX 5700

</details>

0. **Please describe your issue in as much detail as possible**

    When installing Steam, one of the windows obviously (ultimately) renders as a Qt or GTK window. It looks great, especially on KDE Plasma (obv. important for Steam Deck). However, the frequently displayed update Window is very obviously non-native. Why is this? It just seems like an obvious oversight. Consequently, I suggest that you change this.

	Culprit:

    ![image](https://github.com/ValveSoftware/steam-for-linux/assets/42837531/b0fa9cdd-9962-46e9-b9f9-a31f2d9b5e66)

0. **Steps for reproducing this issue**

    0. Update Steam.

**Comment by kisak-valve** [comment]
Hello @rokejulianlockhart, this issue was previously evaluated, but I'm having some trouble digging up the older issue report.

From memory, Steam's self-updater process intentionally doesn't use any major frameworks to decorate the window so that there's as few points of failure as possible, and as a result, that also reduces the number of scenarios that would prevent the Steam client from being able to bootstrap itself. Reliability takes priority over cosmetics in this case.

**Comment by rokejulianlockhart** [comment]
Probably better to close an not planned then, right?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ValveSoftware/steam-for-linux/issues/9745#issuecomment-1611479192

@kisak-valve, this might be worth revisiting, because ,ultiple distributions and desktop environments have switched to being Wayland-only, whereas that installer runs under XWayland. I presume we both agree that that's a rather significant point of failure - that is, running under not merely a nested compositor, but display server?

I've updated the original issue to demonstrate the actual inconsistency amongst the dialogs, too.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ValveSoftware/steam-for-linux/issues/9745#issuecomment-2517650114

@kisak-valve, even more importantly, it's not DPI-aware, so it's nigh unreadable at 150% scale on a 16-inch 2560 by 1440-pixel monitor:

![Image](https://github.com/user-attachments/assets/75eaec6d-9c75-46d7-82ed-e576c2412334)

Should I file this separately? I shall if I've no response otherwise.

**Comment by RokeJulianLockhart** [comment]
Should I file this separately? I shall if I've no response otherwise.

**Comment by kisak-valve** [comment]
Nice way to passive aggressively demand a response.

I've already communicated the critical information here with the need to keep this phase of Steam's bootstrapper as simple as possible so that it's reliable. Wiring a framework in to do scaling is a non-starter task.

**Comment by RokeJulianLockhart** [comment]
> Nice way to passive aggressively demand a response.

@kisak-valve, that wasn't my intention: I stated so because some people disable notifications on closed issues, and I believed that it was different enough to warrant a separate issue.

Certainly, *if* that were true, why utilise what you've just criticsed me for against me? We're both adults; if I'd been immature, I'd hope that you wouldn't lower yourself to that level.

Irrespective, enough of theoreticals: I'm not going to attempt reverse psychology on a corporation, so I wouldn't be here unless my sole intention was to assist. Remember that we're merely discussing a modal window, so thanks, sincerely, for the clarification.

**Comment by RokeJulianLockhart** [comment]
[`tModLoader/tModLoader/issues/4315`](https://github.com/tModLoader/tModLoader/issues/4315#issue-2427744943) may be relevant, if SDL renders this.
