### ISSUE TITLE
Unexpected behaviour

### ISSUE THREAD

**Issue by wojgie** [ValveSoftware/steam-for-linux#9795]
#### Your system information

* Steam client version (build number or date): 1688428930
* Distribution (e.g. Ubuntu): Arch
* Opted into Steam client beta?: [Yes/No] Yes.
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia/Intel/AMD Nvidia

#### Please describe your issue in as much detail as possible: Happens
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:

0. important: don't use `-vgui`!

1. Open CS:GO (probably any game with in game transactions)
2. Buy something.

Should happen: you should get the buy menu with an "authorize" button.
Happens:

The steam animation (the one while loading the buy menu) stops spinning. Then the overlay just shuts down and also sometimes crashes CS:GO. Then Steam window pops up, steam seems to load the same way like when its loaded first time (spinning steam logo, the webpage slowly renders). and then the super unexpected stuff happens. These things are completely random and include:
- "Add a non-steam game" window pops up.
- this weird text shows up: 
![image](https://github.com/ValveSoftware/steam-for-linux/assets/89017406/38ec94d6-ce4c-423c-88f8-18dc57b5f08e)

- steam starts checking for updates
![image](https://github.com/ValveSoftware/steam-for-linux/assets/89017406/025cd0b2-ed0a-42a7-bfc4-6d4f4e80825e)

- controller setup window pops up
- steam opens up in mini mode (only library and only in list) yet after i just click on the steam icon on tray it comes back to being normal.
- asks me if i want to participate in steam hardware survey (i already did for 2023) (if i agree it just bugs out)
- asks me if i want to backup game files
- asks me to enter product code
- asks for authorization (a window pops up with 6 places to enter some code i think this is the steamlink code)
- steam settings screen pops up
- steam tray is unresponsive
- after the purchase menu crashed and i open a regular browser from the overlay. **it usually doesn't have titlebar/tabs**.

I think it might be something with handling `steam://` URL, mini library, windows popping up.

Also: 

i have a video of this happening + logs but i really don't want to share these here, is there a other way?

**Comment by SirFritz** [comment]
Happens to me too but instead sometimes after opening the steam overlay (was playing system shock 2023 with proton experimental).   The overlay crashes and steam then goes into this weird state.  Sometimes it starts throwing up errors too and becomes unusable.

Fedora 38
i58600k
rx6700xt
32gb ram

**Comment by michael-n0813** [comment]
I think this is related to a crash with the web browser steam has inbuilt it also happens outside of games when the browser crashes and I try to start a game or when the overlay crashes and I'm in a a game. I was playing APICO. This seems like a major issue and I hope it gets fixed soon as I have to restart my computer to fix it, restarting steam doesn't work to fix the issue.

Arch linux
AMD 5600x
AMD RX6700XT

**Comment by teddybee-r** [comment]
Fedora Kinoite, Flatpak Steam, Wayland, Ryzen 5 2600 & RX570

Trying to buy something in DotA2 shows the loading spinner into crash of the overlay and steam restarting. The game keeps running.

Ever since the hardware acceleration support update my Steam has shown random blank pages when clicking on things requiring me to close and open the window. When I first open the friends tab I see one of my four favorites and EVERYTHING else is empty. Requires reopening as well.

**Comment by nmirthes** [comment]
I'm being hit hard by this as well because I'm also experiencing stutter from [#5727] if Steam's overlay is off.

Ubuntu 22.04.2, regular Steam, X11, Nvidia 535.86.05 and Intel i5/GTX 1650.

Starting a game with release Steam can lead to random prompts from various Steam features popping up. Recent beta Steam tries to shut down and hangs while trying. This all seems to stem from cached data retained while using the overlay in-game. Deleting In-Game Overlay Data allows me to launch a game again without Steam wigging out until the in-game overlay is used.

**Comment by teddybee-r** [comment]
While trying to fix buying anything in game I tried the new big picture mode and came to the conclusion that it is impossible to buy anything in game for me. But the BP overlay does not come with a steam crash.

On the Steam Deck it is the same. I click authorize in the overlay and it just closes without doing anything.

My exact steps are

1. Open Dota
2. Purchase 1 month Dota+
3. Overlay opens
4. Click authorize
5. No purchase was made and the overlay closes.

**Comment by nfinite-recursion** [comment]
> Deleting In-Game Overlay Data allows me to launch a game again without Steam wigging out until the in-game overlay is used.

Can confirm that this (temporarily) fixes the issue. Thanks nmirthes! I think you're on the right track!

Steam > Settings > In Game > Delete Web Browser Data > Delete

It's as if the new UI is loading the cached files and executing them as input.

**Comment by Turmfalke2** [comment]
I was able to buy dota + after enabling the steam beta (Settings -> Interface)

**Comment by orzen** [comment]
I think this started to happen to me once the new UI was launched. The explanation that "Steam sends events to the wrong windows" sounds accurate.

I experience this when I click to queue up in dota and quickly swap to a different window(like "tabbing" out from the game) in a different virtual workspace.

**Comment by CodrCheems** [comment]
>    "Add a non-steam game" window pops up.
    this weird text shows up:
    image
    steam starts checking for updates
    image
    controller setup window pops up
    steam opens up in mini mode (only library and only in list) yet after i just click on the steam icon on tray it comes back to being normal.
    asks me if i want to participate in steam hardware survey (i already did for 2023) (if i agree it just bugs out)
    asks me if i want to backup game files
    asks me to enter product code
    asks for authorization (a window pops up with 6 places to enter some code i think this is the steamlink code)
    steam settings screen pops up
    steam tray is unresponsive
    after the purchase menu crashed and i open a regular browser from the overlay. it usually doesn't have  =titlebar/tabs.
    
This happens to me too on a Ryzen 7 1700 with a RX470 4GB with AMDGPU OSS driver on Fedora 38 Gnome Wayland session. It happens whilst playing "A dance of fire and ice" with the exact same as mentioned behaviour as the author of the issue wrote with a native steam package from RPMFusion repository. It happens only in this game recently because when I launch "Snowrunner" it doesn't happen at all and it started happening around a week after installing the game and it might be also connected to steam overlay crashing some titles for me as I saw somebody having this issue and a temporary fix was deleting overlay data also the behaviour stays until I restart steam and won't launch the game afterwards. So it **might** be connected to issue #9586.

**Comment by Bfgeshka** [comment]
Last several days steam was jumping on game's desktop tag, even if it ws on a different one. Or steam window just dissapeared completely while still working.

Cannot say more because today steam broke completely and cannot be started.

**Comment by nmirthes** [comment]
This seems fixed for me on the most recent stable release. I don't use the overlay features a whole lot, but I'm not having any issues when I do. That's despite trying to reproduce the problems I described previously.

**Comment by sashistillfrvr** [comment]
Sorry for opening again this issue, but i'm experiencing exactly the same behavior again.
Using Arch Linux + Hyprland, when opening a game, suddenly starts to doing this random popus and tries to shutdown steam itself. when using big picture, this doesn't happen.

![Image](https://github.com/user-attachments/assets/46ca8b32-cb5d-49ef-b5cc-525e950f1921)

![Image](https://github.com/user-attachments/assets/2a67762f-67de-4838-a2da-ae2ae10e0c55)

![Image](https://github.com/user-attachments/assets/4029ba19-4b24-4202-b013-73a2d9c351ae)

**Comment by sashistillfrvr** [comment]
This are my logs

[steam-logs.tar.gz](https://github.com/user-attachments/files/20732721/steam-logs.tar.gz)

**Comment by FRBFStudios** [comment]
Exact same situation here, it just started doing this out of nowhere
