### ISSUE TITLE
XCOM: Enemy Unknown Linux native client not launching and crashes

### ISSUE THREAD

**Issue by chknatwork** [ValveSoftware/steam-for-linux#9858]
#### Your system information

* Steam client version (build number or date):  1689034492
* Distribution (e.g. Ubuntu): Manjaro 23.0.0 UltimaThule
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia 1650 MaxQ

#### Please describe your issue in as much detail as possible:
XCOM: Enemy Unknown not launching - showing  00c8:err:xrandr:xrandr14_get_adapters Failed to get adapters amongst other errors in terminal

#### Steps for reproducing this issue:

1.  Click Play to launch XCOM:EU
2. Doesn't launch and goes back to steam client

*i=other native games seem to work like Neverwinter Nights by Beamdog and Divinity Original Sin Enhanced Edition using Proton
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12061463/steam-logs.tar.gz)

**Comment by kisak-valve** [comment]
Hello @chknatwork, a logged message like `00c8:err:xrandr:xrandr14_get_adapters Failed to get adapters` is something you'd see coming out of Proton instead of a Linux native game port. Looking at your compat_log.txt, it looks like the game is configured to use some version of Proton GE.

We're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/4061#issuecomment-1636768334.
