### ISSUE TITLE
Adding a new Steam library folder fails with no error

### ISSUE THREAD

**Issue by Sparkwave2** [ValveSoftware/steam-for-linux#9859]
#### Your system information

* Steam client version (build number or date): 1689034492
* Distribution (e.g. Ubuntu): Linux Mint
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12062263/steam-logs.tar.gz)
* GPU: Nvidia GTX 1650

#### Please describe your issue in as much detail as possible:
Steam does not add a library folder. When trying to add one, it does not display an error message, it creates a steamapps folder, and then does nothing.

#### Steps for reproducing this issue:

1. Open Steam
2. Open Settings
3. Open Storage
4. Click the + icon to a new library folder
5. Select an empty directory in the file manager
6. Click "open"
7. The only folder being created is an empty steamapps folder, Steam does not recognize it as library.

Steam Runtime Diagnostics: https://gist.github.com/Sparkwave2/5f6a35c299fc2188f904dc2b1177bbc5

**Comment by kisak-valve** [comment]
Hello @Sparkwave2, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by Sparkwave2** [comment]
I updated it with the link, here's a link to it again just in case: https://gist.github.com/Sparkwave2/5f6a35c299fc2188f904dc2b1177bbc5

**Comment by peniblec** [comment]
Same symptoms here, on openSUSE Tumbleweed. Found no clue in the logs, but running `steam` from the console and scanning stdout/stderr, I spotted:

```
sh: line 1: /home/peniblec/media/.steam_exec_test.sh: Permission denied
Failed system("/home/peniblec/media/.steam_exec_test.sh") in execute test: 32256
```

`/home/peniblec/media` is a new mount point I just added, on a newly formatted drive with…

```
$ mount | grep media
/dev/nvme0n1p1 on /home/peniblec/media type xfs (rw,nosuid,nodev,noexec,relatime,attr2,inode64,logbufs=8,logbsize=32k,sunit=32,swidth=256,noquota,user)
```

… and I was trying to add a new library folder under `/home/peniblec/media/games/steam`.  Paths not under `~/media` were successfully added, but paths under `~/media` could not be, with the symptoms described by @Sparkwave2.

Turns out I asked the distro's partition wizard (YaST Partitioner) for the partition to be "mountable by user", which IIUC translates to the `user` option in `fstab`, which, [quoth `mount(8)`](https://man7.org/linux/man-pages/man8/mount.8.html#FILESYSTEM-INDEPENDENT_MOUNT_OPTIONS),

> implies the options `noexec`, `nosuid`, and `nodev` (unless overridden by subsequent options, as in the option line `user,exec,dev,suid`).

So in my specific instance, 

* going back to the YaST partitioner,
* `Mounting Options` ⇒ `Fstab Options…` ⇒ `Arbitrary Option Value` ⇒ `exec`, 
* committing the changes, 
* restarting the system, 
* confirming that `/etc/fstab` says `user,exec` and `mount` no longer says `noexec`, 

… did the trick: I can now add `/home/peniblec/media/games/steam` as a library folder, and move games there.

Odds are slim that this mount option goof matches your issue exactly @Sparkwave2; FWIW though I can at least confirm the failure mode: Steam creates a `steamapps` subfolder, then does nothing UI-wise to acknowledge that creation or report the error that interrupted the operation.

**Comment by Sparkwave2** [comment]
I can confirm that adding `exec` after `user` in the mount options fixes the issue.

**Comment by 8leggedunicorn** [comment]
@peniblec thank you for publicly posting as it resolved my issue.

**Comment by rdp** [comment]
Yeah tailing the log files (or watching stdout) is the way to diagnose.  :)

I think that if adding a location fails, Steam should at least have a warning message popup "check your logs for why".  Even better would be the exact error....

It is really confusing when just nothing happens...

**Comment by gabriele2000** [comment]
Assuming there's no issue with the filesystem or permissions:
 
- Create a "Steam" folder where you want your library
- Point Steam into the newly created folder
- Enjoy

**Comment by mercster** [comment]
I'm seeing this as well.  I already have a second Steam Library (pointing to ~/Steam)... I added another Linux partition to the system.  Keep trying to add it as third library, Steam creates empty 'steamapps' folder, and it just silently fails.  

EDIT: Odd.... my fstab doesn't have "noexec" in the mount line, but yeah, that's why, I can't execute files on that partition.. wonder what's wrong...
