### ISSUE TITLE
Wrong icons for some games in .desktop files

### ISSUE THREAD

**Issue by quaec** [ValveSoftware/steam-for-linux#989]
Some games don't have a (correct) icon associated with them in the .desktop-file for the system menu integration (for example Braid, Half-Life and Counter-Strike).

I'm using Ubuntu 12.04.1 LTS (64 Bit) with the standard Unity DE.

As you can see in the .desktop-file below, the game uses the "steam" icon and not a game-specific icon.

**"Counter-Strike (Beta).desktop" file in** `/home/username/.local/share/applications/`

```
[Desktop Entry]
Name=Counter-Strike (Beta)
GenericName=Steam game
Comment=Play this game
Exec=steam steam://rungameid/10
Icon=steam
Terminal=false
Type=Application
Categories=Game;
```

**System information**

```
Prozessor:
    Hersteller: AuthenticAMD
    Geschwindigkeit: 3200 MHz
    4 logische Prozessoren
    4 technische Prozessoren
    HyperThreading:  Nicht unterstützt
    FCMOV:  Unterstützt
    SSE2:  Unterstützt
    SSE3:  Unterstützt
    SSSE3:  Unterstützt
    SSE4a:  Unterstützt
    SSE41:  Nicht unterstützt
    SSE42:  Nicht unterstützt

Netzwerk-Informationen:
    Netzwerk-Geschwindigkeit: 

Betriebssystem:
    Ubuntu 12.04.1 LTS (64 Bit)
    Kernel-Name: Linux
    Kernel-Version: 3.2.0-36-generic
    X-Server-Vendor: The X.Org Foundation
    X-Server-Release: 11103000

Grafikkarte:
    Treiber: NVIDIA Corporation GeForce GTX 260/PCIe/SSE2

    Treiber-Version: 3.3.0 NVIDIA 310.14
    Desktop-Farbtiefe: 24 Bit per Pixel
    Monitor-Aktualisierungsrate: 59 Hz
    Anbieterkennung: 0x10de
    Gerätekennung: 0x5e2
    Anzahl der Monitore: 2
    Anzahl der logischen Grafikkarten: 2
    Prim. Anzeigeauflösung: 1680 x 1050
    Desktop-Auflösung: 2960 x 1050
    Prim. Anzeigegröße: 47,4 cm x 29,6 cm (55,8 cm diag.)

    Primärer Bus: PCI Express 16x
    Primärer VRAM: 896 MB
    Unterstützte MSAA-Modi: 2x 4x 8x 16x 

Soundkarte:
    Audiogerät: VIA VT1708S

Speicher:
    RAM: 3953 MB

Weitere Daten:
    UI-Sprache: Deutsch (Deutsch)
    LANG:  de_DE.UTF-8
    Mikrofon: Not set
    Verfügbarer Festplattenspeicher insgesamt: 928699 MB
    Größter freier Festplattenspeicherblock: 54232 MB

Installierte Software:

Neueste Fehlerberichte:
```

**Comment by rudmint** [comment]
ahem... a friend told me Hatoful Boyfriend has this issue...

**Comment by eagleflo** [comment]
Grim Fandango: Remastered is missing its icon.

**Comment by MrSchism** [comment]
Send an email to the studio and let them know, @eagleflo

**Comment by eagleflo** [comment]
I don't have any contacts at Double Fine and don't know how to describe the fix to the issue. All I could do is link here. I've assumed Valve is in direct contact with the devs responsible for Linux builds.

Maybe this is something Valve should be addressing via documentation, seeing as it is a very common omission for studios to make?

**Comment by Plaque-fcc** [comment]
Hi! 

  Steam Forums is the proper place for that. Or you may want to visit their website and leave your feedback there. I guess. 


9 мая 2015 г. 0:05:22 EET, Aku Kotkavuo <notifications@github.com> пишет:
>I don't have any contacts at Double Fine and don't know how to describe
>the fix to the issue. All I could do is link here. I've assumed Valve
>is in direct contact with the devs responsible for Linux builds.
>
>Maybe this is something Valve should be addressing via documentation,
>seeing as it is a very common omission for studios to make?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ValveSoftware/steam-for-linux/issues/989#issuecomment-100366387

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by Cheeseness** [comment]
I have contacts at Double Fine and have reached out to see if we can get this looked into for Pnauts, Grim, CQ, CQ2 and Stacking (and BL if that has the same problem - I don't have that installed at the moment to check).

**Comment by MrSchism** [comment]
Double Fine can be contacted at: support@doublefine.com (for future reference)

**Comment by Cheeseness** [comment]
I got an email back from Greg Rice at Double Fine a couple of days ago saying it would be looked into. As soon as I hear confirmation that it has been, I'll report back.

**Comment by ViBENo1** [comment]
cool but how many years it take to fix the icons finally?

**Comment by prcastro** [comment]
I still believe this issue affects a important percentage of Linux games on Steam

**Comment by kisak-valve** [comment]
Closing as there is no centralized solution for this.

Please contact individual game devs for each missing icon on a per-game basis.

**Comment by citizen-anon-x** [comment]
Tad late to this discussion but this is a lack of icons being readied for GNU+Linux, as well as a malformed .desktop file. You can usually find a game's icon in it's folder, like for instance: 
.local/share/Steam/steamapps/common/Bastion/

Valve, simply having the information on creating .desktop files amongst the developer information for GNU+Linux game devs would be a great place to start. I have found that aside from the missing .png images in .local/share/icons/hicolor/, the icon line is incomplete as you can see below. It's really very simple. I am posting this now, 04/27/2018 because this is still an issue that should have been resolved years ago.

[Desktop Entry]
Name=Bastion
Comment=Play this game on Steam
Exec=steam steam://rungameid/107100
Icon=steam      <=    This should read Icon=steam_icon_107100 The .png extension is not needed.
Terminal=false
Type=Application
Categories=Game;

I hope this helps. If it does not get resolved, find the .png or .bmp image for your game in it's folder. If it is already a .png, rename it to the appropriate steam_icon_game-ID as shown above, and paste it into the appropriate hicolor icon directories and then use GIMP to resize as needed per directory size specification. If it is a .bmp, just use GIMP to export it as a .png and follow the above directions.

For instance, the properly named bastion icon would be in these hicolor icon directories in your home folder.

.local/share/icons/hicolor/256x256/apps/steam_icon_107100.png
.local/share/icons/hicolor/128x128/apps/steam_icon_107100.png
.local/share/icons/hicolor/96x96/apps/steam_icon_107100.png
.local/share/icons/hicolor/80x80/apps/steam_icon_107100.png
.local/share/icons/hicolor/72x72/apps/steam_icon_107100.png
.local/share/icons/hicolor/64x64/apps/steam_icon_107100.png
.local/share/icons/hicolor/56x56/apps/steam_icon_107100.png
.local/share/icons/hicolor/48x48/apps/steam_icon_107100.png
.local/share/icons/hicolor/32x32/steam_icon_107100.png

I am sure you get the point. =)

**Comment by Plagman** [comment]
Yes, the problem was that we didn't have .pngs to put int here because the developer never specified Linux icon files, only a Windows icon. The next Beta will include a systemic fix for this that will let the Linux client fall back to Windows icons; games will have to be reinstalled and the shortcuts recreated for the proper icon to get redownloaded, unfortunately.

**Comment by Oaklight** [comment]
wrong icon for Ancestors: The Humankind Odyssey
