### ISSUE TITLE
Steam UI: "Create or select new steam library folder" dialog is empty

### ISSUE THREAD

**Issue by memchr** [ValveSoftware/steam-for-linux#9944]
#### Your system information

* Steam client version (build number or date): Thu Aug  3 12:50:28 UTC 2023
* Distribution: Arch (rolling)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: cannot disclose
* GPU: AMD, NVIDIA, intel and virgl (doesn't matter)

#### Please describe your issue in as much detail as possible:

The "Create or select new steam library folder" dialog is empty.

Can be reproduced with fresh Steam installations on different GPUs and VMs.

![image](https://github.com/ValveSoftware/steam-for-linux/assets/118117622/57a97a9c-57b9-4144-98b4-b507804e772b)
#### Steps for reproducing this issue:

- Clean install arch
- Install steam
- Launch steam
- Goto settings -> storage -> add new steam library

**Comment by kisak-valve** [comment]
Hello @memchr, Steam should be calling xdg-desktop-portal to open a user-selected file dialog box, but the Arch packaging does not currently require the relevant dependency to be installed with Steam. This is a distro packaging issue being tracked at https://bugs.archlinux.org/task/78625. You're reaching this dialog window because the xdg-desktop-portal failed for some reason.

Install the `xdg-desktop-portal` system package and the corresponding backend of your choice. (https://wiki.archlinux.org/title/XDG_Desktop_Portal)

**Comment by memchr** [comment]
Hi @kisak-valve, I have `xdg-desktop-portal` installed on my system, but it seems that the `xdg-desktop-portal-wlr` implementation does not support the file chooser. I will close this issue, thank you for your time.

**Comment by billtown** [comment]
I have this problem on fedora 38, gnome 44.4. xdg-desktop-portal is installed and so is xdg-desktop-portal-gnome for my environment of GNOME, but I magically lost my existing library location  after restarting steam. It was in /media/steam   I can no longer add my existing library back and receive #ContentManagement_Error_   I too get an empty dialog.

I see steam attempt to write to " /media/.steam_exec_test.sh" but it should be attempting  to write to 
"Couldn't write /media/steam/.steam_exec_test.sh"  No clue why my locations were magically removed.

Changing perms against my wishes on /media, steam could then recreate the very restrictive path (unchoosable by me)  in /media/SteamLibrary which is totally useless.  I was  able to get my install to work again (and get back my lost progress), by fapping around and letting steam install in /media/SteamLibrary then moving all my crap from /media/steam.  I've had to loosen my perms on /media.  This sucks.  This all occurred after a large outage today.   I don't feel like xdg-desktop-portal is broken, because I can "browse files" from steam.  Posting to a closed ticket because I really found nothing else on the internet similar to my issue.
