### ISSUE TITLE
SteamUI

### ISSUE THREAD

**Issue by SJK9906** [ValveSoftware/steam-for-linux#9973]
#### Your system information

* Steam client version (build number or date): 
Versione di Steam:  1690583737
Data della build del client di Steam:  ven 28 lug 20:44 UTC -08:00
Data della build Web di Steam:  sab 29 lug 0:21 UTC -08:00
Versione API di Steam:  SteamClient020
* Distribution (e.g. Ubuntu): Garuda Linux (64 bit)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs:[steamui_system.txt](https://github.com/ValveSoftware/steam-for-linux/files/12300431/steamui_system.txt)
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
the client steam don't use a screen and font settings and is too small to use
![Screenshot_20230808_221325](https://github.com/ValveSoftware/steam-for-linux/assets/129201282/5339b4c9-29f5-4937-b266-22c4c002e370)

#### Steps for reproducing this issue:
1. install arch or arch based distro with KDEplasma
2. install steam
3. open steam client interface

**Comment by kisak-valve** [comment]
Hello @SJK9906, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/9209.

You should be able to workaround this issue by completely closing Steam, then running Steam with `STEAM_FORCE_DESKTOPUI_SCALING=2.0 steam` or `steam -forcedesktopscaling=2.0` (adjusting 2.0 to your preference).

Closing in favor of the older issue report.
