### ISSUE TITLE
Now the tray icon does not show when right click menu and does not show steam on left click.

### ISSUE THREAD

**Issue by skvili** [ValveSoftware/steam-for-linux#9993]
#### Your system information

* Steam client version (build number or date): 1690583737
* Distribution (e.g. Ubuntu): Debian GNU/Linux 12 (bookworm)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`]
* GPU: Nvidia

#### Please describe your issue in as much detail as possible:
The tray icon does not show when right click menu and does not show steam on left click.

#### Steps for reproducing this issue:

1. Run Steam
2. Try click on tray icon
3. 
[logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/12354377/logs.tar.gz)

**Comment by kisak-valve** [comment]
Hello @skvili, for the right click menu on Steam's tray icon, can you check what files are listed in `~/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs*` (or maybe `~/.steam/debian-installation/ubuntu12_32/steam-runtime/pinned_libs*` if you're using the distro-modified Steam package), then delete the pinned_libs* folders so that Steam regenerates them the next time it is started.

For left click to show the Steam client, that issue is being tracked at #4836.
